#+title: Los antivirus y GNU/Linux
#+date: <2008-07-18 20:59>
#+author: Godofredo Fdez.
#+description: http://free.avg.com/ww.download?prd=afl#tba1 http://www.eicar.org/anti_virus_test_file.htm# [19:21:29(root@surco)/home/godo/temp]> dpkg -i avg75fld-r51-a1243.i386.deb Seleccionando el paquete avg75fld previamente no seleccionado. (Leyendo la base de datos ... 158239 ficheros y directorios instalados actualmente.) Desempaquetando avg75fld (de avg75fld-r51-a1243.i386.deb) ... Configurando avg75fld (7.5.51_a1243) ... Installing 'avgd' service initscripts... Registering 'avgd' service to runlevels...
#+filetags: 
#+options: _:nil
#+nid: 288

http://free.avg.com/ww.download?prd=afl#tba1

http://www.eicar.org/anti_virus_test_file.htm#

[19:21:29(root@surco)/home/godo/temp]> dpkg -i avg75fld-r51-a1243.i386.deb
Seleccionando el paquete avg75fld previamente no seleccionado.
(Leyendo la base de datos ...
158239 ficheros y directorios instalados actualmente.)
Desempaquetando avg75fld (de avg75fld-r51-a1243.i386.deb) ...
Configurando avg75fld (7.5.51_a1243) ...
Installing 'avgd' service initscripts...
Registering 'avgd' service to runlevels...
update-rc.d: warning: /etc/init.d/avgd missing LSB style header entry 'required-start'
update-rc.d: warning: /etc/init.d/avgd missing LSB style header entry 'required-stop'
Adding system startup for /etc/init.d/avgd ...
/etc/rc0.d/K20avgd -> ../init.d/avgd
/etc/rc1.d/K20avgd -> ../init.d/avgd
/etc/rc6.d/K20avgd -> ../init.d/avgd
/etc/rc3.d/S20avgd -> ../init.d/avgd
/etc/rc5.d/S20avgd -> ../init.d/avgd
Please launch the '/opt/grisoft/avggui/bin/avggui_update_licinfo.sh'
script as root for updating license information.

AVG 7.5 Anti-Virus Free for Linux successfully installed.
[19:21:52(root@surco)/home/godo/temp]> [19:21:56(root@surco)/home/godo/temp]> [19:21:57(root@surco)/home/godo/temp]> avgupdate -o
Preparándose para descargar archivos desde 'http://www.grisoft.cz/softw/70/update/'.
Descargando archivo: avginfo.ctf [ 7270B]
Descargando archivo: u7avi1340u9.bin [6240944B]
Descargando archivo: u7iavi1560fe.bin [25713831B]
Actualizando...
La actualización en línea finalizó correctamente.
[19:24:45(root@surco)/home/godo/temp]> [19:24:47(root@surco)/home/godo/temp]> [19:24:47(root@surco)/home/godo/temp]> avgupdate -o
Preparándose para descargar archivos desde 'http://www.grisoft.cz/softw/70/update/'.
Descargando archivo: avginfo.ctf [ 7270B]
Archivo: avginfo.ctf no modificado.
No hay nada nuevo para actualizar.
[19:26:31(root@surco)/home/godo/temp]> [19:26:35(root@surco)/home/godo/temp]>

[19:40:09(godo@surco)~]> alias | grep avg
alias avgq='avgqrtctl -l -S D'
alias scan='avgscan -scan -heur -arc'
alias usbm='mount /mnt/usbflash; avgscan -scan -heur -arc /mnt/usbflash'
[19:40:19(godo@surco)~]> usbm
AVG7 Anti-Virus command line scanner
Copyright (c) 2007 GRISOFT, s.r.o.
Versión del programa 7.5.51, motor 442
Base de datos de virus: Versión 270.5.1/1560 2008-07-18
El tipo de licencia es GRATUITO.
/mnt/usbflash/eicarcom2.zip:\eicar_com.zip:\eicar.com Se identificó un virus EICAR_Test
/mnt/usbflash/eicarcom2.zip Se identificó un virus EICAR_Test
Analizados: 1226 archivos, 0 sectores
Infecciones: 1
Errores: 0
[19:47:26(godo@surco)~]>

[10:35:55(godo@alpechin)~]> more /tmp/avgupdate.txt
Preparándose para descargar archivos desde 'http://www.grisoft.cz/softw/70/update/'.
Descargando archivo: avginfo.ctf [ 7270B]
65% [avginfo.ctf 100% 4.65KB/4.65KB] 996B/s 2
Descargando archivo: u7avi1343u1323u8.bin [ 233372B]
0% [u7avi1343u1323u8.bin 0% 1.14KB/227.90KB] 15
1% [u7avi1343u1323u8

0KB] 3.98KB/s 4m10s
3u1323u8.bin 34% 78.91KB/227.90KB] 5.56KB/s 2m54s
11% [u7avi1343u1323u8.bin 50% 115.68KB/227.9
16% [u7avi1
1m27s
.bin 100% 227.90KB/227.90KB] 11.21KB/s 1m13s
Descargando archivo: u7iavi1567u1515bb.bin [ 838538B]
22% [u7iavi1567u1515bb.bin 1% 11.04KB/818.
28% [u7iavi1

162.34KB/818.88KB] 5.77KB/s 47s
43% [u7iavi1567u1515bb.bin 28% 230.22KB/818.88KB] 7.65KB/s 38
51% [u7iavi1567u1515bb.bin 38

.88KB] 12.25KB/s 20s
vi1567u1515bb.bin 60% 496.51KB/818.88KB] 13.29KB/s 16s
73% [u7iavi1567u1515bb.bin 66% 545.55KB
79% [
28KB/s 8s
b.bin 88% 723.73KB/818.88KB] 16.42KB/s 4s
99% [u7iavi1567u1515bb.bin 99% 811.40KB/818.88KB] 17
Actualizando...
La actualización en línea finalizó correctamente.
[10:36:07(godo@alpechin)~]>


[[https://docs.google.com/forms/d/e/1FAIpQLSeGnXB3zyaNVYcb_2EoO8C5HRc6Emx-2rv2QS6OWNFz1yYSBQ/viewform?usp=pp_url&entry.55081144=Los%20antivirus%20y%20GNU%2FLinux][Dejar comentario]].

