#+title: AndLinux, de Jaunty a Karmic
#+date: <2011-10-21 13:49>
#+author: Godofredo Fdez.
#+description: [11:44:15(root@andLinux)/home/godo]> apt-get update Ign http://us.archive.ubuntu.com jaunty Release.gpg Ign http://us.archive.ubuntu.com jaunty/main Translation-es Ign http://us.archive.ubuntu.com jaunty/restricted Translation-es Ign http://security.ubuntu.com jaunty-security Release.gpg Ign http://security.ubuntu.com jaunty-security/main Translation-es Ign http://security.ubuntu.com jaunty-security/restricted Translation-es
#+filetags: 
#+options: _:nil
#+nid: 432

[11:44:15(root@andLinux)/home/godo]> apt-get update
Ign http://us.archive.ubuntu.com jaunty Release.gpg
Ign http://us.archive.ubuntu.com jaunty/main Translation-es
Ign http://us.archive.ubuntu.com jaunty/restricted Translation-es
Ign http://security.ubuntu.com jaunty-security Release.gpg
Ign http://security.ubuntu.com jaunty-security/main Translation-es
Ign http://security.ubuntu.com jaunty-security/restricted Translation-es
Ign http://us.archive.ubuntu.com jaunty/universe Translation-es
Ign http://us.archive.ubuntu.com jaunty/multiverse Translation-es
Ign http://us.archive.ubuntu.com jaunty-updates Release.gpg
Ign http://us.archive.ubuntu.com jaunty-updates/main Translation-es
Ign http://us.archive.ubuntu.com jaunty-updates/restricted Translation-es
Ign http://us.archive.ubuntu.com jaunty-updates/universe Translation-es
Ign http://us.archive.ubuntu.com jaunty-updates/multiverse Translation-es
Ign http://security.ubuntu.com jaunty-security/universe Translation-es
Ign http://security.ubuntu.com jaunty-security/multiverse Translation-es
Ign http://security.ubuntu.com jaunty-security Release
Ign http://us.archive.ubuntu.com jaunty Release
Ign http://us.archive.ubuntu.com jaunty-updates Release
Ign http://security.ubuntu.com jaunty-security/main Packages
Ign http://us.archive.ubuntu.com jaunty/main Packages
Ign http://us.archive.ubuntu.com jaunty/restricted Packages
Ign http://us.archive.ubuntu.com jaunty/universe Packages
Ign http://us.archive.ubuntu.com jaunty/multiverse Packages
Ign http://security.ubuntu.com jaunty-security/restricted Packages
Ign http://security.ubuntu.com jaunty-security/universe Packages
Ign http://security.ubuntu.com jaunty-security/multiverse Packages
Ign http://us.archive.ubuntu.com jaunty-updates/main Packages
Ign http://us.archive.ubuntu.com jaunty-updates/restricted Packages
Ign http://us.archive.ubuntu.com jaunty-updates/universe Packages
Err http://security.ubuntu.com jaunty-security/main Packages
404 Not Found [IP: 91.189.92.167 80]
Err http://security.ubuntu.com jaunty-security/restricted Packages
404 Not Found [IP: 91.189.92.167 80]
Ign http://us.archive.ubuntu.com jaunty-updates/multiverse Packages
Err http://us.archive.ubuntu.com jaunty/main Packages
404 Not Found [IP: 91.189.92.183 80]
Err http://us.archive.ubuntu.com jaunty/restricted Packages
404 Not Found [IP: 91.189.92.183 80]
Err http://us.archive.ubuntu.com jaunty/universe Packages
404 Not Found [IP: 91.189.92.183 80]
Err http://us.archive.ubuntu.com jaunty/multiverse Packages
404 Not Found [IP: 91.189.92.183 80]
Err http://security.ubuntu.com jaunty-security/universe Packages
404 Not Found [IP: 91.189.92.167 80]
Err http://us.archive.ubuntu.com jaunty-updates/main Packages
404 Not Found [IP: 91.189.92.183 80]
Err http://us.archive.ubuntu.com jaunty-updates/restricted Packages
404 Not Found [IP: 91.189.92.183 80]
Err http://us.archive.ubuntu.com jaunty-updates/universe Packages
404 Not Found [IP: 91.189.92.183 80]
Err http://us.archive.ubuntu.com jaunty-updates/multiverse Packages
404 Not Found [IP: 91.189.92.183 80]
Err http://security.ubuntu.com jaunty-security/multiverse Packages
404 Not Found [IP: 91.189.92.167 80]
W: Imposible obtener http://security.ubuntu.com/ubuntu/dists/jaunty-security/main/binary-i386/Packages 404 Not Found [IP: 91.189.92.167 80]

W: Imposible obtener http://us.archive.ubuntu.com/ubuntu/dists/jaunty/main/binary-i386/Packages 404 Not Found [IP: 91.189.92.183 80]

W: Imposible obtener http://us.archive.ubuntu.com/ubuntu/dists/jaunty/restricted/binary-i386/Packages 404 Not Found [IP: 91.189.92.183 80]

W: Imposible obtener http://us.archive.ubuntu.com/ubuntu/dists/jaunty/universe/binary-i386/Packages 404 Not Found [IP: 91.189.92.183 80]

W: Imposible obtener http://us.archive.ubuntu.com/ubuntu/dists/jaunty/multiverse/binary-i386/Packages 404 Not Found [IP: 91.189.92.183 80]

W: Imposible obtener http://security.ubuntu.com/ubuntu/dists/jaunty-security/restricted/binary-i386/Packages 404 Not Found [IP: 91.189.92.167 80]

W: Imposible obtener http://security.ubuntu.com/ubuntu/dists/jaunty-security/universe/binary-i386/Packages 404 Not Found [IP: 91.189.92.167 80]

W: Imposible obtener http://security.ubuntu.com/ubuntu/dists/jaunty-security/multiverse/binary-i386/Packages 404 Not Found [IP: 91.189.92.167 80]

W: Imposible obtener http://us.archive.ubuntu.com/ubuntu/dists/jaunty-updates/main/binary-i386/Packages 404 Not Found [IP: 91.189.92.183 80]

W: Imposible obtener http://us.archive.ubuntu.com/ubuntu/dists/jaunty-updates/restricted/binary-i386/Packages 404 Not Found [IP: 91.189.92.183 80]

W: Imposible obtener http://us.archive.ubuntu.com/ubuntu/dists/jaunty-updates/universe/binary-i386/Packages 404 Not Found [IP: 91.189.92.183 80]

W: Imposible obtener http://us.archive.ubuntu.com/ubuntu/dists/jaunty-updates/multiverse/binary-i386/Packages 404 Not Found [IP: 91.189.92.183 80]

E: Algunos archivos de índice no se han podido descargar, se han ignorado,
o se ha utilizado unos antiguos en su lugar.
[11:44:20(root@andLinux)/home/godo]>
[11:44:21(root@andLinux)/home/godo]>
[11:44:21(root@andLinux)/home/godo]>
[11:44:21(root@andLinux)/home/godo]> au
Leyendo lista de paquetes... Hecho
Creando árbol de dependencias
Leyendo la información de estado... Hecho
0 actualizados, 0 se instalarán, 0 para eliminar y 0 no actualizados.
[11:44:30(root@andLinux)/home/godo]> exit
exit
[11:44:39(godo@andLinux)~]> clear
[11:44:41(godo@andLinux)~]> sudo su
[11:44:44(root@andLinux)/home/godo]> apt-get update
Ign http://security.ubuntu.com jaunty-security Release.gpg
Ign http://security.ubuntu.com jaunty-security/main Translation-es
Ign http://security.ubuntu.com jaunty-security/restricted Translation-es
Ign http://us.archive.ubuntu.com jaunty Release.gpg
Ign http://us.archive.ubuntu.com jaunty/main Translation-es
Ign http://us.archive.ubuntu.com jaunty/restricted Translation-es
Ign http://security.ubuntu.com jaunty-security/universe Translation-es
Ign http://security.ubuntu.com jaunty-security/multiverse Translation-es
Ign http://security.ubuntu.com jaunty-security Release
Ign http://us.archive.ubuntu.com jaunty/universe Translation-es
Ign http://us.archive.ubuntu.com jaunty/multiverse Translation-es
Ign http://us.archive.ubuntu.com jaunty-updates Release.gpg
Ign http://us.archive.ubuntu.com jaunty-updates/main Translation-es
Ign http://us.archive.ubuntu.com jaunty-updates/restricted Translation-es
Ign http://us.archive.ubuntu.com jaunty-updates/universe Translation-es
Ign http://us.archive.ubuntu.com jaunty-updates/multiverse Translation-es
Ign http://security.ubuntu.com jaunty-security/main Packages
Ign http://us.archive.ubuntu.com jaunty Release
Ign http://us.archive.ubuntu.com jaunty-updates Release
Ign http://security.ubuntu.com jaunty-security/restricted Packages
Ign http://security.ubuntu.com jaunty-security/universe Packages
Ign http://security.ubuntu.com jaunty-security/multiverse Packages
Ign http://us.archive.ubuntu.com jaunty/main Packages
Ign http://us.archive.ubuntu.com jaunty/restricted Packages
Ign http://us.archive.ubuntu.com jaunty/universe Packages
Ign http://us.archive.ubuntu.com jaunty/multiverse Packages
Err http://security.ubuntu.com jaunty-security/main Packages
404 Not Found [IP: 91.189.92.167 80]
Err http://security.ubuntu.com jaunty-security/restricted Packages
404 Not Found [IP: 91.189.92.167 80]
Ign http://us.archive.ubuntu.com jaunty-updates/main Packages
Ign http://us.archive.ubuntu.com jaunty-updates/restricted Packages
Ign http://us.archive.ubuntu.com jaunty-updates/universe Packages
Err http://security.ubuntu.com jaunty-security/universe Packages
404 Not Found [IP: 91.189.92.167 80]
Ign http://us.archive.ubuntu.com jaunty-updates/multiverse Packages
Err http://us.archive.ubuntu.com jaunty/main Packages
404 Not Found [IP: 91.189.92.183 80]
Err http://us.archive.ubuntu.com jaunty/restricted Packages
404 Not Found [IP: 91.189.92.183 80]
Err http://us.archive.ubuntu.com jaunty/universe Packages
404 Not Found [IP: 91.189.92.183 80]
Err http://us.archive.ubuntu.com jaunty/multiverse Packages
404 Not Found [IP: 91.189.92.183 80]
Err http://security.ubuntu.com jaunty-security/multiverse Packages
404 Not Found [IP: 91.189.92.167 80]
Err http://us.archive.ubuntu.com jaunty-updates/main Packages
404 Not Found [IP: 91.189.92.183 80]
Err http://us.archive.ubuntu.com jaunty-updates/restricted Packages
404 Not Found [IP: 91.189.92.183 80]
Err http://us.archive.ubuntu.com jaunty-updates/universe Packages
404 Not Found [IP: 91.189.92.183 80]
Err http://us.archive.ubuntu.com jaunty-updates/multiverse Packages
404 Not Found [IP: 91.189.92.183 80]
W: Imposible obtener http://security.ubuntu.com/ubuntu/dists/jaunty-security/main/binary-i386/Packages 404 Not Found [IP: 91.189.92.167 80]

W: Imposible obtener http://security.ubuntu.com/ubuntu/dists/jaunty-security/restricted/binary-i386/Packages 404 Not Found [IP: 91.189.92.167 80]

W: Imposible obtener http://security.ubuntu.com/ubuntu/dists/jaunty-security/universe/binary-i386/Packages 404 Not Found [IP: 91.189.92.167 80]

W: Imposible obtener http://security.ubuntu.com/ubuntu/dists/jaunty-security/multiverse/binary-i386/Packages 404 Not Found [IP: 91.189.92.167 80]

W: Imposible obtener http://us.archive.ubuntu.com/ubuntu/dists/jaunty/main/binary-i386/Packages 404 Not Found [IP: 91.189.92.183 80]

W: Imposible obtener http://us.archive.ubuntu.com/ubuntu/dists/jaunty/restricted/binary-i386/Packages 404 Not Found [IP: 91.189.92.183 80]

W: Imposible obtener http://us.archive.ubuntu.com/ubuntu/dists/jaunty/universe/binary-i386/Packages 404 Not Found [IP: 91.189.92.183 80]

W: Imposible obtener http://us.archive.ubuntu.com/ubuntu/dists/jaunty/multiverse/binary-i386/Packages 404 Not Found [IP: 91.189.92.183 80]

W: Imposible obtener http://us.archive.ubuntu.com/ubuntu/dists/jaunty-updates/main/binary-i386/Packages 404 Not Found [IP: 91.189.92.183 80]

W: Imposible obtener http://us.archive.ubuntu.com/ubuntu/dists/jaunty-updates/restricted/binary-i386/Packages 404 Not Found [IP: 91.189.92.183 80]

W: Imposible obtener http://us.archive.ubuntu.com/ubuntu/dists/jaunty-updates/universe/binary-i386/Packages 404 Not Found [IP: 91.189.92.183 80]

W: Imposible obtener http://us.archive.ubuntu.com/ubuntu/dists/jaunty-updates/multiverse/binary-i386/Packages 404 Not Found [IP: 91.189.92.183 80]

E: Algunos archivos de índice no se han podido descargar, se han ignorado,
o se ha utilizado unos antiguos en su lugar.
[11:44:51(root@andLinux)/home/godo]> apt-get upgrade
Leyendo lista de paquetes... Hecho
Creando árbol de dependencias
Leyendo la información de estado... Hecho
0 actualizados, 0 se instalarán, 0 para eliminar y 0 no actualizados.
[11:44:56(root@andLinux)/home/godo]>
[11:44:57(root@andLinux)/home/godo]>

[11:52:54(root@andLinux)/home/godo]> actualizamos sources.list
bash: actualizamos: orden no encontrada
[11:53:02(root@andLinux)/home/godo]>
[11:53:03(root@andLinux)/home/godo]>
[11:53:03(root@andLinux)/home/godo]> apt-get update
Des:1 http://us.archive.ubuntu.com karmic Release.gpg [189B]
Des:2 http://us.archive.ubuntu.com karmic/main Translation-es [775kB]
Des:3 http://us.archive.ubuntu.com karmic/restricted Translation-es [3830B]
Des:4 http://us.archive.ubuntu.com karmic/universe Translation-es [1678kB]
Des:5 http://us.archive.ubuntu.com karmic/multiverse Translation-es [128kB]
Des:6 http://us.archive.ubuntu.com karmic-updates Release.gpg [198B]
Ign http://us.archive.ubuntu.com karmic-updates/main Translation-es
Ign http://us.archive.ubuntu.com karmic-updates/restricted Translation-es
Ign http://us.archive.ubuntu.com karmic-updates/universe Translation-es
Ign http://us.archive.ubuntu.com karmic-updates/multiverse Translation-es
Des:7 http://us.archive.ubuntu.com karmic-security Release.gpg [198B]
Ign http://us.archive.ubuntu.com karmic-security/main Translation-es
Ign http://us.archive.ubuntu.com karmic-security/restricted Translation-es
Ign http://us.archive.ubuntu.com karmic-security/universe Translation-es
Ign http://us.archive.ubuntu.com karmic-security/multiverse Translation-es
Des:8 http://us.archive.ubuntu.com karmic Release [65,9kB]
Des:9 http://us.archive.ubuntu.com karmic-updates Release [51,3kB]
Des:10 http://us.archive.ubuntu.com karmic-security Release [51,3kB]
Des:11 http://us.archive.ubuntu.com karmic/main Packages [1737kB]
Des:12 http://us.archive.ubuntu.com karmic/restricted Packages [8108B]
Des:13 http://us.archive.ubuntu.com karmic/universe Packages [6645kB]
Des:14 http://us.archive.ubuntu.com karmic/multiverse Packages [249kB]
Des:15 http://us.archive.ubuntu.com karmic-updates/main Packages [438kB]
Des:16 http://us.archive.ubuntu.com karmic-updates/restricted Packages [1395B]
Des:17 http://us.archive.ubuntu.com karmic-updates/universe Packages [251kB]
Des:18 http://us.archive.ubuntu.com karmic-updates/multiverse Packages [14,3kB]
Des:19 http://us.archive.ubuntu.com karmic-security/main Packages [298kB]
Des:20 http://us.archive.ubuntu.com karmic-security/restricted Packages [20B]
Des:21 http://us.archive.ubuntu.com karmic-security/universe Packages [132kB]
Des:22 http://us.archive.ubuntu.com karmic-security/multiverse Packages [7062B]
Descargados 12,5MB en 1min 5s (191kB/s)
Leyendo lista de paquetes... Hecho
[11:54:22(root@andLinux)/home/godo]>
[11:54:24(root@andLinux)/home/godo]>
[11:54:24(root@andLinux)/home/godo]> apt-get install gdb gcc
Leyendo lista de paquetes... Hecho
Creando árbol de dependencias
Leyendo la información de estado... Hecho
Se instalarán los siguientes paquetes extras:
binutils cpp cpp-4.4 gcc-4.4 gcc-4.4-base libgcc1 libgomp1 libreadline6
Paquetes sugeridos:
binutils-doc cpp-doc gcc-4.4-locales gcc-multilib manpages-dev autoconf automake1.9 libtool
flex bison gcc-doc gcc-4.4-multilib libmudflap0-4.4-dev gcc-4.4-doc libgcc1-dbg
libgomp1-dbg libmudflap0-dbg libcloog-ppl0 libppl-c2 libppl7 gdb-doc
Se instalarán los siguientes paquetes NUEVOS:
cpp-4.4 gcc-4.4 gcc-4.4-base gdb libreadline6
Se actualizarán los siguientes paquetes:
binutils cpp gcc libgcc1 libgomp1
5 actualizados, 5 se instalarán, 0 para eliminar y 645 no actualizados.
Necesito descargar 10,4MB de archivos.
Se utilizarán 19,3MB de espacio de disco adicional después de esta operación.
¿Desea continuar [S/n]? n
Abortado.
[11:55:35(root@andLinux)/home/godo]> apt-get install gdb
Leyendo lista de paquetes... Hecho
Creando árbol de dependencias
Leyendo la información de estado... Hecho
Se instalarán los siguientes paquetes extras:
libreadline6
Paquetes sugeridos:
gdb-doc
Se instalarán los siguientes paquetes NUEVOS:
gdb libreadline6
0 actualizados, 2 se instalarán, 0 para eliminar y 650 no actualizados.
Necesito descargar 2038kB de archivos.
Se utilizarán 4342kB de espacio de disco adicional después de esta operación.
¿Desea continuar [S/n]?
[11:55:55(root@andLinux)/home/godo]> apt-get install gdb gcc
Leyendo lista de paquetes... Hecho
Creando árbol de dependencias
Leyendo la información de estado... Hecho
Se instalarán los siguientes paquetes extras:
binutils cpp cpp-4.4 gcc-4.4 gcc-4.4-base libgcc1 libgomp1 libreadline6
Paquetes sugeridos:
binutils-doc cpp-doc gcc-4.4-locales gcc-multilib manpages-dev autoconf automake1.9 libtool
flex bison gcc-doc gcc-4.4-multilib libmudflap0-4.4-dev gcc-4.4-doc libgcc1-dbg
libgomp1-dbg libmudflap0-dbg libcloog-ppl0 libppl-c2 libppl7 gdb-doc
Se instalarán los siguientes paquetes NUEVOS:
cpp-4.4 gcc-4.4 gcc-4.4-base gdb libreadline6
Se actualizarán los siguientes paquetes:
binutils cpp gcc libgcc1 libgomp1
5 actualizados, 5 se instalarán, 0 para eliminar y 645 no actualizados.
Necesito descargar 10,4MB de archivos.
Se utilizarán 19,3MB de espacio de disco adicional después de esta operación.
¿Desea continuar [S/n]?
Des:1 http://us.archive.ubuntu.com karmic-updates/main gcc-4.4-base 4.4.1-4ubuntu9 [113kB]
Des:2 http://us.archive.ubuntu.com karmic-updates/main libgcc1 1:4.4.1-4ubuntu9 [55,0kB]
Des:3 http://us.archive.ubuntu.com karmic/main libreadline6 6.0-5 [146kB]
Des:4 http://us.archive.ubuntu.com karmic-updates/main cpp-4.4 4.4.1-4ubuntu9 [3544kB]
Des:5 http://us.archive.ubuntu.com karmic/main cpp 4:4.4.1-1ubuntu2 [35,9kB]
Des:6 http://us.archive.ubuntu.com karmic-updates/main binutils 2.20-0ubuntu2 [1599kB]
Des:7 http://us.archive.ubuntu.com karmic-updates/main libgomp1 4.4.1-4ubuntu9 [24,2kB]
Des:8 http://us.archive.ubuntu.com karmic-updates/main gcc-4.4 4.4.1-4ubuntu9 [2976kB]
Des:9 http://us.archive.ubuntu.com karmic/main gcc 4:4.4.1-1ubuntu2 [5078B]
Des:10 http://us.archive.ubuntu.com karmic/main gdb 7.0-0ubuntu1 [1892kB]
Descargados 10,4MB en 49s (210kB/s)
Seleccionando el paquete gcc-4.4-base previamente no seleccionado.
(Leyendo la base de datos ...
107530 ficheros y directorios instalados actualmente.)
Desempaquetando gcc-4.4-base (de .../gcc-4.4-base_4.4.1-4ubuntu9_i386.deb) ...
Configurando gcc-4.4-base (4.4.1-4ubuntu9) ...
(Leyendo la base de datos ...
107538 ficheros y directorios instalados actualmente.)
Preparando para reemplazar libgcc1 1:4.3.3-5ubuntu4 (usando .../libgcc1_1%3a4.4.1-4ubuntu9_i386.deb) ...
Desempaquetando el reemplazo de libgcc1 ...
Configurando libgcc1 (1:4.4.1-4ubuntu9) ...

Procesando disparadores para libc6 ...
ldconfig deferred processing now taking place
Seleccionando el paquete libreadline6 previamente no seleccionado.
(Leyendo la base de datos ...
107538 ficheros y directorios instalados actualmente.)
Desempaquetando libreadline6 (de .../libreadline6_6.0-5_i386.deb) ...
Seleccionando el paquete cpp-4.4 previamente no seleccionado.
Desempaquetando cpp-4.4 (de .../cpp-4.4_4.4.1-4ubuntu9_i386.deb) ...
Preparando para reemplazar cpp 4:4.3.3-1ubuntu1 (usando .../cpp_4%3a4.4.1-1ubuntu2_i386.deb) ...
Desempaquetando el reemplazo de cpp ...
Preparando para reemplazar binutils 2.19.1-0ubuntu3 (usando .../binutils_2.20-0ubuntu2_i386.deb) ...
Desempaquetando el reemplazo de binutils ...
Preparando para reemplazar libgomp1 4.3.3-5ubuntu4 (usando .../libgomp1_4.4.1-4ubuntu9_i386.deb) ...
Desempaquetando el reemplazo de libgomp1 ...
Seleccionando el paquete gcc-4.4 previamente no seleccionado.
Desempaquetando gcc-4.4 (de .../gcc-4.4_4.4.1-4ubuntu9_i386.deb) ...
Preparando para reemplazar gcc 4:4.3.3-1ubuntu1 (usando .../gcc_4%3a4.4.1-1ubuntu2_i386.deb) ...
Removing old gcc doc directory.
Desempaquetando el reemplazo de gcc ...
Seleccionando el paquete gdb previamente no seleccionado.
Desempaquetando gdb (de .../gdb_7.0-0ubuntu1_i386.deb) ...
Procesando disparadores para man-db ...
Configurando libreadline6 (6.0-5) ...

Configurando cpp-4.4 (4.4.1-4ubuntu9) ...
Configurando cpp (4:4.4.1-1ubuntu2) ...

Configurando binutils (2.20-0ubuntu2) ...

Configurando libgomp1 (4.4.1-4ubuntu9) ...

Configurando gcc-4.4 (4.4.1-4ubuntu9) ...
Configurando gcc (4:4.4.1-1ubuntu2) ...

Configurando gdb (7.0-0ubuntu1) ...

Procesando disparadores para libc6 ...
ldconfig deferred processing now taking place
[11:58:04(root@andLinux)/home/godo]>
[12:08:04(root@andLinux)/home/godo]>
[12:08:04(root@andLinux)/home/godo]>
[12:08:04(root@andLinux)/home/godo]> apt-get install octave
Leyendo lista de paquetes... Hecho
Creando árbol de dependencias
Leyendo la información de estado... Hecho
El paquete octave es un paquete virtual provisto por:
octave3.2 3.2.2-2build1
octave3.0 1:3.0.5-6ubuntu2
Necesita seleccionar explícitamente uno para instalar.
E: El paquete octave no tiene candidato para su instalación
[12:08:18(root@andLinux)/home/godo]> apt-get install octave3.2
Leyendo lista de paquetes... Hecho
Creando árbol de dependencias
Leyendo la información de estado... Hecho
Se instalarán los siguientes paquetes extras:
gnuplot gnuplot-nox gnuplot-x11 groff groff-base libamd2.2.0 libarpack2 libatlas3gf-base
libblas3gf libc-bin libc-dev-bin libc6 libc6-dev libc6-i686 libcamd2.2.0 libccolamd2.7.1
libcholmod1.7.1 libcolamd2.7.1 libcups2 libcxsparse2.2.3 libfltk1.1 libftgl2 libgcrypt11
libgfortran3 libglib2.0-0 libglpk0 libgnutls26 libgpg-error0 libgraphicsmagick++3
libgraphicsmagick3 libgssapi-krb5-2 libgtk2.0-0 libhdf5-serial-1.6.6-0 libibverbs1
libk5crypto3 libkrb5-3 libkrb5support0 liblapack3gf libopenmpi1.3 libqhull5 libqrupdate1
libselinux1 libstdc++6 libtasn1-3 libumfpack5.4.0 libwxbase2.8-0 libwxgtk2.8-0
octave3.2-common
Paquetes sugeridos:
gnuplot-doc libatlas3gf-3dnow libatlas3gf-sse libatlas3gf-sse2 glibc-doc manpages-dev
rng-tools libiodbc2-dev libmysqlclient15-dev gnutls-bin graphicsmagick-dbg krb5-doc
krb5-user librsvg2-common gvfs libgnomeprintui2.2-0 octave3.2-info octave3.2-doc
octave3.2-htmldoc octave3.2-headers octave3.2-emacsen
Paquetes recomendados
atlas3-base libglib2.0-data
Los siguientes paquetes se ELIMINARÁN:
belocs-locales-bin
Se instalarán los siguientes paquetes NUEVOS:
gnuplot gnuplot-nox gnuplot-x11 groff libamd2.2.0 libarpack2 libatlas3gf-base libblas3gf
libc-bin libc-dev-bin libc6-i686 libcamd2.2.0 libccolamd2.7.1 libcholmod1.7.1
libcolamd2.7.1 libcxsparse2.2.3 libfltk1.1 libftgl2 libgfortran3 libglpk0
libgraphicsmagick++3 libgraphicsmagick3 libgssapi-krb5-2 libhdf5-serial-1.6.6-0 libibverbs1
libk5crypto3 libkrb5-3 libkrb5support0 liblapack3gf libopenmpi1.3 libqhull5 libqrupdate1
libumfpack5.4.0 libwxbase2.8-0 libwxgtk2.8-0 octave3.2 octave3.2-common
Se actualizarán los siguientes paquetes:
groff-base libc6 libc6-dev libcups2 libgcrypt11 libglib2.0-0 libgnutls26 libgpg-error0
libgtk2.0-0 libselinux1 libstdc++6 libtasn1-3
12 actualizados, 37 se instalarán, 1 para eliminar y 633 no actualizados.
Necesito descargar 50,9MB de archivos.
Se utilizarán 110MB de espacio de disco adicional después de esta operación.
¿Desea continuar [S/n]? n
Abortado.
[12:08:43(root@andLinux)/home/godo]> df
S.ficheros Tamaño Usado Disp Uso% Montado en
/dev/cobd0 4,0G 2,4G 1,6G 61% /
tmpfs 125M 0 125M 0% /lib/init/rw
varrun 125M 76K 125M 1% /var/run
varlock 125M 0 125M 0% /var/lock
udev 125M 228K 125M 1% /dev
tmpfs 125M 0 125M 0% /dev/shm
31 39G 23G 17G 59% /mnt/and
/dev/cofs0 73G 16G 58G 22% /mnt/win
[12:08:44(root@andLinux)/home/godo]> apt-get install octave3.2
Leyendo lista de paquetes... Hecho
Creando árbol de dependencias
Leyendo la información de estado... Hecho
Se instalarán los siguientes paquetes extras:
gnuplot gnuplot-nox gnuplot-x11 groff groff-base libamd2.2.0 libarpack2 libatlas3gf-base
libblas3gf libc-bin libc-dev-bin libc6 libc6-dev libc6-i686 libcamd2.2.0 libccolamd2.7.1
libcholmod1.7.1 libcolamd2.7.1 libcups2 libcxsparse2.2.3 libfltk1.1 libftgl2 libgcrypt11
libgfortran3 libglib2.0-0 libglpk0 libgnutls26 libgpg-error0 libgraphicsmagick++3
libgraphicsmagick3 libgssapi-krb5-2 libgtk2.0-0 libhdf5-serial-1.6.6-0 libibverbs1
libk5crypto3 libkrb5-3 libkrb5support0 liblapack3gf libopenmpi1.3 libqhull5 libqrupdate1
libselinux1 libstdc++6 libtasn1-3 libumfpack5.4.0 libwxbase2.8-0 libwxgtk2.8-0
octave3.2-common
Paquetes sugeridos:
gnuplot-doc libatlas3gf-3dnow libatlas3gf-sse libatlas3gf-sse2 glibc-doc manpages-dev
rng-tools libiodbc2-dev libmysqlclient15-dev gnutls-bin graphicsmagick-dbg krb5-doc
krb5-user librsvg2-common gvfs libgnomeprintui2.2-0 octave3.2-info octave3.2-doc
octave3.2-htmldoc octave3.2-headers octave3.2-emacsen
Paquetes recomendados
atlas3-base libglib2.0-data
Los siguientes paquetes se ELIMINARÁN:
belocs-locales-bin
Se instalarán los siguientes paquetes NUEVOS:
gnuplot gnuplot-nox gnuplot-x11 groff libamd2.2.0 libarpack2 libatlas3gf-base libblas3gf
libc-bin libc-dev-bin libc6-i686 libcamd2.2.0 libccolamd2.7.1 libcholmod1.7.1
libcolamd2.7.1 libcxsparse2.2.3 libfltk1.1 libftgl2 libgfortran3 libglpk0
libgraphicsmagick++3 libgraphicsmagick3 libgssapi-krb5-2 libhdf5-serial-1.6.6-0 libibverbs1
libk5crypto3 libkrb5-3 libkrb5support0 liblapack3gf libopenmpi1.3 libqhull5 libqrupdate1
libumfpack5.4.0 libwxbase2.8-0 libwxgtk2.8-0 octave3.2 octave3.2-common
Se actualizarán los siguientes paquetes:
groff-base libc6 libc6-dev libcups2 libgcrypt11 libglib2.0-0 libgnutls26 libgpg-error0
libgtk2.0-0 libselinux1 libstdc++6 libtasn1-3
12 actualizados, 37 se instalarán, 1 para eliminar y 633 no actualizados.
Necesito descargar 50,9MB de archivos.
Se utilizarán 110MB de espacio de disco adicional después de esta operación.
¿Desea continuar [S/n]?
Des:1 http://us.archive.ubuntu.com karmic-updates/main libc-dev-bin 2.10.1-0ubuntu19 [207kB]
Des:2 http://us.archive.ubuntu.com karmic-updates/main libc6-dev 2.10.1-0ubuntu19 [4762kB]
Des:3 http://us.archive.ubuntu.com karmic-updates/main libc-bin 2.10.1-0ubuntu19 [715kB]
Des:4 http://us.archive.ubuntu.com karmic-updates/main libc6 2.10.1-0ubuntu19 [3760kB]
Des:5 http://us.archive.ubuntu.com karmic-updates/main libc6-i686 2.10.1-0ubuntu19 [1199kB]
Des:6 http://us.archive.ubuntu.com karmic/main libselinux1 2.0.85-2ubuntu2 [79,4kB]
Des:7 http://us.archive.ubuntu.com karmic-updates/main libstdc++6 4.4.1-4ubuntu9 [346kB]
Des:8 http://us.archive.ubuntu.com karmic/main libgpg-error0 1.6-1ubuntu1 [18,5kB]
Des:9 http://us.archive.ubuntu.com karmic/main libgcrypt11 1.4.4-2ubuntu2 [267kB]
Des:10 http://us.archive.ubuntu.com karmic-updates/main libglib2.0-0 2.22.3-0ubuntu1 [913kB]
Des:11 http://us.archive.ubuntu.com karmic/main libtasn1-3 2.2-1 [54,5kB]
Des:12 http://us.archive.ubuntu.com karmic/main libgnutls26 2.8.3-2 [406kB]
Des:13 http://us.archive.ubuntu.com karmic/main groff-base 1.20.1-5 [1091kB]
Des:14 http://us.archive.ubuntu.com karmic-updates/main libkrb5support0 1.7dfsg~beta3-1ubuntu0.13 [41,4kB]
Des:15 http://us.archive.ubuntu.com karmic-updates/main libk5crypto3 1.7dfsg~beta3-1ubuntu0.13 [103kB]
Des:16 http://us.archive.ubuntu.com karmic-updates/main libkrb5-3 1.7dfsg~beta3-1ubuntu0.13 [339kB]
Des:17 http://us.archive.ubuntu.com karmic-updates/main libgssapi-krb5-2 1.7dfsg~beta3-1ubuntu0.13 [110kB]
Des:18 http://us.archive.ubuntu.com karmic/universe gnuplot-nox 4.2.5-2 [831kB]
Des:19 http://us.archive.ubuntu.com karmic/universe libwxbase2.8-0 2.8.10.1-0ubuntu1 [689kB]
Des:20 http://us.archive.ubuntu.com karmic-updates/main libcups2 1.4.1-5ubuntu2.7 [213kB]
Des:21 http://us.archive.ubuntu.com karmic-updates/main libgtk2.0-0 2.18.3-1ubuntu2.2 [2352kB]
Des:22 http://us.archive.ubuntu.com karmic/universe libwxgtk2.8-0 2.8.10.1-0ubuntu1 [3455kB]
Des:23 http://us.archive.ubuntu.com karmic/universe gnuplot-x11 4.2.5-2 [724kB]
Des:24 http://us.archive.ubuntu.com karmic/universe gnuplot 4.2.5-2 [1064B]
Des:25 http://us.archive.ubuntu.com karmic/main groff 1.20.1-5 [3437kB]
Des:26 http://us.archive.ubuntu.com karmic/main libamd2.2.0 1:3.4.0-1ubuntu2 [21,2kB]
Des:27 http://us.archive.ubuntu.com karmic-updates/main libgfortran3 4.4.1-4ubuntu9 [240kB]
Des:28 http://us.archive.ubuntu.com karmic/main libblas3gf 1.2-2 [221kB]
Des:29 http://us.archive.ubuntu.com karmic/universe libatlas3gf-base 3.6.0-22ubuntu2 [5148kB]
Des:30 http://us.archive.ubuntu.com karmic/main liblapack3gf 3.2.1-1 [3116kB]
Des:31 http://us.archive.ubuntu.com karmic/universe libibverbs1 1.1.2-1ubuntu2 [28,6kB]
Des:32 http://us.archive.ubuntu.com karmic-updates/universe libopenmpi1.3 1.3.2-3ubuntu1.1 [1142kB]
Des:33 http://us.archive.ubuntu.com karmic/universe libarpack2 2.1+parpack96.dfsg-2build1 [252kB]
Des:34 http://us.archive.ubuntu.com karmic/main libcamd2.2.0 1:3.4.0-1ubuntu2 [19,1kB]
Des:35 http://us.archive.ubuntu.com karmic/main libccolamd2.7.1 1:3.4.0-1ubuntu2 [20,9kB]
Des:36 http://us.archive.ubuntu.com karmic/main libcolamd2.7.1 1:3.4.0-1ubuntu2 [16,4kB]
Des:37 http://us.archive.ubuntu.com karmic/main libcholmod1.7.1 1:3.4.0-1ubuntu2 [363kB]
Des:38 http://us.archive.ubuntu.com karmic/main libcxsparse2.2.3 1:3.4.0-1ubuntu2 [86,7kB]
Des:39 http://us.archive.ubuntu.com karmic/main libfltk1.1 1.1.9-6ubuntu2 [461kB]
Des:40 http://us.archive.ubuntu.com karmic/universe libftgl2 2.1.3~rc5-2 [109kB]
Des:41 http://us.archive.ubuntu.com karmic/universe libglpk0 4.38-1 [400kB]
Des:42 http://us.archive.ubuntu.com karmic/universe libgraphicsmagick3 1.3.5-5.1 [1290kB]
Des:43 http://us.archive.ubuntu.com karmic/universe libgraphicsmagick++3 1.3.5-5.1 [183kB]
Des:44 http://us.archive.ubuntu.com karmic/universe libhdf5-serial-1.6.6-0 1.6.6-4ubuntu2 [667kB]
Des:45 http://us.archive.ubuntu.com karmic/universe libqhull5 2009.1-1 [156kB]
Des:46 http://us.archive.ubuntu.com karmic/universe libqrupdate1 1.0.1-1 [57,4kB]
Des:47 http://us.archive.ubuntu.com karmic/main libumfpack5.4.0 1:3.4.0-1ubuntu2 [315kB]
Des:48 http://us.archive.ubuntu.com karmic/universe octave3.2-common 3.2.2-2build1 [670kB]
Des:49 http://us.archive.ubuntu.com karmic/universe octave3.2 3.2.2-2build1 [9761kB]
Descargados 50,9MB en 4min 6s (206kB/s)
Extrayendo plantillas para los paquetes: 100%
Preconfigurando paquetes ...
(Leyendo la base de datos ...
107662 ficheros y directorios instalados actualmente.)
Desinstalando belocs-locales-bin ...
Procesando disparadores para man-db ...
Seleccionando el paquete libc-dev-bin previamente no seleccionado.
(Leyendo la base de datos ...
107651 ficheros y directorios instalados actualmente.)
Desempaquetando libc-dev-bin (de .../libc-dev-bin_2.10.1-0ubuntu19_i386.deb) ...
Reemplazando ficheros del paquete antiguo libc6-dev ...
Preparando para reemplazar libc6-dev 2.9-4ubuntu6.3 (usando .../libc6-dev_2.10.1-0ubuntu19_i386.deb) ...
Desempaquetando el reemplazo de libc6-dev ...
Seleccionando el paquete libc-bin previamente no seleccionado.
dpkg: considerando la desconfiguración de libc6, ya que lo rompería la instalación de `libc-bin' ...
dpkg: sí, se desconfigurará libc6 (roto por libc-bin).
Desempaquetando libc-bin (de .../libc-bin_2.10.1-0ubuntu19_i386.deb) ...
Desconfigurando libc6 ...
Reemplazando ficheros del paquete antiguo libc6 ...
Procesando disparadores para man-db ...
Configurando libc-bin (2.10.1-0ubuntu19) ...
Instalando una nueva versión del fichero de configuración /etc/bindresvport.blacklist ...

(Leyendo la base de datos ...
107691 ficheros y directorios instalados actualmente.)
Preparando para reemplazar libc6 2.9-4ubuntu6.3 (usando .../libc6_2.10.1-0ubuntu19_i386.deb) ...
Removing obsolete conffile /etc/init.d/glibc.sh ...
Checking for services that may need to be restarted...
Checking init scripts...
Desempaquetando el reemplazo de libc6 ...
Procesando disparadores para man-db ...
Configurando libc6 (2.10.1-0ubuntu19) ...
Checking for services that may need to be restarted...
Checking init scripts...

Restarting services possibly affected by the upgrade:
ssh: stopping...starting...done.
rsync: stopping...starting...done.
cups: stopping...starting...done.
cron: stopping...starting...done.

Services restarted successfully.

Procesando disparadores para libc-bin ...
ldconfig deferred processing now taking place
Seleccionando el paquete libc6-i686 previamente no seleccionado.
(Leyendo la base de datos ...
107679 ficheros y directorios instalados actualmente.)
Desempaquetando libc6-i686 (de .../libc6-i686_2.10.1-0ubuntu19_i386.deb) ...
Preparando para reemplazar libselinux1 2.0.65-5build1 (usando .../libselinux1_2.0.85-2ubuntu2_i386.deb) ...
Desempaquetando el reemplazo de libselinux1 ...
Configurando libselinux1 (2.0.85-2ubuntu2) ...

Procesando disparadores para libc-bin ...
ldconfig deferred processing now taking place
(Leyendo la base de datos ...
107731 ficheros y directorios instalados actualmente.)
Preparando para reemplazar libstdc++6 4.3.3-5ubuntu4 (usando .../libstdc++6_4.4.1-4ubuntu9_i386.deb) ...
Desempaquetando el reemplazo de libstdc++6 ...
Configurando libstdc++6 (4.4.1-4ubuntu9) ...

Procesando disparadores para libc-bin ...
ldconfig deferred processing now taking place
(Leyendo la base de datos ...
107731 ficheros y directorios instalados actualmente.)
Preparando para reemplazar libgpg-error0 1.4-2ubuntu7 (usando .../libgpg-error0_1.6-1ubuntu1_i386.deb) ...
Desempaquetando el reemplazo de libgpg-error0 ...
Preparando para reemplazar libgcrypt11 1.4.1-2ubuntu1 (usando .../libgcrypt11_1.4.4-2ubuntu2_i386.deb) ...
Desempaquetando el reemplazo de libgcrypt11 ...
Preparando para reemplazar libglib2.0-0 2.20.1-0ubuntu2.1 (usando .../libglib2.0-0_2.22.3-0ubuntu1_i386.deb) ...
Desempaquetando el reemplazo de libglib2.0-0 ...
Preparando para reemplazar libtasn1-3 1.5-1 (usando .../libtasn1-3_2.2-1_i386.deb) ...
Desempaquetando el reemplazo de libtasn1-3 ...
Preparando para reemplazar libgnutls26 2.4.2-6ubuntu0.1 (usando .../libgnutls26_2.8.3-2_i386.deb) ...
Desempaquetando el reemplazo de libgnutls26 ...
Preparando para reemplazar groff-base 1.18.1.1-22build1 (usando .../groff-base_1.20.1-5_i386.deb) ...
Desempaquetando el reemplazo de groff-base ...
Seleccionando el paquete libkrb5support0 previamente no seleccionado.
Desempaquetando libkrb5support0 (de .../libkrb5support0_1.7dfsg~beta3-1ubuntu0.13_i386.deb) ...
Reemplazando ficheros del paquete antiguo libkrb53 ...
Seleccionando el paquete libk5crypto3 previamente no seleccionado.
Desempaquetando libk5crypto3 (de .../libk5crypto3_1.7dfsg~beta3-1ubuntu0.13_i386.deb) ...
Reemplazando ficheros del paquete antiguo libkrb53 ...
Seleccionando el paquete libkrb5-3 previamente no seleccionado.
Desempaquetando libkrb5-3 (de .../libkrb5-3_1.7dfsg~beta3-1ubuntu0.13_i386.deb) ...
Reemplazando ficheros del paquete antiguo libkrb53 ...
Seleccionando el paquete libgssapi-krb5-2 previamente no seleccionado.
Desempaquetando libgssapi-krb5-2 (de .../libgssapi-krb5-2_1.7dfsg~beta3-1ubuntu0.13_i386.deb) ...
Reemplazando ficheros del paquete antiguo libkrb53 ...
Seleccionando el paquete gnuplot-nox previamente no seleccionado.
Desempaquetando gnuplot-nox (de .../gnuplot-nox_4.2.5-2_i386.deb) ...
Seleccionando el paquete libwxbase2.8-0 previamente no seleccionado.
Desempaquetando libwxbase2.8-0 (de .../libwxbase2.8-0_2.8.10.1-0ubuntu1_i386.deb) ...
Preparando para reemplazar libcups2 1.3.9-17ubuntu3.9 (usando .../libcups2_1.4.1-5ubuntu2.7_i386.deb) ...
Desempaquetando el reemplazo de libcups2 ...
Preparando para reemplazar libgtk2.0-0 2.16.1-0ubuntu2 (usando .../libgtk2.0-0_2.18.3-1ubuntu2.2_i386.deb) ...
Desempaquetando el reemplazo de libgtk2.0-0 ...
Seleccionando el paquete libwxgtk2.8-0 previamente no seleccionado.
Desempaquetando libwxgtk2.8-0 (de .../libwxgtk2.8-0_2.8.10.1-0ubuntu1_i386.deb) ...
Seleccionando el paquete gnuplot-x11 previamente no seleccionado.
Desempaquetando gnuplot-x11 (de .../gnuplot-x11_4.2.5-2_i386.deb) ...
Añadiendo `diversion of /usr/bin/gnuplot to /usr/bin/gnuplot-nox by gnuplot-x11'
Añadiendo `diversion of /usr/share/man/man1/gnuplot.1.gz to /usr/share/man/man1/gnuplot-nox.1.gz by gnuplot-x11'
Seleccionando el paquete gnuplot previamente no seleccionado.
Desempaquetando gnuplot (de .../gnuplot_4.2.5-2_all.deb) ...
Seleccionando el paquete groff previamente no seleccionado.
Desempaquetando groff (de .../groff_1.20.1-5_i386.deb) ...
Seleccionando el paquete libamd2.2.0 previamente no seleccionado.
Desempaquetando libamd2.2.0 (de .../libamd2.2.0_1%3a3.4.0-1ubuntu2_i386.deb) ...
Seleccionando el paquete libgfortran3 previamente no seleccionado.
Desempaquetando libgfortran3 (de .../libgfortran3_4.4.1-4ubuntu9_i386.deb) ...
Seleccionando el paquete libblas3gf previamente no seleccionado.
Desempaquetando libblas3gf (de .../libblas3gf_1.2-2_i386.deb) ...
Seleccionando el paquete libatlas3gf-base previamente no seleccionado.
Desempaquetando libatlas3gf-base (de .../libatlas3gf-base_3.6.0-22ubuntu2_i386.deb) ...
Seleccionando el paquete liblapack3gf previamente no seleccionado.
Desempaquetando liblapack3gf (de .../liblapack3gf_3.2.1-1_i386.deb) ...
Seleccionando el paquete libibverbs1 previamente no seleccionado.
Desempaquetando libibverbs1 (de .../libibverbs1_1.1.2-1ubuntu2_i386.deb) ...
Seleccionando el paquete libopenmpi1.3 previamente no seleccionado.
Desempaquetando libopenmpi1.3 (de .../libopenmpi1.3_1.3.2-3ubuntu1.1_i386.deb) ...
Seleccionando el paquete libarpack2 previamente no seleccionado.
Desempaquetando libarpack2 (de .../libarpack2_2.1+parpack96.dfsg-2build1_i386.deb) ...
Seleccionando el paquete libcamd2.2.0 previamente no seleccionado.
Desempaquetando libcamd2.2.0 (de .../libcamd2.2.0_1%3a3.4.0-1ubuntu2_i386.deb) ...
Seleccionando el paquete libccolamd2.7.1 previamente no seleccionado.
Desempaquetando libccolamd2.7.1 (de .../libccolamd2.7.1_1%3a3.4.0-1ubuntu2_i386.deb) ...
Seleccionando el paquete libcolamd2.7.1 previamente no seleccionado.
Desempaquetando libcolamd2.7.1 (de .../libcolamd2.7.1_1%3a3.4.0-1ubuntu2_i386.deb) ...
Seleccionando el paquete libcholmod1.7.1 previamente no seleccionado.
Desempaquetando libcholmod1.7.1 (de .../libcholmod1.7.1_1%3a3.4.0-1ubuntu2_i386.deb) ...
Seleccionando el paquete libcxsparse2.2.3 previamente no seleccionado.
Desempaquetando libcxsparse2.2.3 (de .../libcxsparse2.2.3_1%3a3.4.0-1ubuntu2_i386.deb) ...
Seleccionando el paquete libfltk1.1 previamente no seleccionado.
Desempaquetando libfltk1.1 (de .../libfltk1.1_1.1.9-6ubuntu2_i386.deb) ...
Seleccionando el paquete libftgl2 previamente no seleccionado.
Desempaquetando libftgl2 (de .../libftgl2_2.1.3~rc5-2_i386.deb) ...
Seleccionando el paquete libglpk0 previamente no seleccionado.
Desempaquetando libglpk0 (de .../libglpk0_4.38-1_i386.deb) ...
Seleccionando el paquete libgraphicsmagick3 previamente no seleccionado.
Desempaquetando libgraphicsmagick3 (de .../libgraphicsmagick3_1.3.5-5.1_i386.deb) ...
Seleccionando el paquete libgraphicsmagick++3 previamente no seleccionado.
Desempaquetando libgraphicsmagick++3 (de .../libgraphicsmagick++3_1.3.5-5.1_i386.deb) ...
Seleccionando el paquete libhdf5-serial-1.6.6-0 previamente no seleccionado.
Desempaquetando libhdf5-serial-1.6.6-0 (de .../libhdf5-serial-1.6.6-0_1.6.6-4ubuntu2_i386.deb) ...
Seleccionando el paquete libqhull5 previamente no seleccionado.
Desempaquetando libqhull5 (de .../libqhull5_2009.1-1_i386.deb) ...
Seleccionando el paquete libqrupdate1 previamente no seleccionado.
Desempaquetando libqrupdate1 (de .../libqrupdate1_1.0.1-1_i386.deb) ...
Seleccionando el paquete libumfpack5.4.0 previamente no seleccionado.
Desempaquetando libumfpack5.4.0 (de .../libumfpack5.4.0_1%3a3.4.0-1ubuntu2_i386.deb) ...
Seleccionando el paquete octave3.2-common previamente no seleccionado.
Desempaquetando octave3.2-common (de .../octave3.2-common_3.2.2-2build1_all.deb) ...
Seleccionando el paquete octave3.2 previamente no seleccionado.
Desempaquetando octave3.2 (de .../octave3.2_3.2.2-2build1_i386.deb) ...
Procesando disparadores para man-db ...
Configurando libc-dev-bin (2.10.1-0ubuntu19) ...
Configurando libc6-dev (2.10.1-0ubuntu19) ...
Configurando libc6-i686 (2.10.1-0ubuntu19) ...

Configurando libgpg-error0 (1.6-1ubuntu1) ...

Configurando libgcrypt11 (1.4.4-2ubuntu2) ...

Configurando libglib2.0-0 (2.22.3-0ubuntu1) ...

Configurando libtasn1-3 (2.2-1) ...

Configurando libgnutls26 (2.8.3-2) ...

Configurando groff-base (1.20.1-5) ...

Configurando libkrb5support0 (1.7dfsg~beta3-1ubuntu0.13) ...

Configurando libk5crypto3 (1.7dfsg~beta3-1ubuntu0.13) ...

Configurando libkrb5-3 (1.7dfsg~beta3-1ubuntu0.13) ...

Configurando libgssapi-krb5-2 (1.7dfsg~beta3-1ubuntu0.13) ...

Configurando gnuplot-nox (4.2.5-2) ...

Configurando libwxbase2.8-0 (2.8.10.1-0ubuntu1) ...

Configurando libcups2 (1.4.1-5ubuntu2.7) ...

Configurando libgtk2.0-0 (2.18.3-1ubuntu2.2) ...

Configurando libwxgtk2.8-0 (2.8.10.1-0ubuntu1) ...

Configurando gnuplot-x11 (4.2.5-2) ...
Configurando gnuplot (4.2.5-2) ...
Configurando groff (1.20.1-5) ...

Configurando libamd2.2.0 (1:3.4.0-1ubuntu2) ...

Configurando libgfortran3 (4.4.1-4ubuntu9) ...

Configurando libblas3gf (1.2-2) ...

Configurando libatlas3gf-base (3.6.0-22ubuntu2) ...

Configurando liblapack3gf (3.2.1-1) ...

Configurando libibverbs1 (1.1.2-1ubuntu2) ...

Configurando libopenmpi1.3 (1.3.2-3ubuntu1.1) ...

Configurando libarpack2 (2.1+parpack96.dfsg-2build1) ...

Configurando libcamd2.2.0 (1:3.4.0-1ubuntu2) ...

Configurando libccolamd2.7.1 (1:3.4.0-1ubuntu2) ...

Configurando libcolamd2.7.1 (1:3.4.0-1ubuntu2) ...

Configurando libcholmod1.7.1 (1:3.4.0-1ubuntu2) ...

Configurando libcxsparse2.2.3 (1:3.4.0-1ubuntu2) ...

Configurando libfltk1.1 (1.1.9-6ubuntu2) ...

Configurando libftgl2 (2.1.3~rc5-2) ...

Configurando libglpk0 (4.38-1) ...

Configurando libgraphicsmagick3 (1.3.5-5.1) ...

Configurando libgraphicsmagick++3 (1.3.5-5.1) ...

Configurando libhdf5-serial-1.6.6-0 (1.6.6-4ubuntu2) ...
Configurando libqhull5 (2009.1-1) ...

Configurando libqrupdate1 (1.0.1-1) ...

Configurando libumfpack5.4.0 (1:3.4.0-1ubuntu2) ...

Configurando octave3.2-common (3.2.2-2build1) ...
Configurando octave3.2 (3.2.2-2build1) ...

Procesando disparadores para libc-bin ...
ldconfig deferred processing now taking place
[12:16:22(root@andLinux)/home/godo]> apt-get clean
[12:57:29(root@andLinux)/home/godo]> exit
exit
[12:57:34(godo@andLinux)~]>


[[https://docs.google.com/forms/d/e/1FAIpQLSeGnXB3zyaNVYcb_2EoO8C5HRc6Emx-2rv2QS6OWNFz1yYSBQ/viewform?usp=pp_url&entry.55081144=AndLinux%2C%20de%20Jaunty%20a%20Karmic][Dejar comentario]].

