#+title: Búsqueda en no publicados o Controlar acceso a publicados
#+date: <2016-10-19 11:51>
#+author: godest
#+description: Este tema surge porque deseo dedicar el tipo de contenido "blog" a almacenar contenidos que sólo sean accesibles para mí: reflexiones, diario, apuntes, etc.…
#+filetags: 
#+options: _:nil
#+nid: 557

Este tema surge porque deseo dedicar el tipo de contenido "blog" a almacenar contenidos que sólo sean accesibles para mí: reflexiones, diario, apuntes, etc.

Actualmente mantengo el tipo blog como "no publicado", y los permisos asociados es que un "usuario registrado", que es mi rol, pueda editar y ver su propio contenido. Esto me permite editar nodos de tipo "blog" y acceder a ellos para leerlos. SIN EMBARGO, OBSERVO QUE AÚN ESTANDO AUTENTICADO, ES DECIR, AÚN ACTUANDO CON ROL "USUARIO REGISTRADO" *NO SOY CAPAZ DE BUSCAR (con el buscador propio de Drupal, le llamo "Buscador Interno") CONTENIDO EN NODOS "NO PUBLICADOS"*. Y esto dificulta mucho su gestión y consulta rápida. --> la vía a explorar manteniendo este enfoque es *ver si existe alguna forma de indexar y buscar este tipo de contenido "no publicado"*.

Como planteamiento alternativo: avanzar en la idea de publicar el contenido "blog" y restringir el acceso a dicho contenido sólo a "usuarios registrados" (lo vería tanto Esther como yo, pues ambos mantenemos ese tipo de rol). Algunos módulos que permiten avanzar por aquí, controlando permisos, son:

0.- Reflexión general:
0.1.- http://drupal.stackexchange.com/questions/83142/how-to-restrict-node-access-based-on-user-roles
0.2.- https://www.drupal.org/node/270000
1.- https://www.drupal.org/node/1539922#comment-5923726
2.- https://www.drupal.org/project/nodeaccess
3.- https://www.drupal.org/project/deny_access

Adjunto excel donde he filtrado por estabilidad en Drupal 7 para llegar a los tres mencionados en los puntos 1, 2 y 3 de arriba.

** Archivos adjuntos
- [[https://godest.vivencias.net/static/files/Módulos para control de acceso por tipo de contenido en Drupal 7.xlsx][Módulos para control de acceso por tipo de contenido en Drupal 7.xlsx]]

[[https://docs.google.com/forms/d/e/1FAIpQLSeGnXB3zyaNVYcb_2EoO8C5HRc6Emx-2rv2QS6OWNFz1yYSBQ/viewform?usp=pp_url&entry.55081144=B%C3%BAsqueda%20en%20no%20publicados%20o%20Controlar%20acceso%20a%20publicados][Dejar comentario]].

