#+title: ElementaryOS, Pantheon y Debian
#+date: <2019-05-28 09:56>
#+author: Godofredo Fdez.
#+description: Por un problema que que tenido en mi Windows 10 de casa (un tanto surrealista: la tarjeta de vídeo no funciona bien - de la noche a la mañana no me saca señal…
#+filetags: 
#+options: _:nil
#+nid: 566

Por un problema que que tenido en mi Windows 10 de casa (un tanto surrealista: la tarjeta de vídeo no funciona bien - de la noche a la mañana no me saca señal simultánea para ambas pantallas. Esto da para otro post -), para descartar un error de Hardware he instalado físicamente de nuevo Debian en mi máquina, dejando un arranque dual: Debian (vuelve a ser mi S.O. por defecto) y Windows 10.

Desde que dejé de utilizar [[https://kde.org/][KDE]] por su tremenda envergadura (estoy hablando de aquel entonces cuadno KDE pasó de la versión 3.5 a la 4.x, y no sé si esto ha cambiado o si, con el avance de los tiempos, el demarrage en recursos que exigió en su día hoy ya es compensado por el incremente de la potencia del hardware que puede ya formar parte de la mayoría de las máquinas), he buscado un escritorio en GNU/Linux con el que me sintiera cómodo tanto funcionalmente como estéticamente. Googleando he visto estos días diferentes escritorios y he de reconocer que el que más me ha impactado es este: *Pantheon*, escritorio desarrollado para formar parte de [[https://elementary.io/es/][ElementaryOS]] (distribución basada en Ubuntu que, a su vez, se basa en Debian). Así que, me planteé por qué no seguir con mi Debian, que tan estable es y que tanto me ha aportado a lo largo de mi vida (todo lo que sé de GNU/Linux, que creo que no es poco), pero aliñándola con el escritorio que actualmente mejor se adapta a lo que busco: simplicidad, funcionalidad -básica pero estable- y estética.

Aquí un par de artículos que me han servido como referencia en todo el proceso:
1. https://entornosgnulinux.com/2017/02/19/como-instalar-pantheon-en-debian-9-stretch/
2. https://linuxconfig.org/how-to-install-the-pantheon-desktop-on-debian

Y a continuación un paso a paso para llevarlo a cabo con éxito (ya probado por mí):

1. Source list para instalar Pantheon en Debian.
Fuentes principales para Debian Stretch:

#+begin_example

godo@TuChi:/etc/apt$ more sources.list
# 

# deb cdrom:[Debian GNU/Linux 9.9.0 _Stretch_ - Official amd64 NETINST 20190427-10:30]/ stretch main

#deb cdrom:[Debian GNU/Linux 9.9.0 _Stretch_ - Official amd64 NETINST 20190427-10:30]/ stretch main

deb http://ftp.cica.es/debian/ stretch main contrib non-free
deb-src http://ftp.cica.es/debian/ stretch main contrib non-free

deb http://security.debian.org/debian-security stretch/updates main contrib non-free
deb-src http://security.debian.org/debian-security stretch/updates main contrib non-free

# stretch-updates, previously known as 'volatile'
deb http://ftp.cica.es/debian/ stretch-updates main contrib non-free
deb-src http://ftp.cica.es/debian/ stretch-updates main contrib non-free

# Multimedia
deb http://www.deb-multimedia.org stretch main

#+end_example

Otras fuentes, en concreto las que nos atañen ;-):

#+begin_example

godo@TuChi:/etc/apt$ cd sources.list.d/
godo@TuChi:/etc/apt/sources.list.d$ ls
appcenter.list  pantheon-debian.list  virtualbox.list
godo@TuChi:/etc/apt/sources.list.d$ more *
::::::::::::::
appcenter.list
::::::::::::::
deb http://packages.elementary.io/appcenter xenial main
::::::::::::::
pantheon-debian.list
::::::::::::::
deb http://gandalfn.ovh/debian stretch-loki main contrib
::::::::::::::
virtualbox.list
::::::::::::::
deb http://download.virtualbox.org/virtualbox/debian stretch contrib
godo@TuChi:/etc/apt/sources.list.d$ 

#+end_example

- - -

2. Para hacer que el foco siga al ratón:
godo@TuChi:~/$ gsettings set org.gnome.desktop.wm.preferences focus-mode 'sloppy'

- - -

3. Mas cositas que aún no sé para qué sirven:
apt install elementary-tweaks indicator-application indicator-systemtray-unity indicator-multiload

- - -

4. Lo mejor de todo: atajos de teclado o shortcuts. A few handy shortucts using the Super key (Command key on a Mac, Windows key on a PC).
WIN + Space: app launcher.
WIN + H: minimizar ventana.
WIN + W: window overview.
WIN + S: workspace overview.
WIN + L: lock.
WIN + <- / ->: move between workspaces.
WIN + A: show all windows.
WIN + TAB: cycle workspaces.
WIN + Click + Drag: move windows.

Y así funcionan todos los atajos menos uno, WIN [Super key] + Space, que a mí es uno de los que más me interesan. Googleando encuentro que en Ubuntu ese atajo ya está siendo utilizado por ibus, por tanto, al reutilizarlo desde Pantheon hay solape y no funciona. Hay que hacer esto:
1. Desde un terminal ejecutado por el propio usuario, (sin ser root), ejecutamos:
a) ibus-setup
b) vemos el atajo existente, efectivamente: Super+space.
c) lo eliminamos y metemos otro: Shift+space.
2. Yo creo que con el paso 1. ya es suficiente. No obstante, yo había instalado ya estas herramientas:
a) sudo apt install dconf-tools xdotool
b) y ejecutado "godo@TuChi:~$ dconf-editor", navegado hasta: org->gnome->desktop->wm->keybindings->panel-main-menu
Y comprobado que la tecla asociada era: ['space']

- - -

- - -
Nota 1: un poco off-topic pero con cierta relación ;-). A mí siempre me ha gustado tener en mi máquina (simplificando y yendo al grano) tres particiones:
1. Windows
2. Datos (compartida tanto con Windows, 1., como con GNU/Linux, 3.)
3. GNU/Linux - Debian - desde el infinito y más allá.

Si deseas tener la partición de Datos montada automáticamente cuando arranque tu GNU/Linux, lee esto:
http://godest.vivencias.net/content/montando-una-partici%C3%B3n-ntfs-justo-al-arrancar-una-m%C3%A1quina-gnulinux

Nota 2: software adicional que te ayudará en tu día a día:
http://godest.vivencias.net/content/el-software-que-instalo-en-mi-gnulinux\\


[[https://docs.google.com/forms/d/e/1FAIpQLSeGnXB3zyaNVYcb_2EoO8C5HRc6Emx-2rv2QS6OWNFz1yYSBQ/viewform?usp=pp_url&entry.55081144=ElementaryOS%2C%20Pantheon%20y%20Debian][Dejar comentario]].

