#+title: Comenzando de nuevo...
#+date: <2020-01-08 07:55>
#+author: Godofredo Fdez.
#+description: OBJETIVOS: 1) Perder peso. Comienzo en 96 kilos. 2) Correr 10k en menos de 60 minutos en 10 semanas (18 de octubre 2020) Intento seguir este plan:…
#+filetags: 
#+options: _:nil
#+nid: 574

*OBJETIVOS:
1) Perder peso. Comienzo en 96 kilos.
2) Correr 10k en menos de 60 minutos en 10 semanas (18 de octubre 2020)*

Intento seguir este plan: https://www.carreraspopulares.com/noticia/plan-para-correr-10k-en-menos-de-60-minutos (ver detalle en las sesiones a continuación: orden blog: la primera está abajo del todo).
Me gusta porque sólo requiere entrenar 3 días por semana: martes, jueves y domingo. Esto se adapta perfectamente a mis planes.

*=== CALENDARIO DE SESIONES Y SENSACIONES ===*

*SEMANA 10: 2020* * Lunes: Descanso
Peso:

* Martes: 4 km Trote suave. 6:30 + 2 km 6:15 + 1 km 6:00
* Miércoles: Descanso
* Jueves: 3 km trote suave + 2 km a 6:00
* Viernes: descanso
* Sábado: descanso
* Domingo: Carrera

*SEMANA 9: 2020* * Lunes: Descanso
Peso:

* Martes: 3 km Trote suave. 6:30 + 3 km 6:00 + 1 km 5:45
* Miércoles: Descanso
* Jueves: 3 km trote suave + 3 km a 6:00 + 1 km a 5:40 + 1 km trote suave
* Viernes: descanso
* Sábado: descanso
* Domingo: 50 minutos trote 6:15 + 1 km a 5:45

*SEMANA 8: 2020* * Lunes: Descanso
Peso:

* Martes: 3 km Trote suave. 6:30 + 3 km 6:00 + 1 km 5:45
* Miércoles: Descanso
* Jueves: 3 km trote suave + Fartlek (2 minutos a 5:30 + 3 minutos a 5:45 + 6 minutos a 6:00 + 3 minutos a 5:45 + 2 minutos a 5:30) + 1km de trote suave
* Viernes: descanso
* Sábado: descanso
* Domingo: 50 minutos trote 6:15 + 15 minutos acondicionamiento físico

*SEMANA 7: 2020* * Lunes: Descanso
Peso:

* Martes: 4 km Trote suave. 6:30 + 2 km 6:15 + 1 km 6:00
* Miércoles: Descanso
* Jueves: 3 km trote suave + 2x (4 series de 500 metros a 5:45 con 1:30 de descanso entre series) + 1km de trote suave
* Viernes: descanso
* Sábado: descanso
* Domingo: 50 minutos trote suave 6:30 + 15 minutos acondicionamiento físico

*SEMANA 6: 2020* * Lunes: Descanso
Peso:

* Martes: 4 km Trote suave. 6:30 + 2 km 6:15 + 1 km 6:00
* Miércoles: Descanso
Jueves: 3 km trote suave + 2 km a 6:00 + 1 km a 5:45 + 1 km trote suave
* Viernes: descanso
* Sábado: descanso
* Domingo: 50 minutos trote suave 6:30 + 15 minutos acondicionamiento físico

*SEMANA 5: 2020* * Lunes: Descanso
Peso:

* Martes: 4 km Trote suave. 6:30 + 3 km 6:15
* Miércoles: Descanso
* Jueves: 3 km trote suave + 2 km a 6:15 + 1 km a 6:00 + 1 km trote suave
* Viernes: descanso
* Sábado: descanso
* Domingo: 50 minutos trote suave 6:30 + 15 minutos acondicionamiento físico

*SEMANA 4: 2020* * Lunes: Descanso
Peso:

* Martes: 4 km Trote suave. 6:30 + 2 km 6:15
* Miércoles: Descanso
* Jueves: 3 km trote suave + Fartlek (1 minuto a 5:30 -- 3 minutos a 5:50 -- 5 minutos a 6:15 -- 3 minutos a 5:50 -- 1 minuto a 5:30) + 1 km trote suave
* Viernes: descanso
* Sábado: descanso
* Domingo: 50 minutos trote suave 6:30 + 20 minutos acondicionamiento físico

*SEMANA 3: 2020* * Lunes: Descanso
Peso:

* Martes: 5 km de trote suave a 6:30 + acondicionamiento físico
* Miércoles: Descanso
* Jueves: 3 km trote suave + 2x (3 series 500 metros 6:00 con 1:30 de descanso entre series) + 1 km trote suave
* Viernes: descanso
* Sábado: descanso
* Domingo: 45 minutos trote suave 6:30 + 20 minutos acondicionamiento físico

*SEMANA 2: 2020* * Lunes: Descanso -> calistenia de core, brazos y piernas. Estiramientos.
Peso:

* Martes: 5 km de trote suave a 6:30-6:45 + acondicionamiento físico
* Miércoles: Descanso -> calistenia de core, brazos y piernas. Estiramientos.
* Jueves: 3 km trote suave + 5 series de 500 metros a 6:00 + 1 km trote suave
* Viernes: descanso -> estiramientos.
* Sábado: descanso -> calistenia de core, brazos y piernas. Estiramientos.
* Domingo: 45 minutos de trote suave 6:30

*SEMANA 1: del 10-16 de agosto 2020* Correr una carrera de 10 kilómetros en menos de 1 hora puede ser un plan ambicioso para mucha gente que no lo haya hecho nunca. En primer lugar, debemos saber que este plan no se puede comenzar desde cero. Es decir, que la persona que lo quiera ejecutar ya debe tener una base de entrenamientos anterior que nos permita salir a correr al menos 45 - 50 minutos sin problemas. Existen muchos tipos diferentes de planes. Cada uno debería escoger uno que se le adapte a sus condiciones, aunque lo ideal es que pudierais contar con un entrenador que os lo adapte a vuestras necesidades y os lo vaya moldeando según avanzáis.

Lo ideal es que sepáis en qué condición física estáis y que, incluso, hayáis pasado algún reconocimiento médico. Además, la alimentación y el descanso son partes fundamentales de nuestro objetivo, por tanto, nos deberán acompañar en todo momento. Y recuerda, si notas molestias o tienes las piernas cargadas, es que necesitas una visita a tu fisioterapeuta.

* Lunes: Descanso
Peso: 96k.

* Martes: 4 km Trote suave. 6:30-6:45
Es el primer día. Todavía no tengo este plan. Anoche miré este otro: https://www.sanitas.es/sanitas/seguros/es/particulares/biblioteca-de-salud/ejercicio-deporte/planes-entrenamiento/entrenamiento-nivel-inicial10Km.html. Así que hoy he hecho: 7 minutos andando rápido, 15 minutos trotando, 3 minutos andando rápido, 15 minutos trotando y ya andando hasta casa, estirando antes.
Métricas: Tiempo: 45:27. Distancia: 6,01km. Ritmo: 7:34. Frec. cardiaca media: 144ppm. Frec. cardiaca máxima: 165ppm.Training Effect: 3,5. Calorías: 553. Tiempo de recuperación: 30 horas. Zapatillas: Saucony Guide 9 negras.
Sensaciones: durante la carrera me siento bien, quizá la segunda parte me siento algo más cansado. Siento una ligera molestia en el tobillo izquierdo. Tengo que ajustar mejor el recorrido para acabar más cerca de casa. Tras estirar me siento bien, cansado pero bien.

* Miércoles: Descanso/natación/bici

* Jueves: 3 km de trote suave + 2 km a 6:15 + 1 km trote suave
Métricas: Tiempo: 48:52. Distancia: 6,50km. Ritmo: 7:31. Frec. cardiaca media: 141ppm. Frec. cardiaca máxima: 168ppm. Training Effect: 3,8. Calorías: 595. Tiempo de recuperación: 36 horas. Zapatillas: Saucony Guide 9 negras.
Sensaciones:
Comienzo calentando: 5min. andando rápido.
Luego hago 3km de trote suave, en la zona de frecuencia aeróbica que me marca mi Garmin. Me resulta fácil mantenerme en dicha zona.
El Garmin (Forerunner 735XT) me marca el cambio de "intervalo": paso a hacer 2km a un ritmo alrededor de los 6:25. Acabo bastante cansado y con las pulsaciones en torno a 168ppm en la parte final.
Recupero andando rápido 1km, intentando mantenerme en la zona aeróbica que de nuevo me va señalando el reloj.
Estiro en el parque: gemelos hundiendo el tobillo desde el borde de la acera. Toda la pierna, parte posterior, levantándola y manteniéndola recta apoyada en un banco. Cuadriceps, doblando la rodilla y tirando del tobillo para atrás.

* Viernes: descanso -> estiramientos.
* Sábado: descanso -> calistenia de core, brazos y piernas.
* Domingo: 40 minutos de trote suave 6:30 + ejercicios de acondicionamiento físico

*=== OLD === === OLD === === OLD === === OLD ===*

*SEMANA DEL 6-12 DE ENERO DE 2020* Domingo, 12: Carrera continua. Rubén me acompaña en su bici. 4,58 Km. 31:49. Ritmo: 6:56. Training Effect: 3,5. Saucony negras.
Sábado, 11: Carrera continua. Dehesa Tornero. Rubén me acompaña en su bici. 4,64 Km. 36:06. Ritmo: 7:47. Training Effect: 3,2. Saucony negras.
Jueves, 9: Carrera continua. Rubén me acompaña en su bici. 3,00 Km. Tiempo: 21:15. Ritmo: 7:05. Training Effect: 2,4. Saucony negras.
Martes, 7: Peso: 95 Kg. Carrera continua. 3,69 Km. Tiempo: 25:34. Ritmo: 6:56. Training Effect: 3,00. Saucony negras.


[[https://docs.google.com/forms/d/e/1FAIpQLSeGnXB3zyaNVYcb_2EoO8C5HRc6Emx-2rv2QS6OWNFz1yYSBQ/viewform?usp=pp_url&entry.55081144=Comenzando%20de%20nuevo...][Dejar comentario]].

