#+title: Como configurar una memoria USB
#+date: <2004-05-08 20:46>
#+description: 
#+filetags: GNU/LINUX

Has de dar soporte en el kernel a los siguientes módulos:
- =sd_mod=
- usb-storage

Has de añadir a "/etc/fstab" la siguiente línea:
#+begin_src sh
/dev/sda1 /mnt/usbflash vfat user,noauto,umask=0 0 0
#+end_src

Para usar el dispositivo el superusuario *root* ha de cargar el módulo que lo gestiona: 
#+begin_src sh
modprobe usb-storage
#+end_src

Cualquier usuario lo puede montar con: 
#+begin_src sh
mount /mnt/usbflash
#+end_src

Una vez montado se utiliza como si de un disquete se tratara.

*¡OJO! Para evitar daños antes de desconectarlo has de hacer:* 
#+begin_src sh
umount /mnt/usbflash 
#+end_src

Al finalizar con este comando te aseguras que el dispositivo no está en uso, pudiéndolo desconectar de forma segura.

** Comentarios
*** Anonymous (no verificado Mar, 07/12/2004 - 15:10)
Hola, pues muy bueno tu blog, en especial este tutor, porfin pude bajar mis fotos de la camara :)

Muchas gracias y felicidades.

*** Godofredo Fdez. (Jue, 23/12/2004 - 15:17)
...de nada.

Bueno, lo tengo algo abandonado por la "exigida" dedicación a otros quehaceres. Pero este tipo de comentarios me sirven de aliento para seguir con él y me hacen plantearme el dedicar unos 15min. al día para ir modelando nuevos contenidos.

Gracias a ti.

*** drimakus (Lun, 07/02/2005 - 15:28)
Sincronización en la grabación de datos
Yo utilizo la opción "sync" de mount para montar mi memoria USB:

user,sync,noauto...

Sin esta opción, las transferencias de datos hacia la memoria pasan por algún "buffer" intermedio, encargándose el sistema operativo del trasbase de datos entre este "buffer" y la memoria como en segundo plano. De este modo, si el movimiento de datos lo hacemos, por ejemplo, con "konqueror" veremos que el diálogo de progreso de la copia/movimiento de ficheros finaliza muy rápidamente. Y sin embargo la luz que pueda tener la memoria seguirá indicando actividad.

Con esta opción habilitada, por otro lado, uno va viendo, al hacer la transferencia de datos hacia la memoria, la velocidad real de grabación de la misma en el mismo diálogo de progreso.

Se consigue que no sea tan crítico extraer la memoria USB sin haberla desmontado, por lo menos en cuanto a la integridad de la información almacenada. Aunque también aconsejo realizar el desmontado siempre antes de extraer la memoria.

*** Godofredo Fdez. (Mar, 08/02/2005 - 12:38)
Muchas gracias

...por compartir este detalle CON importancia ;-) ... y por animarte a ser uno de nosotros.

Bienvenido.

*** Anonymous (no verificado Mar, 02/10/2007 - 20:21)
duda
HOLA QUE TAL A TODOS.
TENGO UN PROBLEMA Y NO SE COMO RESOLVERLO, BUENO SE TRATA DE LA COMPU, LO QUE PASA QUE TENGO LA MEMORIA USB, Y LA COMPU TIENE LA ENTRADA PERO NO LA RECONOCE COMO CONFIGURO LA COMPU PARA QUE LEA LA MEMORIA?
ESTA ES LANIXY TENIA WINDOWS MILLENIUM Y LE CAMBIE A WINDOWS XP, NO SE SI ESO AFECTA.
BUENO GRACIAS Y ESPERO SU PRONTA RESPUESTA.

*** Godofredo Fdez. (Vie, 05/10/2007 - 18:51)
USB en Windows XP
Hola. Es muy extraño lo que te está pasando. El Windows XP es uno de los sistemas operativos mejores de Microsoft (para mi gusto incluso mejor que Windows Vista, incluso), y suele traer ya implementados los controladores de los puertos USB. Si tienes Internet te aconsejo que hagas lo siguiente:

- Conéctate a Internet.
- Conecta la memoria USB al puerto.
- Espera un ratito y, si el ordenador no detecta dicha memoria sigue con el siguiente paso.
- Abre windows ---> panel de control ---> agregar nuevo hardware.
- Realiza cada uno de los pasos que te vaya mostrando el asistente.
- Si no encuentra los drivers te preguntará si quieres que los busque en "localizaciones específicos", entre ellos Internet. Selecciona esta opción y prosigue

Tras realizar estos pasos estoy casi seguro de que Windows XP detectará la memoria. Si aún así sigue sin detectarla intenta esto otro:

- Abre el Internet Explorer.
- Menú herramientas ---> WindowsUpdate.
- Instala todas las actualizaciones disponibles.

Y como última opción, ¡Pásate a GNU/Linux!

¡Suerte!

*** Anonymous (no verificado Mié, 11/03/2009 - 14:20)
pregunta
hola lo que pasa es que tengo una usb y cuando le meto los archivos quedan defectuosos

*** Godofredo Fdez. (Mié, 11/03/2009 - 17:50)
Desconectar hardware con seguridad
Me da la impresión de que utilizas Windows y no estás "desconectando el hardware con seguridad" y no dejas tiempo para que se copien tus archivos. Has de buscar en la barra de inicio del windows, al lado derecho, cerca del reloj, un icono con una flechita verde, pulsar con el ratón y elegir "desconectar hardware con seguridad".

Si utilizas GNU/Linux puedes ver que aparece un icono en el escritorio (depende de la distribución que uses), pulsas sobre él con el botón derecho del ratón y le das a la opción de desmontar.

Cuanto terminen las acciones descritas en los párrafos anteriores te aparecerá un mensaje indicándote que "ahora puedes desconectar tu usb". Si lo desconectas antes de realizar las acciones que te indico puede que no le de tiempo a copiar los archivos al usb y te aparezcan defectuosos. Si estás haciendo este proceso, y aún así te aparecen defectuosos o tienes un virus o se te ha estropeado el usb: un servicio técnico te ayudará.

Gracias.

Salud.

*** carlos fernando (no verificado Jue, 26/03/2009 - 20:25)
sobre desconectar USB forma segura
hola en mi laptop tuve un problema en el lado derecho de mi pantalla y no puedo ver la parte donde se ubica el icono con una flechita verde, se que se puede colocar en el escritorio como un icono u otro programa, quisiera saber si alguien sabe como hacerlo o donde ubicarlo para ponerlo en mi escritorio, y poder desconectar mi memoria USB, gracias.
escribanme aqui

calin_sc@hotmail.com
carlos fernando

avisenme por fa para poder ingresar de nuevo aqui
si encuentro la solucion para ponerla tambien, gracias

*** Anonymous (no verificado Mié, 11/03/2009 - 14:30)
S.O.S
porfa alguien que me ayude con mi usb

*** Marriola (no verificado Lun, 27/07/2009 - 04:28)
Memorias USB desinstaladas
Los moscas IT de mi trabajo desinstalaron en masa el acceso a las memorias USB, quiero volver a utilizarlos, como lo hago por favor?. Uso Windows XP. Gracias anticipadas
