#+title: Patentes de Software
#+date: <2004-06-12 10:53>
#+author: Godofredo Fdez.
#+description: A continuaci&oacute;n voy a realizar una breve reflexi&oacute;n (al final no me ha quedado tan breve pero espero que s&iacute; completa) sobre las patentes de software y sobre la influencia que estas tendr&aacute;n en un futuro inmediato en la forma de concebir el trabajo con nuestro ordenador personal, principalmente, en nuestras empresas, por ende, y en
#+filetags: Pensamiento Software
#+options: _:nil
#+nid: 9

#+begin_export html
<a href="http://demo.ffii.org/"><img src="http://demo.ffii.org/banner.php?i=25" border="0" alt="NO to software patents - come to brussels on 14 april" height="60" width="468" /></a>
#+end_export

--------------

A continuación voy
a realizar una breve reflexión (al final no me ha quedado tan
breve pero espero que sí completa) sobre las patentes de
software y sobre la influencia que estas tendrán en un futuro
inmediato en la forma de concebir el trabajo con nuestro ordenador
personal, principalmente, en nuestras empresas, por ende, y en
nuestra sociedad, por supuesto.

** ¿Por
qué se patenta?

Recuerdo que había
un tema, en una de las asignaturas (¿economía?) que
cursé estos años atrás en la titulación
de “Investigación y Técnicas de Mercado”,
en la que se trataba el tema de las patentes desde un punto de vista
global, es decir: respecto a la producción e innovación,
respecto al precio del producto, respecto a las acciones de
comunicación que había que emprender y mantener y
respecto a la distribución del mismo.

*Respecto a la
producción e innovación* se supone que es protegida
y garantizada por la patente, ya que ésta confiere en
exclusiva al patentador la capacidad de producir y comercializar lo
patentado durante un periodo de tiempo que suele estar en torno a los
15 ó 20 años. Así, se cree, que los organismos
(empresas, instituciones, personas físicas, etc.) con ánimo
de lucro (de no ser así ninguna de estas palabras tendría
sentido) están incentivados en investigar e innovar, y a
dedicar dinero a ello: cuando logran un producto nuevo, lo cual les
ha supuesto un coste de investigación y desarrollo, pueden
patentarlo, lo que los resarcirá de los gastos incurridos
(periodo de amortización del producto) y los enriquecerá
(resto del tiempo que aún pervive la patente y en el que se
sigue ganando dinero).

Evidentemente, durante el
periodo de vida de la patente la situación creada se asemeja
mucho a un monopolio(frente a los monopolios naturales este sería
un monopolio judicial): sólo hay un productor que controla
todo el mercado o, con algo de suerte para los consumidores (y más
para el primer productor y patentador), varios productores que se
repartirían el mercado sin ánimo de guerras
competitivas. ¿Qué animo de guerra competitiva van a
tener el que compra la patente y el que la vende? No nos engañemos,
el que vende la patente es porque ya goza de una situación en
el mercado que le permite vivir a sus anchas, y obtiene la guinda con
el dinero ingresado por la venta (que, por la cantidad que supone,
está lejos de ser posibilidad de todo el mundo, estando sólo
al alcance de unos pocos y grandes), y el que la compra que ánimo
de guerra va a tener si sabe que se tiene que conformar con las
migajas que le ha dejado “el primero” y que al menor
atisbo de agresión será barrido del mercado.

En fin, siendo consciente
de mi falta de autoridad en la materia, me atrevo a pensar que pocos
autores son los que no aceptan
que la situación creada es un monopolio, y en el caso menos
malo, un oligopolio.

*Respecto al precio*,
y comportándome fielmente a lo expresado por la teoría
económica, lo fija el mercado. Pero claro, aquí el
mercado es el monopolio, y el agente monopolista es el patentador. Es
decir, el patentador pondrá el precio que estime oportuno a su
producto. Si puedes pagarlo lo disfrutas, si no, te mueres (como ya
ocurre en algunos países del tercer mundo con algunas
vacunas). Aquí también siguen estando los gobiernos,
pero ¿quién tiene más poder éstos o las
grandes multinacionales? Si alguno regulara en su contra ¿cuánto
tiempo más estaría en el poder?

*Respecto a las acciones de comunicación y distribución*,
es evidente que el producto será distribuido y dado a conocer
en aquellas zonas que lo pueden adquirir. Podríamos decir que
el patentador elige correr la maratón en llano huyendo de
cuestas y malas sendas: llega a dónde le es suficiente para
obtener los mayores ingresos, donde con pequeños esfuerzos
(costes) obtiene grandes satisfacciones (beneficios)

Es por todo ello por lo
que se dice que el monopolio, en este caso *la patente, tiene un
coste social* durante
sus años de vida la sociedad no puede disfrutarla como se
supone que la disfrutaría si el escenario fuera un mercado
libre y en competencia (cuanto más cerca de la perfecta
mejor).

** ¿Qué
se patenta?

Según la Ley
11/1986 de Patentes, vigente actualmente en nuestro país, y
más concretamente en su “TÍTULO II.
PATENTABILIDAD”, artículo 4, punto primero: “Son
patentables las invenciones nuevas, que impliquen actividad inventiva
y sean susceptibles de aplicación industrial, aún
cuando tengan por objeto un producto que esté compuesto o que
contenga materia biológica, o un procedimiento mediante el
cual se produzca, transforme o utilice materia biológica”.

Como se puede observar,
lo más cerca que la actual ley de patentes está de un
PROCESO creativo, de un PROCEDIMIENTO, es cuando dice: “... o
un procedimiento mediante el cual se produzca, transforme o utilice
materia biológica”. Pero, está claro que en la
programación (proceso de producción del software) ni se
produce, ni se transforma o utiliza materia biológica (aunque
nuestro cerebro esté consumiendo cantidad ingente de glucosa,
y por tanto transformándola en energía creativa -en
fin, no se puede hilar tan fino-).

Por si cabe alguna duda
del actual estado de “patentabilidad”de los programas de
ordenador, y por tanto de la programación en sí, en
este mismo artículo 4, punto 4.c), de nuestra ley, leemos lo
siguiente:”No se considerarán invenciones en el sentido
de los apartados anteriores, en particular: los planes, reglas y
métodos para el ejercicio de actividades intelectuales, para
juegos o para actividades económico-comerciales, así
como los PROGRAMAS DE ORDENADORES”.

Y aquí, uno, que
no está acostumbrado a dejar de planteárselo todo, empieza a pensar: “¿Qué ha cambiado en el entorno
del software para que nuestros queridos políticos comiencen a
plantearse la patentabilidad, que antes negaban, de los PROGRAMAS DE
ORDENADORES? ¿Son nuestros políticos los que han
removido estas aguas o algún otro agente? ¿No serán
las grandes multinacionales del software? ¿por qué?
Porque, no me podrán venir con la escusa inicial: “es
que con las patentes se incentiva la invención, desarrollo e
innovación”. Señores, ¡miren a su
alrededor! ¿Qué sector ha inventado, desarrollado,
innovado, evolucionado MÁS en estos últimos 20 años
(por situarnos cerca de la fecha en la que el señor Stallman
creó la Free Software Fundation, y por ver así el
¿daño? que el software libre ha producido a estos tan
prestigiosos conceptos de hoy en día)? ¿Cuántos
“procesadores de textos” hay libres, cuántas
“hojas de cálculo”, cuántos programas de
navegación por Internet, cuántos lectores de correo, y
cuánto más del resto? ¿Y qué significa el
propio nacimiento y despegue y desarrollo de Internet? Y, ¿hubiera
sucedido todo esto con sus flamantes patentes?

Pero todo este entorno
normativo va a cambiar, estamos a un único paso de que suceda.
Hasta hace bien poco lo único que se podía patentar era
un producto final... ahora (en un futuro próximo) ya se pueden
patentar ideas y procesos. Y esto ya es grande amigos, esto
significa: TODO. ¡algoritmos! ¡trozos de código
que generan una barra de desplazamiento! ¡la barra de progreso
de una tarea, sí, la que aparece cuando estás copiando
un archivo desde una carpetita a otra! ¡TODO!

** ¿Y desde el punto de vista del software?

Bien, voy a comenzar este
apartado con una noticia, a modo de ejemplo (servirían otros
muchos), que leí el día 17 de mayo de 2004 en
barrapunto.com: . La idea es genial ¿? Los chicos de Apple han
patentado lo siguiente: cuando una ventana no se está
utilizando esta comienza a hacerse cada vez más transparente
hasta que, si sigue sin utilizarse, logra la transparencia completa
dejando ver lo que hay detrás de ella (que se supone que se ha
utilizado y se sigue utilizando, digo yo, porque si no ya sería
a su vez transparente), de tal modo que las acciones que se realicen
en ese área de la pantalla que ocupa la ventana que está
volviéndose transparente no son entendidas por esta, sino que
pueden ser interpretadas por la ventana que estaba siendo cubierta
por la que ahora es transparente, y así, la deja ver a su
través.

Comienza el espectáculo.
Unos dirán: “jolín, esa gran idea ha de ser
patentada porque la verdad es que se lo han “currao” y
eso les permite distinguir el producto, hacerlo mejor, y ganarse así
usuarios, y dinero, claro está”. Otros decimos: “jolín,
esa gran idea NO HA DE SER PATENTADA, *las ideas no se patentan
hombre*, se patentan productos, lo cual vemos con cierta
normalidad muchos (otros muchos ni siquiera esto ven normal de ser
patentando, pero en fin, no vamos a tensar posturas que luego me
tachan de radical, y este término tiene una carga semántica
muy negativa en la actualidad).

Muy bien, patente usted
su nuevo producto e incluso denuncie a los que por medio de técnicas
de ingeniería inversa le están copiando el código
y están haciendo lo mismo que ha hecho usted, con sus mismas
armas: con su código, pero no impida que alguien más se
lo trabaje y obtenga algo parecido CON SUS PROPIOS MEDIOS.

Y digo yo, recurriendo a
otra área de conocimiento: la literatura, que nos permita
tener cierta perspectiva histórica y cierta profundidad de
análisis, e intentando establecer una analogía con el
área de conocimiento de la programación: tanto la
literatura como la programación utilizan elementos comunes: un
lenguaje, unas formas o una estructura, y un fondo o un contenido que
expresar. Pues eso, y digo yo, ¿qué hubiese pasado si
el primer creador de un soneto hubiese patentado “la idea”
de soneto? ¿y si el primer creador de un cuento hubiese
patentado “la idea” de cuento? Y cuando digo la idea me
refiero a, según el DRAE:

<<0_1>>*soneto.* (Del it. /sonetto,/ y este del lat. /sonus/, sonido). *1.* m. Composición poética que consta de catorce versos
endecasílabos distribuidos en dos cuartetos y dos tercetos. En
cada uno de los cuartetos riman, por regla general, el primer verso
con el cuarto y el segundo con el tercero, y en ambos deben ser unas
mismas las consonancias. En los tercetos pueden ir estas ordenadas de
distintas maneras.

Estoy de acuerdo con que
se patente algo en concreto pero no la idea. Quizá alguien
logre el como hacer una ventana transparente con el tiempo utilizando
líneas de código totalmente distintas a las de Apple, e
incluso obteniendo un resultado también distinto.

El ejemplo de los
antivirus también es muy claro: ¿qué hubiese
pasado si alguien hubiese registrado la forma de buscar trozos de
programa que se reconocen como virus? ¿Cuantos productos hoy
en día no utilizan un archivo de firmas donde tienen un
conjunto de patrones que intentan identificar en los archivos que se
pretenden “curar”? ¿Cuántos vendedores de
soluciones antivirus habría en la actualidad? ¿Y con
qué calidad?

¿Y si se hubiera
patentado el hecho de copiar un archivo de una carpeta a otra
arrastrándolo? ¿O el hecho de copiar una hoja de
cálculo a una nueva quedando la primera protegida ante cambios
y la segunda sirviendo como banco de pruebas?

** ¿Cómo
van a influir las patentes?

Comenzaré aquí
con otro ejemplo para delimitar bien dos conceptos que utilizaré
en el siguiente párrafo. Supongamos que a dos personas, cada
una situada en un país muy lejano y sin ninguna relación,
se les ocurre, o se les plantea la necesidad, de crear un programa,
una aplicación software, que les resuelva la problemática
de sumar varias cantidades. Este sería el concepto de idea
general: “hacer un programa para sumar cantidades”.
Uno de ellos puede resolver dicho problema solicitando al usuario del
programa una cantidad, pulsar intro, otra cantidad, pulsar intro y
así hasta terminar con, en lugar de una cantidad,
introduciendo un espacio en blanco y pulsando intro; el programa
interpreta que ese es el final de la suma, sumaría todas las
cantidades recogidas y mostraría el resultado en pantalla.
Esta sería la brillante idea particular:
“el proceso utilizado para realizar la suma y mostrar el
resultado”, que ha tenido el primero de nuestros
programadores. Al segundo de nuestros programadores se le podría
ocurrir hacer un programa que solicitara todas las cantidades a sumar
separadas por coma, al pulsar intro se leería una única
línea con todas esas cantidades y las comas que las separan,
se analizaría la línea y se extraerían las
cantidades en ella introducidas, se sumarían y se mostraría
el resultado por pantalla, esta sería otra brillante idea
particular que solventa una misma necesidad o idea general.

He dado por supuesto en
el punto anterior (¿Y desde el punto de vista del software?)
que lo que se patenta es la idea general, y no un trozo de
código con los efectos que este consigue (patentándose
en este segundo caso la brillante idea particular y el código
que la lleva a cabo). Mi suposición es así más
extrema, porque si hubiera que patentar el código=brillante
idea particular, Y NO LA IDEA GENERAL, seríamos capaces de
lograr el mismo efecto con otro código y, de ante mano, no
habría ningún problema.

Pero lo hay, y por eso he
elegido la situación extrema para mi explicación,
porque ambas resultan ser igual de perniciosas para el pequeño
programador y la pequeña organización (en el sentido
amplio: instituciones como gobiernos regionales, pequeñas
empresas, organizaciones sin ánimo de lucro, etc.).

Si alguien lograra el
mismo efecto que nuestro ejemplo de referencia, y fuera denunciado
por violar una patente, aunque lo hubiera conseguido con código
distinto: ¿Quién tiene el suficiente tiempo y dinero
para poder convencer a un juez en el litigio? ¿Quién
puede pagar un equipo de profesionales capaz de enfrentarse con éxito
a los equipos jurídicos de las grandes multinacionales? ¿Quién
está dispuesto a ello, a asumir el riesgo? ¿Y quién
dispuesto a recorrer cientos de bases de datos con miles de patentes
para ver si está infligiendo alguna, a la hora de sentarse
frente a su ordenador y ponerse a escribir código?

La respuesta a todas
estas preguntas nos lleva a una situación triste: el ordenador
se convertirá en un electrodoméstico más, con su
guía de uso y con sus limitaciones: tienes un botón que
hace esto y otro botón que hace lo otro, si necesitas o se te
ocurre un programa con un tercer botón, te compras una versión
posterior del electrodoméstico, que ya lo traerá (si
antes se lo has sugerido y te han escuchado, claro está). No
vamos a poder programar, crear nuestras propias aplicaciones. A largo
plazo estamos ante un sistema cerrado. Eso sí, las patentes
seguirán protegiendo la invención, desarrollo e
innovación, que avanzarán en el terreno del software a
ritmos insospechados en la actualidad (con suerte a botón por
versión, y a versión cada dos años).

¿Cómo no se
dan cuenta que esta forma de patentar limitará cualquier
posibilidad de creación? Si, volviendo a nuestro ejemplo,
ambos programadores patentaran su código del sumador, y eso se
repitiera “n” veces, con “n” tendiendo a
infinitas posibilidades de plasmar la suma, ¿quien podrá
lograr un código distinto para hacer un sumador dentro de 5 ó
6 años? ¿Y cuánto tiempo habrá que
invertir para comprobar que tu sumador no está violando
ninguna patente, lo que equivale a comprobar millones de líneas
de código, de otros sumadores?

Yo creo que se me debe de
estar escapando algo porque un animal racional no puede ser capaz de
crear este tipo de situaciones. El dinero es capaz de hasta volvernos
tontos.

** ¿Cuándo
y dónde se ha realizado, y sigue realizándose, el
proyecto de patentes de software?

Voy a ser muy breve en
este punto: la primera presentación del proyecto ante el
Parlamento Europeo (septiembre de 2003) fue rechazada por éste
(muchas acciones se llevaron a cabo para transmitir nuestra
disconformidad a la opinión de los parlamentarios). Pero,
queridos participantes de una democracia, el consejo de ministros
llevado a cabo los días 17 y 18 de mayo de 2004, pasando de lo
que dijo el Parlamento Europeo, retoma el tema y decide aprobar la
ley de patentes de software (postura democrática donde las
haya).

Actualmente estamos en
este punto, ¿qué resta para la aprobación
definitiva? En un proceso llamado de “codecisión”
(intentando salvar la herida democracia), el acuerdo alcanzado en el
consejo de ministros ha de ser refrendado en segunda vuelta por el
Parlamento Europeo (se admiten apuestas).

** ¿Quién?

Es por tanto alucinante
comprobar como los estados han intentado cargarse, o superar,
situaciones de mercados en monopolio natural (según su
estructura de costes), se supone que siempre con el ánimo de
reinventar la rueda que haga que el mundo se deslice mejor y más
suave para el ciudadano, mientras que, en ese mismo mundo, siguen
reinventándola, quién duda que con el mismo ánimo,
pero ahora volviendo a la forma que tenía antes de su primera
reinvención.

Perdón, ¿he
dicho los estados? ¿las multinacionales?

En fin, estoy empezando a
delirar.

** ¿Merece
la pena ir a votar el día 13 de junio de 2004: “elecciones
al parlamento europeo”?

Permitidme que no
responda a esta pregunta, ya somos adultos y “supuestamente”
libres. Sólo una referencia a lo que opinan nuestros
principales representantes sobre este tema, para que elaboréis
vuestras propias conclusiones y opciones de voto: [[http://barrapunto.com/article.pl?sid=04/05/29/1051237]]

Hay podéis
encontrar una noticia y las respuestas de casi todos.

** ¿Dónde puedo seguir informado?

Bien es cierto que los
habituales medios masivos de comunicación parecen pasar mucho
de esta noticia, creo que he recibido una única información
por un suplemento digital de alguno de ellos: [[http://www.elmundo.es/elmundo/navegante.html][http://elmundo.es/navegante/]]

Yo os recomiendo
principalmente (en ellas podéis encontrar enlaces valiosos a
otras):

[[http://demo.ffii.org/]] (sobre todo el wiki).

[[http://petition.eurolinux.org/index_html?LANG=es]] (firmar la petición para evitar que se aprueben)

Y como no: [[http://barrapunto.com/]]

SALUD, y a seguir
viviendo.


[[https://docs.google.com/forms/d/e/1FAIpQLSeGnXB3zyaNVYcb_2EoO8C5HRc6Emx-2rv2QS6OWNFz1yYSBQ/viewform?usp=pp_url&entry.55081144=Patentes%20de%20Software][Dejar comentario]].

** Comentarios

*** Ping a Bitacoras.com (Anónimo 16/06/2004 - 00:22)
Ya está la bitácora listada en Bitacoras.com

Puedes hacer ping e informar así de las actualizaciones a través de nuestra página: http://www.bitacoras.com/directorio/ping_manual.php

Deberás hacer ping con la dirección URL con que estás registrado en el directorio...

Gracias
