#+title: ¿Aun no hablas el  nuevo I+D+ioma?
#+date: <2004-05-27 13:59>
#+author: Esther
#+description: A estas alturas se encuentra algo obsoleto el discurso que justifica el protagonismo de la I+D+i como causa impulsora de cambios sociales y económicos. Ya no necesita que nadie la defienda ni la alabe, pues su propia presencia es distintivo de modernidad, dinamismo y progreso. Pecará de I+D+iotez aquel partido político que no se precie de ondear estas capicúas iniciales en sus discursos electorales. A modo ilustrativo pongo el ejemplo del “recién estrenado” Gobierno Autonómico andaluz, que ha apostado entre sus iniciativas más fuertes por la creación de la Consejería de Innovación, Ciencia y Empresa, Consejería Estrella de esta legislatura (por favor, abstenerse de hacer chistes galácticos sobre estrellas supernovas).
#+filetags: I+D+i
#+options: _:nil
#+nid: 8

A estas alturas se encuentra algo obsoleto el discurso que justifica el protagonismo de la I+D+i como causa impulsora de cambios sociales y económicos. Ya no necesita que nadie la defienda ni la alabe, pues su propia presencia es distintivo de modernidad, dinamismo y progreso.
Pecará de I+D+iotez aquel partido político que no se precie de ondear estas capicúas iniciales en sus discursos electorales. A modo ilustrativo pongo el ejemplo del “recién estrenado” Gobierno Autonómico andaluz, que ha apostado entre sus iniciativas más fuertes por la creación de la Consejería de Innovación, Ciencia y Empresa, Consejería Estrella de esta legislatura (por favor, abstenerse de hacer chistes galácticos sobre estrellas supernovas).
Y, ¿qué empresa altamente competitiva no cuenta con algún departamento de Investigación, Desarrollo e Innovación Tecnológica?.
Estamos, por fin, enganchados al nuevo carro, pero, ¿a qué velocidad vamos?, ¿cuánto I+D+I estamos siendo?. Peor aún, ¿cómo disiparíamos esa terrible duda de cuantificar lo Ideativos y Desarrollados Inteligentemente que somos? Oh!!! ¿Cómo medimos la I+D+I?. Lo siento, eso lo dejaremos para otro día. Intentemos distinguir antes cuáles son los componentes de un sistema regional de investigación.
Al ser el que mejor conozco me limitaré al sistema andaluz. Para que la cosa funcione bien debe existir alguien que oferte y alguien que demande investigación.
Ni qué decir tiene que la investigación la investigan los investigadores, ¿no?. Éstos se aglutinan, guiados por el criterio de investigar en la misma línea, en grupos de investigación y nacen en el seno de las Universidades y los Centros de Investigación. Por su trabajo y esfuerzo común se origina la oferta de investigación. En este sentido, Andalucía posee alrededor de 1.800 grupos de investigación, que reúnen aproximadamente 17.000 personas (doctores, titulados superiores, titulados medios y personal auxiliar). 17.000 personas ideando y experimentando sobre lo desconocido y asentando las bases de esas certezas deslumbrantes que en ocasiones singulares tenemos el placer de degustar en algún telediario o algún programa atípico.
Y, ¿quién demanda investigación?, ¿quién sería capaz de invertir capital en adrenalínica y arriesgada tarea de investigar? En Andalucía el mayor esfuerzo en investigación lo realizan las Administraciones Públicas con un peso de más del 70% (según los últimos datos del Instituto Nacional de Estadística) en el total de inversión en I+D+I. Pero no es esta una situación sostenible, más aún con la incorporación de nuestros diez nuevos compañeros a la Unión Europea, que absorberán gran parte de los fondos estructurales y sociales que actualmente recibe Andalucía. Entonces, ¿quién necesita nuevas ideas, mejoras en los procesos de producción, productos innovadores? Las empresas toman el papel de protagonistas en la parte que corresponde a la demanda de investigación. Se tiene, no obstante, en Andalucía poca cultura empresarial innovadora, lo que nos produce como resultado un sistema desequilibrado, con una oferta amplia y creciente y una estancada demanda. Consecuencias de la I+D+Iosincrasia andaluza.
Todavía queda una parcela sin cubrir. ¿Cómo saben los investigadores qué necesitan las empresas que se investigue?, ¿cómo saben las empresas si lo que necesitan está ya investigado? La respuesta a esta pregunta forma el eslabón que conecta oferta y demanda y canaliza las sinergias de ambas partes. Se denomina Transferencia de Tecnología. Tal función la desempeñan en Andalucía el Centro de Enlace Sur de Europa Andalucía CESEAND que realiza tareas de transferencia de tecnología transnacional (www.ceseand.cica.es), el Centro de Innovación y Transferencia de Tecnología de Andalucía CITAndalucía con la misma función pero en el ámbito de la Comunidad Autónoma, las Oficinas de Transferencia de Resultados de la Investigación OTRIs pertenecientes a las Universidades y al CSIC (visitar páginas web de cada Universidad, www.ual.es, www.uca.es, www.uco.es, www.ugr.es, www.uhu.es, www.ujaen.es, www.uma.es, www.upo.es y www.use.es y del CSIC www.csic.es), la Red Andaluza de Innovación y Tecnología RAITEC (www.raitec.es) y la Red Andaluza de Transferencia de Resultados de la Investigación RATRI (www.ratri.es)... entre otros.
Os dejo unos días para que estudiéis el nuevo I+D+Ioma y asimiléis conceptos. Podéis ir buscando regla, escuadra, cartabón y metro precisos porque todo esto hay que medirlo... Uf!!!!\\


[[https://docs.google.com/forms/d/e/1FAIpQLSeGnXB3zyaNVYcb_2EoO8C5HRc6Emx-2rv2QS6OWNFz1yYSBQ/viewform?usp=pp_url&entry.55081144=%C2%BFAun%20no%20hablas%20el%20%20nuevo%20I%2BD%2Bioma%3F][Dejar comentario]].

