#+title: Godoutor
#+date: <2005-10-27 23:23>
#+author: José Ignacio
#+description: Qué gran selección de canciones te estamos realizando, Godo... Incluso algunas van editadas y todo...Ya verás cómo te gusta :) Dentro de muy poquito, cuando lo…
#+filetags: Desde_ti
#+options: _:nil
#+nid: 72

Qué gran selección de canciones te estamos realizando, Godo... Incluso algunas van editadas y todo...Ya verás cómo te gusta :)

Dentro de muy poquito, cuando lo tengas, tienes que aprenderte las canciones, ¿eh? Si te gustó el conciertillo de Alfonso, te aseguro que una vez que te sabes las canciones, lo disfrutas el doble. Además cuando te vayan sonando y te atrevas a cantarlas, ya quedaremos, me arrancaré con la guitarra y verás qué guay... ;)

Un abrazo!

PD: ¿Cómo sonarían con guitarra y trompeta? :P


[[https://docs.google.com/forms/d/e/1FAIpQLSeGnXB3zyaNVYcb_2EoO8C5HRc6Emx-2rv2QS6OWNFz1yYSBQ/viewform?usp=pp_url&entry.55081144=Godoutor][Dejar comentario]].

** Comentarios

*** La expectación desbordante... (Godo 13/02/2006 - 21:46)
(Enviado por Godo el Sáb, 29/10/2005 - 21:20)

es lo que invade mi sentir.

Lo de aprenderme las canciones creo que es posible... y es cierto, uno disfruta más de las cosas cuando tiene el suficiente conocimiento de el
las para exprimirle todo su sabor. Lo de tocarlas con guitarra y trompeta, creo que está más difícil, al menos si la trompeta la he de tocar y
o. Nunca he sido muy bueno improvisando, tampoco interpretando... además, hace años que no la toco. Una verdadera pena. Tras llegar a tercero
en el conservatorio mientras cursaba mis años de B.U.P. y C.O.U. fue una de las cosas que sacrifiqué cuando comencé la carrera. Entonces sí te
nía cierta soltura, y me hubiese atrevido con...

En fin, es una de esas cosas que a uno le gustaría hacer y no logra llevarlas a cabo. Un motivo de insatisfacción, por tanto.

Gracias sinceras.

Un abrazo.
