#+title: ...para quien quiere seguir viviendo, claro.
#+date: <2005-07-30 21:48>
#+author: Godofredo Fdez.
#+description: " Para evaluar la inteligencia de un comportamiento, tenemos que justificar previamente la jerarquía de marcos que establecemos, y evaluar desde el superior ".…
#+filetags: Pensamiento
#+options: _:nil
#+nid: 40

"/Para evaluar la inteligencia de un comportamiento, tenemos que justificar previamente la jerarquía de marcos que establecemos, y evaluar desde el superior/".

"Para una persona incapaz de enfrentarse con un problema o de liberarse de la angustia o de soportar el aburrimiento, drogarse es una solución inteligente. El sujeto tiene un fin claro -pasar el bache- y una solución eficaz: un chute de heroína. Hay, sin embargo, un pero. Para ser verdaderamente eficaz debería morir en ese instante, es decir, pasar el bache tendría que ser su máximo marco de referencia. De lo contrario la continuación de la vida -con sus problemas agravados ahora- convierten el chute en un acto poco inteligente. La prolongación temporal es un marco más poderoso que la superación de un instante... para quien quiere seguir viviendo, claro."

[[http://www.anagrama-ed.es/htdocs/fondo/ficha.php?filaid=2489][La inteligencia fracasada]] - Jose Antonio Marina.


[[https://docs.google.com/forms/d/e/1FAIpQLSeGnXB3zyaNVYcb_2EoO8C5HRc6Emx-2rv2QS6OWNFz1yYSBQ/viewform?usp=pp_url&entry.55081144=...para%20quien%20quiere%20seguir%20viviendo%2C%20claro.][Dejar comentario]].

** Comentarios

*** Quizá el problema más duro (Esthher 01/08/2005 - 12:37)
Quizá el problema más duro radique en la dificultad de indentificar ese marco superior, lo que requiere un diálogo interno y conocimiento de nosotros mismos. Y una vez que lo descubramos, sea éste agradable a nuestro entender o no (ej. descubrirse homosexual) reunir las fuerzas para adaptarnos al nuevo hallazgo.

*** ...identificar ese marco superior (Godo 01/08/2005 - 21:31)
Es verdad, hay dos palabras en la frase que exigen un esfuerzo previo: justificar y jerarquía "...tenemos que justificar previamente la jerarquía de marcos que establecemos...". Buscar y establecer ese buen sistema exige bastante meditación (sobre lo que es bueno y lo que es malo), y crítica (qué es mejor y qué es peor). Y ahí topamos con la ética...

...y con otro libro del mismo autor que nos puede servir de ayuda: [[http://www.anagrama-ed.es/htdocs/fondo/ficha.php?filaid=1780][ética para náufragos]]. O quizá, por lo que intuyo en los 3 capítulos que llevo leídos, vayamos recibiendo ayuda para ir modelando ese sistema con las disecciones que el autor va haciendo a lo largo del libro.\\
