#+title: Más spam en las bitácoras
#+date: <2005-09-28 22:22>
#+author: Godofredo Fdez.
#+description: Esta vez me ha tocado vía "trackbacks". Nunca me habían hecho una mención anteriormente, nunca había recibido un trackbacks. Por esto ni siquiera sabía que me funcionaban. Cual fue mi sorpresa ayer cuando vi, en el último recuadro de la columna derecha titulado "Recent trackbacks", cuatro entradas del estilo: Payday Loans Cash Advance L ( no funciona, ya lo he eliminado ). Lo cual suponía cuatro inserciones del siguiente enlace en cuatro de mis historias ( esta , esta , etc.)
#+filetags: Bitácoras
#+options: _:nil
#+nid: 51

Esta vez me ha tocado vía "trackbacks". Nunca me habían hecho una mención anteriormente, nunca había recibido un trackbacks. Por esto ni siquiera sabía que me funcionaban. Cual fue mi sorpresa ayer cuando vi, en el último recuadro de la columna derecha titulado "Recent trackbacks", cuatro entradas del estilo:

[[http://godest.bitacoras.com/?q=node/44#trackback-4][Payday Loans Cash Advance L]] (no funciona, ya lo he eliminado).

Lo cual suponía cuatro inserciones del siguiente enlace en cuatro de mis historias ([[http://godest.bitacoras.com/?q=node/44][esta]], [[http://godest.bitacoras.com/?q=node/43][esta]], etc.)

[[http://www.no-fax-payday-loans-cash.com/][Gane dinero fácil.com]] (no pinchéis, por favor, no entréis en su juego).

En fin... menos mal que los amigos del drupal, como ya comenté [[http://godest.bitacoras.com/?q=node/18][aquí]], han desarrollado un magnífico filtro antispam que uno puede ir educando diciéndole: esto es spam, esto no lo es, etc. (filtro adaptativo, bayesiano). De momento aún se le van colando algunos, esperemos que poco a poco...


[[https://docs.google.com/forms/d/e/1FAIpQLSeGnXB3zyaNVYcb_2EoO8C5HRc6Emx-2rv2QS6OWNFz1yYSBQ/viewform?usp=pp_url&entry.55081144=M%C3%A1s%20spam%20en%20las%20bit%C3%A1coras][Dejar comentario]].

