#+title: ¡Enhorabuena Debian!
#+date: <2005-06-07 16:20>
#+author: Godofredo Fdez.
#+description: Hoy tengo que darle las gracias a los principales mantenedores de mis proyectos, de mis máquinas, de mi pasión... cuanto tiempo juntos, y tanto más, si Dios quiere. Aquí os pongo la noticia oficial del lanzamiento de la nueva versión de Debian GNU/Linux 3.1. Publicación de Debian GNU/Linux 3.1 6 de junio de 2005 El proyecto Debian tiene el placer de anunciar la publicación de Debian GNU/Linux 3.1, de nombre en clave «sarge», después de casi tres años de desarrollo continuo. Debian GNU/Linux es un sistema operativo libre que ofrece soporte para once arquitecturas de microprocesador distintas, incluye los entornos de escritorio KDE, GNOME y GNUstep así como programas criptográficos. También es compatible con la versión 2.3 del estándar de la jerarquía del sistema de ficheros (FHS) e incluye programas de apoyo desarrollados para el estándar LSB.
#+filetags: GNU/Linux
#+options: _:nil
#+nid: 17

Hoy tengo que darle las gracias a los principales mantenedores de mis proyectos, de mis máquinas, de mi pasión... cuanto tiempo juntos, y tanto más, si Dios quiere. Aquí os pongo la noticia oficial del lanzamiento de la nueva versión de Debian GNU/Linux 3.1.

* Publicación de Debian GNU/Linux 3.1

*6 de junio de 2005*

El proyecto Debian tiene el placer de anunciar la publicación de
Debian GNU/Linux 3.1, de nombre en clave «sarge», después de casi tres
años de desarrollo continuo. Debian GNU/Linux es un sistema operativo
libre que ofrece soporte para once arquitecturas de microprocesador
distintas, incluye los entornos de escritorio KDE, GNOME y GNUstep así
como programas criptográficos. También es compatible con la versión
2.3 del estándar de la jerarquía del sistema de ficheros (FHS) e
incluye programas de apoyo desarrollados para el estándar LSB.

Con el desarrollo del nuevo instalador de Debian, esta versión
incluye un mecanismo de instalación nuevo y modular con detección de
hardware y capacidad de instalación automatizada. La instalación se
puede realizar en cerca de treinta idiomas e incluye configuraciones
del servidor X para muchas tarjetas gráficas distintas.

Se ha reescrito el sistema de tareas y se ha hecho más flexible.
Además se ha integrado la herramienta debconf en la mayoría de los
paquetes que se deban configurar, haciendo la instalación más sencilla
y más amigable para el usuario. Puede instalar Debian GNU/Linux desde
distintos medios de instalación como DVDs, CDs, memorias USB, unos
pocos disquetes o desde la red. Puede descargarlo ahora, y pronto
estará disponible en DVD o CD-ROM de un buen número de [[http://www.debian.org/CD/vendors/][vendedores]].

Debian GNU/Linux funciona en distintos tipos de máquinas, desde
pequeños organizadores personales a supercomputadores, pasando por
casi cualquier tipo de máquina intermedia. Se ofrece soporte para once
arquitecturas distintas, incluyendo: Motorola 68k (m68k), Sun SPARC
(sparc), HP Alpha (alpha), Motorola/IBM PowerPC (powerpc), Intel IA-32
(i386) e IA-64 (ia64), HP PA-RISC (hppa), MIPS (mips, mipsel), ARM
(arm) e IBM S/390 (s390).

Esta versión incluye un buen número de programas de
gran tamaño como puedan ser el Entorno de Escritorio K 3.3 (KDE), el
entorno de escritorio GNOME 2.8, el escritorio de GNUstep, XFree86
4.3.0, GIMP 2.2.6, Mozilla 1.7.8, Galeon 1.3.20, Mozilla Thunderbird
1.0.2, Firefox 1.0.4, PostgreSQL 7.4.7, MySQL 4.0.24 y 4.1.11a, la
colección de compiladores de GNU (GCC) 3.3.5, las versiones del núcleo Linux
2.4.27 y 2.6.8, Apache 1.3.33 y 2.0.54, Samba 3.0.14, Python 2.3.5 y
2.4.1, Perl 5.8.4 y muchos más.

Esta es la primera versión de Debian en incluir OpenOffice.org
(1.1.3). También se incluyen programas criptográficos en la distribución
principal. La instalación por omisión incluye OpenSSH y GNU Privacy
Guard, además, en esta versión podrá disponer de cifrado fuerte en
servidores y navegadores web, bases de datos, y muchas otras aplicaciones.

Debian GNU/Linux 3.1 se nutre de los esfuerzos realizados por los
subproyectos Debian-Edu/Skolelinux, Debian-Med y Debian-Accessibility,
que han incrementado el número de paquetes de programas educativos,
los dedicados a la profesión médica, así como de aquellos
especialmente diseñados para personas con discapacidad.

Las actualizaciones a Debian GNU/Linux 3.1 desde la versión
anterior Debian GNU/Linux 3.0, de nombre en clave «woody», se
gestionan automáticamente mediante la herramienta de gestión de
paquetes aptitude, y también hasta cierto punto por la herramienta de
gestión de paquetes apt-get. Como es habitual, los sistemas Debian
GNU/Linux pueden actualizarse sin molestias y sin tiempo de
parada. Puede encontrar instrucciones detalladas sobre cómo instalar y
actualizar Debian GNU/Linux en [[http://www.debian.org/releases/sarge/releasenotes][las notas de
publicación]].

** Acerca de Debian

Debian GNU/Linux es un sistema operativo libre, desarrollado por
más de mil voluntarios de todo el mundo que colaboran mediante
Internet. La dedicación de Debian al Software Libre, su naturaleza no
comercial, y su modelo de desarrollo abierto la hacen única entre las
distribuciones de GNU/Linux.

Los puntos fuertes del proyecto Debian son su enorme base de
voluntarios, su dedicación al contrato social de Debian y su
compromiso de ofrecer el mejor sistema operativo posible. Debian 3.1
es otro paso importante en esa dirección.

** Información de contacto

Si desea más información puede visitar las páginas de Debian en [[http://www.debian.org/]] o enviar un correo
electrónico a <press@debian.org>.


[[https://docs.google.com/forms/d/e/1FAIpQLSeGnXB3zyaNVYcb_2EoO8C5HRc6Emx-2rv2QS6OWNFz1yYSBQ/viewform?usp=pp_url&entry.55081144=%C2%A1Enhorabuena%20Debian%21][Dejar comentario]].

