#+title: El cacareado Internet Explorer 7.0 (IE7 para los amigos)... y sus lagunas.
#+date: <2005-08-15 20:37>
#+author: Godofredo Fdez.
#+description: Antes que nada he de decir que este artículo está inspirado en este otro: diez razones para no confiar en internet explorer 7 , y sobre todo en estos: La verdadera razón por la que Internet Explorer 7 no soportará CSS2 -- Update on Standards and CSS in IE7 . El porqué de escribir este artículo: quiero transmitir el poco respeto que por los estándares muestra Microsoft , a mi entender: el abuso de la posición dominante. Por ejemplo, esta página usa hojas de estilo (css) para modelar su presentación. ¿Qué son estas hojas de estilo ? Son documentos, plantillas, que le dicen a los navegadores como mostrar cada uno de los elementos que aparecen en la página. Aplicadas a lo que estáis viendo: se construye el diseño de la página repartida en tres columnas, dos laterales (donde aparece información secundaria: enlaces, datos, etc.) y una central más ancha (donde aparece la información principal), además se definen cada uno de esos pequeños bloques de información, los colores, los tipos de letra, etc. Por eso esta página se ve mejor con navegadores que respetan estos estándares (como el aconsejado en la columna izquierda: firefox ) que con Internet Explorer.
#+filetags: Software
#+options: _:nil
#+nid: 44

Antes que nada he de decir que este artículo está inspirado en este otro: [[http://www.sahw.com/wp/archivos/2005/08/12/diez-razones-para-no-confiar-en-internet-explorer-7/][diez razones para no confiar en internet explorer 7]], y sobre todo en estos: [[http://barrapunto.com/article.pl?sid=05/08/11/1010242][La verdadera razón por la que Internet Explorer 7 no soportará CSS2]] -- [[http://developers.slashdot.org/article.pl?sid=05/08/01/1147212&tid=113&tid=8][Update on Standards and CSS in IE7]]. El porqué de escribir este artículo: quiero transmitir *el poco respeto que por los estándares muestra Microsoft*, a mi entender: el abuso de la posición dominante. Por ejemplo, esta página usa [[http://www.w3.org/Style/CSS/][hojas de estilo (css)]] para modelar su presentación. ¿Qué son estas /hojas de estilo/? Son documentos, plantillas, que le dicen a los navegadores como mostrar cada uno de los elementos que aparecen en la página. Aplicadas a lo que estáis viendo: se construye el diseño de la página repartida en tres columnas, dos laterales (donde aparece información secundaria: enlaces, datos, etc.) y una central más ancha (donde aparece la información principal), además se definen cada uno de esos pequeños bloques de información, los colores, los tipos de letra, etc. Por eso esta página se ve mejor con navegadores que respetan estos estándares (como el aconsejado en la columna izquierda: [[http://www.mozilla.org/en-US/][firefox]]) que con Internet Explorer. Pues como decía, la siguiente versión del navegador de Microsoft no soportará el estándar definido en CSS2, por lo que muchos creadores de páginas web se verán abocados a la siguiente disyuntiva: creo páginas para internet explorer o creo páginas para el resto del mundo (siguiendo los estándares). Probablemente opten por crearlas para internet explorer ya que este navegador viene de serie en todos los windows (otro abuso de posición dominante, bajo mi punto de vista), y la mayoría de personas que se sientan ante un ordenador utilizan este sistema operativo. ¿[[http://buscon.rae.es/draeI/SrvltGUIBusUsual?TIPO_HTML=2&LEMA=paradoja][Paradojas]] de la vida? Los que utilizamos [[http://www.debian.org][GNU/Linux]] desde hace tiempo nos hemos visto más de una vez en este tipo de problemas: encontramos páginas que no podemos ver porque están diseñadas para IE. Si algo ha hecho avanzar a la humanidad son los acuerdos y el respeto de estos. Algunos ejemplos van desde la normalización del diámetro de las roscas de los tornillos hasta la de la forma en que se comunican los ordenadores a través de un cable. La única arma posible para hacer seguir este camino está en las manos de todos: hagamos uso de productos que respeten los estándares y, desde ahí, que cada cual se quede con el que más le aporte (con el tan traído y llevado valor añadido). Así que... ¡bienvenidos a [[http://www.mozilla.org/en-US/][firefox]]!

--------------

Algunos enlaces para aprender más:

#+BEGIN_QUOTE
  * Organismo de estandarización de la tecnología web:[[http://www.w3.org/][w3c]].
  * Diseño web básico: [[http://www.w3.org/MarkUp/#tutorials][tutoriales de html]] (para conocer el lenguaje en el que se basa la "creación" web).
  * Hojas de estilo: [[http://www.w3.org/Style/CSS/][css]].
  * Problemas de IE 7 con las "CSS 2" en el weblog del propio IE: [[http://blogs.msdn.com/b/ie/archive/2005/07/29/445242.aspx][Standards and CSS in IE]].
#+END_QUOTE


[[https://docs.google.com/forms/d/e/1FAIpQLSeGnXB3zyaNVYcb_2EoO8C5HRc6Emx-2rv2QS6OWNFz1yYSBQ/viewform?usp=pp_url&entry.55081144=El%20cacareado%20Internet%20Explorer%207.0%20%28IE7%20para%20los%20amigos%29...%20y%20sus%20lagunas.][Dejar comentario]].

