#+title: Intoxicación acuosa... y un buen tomate con sal
#+date: <2005-08-17 21:00>
#+author: Godofredo Fdez.
#+description: Supongo que era por la hora, alrededor de las 15:15, por lo que me ha llamado excesivamente la atención un tema tratado en RNE.5 : la intoxicación acuosa o hiperhidratación ( aquí en inglés). Lo relataba Clotilde Vázquez del hospital Ramón y Cajal . Y lo escuchaba en mi coche, mientras volvía del trabajo muerto de hambre :jawdrop:.
#+filetags: Pensamiento
#+options: _:nil
#+nid: 45

Supongo que era por la hora, alrededor de las 15:15, por lo que me ha llamado excesivamente la atención un tema tratado en [[http://www.rtve.es/rne/r5/index.htm][RNE.5]]: la [[http://es.wikipedia.org/wiki/Hiperhidrataci%C3%B3n][intoxicación acuosa o hiperhidratación]] ([[http://en.wikipedia.org/wiki/Water_intoxication][aquí]] en inglés). Lo relataba [[http://www.hrc.es/asistencia/u_nutricion_cm.htm][/Clotilde Vázquez/]] del [[http://www.madrid.org/cs/Satellite?pagename=HospitalRamonCajal/Page/HRYC_home][hospital Ramón y Cajal]]. Y lo escuchaba en mi coche, mientras volvía del trabajo muerto de hambre :jawdrop:.

Nos contaba la doctora que en estos tiempos de excesiva calor, y sobre todo en momentos donde la sudoración es muy fuerte, como en la práctica de deporte a altas temperaturas (ya hay que tener ganas), en trabajos con excesiva exposición al sol (no queda más remedio, hay que ganarse el pan), etc., la pérdida de agua del organismo es mucha, cosa conocida. Lo que no es tan conocido es que junto a la gran cantidad de agua también se pierden "/electrolitos/", en palabras de la propia doctora. Estos /electrolitos/ son sales minerales como el sodio, el potasio, etc. Y si además estamos aquejados de gastroenteritis, diarrea, etc. la pérdida ya es totalmente desmesurada. Las consecuencias pueden ser terribles: desde el edema cerebral hasta el coma, e incluso la muerte.

Decía la doctora que suelen ser habituales los consejos de beber agua frecuentemente pero no son tan habituales los que nos animan a reponer las sales que perdemos.

Y concluía ofreciéndonos la mejor solución/prevención: un buen [[http://es.wikipedia.org/wiki/Gazpacho][gazpacho]] fresquito: sal (cloruro sódico), aceite de oliva, vinagre, TOMATE (que ayuda a la reposición del potasio), zanahoria, pimiento, pepino, ajo, cebolla... También apuntaba la existencia de bebidas isotónicas e incluso la preparación casera de una disolución con sal, limón, etc. (creo que es una especie de suero).

En fin, que *sabios eran nuestros abuelos: un buen tomate con sal*, un cacho de pan, y unos tragos de vino.\\


[[https://docs.google.com/forms/d/e/1FAIpQLSeGnXB3zyaNVYcb_2EoO8C5HRc6Emx-2rv2QS6OWNFz1yYSBQ/viewform?usp=pp_url&entry.55081144=Intoxicaci%C3%B3n%20acuosa...%20y%20un%20buen%20tomate%20con%20sal][Dejar comentario]].

