#+title: Patentes de Software ¡Hemos ganado?
#+date: <2005-07-06 23:31>
#+author: Godofredo Fdez.
#+description: ¡Enhorabuena! Hoy el parlamento europeo ha rechazado la directiva en la que se proponían las patentes de software al estilo USA . La derrota ha sido contundente: 648 votos a favor del rechazo, 14 en contra y 18 abstenciones. Así, hoy deberíamos dormir, y de hecho lo vamos a hacer, más tranquilos. Ahora nos queda preguntarnos: ¿hasta cuando? ¿habrá un nuevo intento? Yo apuesto a que sí, pero según Joaquín Almunia, comisario de Asuntos Económicos, "Si deciden rechazar la posición común, la Comisión no hará una nueva propuesta". Aunque ya se han encargado de "matizarle": la comisaria de Exteriores, Benita Ferrero-Waldner, quien hoy le sustituyó en la sala, dijo que "si el Parlamento nos invita a hacer una nueva propuesta, hablaremos y veremos cuál será el procedimiento futuro"
#+filetags: GNU/Linux I+D+i Pensamiento Software
#+options: _:nil
#+nid: 21

*¡Enhorabuena!*

Hoy el parlamento europeo ha rechazado la directiva en la que se proponían las patentes de software al estilo USA.

La derrota ha sido contundente: 648 votos a favor del rechazo, 14 en contra y 18 abstenciones. Así, hoy deberíamos dormir, y de hecho lo vamos a hacer, más tranquilos.

Ahora nos queda preguntarnos: ¿hasta cuando? ¿habrá un nuevo intento? Yo apuesto a que sí, pero según Joaquín Almunia, comisario de Asuntos Económicos, "Si deciden rechazar la posición común, la Comisión no hará una nueva propuesta". Aunque ya se han encargado de "matizarle": la comisaria de Exteriores, Benita Ferrero-Waldner, quien hoy le sustituyó en la sala, dijo que "si el Parlamento nos invita a hacer una nueva propuesta, hablaremos y veremos cuál será el procedimiento futuro"

En fin... *¡a soñar mientras se pueda!*...y a disfrutar de las [[http://www.gnu.org/philosophy/philosophy.es.html][libertades]].

Tenéis más información [[http://barrapunto.com/article.pl?sid=05/07/06/1052226][aquí]] y [[http://barrapunto.com/~godo.fdez/bitacora][aquí]].


[[https://docs.google.com/forms/d/e/1FAIpQLSeGnXB3zyaNVYcb_2EoO8C5HRc6Emx-2rv2QS6OWNFz1yYSBQ/viewform?usp=pp_url&entry.55081144=Patentes%20de%20Software%20%C2%A1Hemos%20ganado%3F][Dejar comentario]].

