#+title: Ya soy otro becario más
#+date: <2005-10-20 13:44>
#+author: José Ignacio
#+description: Hola a todos! Os escribo para comunicaros la gran noticia: a partir del lunes seré oficialmente becario de Sadiel. Ahora tendré muchas más obligaciones que hasta este momento, más agobios, más ojeras... pero también algo que me aportará muchas cosas positivas y un minisueldecito que me permitirá comprar y regalar discos de Joaquín Calderón a diestro y siniestro ;) Hablando en serio, estoy muy contento. Voy a trabajar en un proyecto open-source relacionado con la educación, y seguro que está muy guay. Creo que Sadiel tiene muchas cosas buenas que ofrecerme y me lo voy a pasar muy bien, sobre todo porque les interesa el concepto de ingeniero-humanista. De momento, como becario durante 6 meses, pero luego ya se verá, una vez que me quite de encima la dichosa asignaturita que me falta para terminar.
#+filetags: Desde_ti
#+options: _:nil
#+nid: 70

Hola a todos! Os escribo para comunicaros la gran noticia: a partir del lunes seré oficialmente becario de Sadiel. Ahora tendré muchas más obligaciones que hasta este momento, más agobios, más ojeras... pero también algo que me aportará muchas cosas positivas y un minisueldecito que me permitirá comprar y regalar discos de Joaquín Calderón a diestro y siniestro ;)

Hablando en serio, estoy muy contento. Voy a trabajar en un proyecto open-source relacionado con la educación, y seguro que está muy guay. Creo que Sadiel tiene muchas cosas buenas que ofrecerme y me lo voy a pasar muy bien, sobre todo porque les interesa el concepto de ingeniero-humanista. De momento, como becario durante 6 meses, pero luego ya se verá, una vez que me quite de encima la dichosa asignaturita que me falta para terminar.

Ya sabéis, telefónicos-solucionadores míos, si queréis veniros os abriré las puertas de la competencia ;) jeje...

Un abrazo para todos!
José Ignacio.

PD: El Joaqui está viviendo ahora en Algeciras, por lo que cada vez se complica más verlo en un concierto :(


[[https://docs.google.com/forms/d/e/1FAIpQLSeGnXB3zyaNVYcb_2EoO8C5HRc6Emx-2rv2QS6OWNFz1yYSBQ/viewform?usp=pp_url&entry.55081144=Ya%20soy%20otro%20becario%20m%C3%A1s][Dejar comentario]].

** Comentarios

*** Se acabó... (José Ignacio 09/05/2006 - 22:14)
Os informo de que ya finalicé mi periodo Sadiel. Ahora posiblemente me dedique a lo mío, ya que tengo posibilidades de entrar en un grupo de I+D. Os mantendré informados ;)

-------------------------------
Dime cuánto tiempo queda,
qué hago, aparte del vago,
finjo estar de acuerdo,
es un milagro que siga estando cuerdo

*** ¿era mas v? (Godo 18/05/2006 - 21:41)
José Ignacio, ¿este comentario no era más "V de Vendetta"? ¿Tú lo has editado con posterioridad? Creo recordad que en su día lo leí y me gustó mucho: por lo atrevido, por lo sincero, por la rabia contenida.

Pero hoy "he venido" a responderte y lo he visto más light (informativo). Recuerdo un análisis de la masificación actual, algún "consejo a lo desesperado"... en fin, aquello que muchas veces pensamos y no nos atrevemos a decir. ¿Dónde está? ;-)

Bueno, la autocensura, supongo.

¡Mucha suerte!

Quien la sigue la consigue ;-)
