#+title: Hoy es mi cumpleaños Feliz :-D
#+date: <2005-10-17 09:22>
#+author: Pili Cantautora
#+description: Queridos compis todos (entiéndase por compis, no sólo los de esta nuestra oficina, sino los de este nuestro rinconcito creado por Godo ;)), hoy es mi cumpleaños feliz!!! :D ya he llegado a mi cuartito de siglo, y estoy muy, muy, muy contenta... Teniendo en cuenta que estaré en TSOL casi todo el día, agradezco mucho tener unos compis tan, tan guays :P Aprovecho que escribo para comentar unas cosillas. Primero, que estoy muy orgullosa del pedazo de fichaje que he hecho con Esther ;) ya nos contarás cómo van tus progresos por el trabajo. Os recuerdo que mañana repite Alfonso... Del tema del recopilatorio cantautoril, no te preocupes Manolo, estamos trabajando en ello :)
#+filetags: Desde_ti
#+options: _:nil
#+nid: 67

Queridos compis todos (entiéndase por compis, no sólo los de esta nuestra oficina, sino los de este nuestro rinconcito creado por Godo ;)), hoy es mi cumpleaños feliz!!! :D ya he llegado a mi cuartito de siglo, y estoy muy, muy, muy contenta... Teniendo en cuenta que estaré en TSOL casi todo el día, agradezco mucho tener unos compis tan, tan guays :P

Aprovecho que escribo para comentar unas cosillas. Primero, que estoy muy orgullosa del pedazo de fichaje que he hecho con Esther ;) ya nos contarás cómo van tus progresos por el trabajo. Os recuerdo que mañana repite Alfonso... Del tema del recopilatorio cantautoril, no te preocupes Manolo, estamos trabajando en ello :)

Espero que paséis muy buen día, besitos para todos! Pili

PD: esta noche es luna llena, significará eso algo?? ;)


[[https://docs.google.com/forms/d/e/1FAIpQLSeGnXB3zyaNVYcb_2EoO8C5HRc6Emx-2rv2QS6OWNFz1yYSBQ/viewform?usp=pp_url&entry.55081144=Hoy%20es%20mi%20cumplea%C3%B1os%20Feliz%20%3A-D][Dejar comentario]].

