#+title: El arte de la "Flinología"
#+date: <2005-10-19 08:52>
#+author: Pili Cantautora
#+description: Una consulta especialmente dedicada a nuestro Romántico: el señor médico que nos atiende en la clínica "flinológica" y que se dedica a la "flinología" se llama…
#+filetags: Desde_ti
#+options: _:nil
#+nid: 69

Una consulta especialmente dedicada a nuestro Romántico: el señor médico que nos atiende en la clínica "flinológica" y que se dedica a la "flinología" se llama "flinólogo", pero... ¿cómo llamamos a la chica que te envuelve en film?? Ahí va una propuesta: en-flin-ador-a :? Habrá que consultarle al académico, por muchos admirado, t mayúscula (T = Arturo Pérez Reverte) ;)

Por cierto, que ayer leí en el bussi que se había añadido al diccionario de la Real Academia (www.rae.es) la palabra "cederrón", ¿no es un poco escalofriante?

Saluditos, P.


[[https://docs.google.com/forms/d/e/1FAIpQLSeGnXB3zyaNVYcb_2EoO8C5HRc6Emx-2rv2QS6OWNFz1yYSBQ/viewform?usp=pp_url&entry.55081144=El%20arte%20de%20la%20%22Flinolog%C3%ADa%22][Dejar comentario]].

** Comentarios

*** Que grande es la Flinoligia!!!! (María_Amebita - 13/02/2006 - 21:29)
(Enviado por María_Amebita el Mié, 19/10/2005 - 10:51)

Yo estoy contigo Pi!! Enflinadora es un termino muy adecuado.

Nosotras queremos estar enflinadas
quien nos enflinara
el enflinador que nos enfline
buen enflinador será.......Puzzled

Saluditos, Amebita\\

*** Polémica... (radioplanner - 13/02/2006 - 21:32)
(Enviado por el radioplanner el Mié, 19/10/2005 - 11:55)

...o filodiversidad, según se mire. "Enflinadora" podría estar muy bien, pero depende siempre de la titulación de la chica en cuestión... no es por titulitis, sólo por claridad y por saber dónde se mete uno. Así pues, deberíamos distinguir entre:
-Enflinóloga: Ha estudiado una diplomatura universitaria sobre las diferentes clases de enflinamientos, su historia y evolución en el tiempo, y cuándo hay que enflinar del derecho o del revés, en sentido horario o antihorario.
-Enflinadora: Ha hecho FP o un módulo de esos que hay ahora. Es muy profesional, se sabe todos los trucos del oficio.
-Enflinista: Ha hecho un curso a distancia de CCC. Mejor no ponerse en sus manos y seguro que tiene un novio cani.

*** entre flin y flin... (joseamebito - 13/02/2006 - 21:34)
(Enviado por joseamebito el Mié, 19/10/2005 - 13:33)

Si ya lo dijo aquel! Entre flin y flin... pastillita laxante.
Pero bueno, sobre las terminologia "fli"...

Entiendo que Flinologo/a es la persona que estudia el flin. Pero que tal flirrollologo/a Seria la persona que estudia el arte del rollo de flin, no? Es decir, la persona que coge el rollo de flin y te disfraza de capullo de seda o de filete de pollo envuelto para guardar en el frigorifico.

saludo flinosos!

*** Un no parar de términos!!!!! (María_Amebita - 13/02/2006 - 21:36)
(Enviado por María_Amebita el Mié, 19/10/2005 - 15:06)

Desde luego esto de la Flinología se está volviendo mucho mas complejo de lo que parecia en un principio, vamos a tener que crear un "Glosario sobre Flinología"

*** Se os está yendo de las manos... (jibseijo - 13/02/2006 - 21:38)
(Enviado por jibseijo el Mié, 19/10/2005 - 17:01)

Esto... ¿os dais cuénta de que se os está yendo la cabeza con todo el universo "flin"? Vais a acabar majaretas como el científico loco ese de Los Simpsons, que por cierto es el profesor Frink, creador de la frinkología... Sticking out tongue

------------------------------
Dime cuánto tiempo queda,
qué hago, aparte del vago,
finjo estar de acuerdo,
es un milagro que siga estando cuerdo
