#+title: ¡Alguien ha llamado!
#+date: <2005-10-14 00:13>
#+author: Godofredo Fdez.
#+description: Ayer dejé el foro inmaculado para ver quien de vosotros se atrevía... supongo que ahora que alguien ya ha roto el hielo (por cierto, radioplanner, de nada. Un placer poner herramientas a la disposición de los buenos coleguillas que quieren compartir) los demás os iréis animando. Por ejemplo, echo de menos una entrada de jibseijo apuntando la tienda friki... a ver si nos vamos decidiendo y hacemos un pedido conjunto. Bueno, poco a poco. :-) Ah! por cierto, que el foro quedará en un plano distinto al de la bitácora (esta tarde, por error de configuración, la primera entrada ha pasado a la portada, ya está subsanado). Considero que la bitácora es algo más personal, y no quiero que pierda ese sabor. Las entradas del foro quedarán disponibles sólo en este, es decir, no pasarán a la página principal de la bitácora. Pero no seáis mal pensados, esto lo hago simplemente por no mezclar, como se dice, "churras" con "merinas". Si así lo deseáis no tenéis que visitar la bitácora para acceder al foro.
#+filetags: Desde_ti
#+options: _:nil
#+nid: 61

Ayer dejé el foro inmaculado para ver quien de vosotros se atrevía... supongo que ahora que alguien ya ha roto el hielo (por cierto, radioplanner, de nada. Un placer poner herramientas a la disposición de los buenos coleguillas que quieren compartir) los demás os iréis animando.

Por ejemplo, echo de menos una entrada de jibseijo apuntando la tienda friki... a ver si nos vamos decidiendo y hacemos un pedido conjunto.

Bueno, poco a poco. :-)

Ah! por cierto, que el foro quedará en un plano distinto al de la bitácora (esta tarde, por error de configuración, la primera entrada ha pasado a la portada, ya está subsanado). Considero que la bitácora es algo más personal, y no quiero que pierda ese sabor. Las entradas del foro quedarán disponibles sólo en este, es decir, no pasarán a la página principal de la bitácora. Pero no seáis mal pensados, esto lo hago simplemente por no mezclar, como se dice, "churras" con "merinas". Si así lo deseáis no tenéis que visitar la bitácora para acceder al foro.

Como véis, en la cabecera azulita he colocado este enlace que os lleva directamente a [[http://godest.bitacoras.com/?q=forum/12][Desde ti]]. Si lo añadís a vuestro bookmark, o favoritos, podréis llegar directamente al foro sin pasar "por la casilla de salida". Así, quien me siga leyendo y comentando será porque de verdad quiere y no porque estaba de paso.

En fin, intento mantener la intimidad de la bitácora abriendo un tablón público paralelo. E intento no aprovecharme de esto último. 8-)

Y otra cosilla: todos los que me conocéis sabéis como ando de tiempo, así que no prometo mucha interactividad }:). Espero que esto no defraude, y si así es, os pido disculpas por adelantado.

Entonces... las musas se fueron a dormir.


[[https://docs.google.com/forms/d/e/1FAIpQLSeGnXB3zyaNVYcb_2EoO8C5HRc6Emx-2rv2QS6OWNFz1yYSBQ/viewform?usp=pp_url&entry.55081144=%C2%A1Alguien%20ha%20llamado%21][Dejar comentario]].

