#+title: Pedro Ricardo Miño y su Piano con Duende
#+date: <2006-05-13 17:21>
#+author: Pili Cantautora
#+description: El pasado jueves 11 tuve una vez más la suerte de disfrutar en directo del "piano con duende" de Pedro Ricardo Miño. Reconozco que no soy para nada una aficionada al flamenco, pero con este chico es diferente... Toca el piano, flamenco. Nacido en Sevilla en 1979, en Triana, es hijo de otros dos grandes artistas, la bailaora Pepa Montes y el guitarrista Ricardo Miño. Hace ya varios años que gracias a mis padres (ellos sí que son grandes aficionados...) pude sentir por primera vez la magia que crea este genial artista en sus conciertos. Para mí es bastante complicado intentar transmitiros lo que en sus conciertos se llega a sentir... En ellos hay un poco de todo, momentos de él solo con el piano, y momentos en los que está realmente bien acompañado... El pasado jueves, y como suele ser habitual en todos sus conciertos, contaba con la compañía de Fernando Terremoto (cantaor), Eléctrico y Bobote (palmeros excepcionales a los que podéis ver en la película-documental "Polígono Sur"), Miguel Vargas al contrabajo (a ratos flamenco, a ratos hindú), y Juan Ruíz a la percusión. En sus conciertos se pasa del chill-out al flamenco más puro... y en ocasiones parece que es propio piano de cola el que va a arrancarse a bailar...
#+filetags: Desde_ti
#+options: _:nil
#+nid: 132

El pasado jueves 11 tuve una vez más la suerte de disfrutar en directo del "piano con duende" de Pedro Ricardo Miño. Reconozco que no soy para nada una aficionada al flamenco, pero con este chico es diferente... Toca el piano, flamenco. Nacido en Sevilla en 1979, en Triana, es hijo de otros dos grandes artistas, la bailaora Pepa Montes y el guitarrista Ricardo Miño. Hace ya varios años que gracias a mis padres (ellos sí que son grandes aficionados...) pude sentir por primera vez la magia que crea este genial artista en sus conciertos.

Para mí es bastante complicado intentar transmitiros lo que en sus conciertos se llega a sentir... En ellos hay un poco de todo, momentos de él solo con el piano, y momentos en los que está realmente bien acompañado... El pasado jueves, y como suele ser habitual en todos sus conciertos, contaba con la compañía de Fernando Terremoto (cantaor), Eléctrico y Bobote (palmeros excepcionales a los que podéis ver en la película-documental "Polígono Sur"), Miguel Vargas al contrabajo (a ratos flamenco, a ratos hindú), y Juan Ruíz a la percusión. En sus conciertos se pasa del chill-out al flamenco más puro... y en ocasiones parece que es propio piano de cola el que va a arrancarse a bailar...

Para mí, que llevo ya unos años viéndole actuar, es muy evidente la evolución que está teniendo Pedro Ricardo. Siempre tímido en los momentos de dirigirse al público, la comunicación con todos sus compañeros en el escenario es increíble, respirándose en todo momento una gran complicidad. Es emocionante ser testigos de cómo sólo a través de las miradas y guiños a través del compás, se puede llegar a alcanzar la total fusión de todos los intrumentos. Como bien apuntó mi hermano el jueves (la primera vez que veía a Pedro Ricardo) llega un momento en el que no se escucha a un piano junto a los demás instrumentos, sino a un todo en total armonía...

Espero que no se os escape la próxima oportunidad que tengamos en Sevilla de verle actuar, que con casi total seguridad será este año en la Bienal de Flamenco. Para mi gusto, se prodiga poco en actuaciones por aquí, y las esperas se hacen largas... Cierto es que no para de viajar, y de aprender. Recientemente ha regresado de la India, en donde ha estado de gira acompañando al brillante músico hindú Ravi Shankar.

Para hacer más corta la espera siempre podemos escuchar su primer disco, "Piano con Duende", aunque como suele ocurrir con los grandes, el trabajo de estudio no tiene comparación con su directo...


[[https://docs.google.com/forms/d/e/1FAIpQLSeGnXB3zyaNVYcb_2EoO8C5HRc6Emx-2rv2QS6OWNFz1yYSBQ/viewform?usp=pp_url&entry.55081144=Pedro%20Ricardo%20Mi%C3%B1o%20y%20su%20Piano%20con%20Duende][Dejar comentario]].

** Comentarios

*** La bienal, ¿está al caer? (Godo 18/05/2006 - 22:02)
La verdad es que tras leer esta crónica de nuestra excelente reportera musical uno siente que está dejando sin conocer un verdadero elixir para sus emociones.

He de reconocer que yo tampoco soy muy aficionado al flamenco, aunque me gusta. A algún que otro concierto he ido y he llegado a emocionarme. Escasamente distingo 2 ó 3 palos, y me cuesta digerir los más hondos.

No he escuchado nada de Pedro Ricardo, pero tras tu fiel retrato de los momentos compartidos con él y su gente, sólo me queda pedirte un favor: ¿te importaría compartir la fecha y lugar de su próxima actuación tan pronto como lo sepas? Si el tiempo, o la autoridad, no lo impiden ¡allí estaré!

Gracias.

*** No en la Bienal 2006 (Pili Cantautora 04/06/2006 - 14:04)
Finalmente, nuestro gozo en un pozo. Aunque todo parecía indicar que Pedro Ricardo volvería a estar este año en la Bienal de Flamenco, por desgracia para nosotros no ha resultado ser así. Este año la Bienal está dedicada especialmente al baile, pero tampoco su madre, la bailaora Pepa Montes, aparece en el cartel. Desde que conozco a la familia, ésta es la primera Bienal en la que no participan, y es una pena...

No pierdo la esperanza de que podamos volver a ver actuar a Pedro Ricardo Miño este año en nuestra ciudad, y busco y rebusco por Internet con la ilusión de encontrar alguna actuación próxima, pero de momento no ha habido mucha suerte... Lo último que he podido encontrar ha sido una actuación en California, nada más y nada menos, hace unas tres semanas... un poquillo lejos, no? :)

Por otro lado, voy a continuar con mis gestiones... espero que dentro de no mucho podamos tener algo así como www.pedroricardomino.com, y que así sea más sencillo para todos seguirle la pista. Ojalá.

*** pues sí que existe! (Pili Cantautora 05/06/2006 - 15:01)
las cosas de la vida, ya existe www.pedroricardomino.com, me dió por problarlo y salió! de todas formas, de información, muy poquita, por no decir que ninguna... Aún así os recomiendo la visita, está colgado uno de los videos que grabó del CD "Piano con Duende", podéis ir poniéndole las caritas a Pedro Ricardo y a alguno de sus acompañantes, aunque el protagonista sale más jovencito de lo que estaba la última vez que le ví... Habrá que ir pensando otros dominios, ¿alguna sugerencia? :)

*** ¿Qué tal este? (Godo 22/06/2006 - 22:51)
pedroricardo.vivencias.net

Yo creo que lo importante es que consigamos ponernos en contacto con él, le comentemos la idea, y si le gusta, que se implique lo mínimo (aunque lo ideal sería: lo máximo) para hacerTE llegar la información que considere oportuna. Como obligatoria estimo que: fechas y lugares de galas y conciertos, pequeña biografía, algunas fotos, pequeños trocitos de grabación...

Bueno, en tus manos (y en las suyas) está el inicio de esta nueva "vivencia" ;-)

*** El Rincon de Pedro Ricardo Miño (Pili Cantautora 11/07/2006 - 14:52)
Aquí seguimos dándole vueltas a la cabeza con el asunto Pedro Ricardo Miño en la red... Hasta ahora rebuscando por Internet lo máximo que he conseguido es enterarme de sus colaboraciones y actuaciones a posteriori, y eso no nos sirve de mucho, para seguirle la pista, eso sí, pero para poco más :) Sé que en su momento nos planteamos llegar hasta él para montarle un pezado de página web, muy completa actualizada, y profesional, pero eso es lo que en realidad me está haciendo retrasar el momento de poner en marcha nuestro pequeño proyecto: el acercamiento al artista. Esas cosas siempre han sido arriesgadas, y no me gustaría que nuestro pianista con duende perdiera su halo de misterio... de momento prefiero mantenerme en la distancia y en el anonimato. Sí que he pensado de todas formas, contactar ya lo antes posible con nuestro "enlace directo", y que sea él, en la medida de lo posible, el que nos mantenga informados. Yo podría poner esa información en el calendario de eventos, y también se podría crear un hilo en el foro, algo así como "Piano con Duende", y ahí os podría comentar sus actuaciones, y las cosillas que leyera por ahí... De esta forma Pedro Ricardo tendría su rinconcito en esta nuestra bitácora, aunque al final no fuera algo a nivel oficial... Ya me comentáis qué os parece la idea.

Aprovecho ya también para comentaros que ayer estuvo Pedro Ricardo en Málaga colaborando en una actuación de Estrella Morente, seguro que estuvo mu guay... ¿cuándo le tocará a Sevilla? no tengo ni idea... y lo que es más importante, ¿nos enteraremos antes de que actúe? ojalá que sí... :)

*** El Rincon de Pedro Ricardo Miño (Amigo 22/07/2008 - 15:43)
Hola!

Siento no haber visto antes este correo, conozco a Ricardo desde hace ya bastantes años y tengo un contacto con él bastante directo, estoy convencido que estaría encantado con vuestra propuesta, la verdad, a mi tambien me gustaría, si algo puedo deciros que si como músico es un mostruo como persona no tiene nombre, es el mejor.

Así que lo dicho, si estais por aquí, nos ponemos en contacto.
Saludos

*** Lo estamos deseando (Godo 23/07/2008 - 18:57)
Hola.

Antes de entrar en materia me gustaría darte las gracias por pasar por aquí y atreverte a dejar tu comentario. Es un placer comprobar como, incluso luchando contra el tiempo, Internet sirve para acortar distancias.

Y para desarrollar la cultura, algo que no siempre aparece en los telediarios porque no suele vender tanto como el morbo y lo oscuro.

Como dice el título de este comentario, estamos deseando ayudar en lo que podamos a Ricardo, y se nos ocurrió por entonces desarrollar una página web con una determinada estructura: dinámica y colaborativa, donde poder ir informando sobre todo aquello que tenga que ver con su universo creativo y musical. Para que el proyecto acabe naciendo pienso que hacen falta dos cosas: tener algo que decir y ganas para decirlo. Luego podemos darle más o menos visos de formalidad, según contemos con mayor o menor grado de beneplácito y apoyo del artista.

Por favor, ponte en contacto con nosotros para intentar lanzarlo si de verdad así lo sientes. [[http://godest.vivencias.net/node/37][Aquí]] puedes encontrar mi dirección de correo electrónico y de "[[http://godest.vivencias.net/node/46][mensajería instantánea]]" para mantener un primer contacto.

Salud.

*** Sí que estamos por aquí! (Pili Cantautora 23/07/2008 - 20:07)
Hola!

Como bien ha confirmado Godo, afortunadamente sí que seguimos estando por aquí! Nos ha hecho mucha ilusión ver tu mensaje, y el poder retomar la idea de poner en marcha un riconcito en la red para Pedro Ricardo.

Para no perder las buenas costumbres... he incluido ya por fin el próximo concierto de Pedro Ricardo en la Bienal y la actuación de sus padres.

Un saludo, y muchas gracias por pasarte por aquí!
