#+title: JAVI OSORIO Y LOS SANTOS PERVERSOS EN FUN CLUB GRATIS
#+date: <2006-09-26 17:43>
#+author: Calavera Bob
#+description: HOLA AMIGOS, EL DÍA 3 DE NOVIEMBRE (viernes) JAVI OSORIO Y LOS SANTOS PERVERSOS STARÁN EN LA SALA FUN CLUB LA ENTRADA ES GRATIS MAS INFORMACIÓN EN…
#+filetags: Desde_ti
#+options: _:nil
#+nid: 170

HOLA AMIGOS,

EL DÍA 3 DE NOVIEMBRE (viernes) JAVI OSORIO Y LOS SANTOS PERVERSOS STARÁN EN LA SALA FUN CLUB

LA ENTRADA ES GRATIS

MAS INFORMACIÓN EN www.javiosorio.net

UN ABRASO,GRACIAS POR LA ATENCIÓN!!

BLUES REEGGAE ROCK FUNKY


[[https://docs.google.com/forms/d/e/1FAIpQLSeGnXB3zyaNVYcb_2EoO8C5HRc6Emx-2rv2QS6OWNFz1yYSBQ/viewform?usp=pp_url&entry.55081144=JAVI%20OSORIO%20Y%20LOS%20SANTOS%20PERVERSOS%20EN%20FUN%20CLUB%20GRATIS][Dejar comentario]].

** Comentarios

*** Esta noche estaremos allí (Godo 03/11/2006 - 18:28)
Hola.

Esta noche nos veremos, Dios mediante, todos los amigos en la sala "Fun Club" de Sevilla, y disfrutaremos de la música y del buen ambiente. Si queréis que nos veamos...

Salud.

*** Yo tambien fuí... (Sofista 06/11/2006 - 12:17)
¡Vaya! Acabo de ver este mesaje... yo también fui al concierto, así que sin saberlo allí estabamos todos juntos y rebujaos, porque hubo bastante gente. Una calor casi insoportable... que mereció la pena aguantar hasta el final, cuando además de Javi Osorio y sus santos perversos apareció ese Joaquín calderón para acompañarlos al violín...¡fantástico!

Después a comprar una de las maquetas, ¡que tampoco hacia calor en esa habitación, je,je! ...(y esto va dirigido especialmente al Señor Osorio) ¡¡¡la próxima vez el concierto en un iglú!!!

...somewhere over the rainbow...

*** sauna gratis (charlycalderon 07/11/2006 - 09:24)
Increible el calor del otro dia en jeje??
Muchas gracias a todos los q aguantaron hasta el final,por que fue una dura prueba de fidelidad q todos superasteis jeje.
Yo personalmentel perdi un par de kilos de cada tobillo, incluso mi bajo perdio algo de peso.
Un saludo a todos , gracias por seguirnos.....

*** Nadie me busca... (Pili Cantautora 09/11/2006 - 08:45)
Holaholita a todos!! llevaba ya mucho tiempo sin escribir (salvo los eventos añadidos al calendario ;)) y la verdad es que el concierto de nuestro amigo Calavera Bob bien merece unas palabritas. Desde luego lo de la calor fue algo insoportable, y ver a Javi con el gorrito de lana no ayudaba! :P pero fue un gustazo verles en un lugar donde poder dar botes a nuestras anchas, y escuchar en directo "Nadie me busca cuando estoy deprimido"... Como peguilla diré que el micro de Charly parecía no funcionar muy bien, y que lo que escuchábamos de sus coros era prácticamente "a pelo", es una pena que no se le escuchara bien...

Me encantó que pudiéramos juntarnos otra vez casi, casi todos (sólo faltó nuestra Mary) y espero que dentro de muy poquito podamos volver a repetir experiencia. Un beso muy fuerte desde Tomares City! :)
