#+title: Qué lío con los planetas...
#+date: <2006-09-07 00:51>
#+author: José Ignacio
#+description: Hola a todos. Me han llegado un par de artículos de Pablo Lonnier Pacheco Railer de la Sociedad Astronómica del Planetario Alfa sobre Plutón, el pimero es un articulo reciente sobre la decisición de la UAI sobre Plutón y el segundo tiene más de un año y se ve que el articulo se adelantó a los hechos que se han producido. A mí me han resultado MUY MUY interesantes, más que aquella revista, y os recomiendo su lectura si tenéis un buen rato libre. Especialmente sé que a Godo le van a gustar... Un saludo de vuestro astrónomo de andar por casa, José Ignacio. ----------------------------------------------------------------------------
#+filetags: Desde_ti
#+options: _:nil
#+nid: 164

Hola a todos. Me han llegado un par de artículos de Pablo Lonnier Pacheco Railer de la Sociedad Astronómica del Planetario Alfa sobre Plutón, el pimero es un articulo reciente sobre la decisición de la UAI sobre Plutón y el segundo tiene más de un año y se ve que el articulo se adelantó a los hechos que se han producido.

A mí me han resultado MUY MUY interesantes, más que aquella revista, y os recomiendo su lectura si tenéis un buen rato libre. Especialmente sé que a Godo le van a gustar...

Un saludo de vuestro astrónomo de andar por casa,
José Ignacio.

----------------------------------------------------------------------------
PLUTÓN: Un planeta con capacidades diferentes
Por Pablo Lonnie Pacheco Railey
pablo@astronomos.org
http://www.sapa.org.mx
Titular de Investigación y Desarrollo
Planetario Alfa

¿Nos puede explicar la desaparición de Plutón del Sistema Solar?
¿Con qué derecho van a quitar a Plutón del Sistema Solar?
¿Por qué ya no lo van a estudiar?

Éstas son preguntas que surgen cuando no se conocen todos los aspectos de la reciente "desplanetización" de Plutón. La noticia fue una "bomba" en los medios informativos y tengo amigos astrónomos que se vistieron de luto el día en que el Planeta Plutón murió.

Plutón no ha desaparecido.
Nadie lo ha quitado, ni lo podrá quitar del Sistema Solar.
Plutón sigue siendo un objeto fascinante, digno de ser estudiado, y recibirá la visita de un artefacto espacial en el 2015.

En la más reciente asamblea de la Unión Astronómica Internacional se definió por votación un asunto que llevaba años sin resolver: la definición de planeta. Por cuestiones históricas, culturales o simplemente sentimentales, muchos astrónomos evadían tocar un punto difícil y espinoso: ¿Qué hacer con Plutón?

Cada vez más se había vuelto evidente que su nombramiento como planeta en 1930 había sido prematuro. Recientemente y mediante el progreso en tecnologías ópticas y de detección, se ha dado el hallazgo de un millar de objetos congelados, a gran distancia del Sol, acompañando a Plutón. Desde hace años, no cabe duda: Plutón pertenece a una gran estructura conocida popularmente como cinturón de Kuiper.

Sí. El Sistema Solar posee 2 cinturones principales: el cinturón de asteroides (objetos de roca y/o metal) que orbitan principalmente entre las trayectorias de Marte y Júpiter; y el cinturón de Kuiper (objetos congelados) cuyas trayectorias típicamente les llevan a revolucionar el Sol a distancias mayores que el planeta Neptuno. Ceres es el objeto más grande del cinturón de asteroides y Plutón el más famoso del cinturón de Kuiper. Recientemente Plutón "ganó" un hermano mayor, cuando se dio a conocer el hallazgo de 2003UB313, otro objeto congelado, ligeramente más grande que Plutón. Si Plutón era planeta ¿Qué hacer con el nuevo inquilino? ¿Cómo clasificarlo?

La NASA quiso imponer la idea de que un planeta más había sido encontrado, pero un sector importante de la comunidad científica no estuvo de acuerdo. La mayoría coincidieron en que --al igual que Plutón-- éste era un objeto más en el cinturón de Kuiper. De este modo, el debate se encendió, los ánimos se calentaron y los científicos fueron orillados a establecer una definición objetiva de la palabra "planeta".

Con la nueva definición de planeta (y de planeta enano), se establece más claramente la naturaleza de los objetos estudiados:

Un planeta es un cuerpo celeste que orbita en torno al Sol y que tiene suficiente masa como para que su propia fuerza de gravedad le permita alcanzar un equilibrio hidrostático, es decir, que presente una forma prácticamente esférica. Además, el campo gravitatorio de este cuerpo ha de ser lo suficientemente intenso como para haber despejado las regiones cercanas al mismo dentro de su órbita. En esta categoría están incluidos 8 planetas: Mercurio, Venus, Tierra, Marte, Júpiter, Saturno y Neptuno. Una propuesta que incluiría 12 planetas fue rechazada antes de la votación.

Un planeta enano es un cuerpo celeste que se encuentra en órbita en torno al Sol y que presenta suficiente masa como para que su gravedad le haga adquirir forma esférica, pero no cuenta con un campo gravitatorio que le permita despejar las regiones vecinas. Un planeta enano no puede ser satélite de otro cuerpo. En esta categoría quedan Ceres, Plutón y 2003UB313 (llamado informalmente Xena). Seguramente se anunciarán más planetas enanos en los próximos años.

Los demás objetos que no sean planetas, planetas enanos o satélites son considerados cuerpos menores del Sistema Solar.

No siempre se puede dar gusto a todos: habrá quienes argumenten que Júpiter y Saturno no son exactamente esféricos (Su veloz rotación los distorsiona) o que los llamados "planetas" no han limpiado del todo sus órbitas (El paso reciente de Toutatis cerca de la Tierra es un recordatorio de que hay una que otra piedra en el camino, y Júpiter y Neptuno son escoltados por asteroides troyanos). Otros hacen alusión a Plutón, que periódicamente cruza la trayectoria de Neptuno, invadiendo carril. En otras palabras, las nuevas definiciones no son terriblemente estrictas, pero --francamente-- son lo suficientemente claras con el fin de evitar malos entendidos.

No es ésta la primera vez que un planeta se ve obligado a abandonar las grandes ligas. Para saber más les recomiendo ampliamente leer el artículo "LA NETA DEL PLANETA: LA NASA ANUNCIA EL DÉCIMO PLANETA" al final de este mensaje.

Saludos y cielos despejados

Vínculos recomendados (en orden alfabético):
2003UB313 http://es.wikipedia.org/wiki/2003_UB313
Artefacto espacial rumbo a Plutón http://www.windows.ucar.edu/tour/link=/space_missions/robotic/pluto_new_horizon/new_horizons_pluto.sp.html
Ceres http://es.wikipedia.org/wiki/%281%29_Ceres
Cinturón de Asteroides http://es.wikipedia.org/wiki/Cintur%C3%B3n_de_asteroides
Cinturón de Kuiper http://es.wikipedia.org/wiki/Cintur%C3%B3n_de_Kuiper
New Horizons http://pluto.jhuapl.edu/
Plutón http://es.wikipedia.org/wiki/Plut%C3%B3n_(planeta )
Unión Astronómica Internacional http://es.wikipedia.org/wiki/Uni%C3%B3n_Astron%C3%B3mica_Internacional

----------------------------------------------------------------------------

**** APENDICE ****

LA NETA DEL PLANETA: LA NASA ANUNCIA EL DÉCIMO PLANETA

Este artículo se escribió hace un año, y te puede dar una idea de porqué la Unión Astronómica Internacional decidió quitar a Plutón de la lista de planetas. ¿Quién lo diría? Algunas partes de esta reflexión se adelantaron a los hechos.

LA NETA DEL PLANETA: LA NASA ANUNCIA EL DÉCIMO PLANETA
Por Pablo Lonnie Pacheco Railey
pablo@astronomos.org
http://www.sapa.org.mx
Sociedad Astronómica del Planetario Alfa
Centro de Astronomía y Ciencias de la Tierra, A.C.
Coordinador Actividades SAPA

El viernes 29 de julio de 2005, cerca de la medianoche me cayó como bomba una noticia emitida por la NASA: anunciaban el descubrimiento del décimo planeta. --¿¿¿¿ QUÉEEEEE ????

Por enésima ocasión tenía ante mis ojos un artículo en el que se afirmaba que, ¡ahora sí! ¡va en serio! ¡no es cáliz!, habían encontrado un planeta más en el Sistema Solar: el famosísimo, el esperado, el aclamado planeta X. Típicamente eso no genera en mí más que un triste suspiro y una sonrisa maliciosa de que alguien se quiere pasar de listo ooooootra vez.

Peeeeero lo que no pude pasar por alto, es que la nota decía claramente que la NASA anunciaba tal hallazgo. Todavía desconfiado, visité el portal electrónico de la NASA y ante mi sorpresa.... ¡SÍ! ¡Era cierto! ¡La N-A-S-A (ya se pueden volver a poner el sombrero) anunciaba el hallazgo del décimo planeta!

Y con todo, volví a sentir desilusión. En estos tiempos la NASA parece estar seriamente preocupada por sus recientes tropiezos y quiere recuperar la credibilidad. Recordando el mal sabor de boca que dejó:

a) Haber incinerado accidentalmente al Mars Climate Observer contra la atmósfera marciana en 1999 (ojo: no es lo mismo pies que metros, pero se les olvidó esa sutil diferencia)
b) Haber estrellado contra el suelo helado de Marte al Mars Polar Lander en 1999.
c) Estrellar en el desierto de Utah a la sonda Genesis con preciadas muestras de átomos solares en 2004 (--dicen las malas lenguas que se dio un " Utahzo"--)
d) Enviar hacia un cometa el telescopio más potente del espacio interplanetario --con problemas de visión incorregibles-- en 2005, y
e) Haber desintegrado en la atmósfera terrestre a 7 astronautas a bordo del Transbordador Espacial Columbia en 2003; tras tanta tragedia, no es extraño que la NASA trate de congraciarse con el público norteamericano.

Pero tengo la corazonada de que la NASA está cometiendo un error, otra vez.

Para empezar, la búsqueda del Planeta X nunca debió haber iniciado. Volvamos atrás unas páginas en la historia y encontraremos que todo empezó con el descubrimiento de Urano: un 13 de marzo de 1781 William Herschel observó lo que al principio creyó era un cometa más. Cuando todo mundo se dio cuenta de que el objeto era un planeta "nuevo" en el Sistema Solar, Herschel --nada tonto-- sugirió llamar al nuevo astro Georgium Sidus, en honor de su patrocinador el Rey Jorge III. Dudo que se tomara a pecho tan cursi nombre, pero --eso sí-- el gesto fue visto con buenos OJO$ por el Rey. Nunca más se tuvo que preocupar Herschel por conseguir una posición privilegiada.

¡Vaya! Parecía que descubrir planetas era buen negocio... ¿dónde habría más plata... perdón... planetas?

En 1766 un astrónomo de nombre Johann Daniel Titius encontró una serie matemática que encajaba con las posiciones de los planetas conocidos. Su tocayo Johann Elert Bode popularizó este ejercicio numérico y muchos se fueron con la finta de que era de su autoría (por eso se conoce como Ley de Bode). La Ley de Bode tenía --sin embargo-- un problema: pronosticaba que entre Marte y Júpiter debía existir un planeta y para muchos era muy claro que en ese espacio no había nada. Peeeeeero, en 1781 Herschel encontró a Urano JUSTO donde estaba pronosticada una posición planetaria según la Ley de Bode.

--¡WOOOOW!
--¡La Ley de Bode sí funcionaba!

Entonces, ¡no había tiempo que perder! Buscaron minuciosamente un planeta más allá de Marte y antes de llegar a Júpiter. La cacería empezó; y el primer día del primer mes del primer año del siguiente siglo (o sea, el 1 de enero de 1801, ` pa acabar pronto) Giussepe Piazzi, un sacerdote italiano, lo encontró. Al igual que Herschel, Piazzi confundió en un principio al objeto con un cometa. Pero Piazzi fue cauteloso: por 5 semanas siguió la trayectoria del misterioso "cometa" --sin decirle a nadie lo que había encontrado-- hasta que cayó enfermo. Además, el objeto se perdió por un tiempo al quedar oculto tras el resplandor del Sol. Al principio algunos dudaron de la veracidad de este reporte.

Tras la recuperación (de los dos), Piazzi nombró al nuevo planeta Ceres, en honor de la diosa patrona de la isla Sicilia. Pero había, al parecer, un problema de status. Ceres no se veía tan ostentoso como Urano. Ceres era tímido, demasiado pequeño para el gusto de la mayoría. Cuando Herschel --descubridor del planeta anterior-- le examinó con el mayor aumento que su telescopio permitió, sugirió que no era un planeta sino un cometa. Herschel calificó al "cometa" de Piazzi como "asteroide", es decir, con el aspecto de una estrella. Herschel sugirió que Ceres no recibiera la categoría de planeta y menos aún cuando en 1802 se había descubierto otro objeto describiendo una trayectoria similar. Con el tiempo apareció otro, y otro, y otro, Y OTRO. ¡Que desgracia! El planeta Ceres se había convertido en la cabecilla de una chusma celeste. Los llamaron asteroides, planetoides, planetas menores y hasta cometoides, pero no, definitivamente no serían llamados planetas.

Pero el planeta de Herschel tampoco era una perita en dulce.

Para 1840 era evidente que Urano era un planeta caprichoso: no seguía el movimiento pronosticado por la física de Newton. De acuerdo con la Ley de Gravitación Universal, un planeta debe acelerarse al acercarse a un objeto masivo y por eso los planetas se aceleran cuando se acercan al Sol. Pero Urano se aceleraba mientras se alejaba del Sol. No parecía tener sentido. Fue entonces que algunos astrónomos, entre quienes se destacan el francés Urbain Le Verrier y el inglés John Couch Adams, defendieron la idea de que la aceleración de Urano se debía a su cercanía con "otro" planeta, no descubierto aún. --¡ Ajá!, y la Luna es de queso-- pensaron muchos astrónomos. Pero nuestros amigos dieron un paso más allá: sugirieron en qué posición del cielo se localizaba el planeta responsable de las desviaciones de Urano. Y así, en menos de 30 minutos, un grupo de astrónomos en el Observatorio de Berlín confirmó que había un planeta a sólo un grado de la posición predicha por Le Verrier (y --luego se demostró-- a cuatro grados de la posición calculada por Adams. El asunto sobre qué país --Inglaterra o Francia-- tenía el derecho a proclamar el hallazgo se convirtió en un pleito internacional que da pena ajena y que se reseña en este sitio: http://axxon.com.ar/rev/146/c-146Divulgacion.htm. El famoso hallazgo aconteció el 23 de septiembre de 1846 y fue un triunfo para la ciencia, pues sirvió para demostrar que --si conocemos las leyes de la naturaleza-- podemos hacer pronósticos muy atinados; en este caso, la existencia de un planeta antes desconocido.

A sólo unos días, y con los ánimos todavía caldeados, los astrónomos empezaron a seguir con atención la trayectoria de Neptuno, y les pareció notar que tampoco se movía apegado a la física newtoniana. --¡ Ajá!-- pensaron --¡otro planeta!-- ¡Ése no se nos escapa! Y así comenzó la famosa búsqueda del planeta que Percival Lowell nombró, en 1905, "Planeta X". Percival Lowell construyó un observatorio específicamente para el hallazgo del Planeta X. Lowell poseía una personalidad optimista y estaba seguro de que encontraría al Planeta X desde su observatorio. Desafortunadamente Lowell no vivió para verlo, pero fue precisamente en ese lugar donde, en 1930, Clyde Tombaugh descubrió a Plutón, cerca de la posición predicha. Sin embargo, las observaciones decepcionaron a muchos: Plutón se veía muy pequeño. Seguramente era INCAPAZ de producir las desviaciones de Neptuno. El hallazgo de Plutón fue una chiripada, mera casualidad. Y surgieron las sospechas --nuevamente-- de que el escurridizo Planeta X se escondía aún en las fronteras externas del Sistema Solar, más allá de Plutón. Y la búsqueda siguió.

Desde entonces, el Planeta X se convirtió en leyenda: una leyenda muuuy redituable. Me pregunto cuántos árboles estarían aún en pie si no se hubiera escrito tanta chatarra. Pero ¡en fin! a mucha gente le gusta consumir chatarra, hasta a mi hijo Pablito.

Plutón es un bicho raro ( ´apa nombrecito, para empezar). No es muy definido que digamos. Se supone que los planetas del Sistema Solar se dividen en planetas terrestres y planetas gaseosos. Los terrestres --como su nombre lo indica-- se parecen a la Tierra: están hechos de roca y metal, su superficie es sólida y se encuentran concentrados cerca del Sol. Los gaseosos --llamados también gigantes-- son como Júpiter: son muy grandes, están cubiertos por gruesas atmósferas de hidrógeno y helio, poseen gran número de satélites y están rodeados por anillos. ¡Ah! Y está Plutón, el cachirul, el peso mosca, que más bien ocupa pertenecer a una clasificación aparte. A mí me gusta ponerlo entre los "planetas menores".

Pero bueno --continuemos con la historia-- ¿Existe algo más allá de Plutón? ¿Existe o no el Planeta X? La respuesta es simple: Sí y No. Hoy sabemos que Plutón está acompañado por un séquito de " Plutinos" (no es broma, los Plutinos existen). Y en cuanto a la existencia del planeta X: cuando la sonda de exploración interplanetaria Voyager 2 visitó a Urano y Neptuno, pudo ratificar y refinar --por mucho-- una serie de datos fundamentales como masa, densidad y tamaño de los planetas gigantes. Y ¿qué creen? Los nuevos datos cuadraron a la perfección con las trayectorias de estos planetas. ¡JÁ! ¡¡¡Los astrónomos habían buscado por casi 150 años un planeta inexistente!!! El Planeta X NUNCA EXISTIÓ. Fue un error de cálculo debido a datos insuficientes o equivocados.

Retrospectivamente surge la pregunta: ¿Por qué a Plutón lo consideraron planeta y a Ceres no? Cualquier astrónomo que haya visto a ambos podrá confirmar que también Plutón parece asteroide, y que es mucho más difícil de ver puesto que la luz que refleja es sumamente tenue. Ceres, por otro lado, puede ser localizado hasta con prismáticos. La verdad es que si Plutón hubiera sido descubierto en cualquier otro observatorio que no fuera el de Lowell, lo más seguro es que lo hubieran catalogado como asteroide. Tras calcular su trayectoria, se preguntarían los astrónomos que #$% estaba haciendo un asteroide más allá de Neptuno y tal vez hubiera iniciado una búsqueda por otros objetos similares.

¿Por qué Plutón es planeta?
Bueno. (suspiro)

Tomaré la respuesta que Pedro Valdés Sada me dio.
Pedro menciona que todo se debe al contexto histórico. Ceres llegó acompañado por el descubrimiento de una muchedumbre de planetas menores, mientras que Plutón fue el planeta consentido por 60 años: Señor absoluto de las profundidades del espacio interplanetario.

Peeeeero, Gerard Kuiper había pronosticado, en 1951, la existencia de un vasto reservorio de cuerpos congelados más allá Plutón. En aquel entonces no existían los telescopios ni la tecnología para verificarlo, pero en 1992 se descubrió a 1992QB1. Sí, más allá de Plutón. Al año siguiente apareció otro, y otro, y otro, Y OTRO. ¿Les suena familiar la historia? Es muy parecido a lo que sucedió con los asteroides. Ahora se conocen alrededor de 1,000 objetos congelados que orbitan al Sol más allá de Neptuno. Algunos llaman a esta familia de planetas menores el Cinturón de Kuiper. Dados los antecedentes que existen, no me sorprende que exista también un debate sobre quién merece el crédito y cuál es el nombre correcto que debe recibir este disco de astros congelados.

¡Qué interesante! Plutón es (hasta ahora) el máximo representante --o cuando menos-- el objeto más grande del cinturón de Kuiper, del mismo modo como Ceres es el objeto más grande del cinturón de asteroides. La diferencia básica es que los asteroides están cerca del Sol y hechos de roca y metal, mientras que los objetos en el cinturón de Kuiper están lejos del Sol y hechos de hielo. Yo sugiero que cada uno se apegue al grupo que pertenece. Si Ceres no es considerado planeta, tal vez Plutón no merezca tampoco tal categoría.

Si Pedro tiene razón, y Ceres no es planeta a causa de su contexto histórico, a mí me parece que el contexto histórico de Plutón ha cambiado y ya no es aquel objeto solitario que lo creímos ser.

¿QUÉ ES UN PLANETA?

Ahora, ¿qué no sería más fácil tomar una decisión al respecto, si tenemos una definición de lo que es un planeta? Pues bien: La palabra planeta tiene un origen griego que significa "errante" o "vagabundo" ¿Por qué un nombre tan despectivo? Bueno, es que los planetas vagan entre las estrellas y no mantienen una posición fija con respecto a las constelaciones. Sin embargo, otros cuerpos del Sistema Solar --como los asteroides o los cometas-- también se mueven entre las constelaciones. Por otro lado, podríamos decir que son planetas los objetos que orbitan a una estrella, pero alrededor del Sol hay --además de planetas-- otros cuerpos celestes. ¡ Mmmmmhh! Difícil decisión.

He escuchado a algunos decir que las estrellas titilan y los planetas no, pero en una noche estable las estrellas no titilan y si hay demasiada turbulencia, hasta los planetas parecen parpadear violentamente.

Otros piensan que es cuestión de tamaño, pero satélites como Titán (Saturno), Ganymede y Callisto (Júpiter) son mayores que Plutón o que Mercurio.

Tal vez el ser planeta tenga que ver con poseer suficiente masa como para quedar redondos (su campo gravitacional los comprime a la forma de una esfera), pero las estrellas también son esféricas, así como algunos satélites y asteroides. Y si de ser rigurosos se trata, planetas como Júpiter y Saturno no son esféricos sino ovalados, por su veloz rotación. Si elaboráramos un modelo a escala de Saturno, podría quedar de 100 cm. de alto por 110 cm. de ancho. El ecuador de estos planetas está ensanchado.

¿Será cuestión de poseer satélites? Lo dudo: Mercurio y Venus no tienen satélites; y ya se ha registrado un puñado de asteroides que poseen satélites (sateloides, les llaman algunos).

¿Atmósfera, como la Tierra? Tampoco. Mercurio no tiene atmósfera, y satélites como Titán (en Saturno) o Tritón (en Neptuno) poseen atmósfera. Incluso hay evidencia indirecta de una débil atmósfera en Ceres.

2003UB313

El nuevo "planeta" fue descubierto por Mike Brown, de la Universidad Tecnológica de California (Caltech), Chad Trujillo (Observatorio Gemini) y David Rabinowitz (Universidad de Yale) El primer registro de este objeto fue obtenido desde el telescopio Samuel Oschin en el Monte Palomar el 21 de octubre de 2003. Eso explica su nombre provisional: 2003UB313 (Ya después le pondrán un nombre más sexy).

2003UB313 es el objeto más distante que se haya observado orbitando al Sol, superando al famoso Sedna. Sedna fue dado a conocer a principios de 2004 --trilladamente-- como "el" nuevo planeta del Sistema Solar. 2003UB313 posee un perihelio (extremo de su órbita cercano al Sol) de 38 unidades astronómicas (recordando que 1 u.a. es la distancia entre el Sol y la Tierra, o aproximadamente 150 millones de Km.). De esta manera, 2003UB313 invade carril, internándose en la órbita de Plutón. Y en su punto más alejado del Sol --en el afelio-- dista a 97 u.a., que es justo donde se encuentra ahora. El período calculado para tamaña vueltesota es de casi 560 años y la inclinación de su órbita es sobresaliente: 45° con respecto a la órbita terrestre (Por eso no había sido descubierto antes, pues se supone que los planetas orbitan al Sol más o menos en el mismo plano). Se estima que su tamaño es de 2,330 a 3,550 Km. de diámetro, dependiendo de qué tan brillante sea su superficie (albedo) y esto lo pone ligeramente encima del tamaño de Plutón. Sí. 2003UB313 es más grande que Plutón, a menos que refleje el 100% de la luz solar (y no existe nada que pueda hacer esto, ni siquiera el espejo del Telescopio Espacial Hubble).

Las observaciones infrarrojas de 2003UB313 señalan que la superficie tiene prácticamente la misma composición que la superficie de Plutón: metano sólido congelado, aunque su color no es rojizo como Plutón sino grisáceo.

Actualmente 2003UB313 se encuentra a 97 unidades astronómicas del Sol. En otras palabras 2003UB313 está más o menos 2 veces más lejos que Plutón, así que en ese lugar hace mucho, mucho frío (-240°C). 2003UB313 se encuentra tan lejos, que sólo puede ser registrado con un telescopio muy grande (mayor a 16" de apertura) desde un sitio muy oscuro, rondando en la constelación de Cetus, el Monstruo Marino.

Uéida-mómen

Si 2003UB313 (¿Cuándo le pondrán el nombre sexy?) fue descubierto desde octubre de 2003... ¿Por qué lo dan a conocer hasta el 2005? Pues porque se requiere un tiempo razonablemente largo para monitorear el movimiento de un objeto así, para poder establecer con seguridad una trayectoria más o menos precisa. Lo menos que desea un astrónomo es arrojar datos sin el respaldo fundamentado de muchas observaciones. De hecho, el equipo de Mike Brown hubiera dejado pasar más tiempo, si no es porque sintieron que un grupo de científicos españoles les estaban pisando los talones. El viernes 29 de julio de 2005 un equipo de astrónomos del Instituto de Astronomía de Andalucía encabezados por el astrónomo José Luis Ortiz anunció un hallazgo realizado con el Telescopio de Sierra Nevada. El objeto --calificado como un pequeño planeta-- es provisionalmente llamado 2003EL61 ¡y aparece acompañado de un satélite!

Curiosamente, el equipo de Brown también había descubierto a 2003EL61, pero no lo había dado a conocer porque querían recabar más datos. Cuando vieron que los españoles les comieron el mandado, se apresuraron en dar a conocer a 2003UB313, apenas 2 horas después del primer anuncio. Y si bien el ambiente entre Brown y Ortiz es cordial, astrónomos americanos y españoles ya iniciaron un acalorado debate con acusaciones de piratería, que dan pena ajena. Otra vez.

Aunque Mike Brown acepta que científicamente Plutón no debería ser considerado planeta --como tampoco ningún otro cuerpo en el cinturón de Kuiper-- defiende que públicamente Plutón (y por ende 2003UB313) debe ser considerado planeta porque culturalmente ya ha sido aceptado como tal (Literalmente dice que la gente ha "abrazado" a Plutón como planeta). Yo pienso diferente. Si por miles de años astrónomos y astrólogos creyeron que la Tierra era el centro del Universo, no importa cuán enraizado estuviera ese concepto, estaba equivocado. Y si por 60 años estuvimos equivocados con respecto a Plutón, nunca es tarde para corregir un error.

Me parece que si la NASA insiste en aceptar también que 2003UB313 es un planeta, al rato encontrarán otro, y otro, y otro, Y OTRO. Y así tendremos una chusma de "planetas". Y la historia se repetirá, una vez más. (Espero morderme la lengua)

Por cierto ¿Quién patrocina a Mike Brown? Nadie menos que la NASA. Sí. La misma NASA que hace el anuncio del hallazgo del décimo planeta. De ahí surge mi desconfianza. No es prudente que la NASA sea juez y parte. Será mucho más fácil y justo si la Unión Astronómica Internacional define cuáles cuerpos del Sistema Solar son planetas y cuáles no.

No soy anti-yanqui pero, después de esta reflexión histórica me pregunto...

¿Qué hubiera pasado si el descubrimiento de Ceres hubiera acontecido en los Estados Unidos?
¿Qué hubiera pasado si el descubrimiento de Plutón hubiera acontecido en una isla del Mediterráneo?

*-*-*-*

Actualización: Al 25 de agosto de 2006, la Unión Astronómica Internacional ha calificado a Plutón de Planeta Enano, quitándolo de la lista de los planetas mayores. 2003UB313 es ligeramente mayor que Plutón.\\


[[https://docs.google.com/forms/d/e/1FAIpQLSeGnXB3zyaNVYcb_2EoO8C5HRc6Emx-2rv2QS6OWNFz1yYSBQ/viewform?usp=pp_url&entry.55081144=Qu%C3%A9%20l%C3%ADo%20con%20los%20planetas...][Dejar comentario]].

