#+title: El pueblo no debería sentir miedo de sus gobernantes. Estos deberían sentir miedo del pueblo.
#+date: <2006-04-27 13:48>
#+author: Godofredo Fdez.
#+description: Vía Uwe Hermann . V oilà! In v iew, a humble v audevillian v eteran, cast v icariously as both v ictim and v illain by the v icissitudes of Fate. This v isage,…
#+filetags: Pensamiento
#+options: _:nil
#+nid: 128

Vía [[http://www.hermann-uwe.de/blog/people-should-not-be-afraid-of-their-governments-governments-should-be-afraid-of-their-people][Uwe Hermann]].

#+BEGIN_EXAMPLE
  Voilà! In                                                       view, a humble

   vaudevillian                                                  veteran, cast 

    vicariously as both                                         victim and

     villain by the                                            vicissitudes of Fate. This 

      visage, no mere                                         veneer of

       vanity, is a                                          vestige of the

        vox populi, now                                     vacant,

         vanished, as the once                             vital

          voice of the                                    verisimilitude now

           venerates what they once                      vilified. However, this 

            valorous                                    visitation of a bygone

             vexation stands                           vivified, and has

              vowed to                                vanquish these 

               venal and                             virulent                   Remember, remember the 5th of November
                vermin                              vanguarding

                 vice and                          vouchsafing the

                  violently                       vicious and

                   voracious                     violation of

                    volition. The only          verdict is 

                     vengeance; a              vendetta held as a 

                      votive, not in          vain, for the

                       value and             veracity of such shall one day

                        vindicate the       vigilant and the

                         virtuous.         Verily, this 

                          vichyssoise of  verbiage 

                           veers most    verbose

                            vis-à-vis an introduction,

                             and so it is my

                              very good honor

                               to meet you

                                and you may

                                 call me

                                    V.
#+END_EXAMPLE

Yes, I've seen [[http://www.imdb.com/title/tt0434409/][V for Vendetta]] today. Very impressing movie, highly recommended! Makes you start to think...

;-)

Sí, yo también [[http://www.imdb.com/title/tt0434409/][la]] vi ayer. Una película impresionante, ¡muy recomendable! Te incita a pensar... (ojalá que a mucha gente).

\\


[[https://docs.google.com/forms/d/e/1FAIpQLSeGnXB3zyaNVYcb_2EoO8C5HRc6Emx-2rv2QS6OWNFz1yYSBQ/viewform?usp=pp_url&entry.55081144=El%20pueblo%20no%20deber%C3%ADa%20sentir%20miedo%20de%20sus%20gobernantes.%20Estos%20deber%C3%ADan%20sentir%20miedo%20del%20pueblo.][Dejar comentario]].

** Comentarios

*** Desde luego (Epaminondas Pantulis 11/05/2006 - 12:36)
Ciertamente es de lo mejor que puede verse en el cine en estos días.\\

*** ¿Habéis leído el libro (Fran 16/06/2006 - 00:29)
¿Habéis leído el libro "1984", de George Orwell? La película me recordó mucho a éste (principalmente por su temática), y ciertamente considero que el libro te hace pensar mucho más...

*** Está en la lista (Godo 16/06/2006 - 14:05)
Hola Fran.

Efectivamente, muchos amigos me han comentado eso mismo. Yo no he leído el libro aún, ni he visto la película (doy fe de que al menos existe una versión llevada al cine), pero lo tengo en la lista. Se puede descargar desde [[http://www.planetalibro.net/ebooks/eam/ebook_view.php?ebooks_books_id=27][aquí]].

Aprovecho para dejar este enlace a [[http://www.planetalibro.net/ebooks/eam/index.php][Planeta Libro]]. Ahí tenéis disponibles muchas obras literarias en formato electrónico, y su descarga no viola ninguna ley pues están ya en el "[[http://es.wikipedia.org/wiki/Dominio_p%C3%BAblico][dominio público]]".

A seguir +leyendo+ creciendo.\\
