#+title: JAVI OSORIO Y LOS SANTOS PERVERSOS
#+date: <2006-11-08 11:26>
#+author: Calavera Bob
#+description: HOLA A TODOS/AS: ESCRIBO PARA DAR LAS GRACIAS. ESTOY DE ACUERDO CON CHARLY,FUE UNA DURA PRUEBA DE FIDELIDAD...Y TAMBIÉN FUE UNA DURA PRUEBA PARA MI PORQUE POR POCO ME DA ALGO...QUE CALOR!! BUENO ESO YA QUEDÓ ATRÁS... OS CUENTO UN POCO LOS PROYECTOS: SE GRABARÁ EL VIDEOCLIP DE "ATRAVESANDO LA LADERA", SE HARÁ UNA COMPLETA RESTAURACIÓN DE LA PÁGINA WEB WWW.JAVIOSORIO.NET QUE FALTA LE HACE YA..SE COLGARÁ MÚSICA GRATIS EN LA PÁGINA, VIDEOS, ETC. Y SE GRABARÁ ALGO NUEVO... CON RESPECTO A LOS CONCIERTOS: HABRÁ DOS VERTIENTES: LA DE JAVI OSORIO Y LOS SANTOS PERVERSOS..
#+filetags: Desde_ti
#+options: _:nil
#+nid: 177

HOLA A TODOS/AS:

ESCRIBO PARA DAR LAS GRACIAS.
ESTOY DE ACUERDO CON CHARLY,FUE UNA DURA PRUEBA DE FIDELIDAD...Y TAMBIÉN FUE UNA DURA PRUEBA PARA MI PORQUE POR POCO ME DA ALGO...QUE CALOR!!

BUENO ESO YA QUEDÓ ATRÁS...

OS CUENTO UN POCO LOS PROYECTOS:

SE GRABARÁ EL VIDEOCLIP DE "ATRAVESANDO LA LADERA", SE HARÁ UNA COMPLETA RESTAURACIÓN DE LA PÁGINA WEB WWW.JAVIOSORIO.NET QUE FALTA LE HACE YA..SE COLGARÁ MÚSICA GRATIS EN LA PÁGINA, VIDEOS, ETC. Y SE GRABARÁ ALGO NUEVO...

CON RESPECTO A LOS CONCIERTOS:

HABRÁ DOS VERTIENTES:

LA DE JAVI OSORIO Y LOS SANTOS PERVERSOS..

Y OTRA EN LA QUE TOCARÉ UN REPERTORIO NUEVO EN EL QUE ME DEDICO A CONTAR HISTORIAS...SÓLO CON GUITARRA Y VOZ...
EN PRINCIPIO ESTÁ EL PROYECTO DE ACTUAR JUNTO A MARIO DÍAZ DE "LOS ASLANDTICOS".MUY PRONTO (ESTE INVIERNO) HAREMOS UN CONCIERTO EN SEVILLA,EN LA SALA MALANDAR..

LO PONDREMOS TODO EN LA PÁGINA WEB.

MUCHÍSIMAS GRACIAS,SIEMPRE ES UN PLACER EN LA PÁGINA DE MI AMIGO GODO Y MI AMIGA ESTHER..QUE EL OTRO DÍA SUPONGO QUE SALDRÍAN CORRIENDO POR LA CALOR Y POR ESO NO LOS VI...

DE NUEVO MUCHAS GRACIAS POR LA ATENCIÓN!!!


[[https://docs.google.com/forms/d/e/1FAIpQLSeGnXB3zyaNVYcb_2EoO8C5HRc6Emx-2rv2QS6OWNFz1yYSBQ/viewform?usp=pp_url&entry.55081144=JAVI%20OSORIO%20Y%20LOS%20SANTOS%20PERVERSOS][Dejar comentario]].

