#+title: Manuel Cuesta en el Perro Andaluz
#+date: <2006-01-03 18:34>
#+author: Pili Cantautora
#+description: Hola chic@s! Feliz Año!! Parece ser que la Temporada Cantautoril 2006 ha empezado fuerte, y aquí estoy una vez más para haceros una proposición indecente ;) Hoy es martes, y como tal, actúa Alfonso del Valle, este año ya de nuevo en El Perro Andaluz... Pero en esta ocasión, como novedad, os propongo ir mañana, miércoles, a ver a Manuel Cuesta (www.manuelcuesta.com). Desde que se mudó a Madrid es difícil verle actuar por aquí y merece la pena aprovechar las pocas oportunidades que aún tenemos... Fue con él con quien José Ignacio aprendió a tocar la guitarra (:)), y aunque es bastante diferente de Alfonso, también tiene su encanto, sin duda, y de hecho suele ser el que más gusta a la primera oída...
#+filetags: Desde_ti
#+options: _:nil
#+nid: 92

Hola chic@s! Feliz Año!! Parece ser que la Temporada Cantautoril 2006 ha empezado fuerte, y aquí estoy una vez más para haceros una proposición indecente ;) Hoy es martes, y como tal, actúa Alfonso del Valle, este año ya de nuevo en El Perro Andaluz... Pero en esta ocasión, como novedad, os propongo ir mañana, miércoles, a ver a Manuel Cuesta (www.manuelcuesta.com). Desde que se mudó a Madrid es difícil verle actuar por aquí y merece la pena aprovechar las pocas oportunidades que aún tenemos... Fue con él con quien José Ignacio aprendió a tocar la guitarra (:)), y aunque es bastante diferente de Alfonso, también tiene su encanto, sin duda, y de hecho suele ser el que más gusta a la primera oída...

Como siempre, el concierto en sí mismo es más bien una excusa para poder pasar todos un ratito agradable. Además, esta vez tenemos también el aliciente de que es en el "Chucho Pulgoso" :P Espero que Manolo se apunte (Mary, convéncele pliss!!), y se produzca nuestro reencuentro (siento muchísimo la entrega frustrada de CDs en la asociación :( ). El concierto es a las 21:30, pero podríamos quedar en torno a las 20:00 para tomarnos algo, y así llegar prontito al chucho y pillar mesa, que el concierto se disfruta más así ;)

De momento nada más, espero que os animéis y que nos veamos mañana las caritas. Besitos!


[[https://docs.google.com/forms/d/e/1FAIpQLSeGnXB3zyaNVYcb_2EoO8C5HRc6Emx-2rv2QS6OWNFz1yYSBQ/viewform?usp=pp_url&entry.55081144=Manuel%20Cuesta%20en%20el%20Perro%20Andaluz][Dejar comentario]].

** Comentarios

*** Gracias por compartir... (Godo 13/02/2006 - 21:44)
(Enviado por Godo el Jue, 05/01/2006 - 22:07)

...la información con este nivel de entusiasmo.

Siento mucho el no haber ido. Llevo varios días de atascos, choques, regates, etc. embutido en ese devenir consumista de estas felices y senti
mentales fiestas. Si no fuera por las vacaciones... Smiling

Ya habrá otra oportunidad. Espero que lo pasarais bien.

Lo dicho: gracias.
