#+title: Alfonso del Valle, otra vez en AntiguaSevilla
#+date: <2006-10-21 19:56>
#+author: Sofista
#+description: Por si no lo sabeis, yo os lo digo... Alfonso vuelve desde el próximo martes a tocar por las noches en la Asociacion Antigua Sevilla, por lo que dijo en el concierto del pasado 19 de octubre en la sala Malandar estará hasta diciembre, en principio. Así que ya sabeís todos los martes en la Calle Castellar, nº 50, a partir de las 21:30 horas. Y con el permiso de Don Calavera Bob, os dejo otras fechas de conciertillos que se harán por aqui, en Sevilla, de la gente de la Asociacion de Cantautores de Sevilla. 26 de octubre, Mafy, Alvaro Laguna y JoseEmilio (que actuará con Antonio Bernal, lo más seguro), en el Pub Magia y Música, a partir de las 21:30 hras (C/Virgen de las Montañas, en Los Remedios)
#+filetags: Desde_ti
#+options: _:nil
#+nid: 175

Por si no lo sabeis, yo os lo digo... Alfonso vuelve desde el próximo martes a tocar por las noches en la Asociacion Antigua Sevilla, por lo que dijo en el concierto del pasado 19 de octubre en la sala Malandar estará hasta diciembre, en principio. Así que ya sabeís todos los martes en la Calle Castellar, nº 50, a partir de las 21:30 horas.

Y con el permiso de Don Calavera Bob, os dejo otras fechas de conciertillos que se harán por aqui, en Sevilla, de la gente de la Asociacion de Cantautores de Sevilla.
26 de octubre, Mafy, Alvaro Laguna y JoseEmilio (que actuará con Antonio Bernal, lo más seguro), en el Pub Magia y Música, a partir de las 21:30 hras (C/Virgen de las Montañas, en Los Remedios)
2 de noviembre, en el Magia y Música, Maria Lora y Manuel Ruiz, 21:30 horas.
8 de noviembre, Mariano Cuesta en el Kafka (Alameda), a partir de las 21:30 horas.
23 de noviembre, Mariano Cuesta y Jose Antonio Delgado, en Magia y Música. A partir de las 21:30 horas.

Besillos a todos\\


[[https://docs.google.com/forms/d/e/1FAIpQLSeGnXB3zyaNVYcb_2EoO8C5HRc6Emx-2rv2QS6OWNFz1yYSBQ/viewform?usp=pp_url&entry.55081144=Alfonso%20del%20Valle%2C%20otra%20vez%20en%20AntiguaSevilla][Dejar comentario]].

