#+title: ¡Chas gracias!
#+date: <2006-05-29 12:36>
#+author: el radioplanner
#+description: Bueno, en un ratín que tengo disponible entre preparativos de viaje y demás, os quisiera dar las gracias a los asistentes al evento... hay que ver lo guapísimos que ibáis todos!!! Espero que os gustara el evento y que lo pasárais bien... nosotros acabamos a las 6 y pico y con un resacón al día siguiente que pa qué os cuento... En fin, también se pueden extraer algunas enseñanzas y nuevos conocimientos del sábado pasado, como lo bien que baila sevillanas nuestro webmaster (el tío sabe cuándo tiene que dar la vuelta y todo) y que hay que llevar calzado cómodo si se quiere aguantar más rato jeje...
#+filetags: Desde_ti
#+options: _:nil
#+nid: 137

Bueno, en un ratín que tengo disponible entre preparativos de viaje y demás, os quisiera dar las gracias a los asistentes al evento... hay que ver lo guapísimos que ibáis todos!!!
Espero que os gustara el evento y que lo pasárais bien... nosotros acabamos a las 6 y pico y con un resacón al día siguiente que pa qué os cuento... En fin, también se pueden extraer algunas enseñanzas y nuevos conocimientos del sábado pasado, como lo bien que baila sevillanas nuestro webmaster (el tío sabe cuándo tiene que dar la vuelta y todo) y que hay que llevar calzado cómodo si se quiere aguantar más rato jeje...
En fin, mi mujer me reclama...
¡¡¡Besitos para todos!!!

P.D.: Un besito también de parte de la cónyuge.


[[https://docs.google.com/forms/d/e/1FAIpQLSeGnXB3zyaNVYcb_2EoO8C5HRc6Emx-2rv2QS6OWNFz1yYSBQ/viewform?usp=pp_url&entry.55081144=%C2%A1Chas%20gracias%21][Dejar comentario]].

** Comentarios

*** Fue un placer (Pili Cantautora 04/06/2006 - 13:36)
Paquito!!! qué lejos os tenemos ahora mismito! espero que estéis disfrutando de lo lindo en tierras vietnamitas, si aquello es tan espectacular en fotos, ya me puedo imaginar lo que tiene que ser verlo en persona...

Que sepas que fue un placer el poder acompañaros en ese día tan bonito para vosotros, estabais guapísimos! por cierto, vaya pedazo de madrina! :)

Respecto al tema de los zapatos, jejeje... eso de ponerse unos zapatos que hace una como 6 años que no los usa es lo que tiene... de todas formas, yo ya he aprendido la lección, y para el evento de nuestra Mariquilla pienso ir preparada, y bailarme algo y todo!!! :P

Besitos matrimonio!!
