#+title: Otras lecturas de verano
#+date: <2006-09-25 17:32>
#+author: Miguel Angel
#+description: Aprovechando el tiempo libre que generan las vacaciones he logrado dedicar parte de mi tiempo a un par de lecturas diferentes a las habituales del período lectivo. Las dos han sido satisfactorias. Os las resumo: El último Catón. Una entretenida - a veces no tanto- historia de intrigas y enredos con diversas Iglesias de por medio, ambientada en distintas ciudades. Una especie de Código da Vinci a la española (Matilde Asensi), pero con mejor prosa - e incluso versos, de Dante-. Travesuras de la niña mala. Una bonita historia sobre el amor y el desamor de un peruano emigrado a Europa durante finales del pasado siglo.
#+filetags: Desde_ti
#+options: _:nil
#+nid: 169

Aprovechando el tiempo libre que generan las vacaciones he logrado dedicar parte de mi tiempo a un par de lecturas diferentes a las habituales del período lectivo. Las dos han sido satisfactorias. Os las resumo:

El último Catón. Una entretenida - a veces no tanto- historia de intrigas y enredos con diversas Iglesias de por medio, ambientada en distintas ciudades. Una especie de Código da Vinci a la española (Matilde Asensi), pero con mejor prosa - e incluso versos, de Dante-.

Travesuras de la niña mala. Una bonita historia sobre el amor y el desamor de un peruano emigrado a Europa durante finales del pasado siglo. Lo último de Mario Vargas Llosa, quizá con algún tinte autobiográfico. Para disfrutar y para reflexionar sobre nuestras pasiones.


[[https://docs.google.com/forms/d/e/1FAIpQLSeGnXB3zyaNVYcb_2EoO8C5HRc6Emx-2rv2QS6OWNFz1yYSBQ/viewform?usp=pp_url&entry.55081144=Otras%20lecturas%20de%20verano][Dejar comentario]].

