#+title: Inauguración de la Primavera con Alfonso
#+date: <2006-03-22 08:44>
#+author: Pili Cantautora
#+description: Buenos días! Aprovechando que he llegado tempranito a la oficina, antes de irme a Granada quería escribir unas palabritas sobre el concierto de anoche... En primer lugar decirle a Antonio que sentimos no podernos despedirnos anoche de él, salimos corriendo con eso del madrugón que nos esperaba hoy... Me alegro mucho de que finalmente nos manifestáramos, aunque hay que reconocer que nos costó arrancar, jejeje, aunque después de eso nuestro Webmaster se lanzó ;) (el tema de la dedicatoria, lo dejo para José Ignacio... qué detalle Godito!) Por cierto, por lo que ví anoche finalmente elegiste la opción de "to shave", y ya se comenta incluso en la web de Alfonso :P
#+filetags: Desde_ti
#+options: _:nil
#+nid: 116

Buenos días! Aprovechando que he llegado tempranito a la oficina, antes de irme a Granada quería escribir unas palabritas sobre el concierto de anoche...

En primer lugar decirle a Antonio que sentimos no podernos despedirnos anoche de él, salimos corriendo con eso del madrugón que nos esperaba hoy... Me alegro mucho de que finalmente nos manifestáramos, aunque hay que reconocer que nos costó arrancar, jejeje, aunque después de eso nuestro Webmaster se lanzó ;) (el tema de la dedicatoria, lo dejo para José Ignacio... qué detalle Godito!) Por cierto, por lo que ví anoche finalmente elegiste la opción de "to shave", y ya se comenta incluso en la web de Alfonso :P

Sé que lo que voy a decir ahora hará que se me eche encima el personal masculino, pero... eché de menos al Chiqui!! :P jejeje, vamos, en algunas canciones especialmente... Sesión Golfa me gustó bastante, aunque siento que a uno de los dos chavales a penas se le escuchara con las guitarras... y de Alfonso... qué voy a decir! me gustó especialmente anoche, para mi gusto transmitía algo especial... ¿sería la primavera? Por cierto, que la canción de Hassam sonó mu guay con la gaita...

Buenos chicos, podría decir muchas cosas más, pero de momento me voy a ir despidiendo, que ya mismo estoy en el coche caminito de Granada... Nos seguimos leyendo por aquí. Saluditos, Pili.

PD: webmaster, mañana vemos lo del calendario...


[[https://docs.google.com/forms/d/e/1FAIpQLSeGnXB3zyaNVYcb_2EoO8C5HRc6Emx-2rv2QS6OWNFz1yYSBQ/viewform?usp=pp_url&entry.55081144=Inauguraci%C3%B3n%20de%20la%20Primavera%20con%20Alfonso][Dejar comentario]].

** Comentarios

*** Qué gran noche... :) (jibseijo 24/03/2006 - 18:25)
Bueno, por fin escribo sobre aquella noche.

Fue una noche genial: empezó muy bien y terminó mejor. De entrada, ese gran momentazo de presentación con Antonio, que no sé si será por lo bien que nos caes o porque realmente fue así, creo que esa noche tocaste mejor que nunca. Cada vez me animo más a ir a una session de esas del pub, tienen que ser muy chulas.

El concierto fue uno de los mejores que recuerdo de Alfonso. Pienso igual que Pili: Alfonso estaba especialmente motivado, como si estuviera empezando en esto ahora, con toda la ilusión del mundo. Me encantó.

Y sobre todo... La dedicatoria! Fue sorpresa sorpresa, no me esperaba que Alfonso tocara una de mis canciones favoritas (por no decir mi favorita) y nos la dedicara a Pili y a mí. Godo, te saliste: muchas gracias. Fue curioso cómo yo mismo notaba la cara de tontito que se me quedó durante la canción, pero no podía evitarlo.

Y otra cosita: durante el concierto se confirmó que compré un telescopio (por ebay a precio de risa) que ayer mismo recogí en Madrid y ya tengo totalmente montado. De momento no he podido probarlo (es de día, está nublado, en fin...) pero esta noche será la gran prueba. Tiene muy buena pinta, y lo mejor es los ratos (y noches) que nos va a dar en el campo cuando llegue la calorcita: piscina, barbacoa, caipirinhas, estrellas... amenizado por nuestra música de fondo. La verdad es que no suena mal, ¿eh? ¡Dentro de poco las imágenes de la sección "Cosmos" estarán tomadas por nosotros mismos!

Pues de momento eso es todo. Lo único que me queda es recordaros que el viernes 31 a las 17:00 presento el PFC y estáis invitados (aula 110, Escuela Superior de Ingenieros).

Un abrazo!
José Ignacio.

----------------------------
Dime cuánto tiempo queda,
qué hago, aparte del vago,
finjo estar de acuerdo,
es un milagro que siga estando cuerdo
