#+title: Soy tecnólogo!!
#+date: <2006-06-29 17:21>
#+author: José Ignacio
#+description: Hola a todos! Quería compartir con todos vosotros que en breve seré "tecnólogo" (aún no tengo del todo claro en qué consiste...). Me alegro mucho de haber…
#+filetags: Desde_ti
#+options: _:nil
#+nid: 147

Hola a todos!

Quería compartir con todos vosotros que en breve seré "tecnólogo" (aún no tengo del todo claro en qué consiste...). Me alegro mucho de haber dejado mi anterior trabajo, que no me aportaba nada a nivel personal, y tras arriesgarme y pertenecer al paro durante un mes y medio he conseguido un puesto en el que creo que me sentiré bastante más a gusto (y encima mejor pagado).

Ánimo a todos los que como yo decidáis echarle valor y poder elegir en vuestra vida!!!!!

Ya mismo estoy comprándome nuevo telescopio, jeje...

Un saludo,
José Ignacio.


[[https://docs.google.com/forms/d/e/1FAIpQLSeGnXB3zyaNVYcb_2EoO8C5HRc6Emx-2rv2QS6OWNFz1yYSBQ/viewform?usp=pp_url&entry.55081144=Soy%20tecn%C3%B3logo%21%21][Dejar comentario]].

** Comentarios

*** Me alegro (Godo 30/06/2006 - 08:18)
Hola.

No sé si es precipitado darte la enhorabuena, lo digo por lo de "en breve seré"...

Ya nos contarás con un poco de más detalle cuando se pueda, supongo.

Pero de lo que más me alegro es de que le echaras valor y de que te arriesgaras a "poder elegir".

Un abrazo.
