#+title: uy uy uy...
#+date: <2006-05-22 22:14>
#+author: el radioplanner
#+description: ...qué ya tengo el evento encima! Un saludo para todos desde la poca paz y la poca tranquilidad del hogar. Todavía no estoy del todo nerviossoosoooso, pero…
#+filetags: Desde_ti
#+options: _:nil
#+nid: 135

...qué ya tengo el evento encima!

Un saludo para todos desde la poca paz y la poca tranquilidad del hogar. Todavía no estoy del todo nerviossoosoooso, pero copo me deca... digooo poco me queda...

Bueno, Godo, te sigo prometiendo algún día un post jugoso (o semijugoso, tampoco vamos a crear altas expectativas... bueno, dejémoslo en semiseco), y cuando pasen estos exámenes, bodas e indochinas, también algo más de frecuencia.

Qué hambre... a ver qué pesco!!!

¡Saludos para tod@s!\\


[[https://docs.google.com/forms/d/e/1FAIpQLSeGnXB3zyaNVYcb_2EoO8C5HRc6Emx-2rv2QS6OWNFz1yYSBQ/viewform?usp=pp_url&entry.55081144=uy%20uy%20uy...][Dejar comentario]].

** Comentarios

*** paquito!!! (Pili Cantautora 24/05/2006 - 08:46)
Hola Paco! qué alegría el verte por aquí, ésta tu semana de concentración pre-eventual ;) Yo tengo ya muchas ganas de que llegue el sábado, y veros a Rocío y a tí muy guapetones y disfrutando de lo lindo después de tanta preparación eventual... Por cierto, que el otro día leí un reportaje sobre un pedazo de hotel en Vietnam, y no veas la pelusilla que me dísteis!! :P

Mucha, mucha suerte para esta semana, y besos miles para los dos!

PD1: hoy se enfrenta nuestra María a Mr. Víctor, ya os contaremos qué tal se da la cosa... no hay dolor!! :)

PD2: Mary ha vuelto!!!

*** ¡y yo! (el radioplanner 24/05/2006 - 20:55)
Pues yo también tengo ganas de que llegue el sábado, y que pase el paripé inicial para ir a lo que importa... ¡al fiestorro!

Espero que nuestra María no se derrumbe ante VV... sabemos que es pequeña pero valiente, pero no sabemos hasta qué grado de crítica destructiva puede soportar.

¡Qué buena noticia que la Mary haya regresado! (para nosotros, que podremos disfrutar de nuevo de su compañía, y para ella al menos porque debe ser signo de que está casi recuperada)

Besuskis para todos!!!

P.D.: Acabo de hacer un examen para el que he tenido que hacer una ruta de la tapa por Sevilla, y tengo un hambre que da calambre...\\

*** Ya esta aquí!!!!!!!!!!! (María 26/05/2006 - 08:53)
Hombreee Paquito!!!!!
Me alegro de verte por aquí! Que poquito te queda!
Mucho ánimo para los dos!

Yo también tengo muchas ganitas de que se sábado para ver lo guapísimos que vais a estar.

Mi encuentro con Víctor fue bien ( dejando a parte que me dijo que tenía: muchas ojeras, los ojos caídos y la mandíbula muy ancha que me hacia parecer mas gorda......pero siempre desde el cariño), fui una chica fuerte!!!!

Bueno pues en un ratito nos vemos!!!
Besos!!!!!
