#+title: ¡Ahorrate 50$ en tu sitio web!
#+date: <2006-11-22 22:16>
#+author: Godofredo Fdez.
#+description: ¿Quieres poner en marcha tu propio Drupal , o cualquier otro proyecto web? En tal caso, déjame hablarte de Dreamhost , que es el proveedor de hosting de godest.vivencias.net, la página que estás leyendo ahora mismo. Se trata de uno de los grandes proveedores de albergue compartido (y dedicado) de Internet, lo que les permite tener un plan de precios competitivo . A destacar los 200GB (¡sí, 200 Gigas, has leído bien!) de espacio en disco (que además se van incrementando 1 GB por semana), los 2TB de ancho de banda (que se van incrementando 16GB cada semana), el registro de un dominio gratuito con el alta y la posibilidad de tener un número ilimitado de subdominios sobre éste y cualquier otro dominio que registres con ellos.
#+filetags: 
#+options: _:nil
#+nid: 178

¿Quieres poner en marcha tu propio [[http://drupal.org][Drupal]], o cualquier otro proyecto web?

En tal caso, déjame hablarte de [[http://www.dreamhost.com/r.cgi?159740][Dreamhost]], que es el proveedor de hosting de godest.vivencias.net, la página que estás leyendo ahora mismo.

Se trata de uno de los grandes proveedores de albergue compartido (y dedicado) de Internet, lo que les permite tener un [[http://www.dreamhost.com/hosting.html][plan de precios competitivo]].

A destacar los 200GB (¡sí, 200 Gigas, has leído bien!) de espacio en disco (que además se van incrementando 1 GB por semana), los 2TB de ancho de banda (que se van incrementando 16GB cada semana), el registro de un dominio gratuito con el alta y la posibilidad de tener un número ilimitado de subdominios sobre éste y cualquier otro dominio que registres con ellos.

¿Y en cuanto a soporte lenguajes? Hay un poco de todo, desde PHP, Perl, MySQL hasta Ruby on Rails... Hay bastante más, aunque, por supuesto, si necesitas alguna más exótica, te la puedes compilar tú mismo usando el acceso ssh.

Recientemente han incluido soporte para svn.

Respecto a fiabilidad y calidad, hasta la fecha, no se ha producido ninguna caída catastrófica ni interrupción significativa del servicio.

Podéis conocer más cosas de las que yo podría contar en una entrada de la bitácora visitando tanto su [[http://blog.dreamhost.com/][blog oficial]] como su [[http://blog.dreamhosters.com/][blog no oficial]], e incluso su [[http://wiki.dreamhost.com/][wiki]].

En conclusión, probablemente [[http://www.dreamhost.com/r.cgi?159740][Dreamhost]] es el hosting con mejor relación calidad precio para dar nuestros primeros pasos.

*¡Oferta, señora, me las quitan de las manos!*

Si seguís [[http://www.dreamhost.com/r.cgi?159740][este enlace]], y al daros de alta en Dreamhost usáis el código promocional GODEST2, os será aplicado automáticamente un descuento de 50$. Lo cual hace que el plan anual L1 salga, por ejemplo, por unos 70$, que parece un precio razonable para al menos probar esto de Drupal en un albergue «de verdad» (nada impide aplicar este descuento al contratar cualquier otro plan de albergue)

Ejem.

Para dejar las cosas completamente claras, con esta operación yo gano 47$, que es el resto de los 97$ que Dreamhost regala a los referrers una vez descontados los 50$ de la promoción que ofrecemos aquí.

Quiero que tú ganes más que yo.

¿Te atreves?

P.D.: Gracias [[http://hronia.blogalia.com/][Epaminondas]].


[[https://docs.google.com/forms/d/e/1FAIpQLSeGnXB3zyaNVYcb_2EoO8C5HRc6Emx-2rv2QS6OWNFz1yYSBQ/viewform?usp=pp_url&entry.55081144=%C2%A1Ahorrate%2050%24%20en%20tu%20sitio%20web%21][Dejar comentario]].

