#+title: Don Quijote de la Mancha
#+date: <2006-10-12 22:01>
#+author: Godofredo Fdez.
#+description: Algunas veces lo había intentado ya, pero leerme la obra cumbre de la literatura española no era fácil. Cuando lo intenté por primera vez (tendría alrededor de los catorce años, y ya había disfrutado con esta serie de dibujos animados ) recuerdo que me parecían las aventuras de un loco, de donde lo único que podía sacar era un cúmulo de absurdos y despropósitos; la segunda vez (rondaría los 18, allá por el último gran verano tras finalizar COU) ya pude experimentar otras sensaciones: la nobleza (no de títulos sino de carácter), la lucha por un ideal, etc., pero reconozco que tampoco me enganchó lo suficiente para atreverme a llegar al final. Cuando un libro no me gusta lo dejo y cambio a otro. Leer ha de ser un placer. Que no me guste un libro no implica que piense que ese libro sea malo sino que, quizá, no sea el momento adecuado para su lectura.
#+filetags: Libros Pensamiento
#+options: _:nil
#+nid: 173

Algunas veces lo había intentado ya, pero leerme la obra cumbre de la literatura española no era fácil. Cuando lo intenté por primera vez (tendría alrededor de los catorce años, y ya había disfrutado con [[http://www.quixote.tv/][esta serie de dibujos animados]]) recuerdo que me parecían las aventuras de un loco, de donde lo único que podía sacar era un cúmulo de absurdos y despropósitos; la segunda vez (rondaría los 18, allá por el último gran verano tras finalizar COU) ya pude experimentar otras sensaciones: la nobleza (no de títulos sino de carácter), la lucha por un ideal, etc., pero reconozco que tampoco me enganchó lo suficiente para atreverme a llegar al final. Cuando un libro no me gusta lo dejo y cambio a otro. Leer ha de ser un placer. Que no me guste un libro no implica que piense que ese libro sea malo sino que, quizá, no sea el momento adecuado para su lectura.

A la tercera ha sido la vencida. El gran [[http://www.donquijotedelamancha2005.com/descarga.php][Don Quijote de la Mancha]] llamó a mi puerta el verano pasado (el año 2005 se conmemoró el IV Centenario de la publicación de la primera edición: 1605) y, durante un año, se convirtió en mi compañero de sueños cada noche antes de apagar la luz.

¡Qué puedo yo decir de este libro TAN GRANDE! Simplemente me atreveré a comentar que en este libro está la historia de la humanidad entera. Se pueden apreciar con una nitidez deslumbrante las distintas caras del ser humano: la traición y la fidelidad, la bajeza y la grandeza, el amor y el desamor... y por supuesto, *el idealismo y el realismo*. Quizá este sea uno de sus grandes secretos. Quizá por esto nunca pase de moda.

Dejo aquí la penúltima punzada que sintió mi corazón, allá por los capítulos finales (el LXVI de la segunda parte, titulado: /Que trata de lo que verá el que lo leyere, o lo oirá el que lo escuchare leer/), que comienza así:

#+BEGIN_EXAMPLE

  Al salir de Barcelona volvió don Quijote a mirar el sitio donde había caído

  y dijo:

  —Aquí fue Troya; aquí mi desdicha, y no mi cobardía, se llevó mis alcan-

  zadas glorias; aquí usó la fortuna conmigo de sus vueltas y revueltas; aquí se

  escurecieron mis hazañas; aquí, finalmente, cayó mi ventura para jamás levan-

  tarse.

  Oyendo lo cual, Sancho dijo:

  —Tan de valientes corazones es, señor mío, tener sufrimiento en las des-

  gracias, como alegría en las prosperidades, y esto lo juzgo por mí mismo; que

  si, cuando era gobernador, estaba alegre, agora, que soy escudero de a pie, no

  estoy triste. Porque he oído decir que esta que llaman por ahí Fortuna es una

  mujer borracha y antojadiza y, sobre todo, ciega, y así, no vee lo que hace, ni

  sabe a quién derriba ni a quién ensalza.

  —Muy filósofo estás, Sancho —respondió don Quijote—; muy a lo discre-

  to hablas; no sé quién te lo enseña. Lo que te sé decir es que no hay fortuna

  en el mundo, ni las cosas que en él suceden, buenas o malas que sean, vienen

  acaso, sino por particular providencia de los cielos, y de aquí viene lo que suele

  decirse que cada uno es artífice de su ventura. Yo lo he sido de la mía, pero no

  con la prudencia necesaria, y así, me han salido al gallarín mis presunciones;

  pues debiera pensar que al poderoso grandor del caballo del de la Blanca Luna

  no podía resistir la flaqueza de Rocinante. Atrevime, en fin; hice lo que pude,

  derribáronme y, aunque perdí la honra, no perdí ni puedo perder la virtud de

  cumplir mi palabra. Cuando era caballero andante atrevido y valiente, con mis

  obras y con mis manos acreditaba mis hechos, y agora, cuando soy escudero

  pedestre, acreditaré mis palabras cumpliendo la que di de mi promesa. Camina,

  pues, amigo Sancho, y vamos a tener en nuestra tierra el año del noviciado, con

  cuyo encerramiento cobraremos virtud nueva para volver al nunca de mí olvi-

  dado ejercicio de las armas.
#+END_EXAMPLE

¿Cuánto nos quedará por vivir?

Y ya con mis años vividos, ¿cuántas otras tantas lecturas tendrá?


[[https://docs.google.com/forms/d/e/1FAIpQLSeGnXB3zyaNVYcb_2EoO8C5HRc6Emx-2rv2QS6OWNFz1yYSBQ/viewform?usp=pp_url&entry.55081144=Don%20Quijote%20de%20la%20Mancha][Dejar comentario]].

** Comentarios

*** A veces me pregunto si no (Epaminondas Pantulis 12/10/2006 - 23:13)
A veces me pregunto si no serás mi alter ego, o yo qué sé. El caso es que a mí me había pasado exactamente igual con El Quijote, por más que lo intenté no me enganchaba. Y, al igual que tú, cuando un libro no me captura, lo suelto. Lo suelto porque mi tiempo de lectura es demasiado escaso como para castigarme leyendo un libro que no me interesa (y, además, también me parece en cierta manera un "castigo" para el libro y su autor, que tal vez no son culpables de no engancharme).

Así que El Quijote cayó para mi cumpleaños el año pasado (además para más inri fue libro de segunda mesa, porque Carrefour lo regalaba por 1€ si comprabas dos que ahora casi ni recuerdo cuáles fueron), y me llevó mis buenos 8 o 9 meses. Probablemente lo que más me sorprendió de la obra de Cervantes fue cómo toca ciertos temas (sobre todo cuando escribe historias dentro de lahistoria) que -mutatis mutandis- podrían ser de rabiosa actualidad. Y es lo que tú dices; las distintas caras del ser humano... ésas estarán ahí siempre, y la captura que El Quijote hace de ellas es lo que hará que nunca pase de moda.

*** Sobre El Quijote (Sofista 21/10/2006 - 20:28)
La primera vez que leí esta obra fue en un comic en doce tomos que me regaló mi abuelo, después también ví la serie de dibujos animados.
Ya en el colegio me leí la obra original de Cervantes, y en la carrera tuve que repetir lectura... y la verdad es que es uno de los libros clásicos que no me ha importado tener que leer por obligación. Me encanta la historia y me encanta el personaje... ojalá hubiera más quijotes por el mundo.
Es verdad, que hay que reconocer, que el libro es largo y que a veces se hace pesado y dan ganas de dejarlo,... pero yo al contrario que vosotros no suelto un libro hasta que no lo he acabado, ¡cosas de cabezonería! no puedo evitarlo, lucho constantemente contra mí misma... y Don Alonso me atrapo desde el primer momento.

Y, ¡sí!, los temas que trata son de rabiosa actualidad, se podría decir que casi podrán ser eternos en este país,... y si lo dudaís leeros también las Novelas Ejemplares... y ya me contaís.

...somewhere over the rainbow...
