#+title: De vuelta y con Cambios
#+date: <2006-08-07 12:49>
#+author: Pili Cantautora
#+description: Hola chicos! Ya estoy en Sevilla otra vez, y esta vez para quedarme ;) He pasado unos diitas muy buenos y familiares en Algeciras (capital de la novena provincia, jeje), e incluso me he bañao!! en fin, mu guay todo... Quería adelantarme un poquito a nuestro reencuentro y contaros que en esta ocasión la vuelta al cole trae cambios... no sé si habréis escuchado ya algo por ahí, imagino que sí, el ala oeste es como un pequeño micromundo... hubiera querido decíroslo yo a todos en persona, pero han salido las cosas de aquella manera... estaba yo tranquilamente en el supersol del pueblo cuando me llamaron para darme la noticia! :)
#+filetags: Desde_ti
#+options: _:nil
#+nid: 156

Hola chicos! Ya estoy en Sevilla otra vez, y esta vez para quedarme ;) He pasado unos diitas muy buenos y familiares en Algeciras (capital de la novena provincia, jeje), e incluso me he bañao!! en fin, mu guay todo...

Quería adelantarme un poquito a nuestro reencuentro y contaros que en esta ocasión la vuelta al cole trae cambios... no sé si habréis escuchado ya algo por ahí, imagino que sí, el ala oeste es como un pequeño micromundo... hubiera querido decíroslo yo a todos en persona, pero han salido las cosas de aquella manera... estaba yo tranquilamente en el supersol del pueblo cuando me llamaron para darme la noticia! :)

Recuerdo cuando le sugerí a Godo que le pusiera foro a esta nuestra bitácora, pensando en que se me acababa la bequita y que sería muy útil para seguir contándonos cosillas... No fue necesario al final usarlo con para tal fin en ese momento, pero ahora parece ser que sí...

Ya os contaré los detalles cuando nos veamos las caritas, que será pasado mañana según lo previsto... Ya sabéis que últimamente no andaba yo muy allá, estaba muy desanimada y desmotivada, qué os voy a contar a vosotros que no sepáis! había pensado incluso pasar de las telecomunicaciones, pero les vamos a dar otra oportunidad...

Ni que decir tiene que cuando llegue el momento os voy a echar muchísimo de menos!! (snif, snif!) sé que compañeros tan requete-guays como vosotros no los voy a poder encontrar en ningún otro sitio mientras que vosotros sigáis ahí, pero no penséis que os voy a dejar escapar!! ni pensarlo!! :P

En fin chicos, nada más de momento, que no quiero ponerme más nostálgica de la cuenta... ya mismo estoy ahí y nos contamos!

Pili


[[https://docs.google.com/forms/d/e/1FAIpQLSeGnXB3zyaNVYcb_2EoO8C5HRc6Emx-2rv2QS6OWNFz1yYSBQ/viewform?usp=pp_url&entry.55081144=De%20vuelta%20y%20con%20Cambios][Dejar comentario]].

** Comentarios

*** ¡Qué puedo decir! (Godo 09/08/2006 - 23:25)
Eso: ¡Qué puedo decir que tú aún no sepas, Pili! Siempre he pensado que la época en la que uno tiene que tender a asentarse en un sitio lo suficientemente bueno para que te deje vivir, a moverse buscando siempre mejorar, es la que precede a la hipoteca, la creación de un hogar compartido y, sobre todo, a la llegada de los hijos. Sabes que siempre lo he transmitido con total claridad y contundencia. Y lo que la gente, quizá, no sabe, es que todo esto llega sin esperártelo, casi sin hacer ruido, de puntillas... y cuando miras a tu alrededor, ¡ahí está! Algunas veces uno se siente extraño.

Por todo ello me alegro muchísimo de que hayas tomado la decisión de buscar un nuevo trabajo (que nunca será ideal, hay muy pocos privilegiados que hacen y viven de lo que les gusta - y además, algunos recaudan "en pasivo" a través del [[http://www.internautas.org/html/3841.html][canon]]), y de que sigas teniendo claro que se trabaja para vivir y no lo contrario. En esta España que nos venden como Europa es cada vez más difícil encontrar a gente equilibrada: unos mueren trabajando y otros no dan un palo al agua en toda su vida, y viven también ¿?

Espero que tus nuevos compañeros nunca lean el penúltimo párrafo que has escrito ;-) Estoy seguro que acabarán superándonos o, al menos, equiparándose a nosotros. En todos lados "cuecen habas" y en todos lados hay gente de todos tipos. Ya nos contarás...

Te echaré de menos, compañera de rincón.

#+BEGIN_QUOTE
  Pero todo continuará.
#+END_QUOTE

*** Mañana, mi primer día (Pili Cantautora 03/09/2006 - 12:27)
Y ya llegó el momento de la verdad... mañana es mi primer día en mi nuevo trabajo. Estoy muy, muy feliz, ilusionada con la idea de descubrir un sitio nuevo, con la esperanza de que las cosas se puedan hacer de otra forma... y a la vez, bastante acongojada :) Ya os contaré qué tal todo, y nos veremos el viernes, o tal vez antes...

*** ¡Mucha suerte! (el radioplanner 04/09/2006 - 10:39)
Me alegro de que empieces tan prontito. Seguro que te va todo estupendamente, verás!!!
