#+title: JAVI OSORIO Y LOS SANTOS PERVERSOS
#+date: <2006-05-05 11:41>
#+author: Calavera Bob
#+description: 7 MAYO en EL PERRO ANDALUZ (C\BUSTOS TAVERA, 11)a las 21:00 h. "ACÚSTICO" 14 MAYO WOMAD (FESTIVAL CÁCERES) SALA BELLE EPOQUE (HORA AÚN POR CONFIRMAR) MÁS…
#+filetags: Desde_ti
#+options: _:nil
#+nid: 129

7 MAYO en EL PERRO ANDALUZ (C\BUSTOS TAVERA, 11)a las 21:00 h.
"ACÚSTICO"

14 MAYO WOMAD (FESTIVAL CÁCERES) SALA BELLE EPOQUE (HORA AÚN POR CONFIRMAR)

MÁS INFORMACIÓN EN WWW.javiosorio.NET


[[https://docs.google.com/forms/d/e/1FAIpQLSeGnXB3zyaNVYcb_2EoO8C5HRc6Emx-2rv2QS6OWNFz1yYSBQ/viewform?usp=pp_url&entry.55081144=JAVI%20OSORIO%20Y%20LOS%20SANTOS%20PERVERSOS][Dejar comentario]].

** Comentarios

*** Otra vez será (Godo 07/05/2006 - 22:27)
Hola Javi.

Muchas gracias por hacernos partícipes de estos acontecimientos. Nosotros (Esther y yo) no hemos podido ir porque nos venía algo mal hoy... y supongo que al WOMAD tampoco iremos. Pero estoy seguro que habrá más y allí estaremos.

Espero que nos sigas informando.

Gracias.

*** Ojalá la próxima... (Pili Cantautora 08/05/2006 - 15:01)
Nosotros tampoco pudimos ir, porque andábamos de vuelta de Madrid... Nos hubiera encantado poder estar, las dos canciones del último concierto en que te vimos (Cantautores Reunidos) nos supieron a poco...

Ojalá que para la próxima podamos ir, y que sea dentro de poco... Estaremos antentos a la web.

Saludos!
