#+title: El Capitán Alatriste
#+date: <2006-08-25 10:36>
#+author: Pili Cantautora
#+description: A día de hoy queda ya tan sólo una semana para el estreno de Alatriste, la película. Llevo un tiempo leyendo mucho por Internet, rebuscando entre toda la información que está ya inundando la red... y he pensado en compartir con vosotros mis primeras impresiones antes del estreno, y así ya luego contrastamos :) Aunque me encantan los libros del Capitán (o tal vez precisamente por eso...), no tengo muy claro si me va a gustar la película o no. Desde luego, va a ser espectacular, respecto a eso no tengo ninguna duda, pero cuanto más comentarios leo más me inquieto... Me consuela saber que a Arturo Pérez-Reverte le ha gustado, pero también es verdad que él ha estado muy presente en el rodaje y conocía el guión, lo más probable es que para mi el choque la primera vez que la vea sea mayor.
#+filetags: Desde_ti
#+options: _:nil
#+nid: 161

A día de hoy queda ya tan sólo una semana para el estreno de Alatriste, la película. Llevo un tiempo leyendo mucho por Internet, rebuscando entre toda la información que está ya inundando la red... y he pensado en compartir con vosotros mis primeras impresiones antes del estreno, y así ya luego contrastamos :)

Aunque me encantan los libros del Capitán (o tal vez precisamente por eso...), no tengo muy claro si me va a gustar la película o no. Desde luego, va a ser espectacular, respecto a eso no tengo ninguna duda, pero cuanto más comentarios leo más me inquieto... Me consuela saber que a Arturo Pérez-Reverte le ha gustado, pero también es verdad que él ha estado muy presente en el rodaje y conocía el guión, lo más probable es que para mi el choque la primera vez que la vea sea mayor.

Respecto a Viggo Mortensen, casi que no tengo duda de que no me va a decepcionar. Caracterizado está increíble, encaja perfectamente con la idea del Capitán que tenía en mi cabeza, su presencia, su mirada... Saber que casi se ha fusionado con el personaje antes y durante el rodaje también hace que se merezca todo mi respeto. Para mí su elección ha sido todo un acierto, aunque a mí nunca se me hubiera ocurrido...

Sobre algunos de los otros personajes, tengo mis dudas. A priori, no me gusta Elena Anaya como Angélica de Alquézar, no me encaja con el personaje, esa cara angelical con tirabuzones rubios, que en realidad es más diablo que ángel... Tampoco me gusta mucho Ariadna Gil como María de Castro. Creo haber leído por ahí que han fusionado los personajes de Caridad La Lebrijana y María de Castro en "la María de Castro de la película", espero que no sea así... En mi opinión La Lebrijana se merece estar presente, aunque sólo sea un instante, bastaría con uno que permitiera dar a entender la mujer que era, posesiva y apasionada, lo que suponía para ella el Capitán... Pronto se desvelara el misterio...

Seguramente mi hermano me diría que soy demasiado purista, que la película es una adaptación de las aventuras, no una representación fidedigna, y tendría toda la razón... Procuraré ir con esa idea clara el día del estreno, para intentar ser más justa a la hora de considerar la película.

Quería aprovechar para comentaros también mi experiencia con la visita guiada "El Madrid del Capitán Alatriste". Me gustó mucho pasear por esas calles de noche, intentar aislarnos de la luz, del ruido... y trasladarnos a la época. Nuestra guía era estupenda y nos contó muchas curiosidades, disfrutamos mucho. Lo que no nos gustó demasiado fue el teatrillo que hacen, ¿cómo puede caer tan bien Malatesta? eso es que algo falla :P

Godito, os echaremos mucho de menos en el estreno. Espero que estéis disfrutando mucho de las merecidas vacaciones, y no os preocupéis, que yo estoy dispuesta a acompañaros cuando vayáis vosotros a ver la peli ;)

Para finalizar sólo una cosita. Con lo de la interpretación de Alatriste he estado indagando por Internet buscando saber algo más de la vida de Viggo, y lo cierto es que me ha sorprendido gratamente. Poeta, pintor, músico... ¿otro renacentista? :)


[[https://docs.google.com/forms/d/e/1FAIpQLSeGnXB3zyaNVYcb_2EoO8C5HRc6Emx-2rv2QS6OWNFz1yYSBQ/viewform?usp=pp_url&entry.55081144=El%20Capit%C3%A1n%20Alatriste][Dejar comentario]].

** Comentarios

*** ya tenemos las entradas! (Pili Cantautora 28/08/2006 - 14:57)
Somos unos frikis, pero así es, ya tenemos las entradas para el estreno de Alatriste :) un día eventual donde los haya, con mi despedida incluida. Espero llegar medio entera al estreno... ya os contaré.

*** Yo ya estoy deseando ver a (Jose Ignacio 28/08/2006 - 16:27)
Yo ya estoy deseando ver a mi doble interpretando a Diego Alatriste...

FDO: José Ignacio Alalegre

*** Me hubiese gustado... (Godo 29/08/2006 - 23:35)
...estar allí y asistir al recorrido del Madrid de la época del capitán. Recuerdo que el año pasado, en nuestra visita a la capital, cuando recorría algunas de las calles de la zona antigua intentaba imaginar como habría sido todo en aquellos siglos...

Debió ser muy gratificante, como cuentas, vuestra experiencia. No descarto el intento de conseguir alcanzarla algún fin de semana.

Respecto al estreno siento igualmente no poder estar. Otra vez será.

Ha llegado a mis manos el suplemento dominical "XLSemanal" del día 20 de agosto, donde viene un reportaje realizado a Arturo Pérez-Reverte y Viggo Mortensen. Me lo llevo por si queréis leerlo.

Todo bien y sin novedades en el frente.

*** Decepción generalizada... (Pili Cantautora 03/09/2006 - 13:37)
Preferiría que el asunto de este comentario fuera más alentador, pero por desgracia no puede ser así... Decepción generalizada es lo que se respira entre los que habíamos adoptado al Capitán Alatriste como algo nuestro, qué se le va a hacer... Mucha promoción, muchos millones de euros, mucho visto bueno por parte de Pérez-Reverte, pero uno se queda con la sensación de que se podría haber hecho mejor, al menos en lo que a la historia se refiere.

Fui a ver la película con la mejor de las disposiciones, dando por hecho que estaba tan sólo basada en los libros, fui preparada para cualquier cambio extraño en la trama, resúmenes agresivos... pero la película falla más allá de todo eso. Desde mi punto de vista, para la persona que va a ver la película sin haber leído los libros, la película es una sucesión de recortes sin hilo conductor alguno, en la que no se entienden la mayoría de las escenas... Para mí ése es el principal punto débil: la película no llega a ser una historia y al final lo más probable es aburrirte, perdido en una sucesión de hechos inconexos.

Para los que hemos leído los libros, un poco más de lo mismo pero peor. Te llevas toda la película esforzándote en no perderte, ayudado por la ventaja de que conoces en profundidad las acciones, lo que hay detrás de cada uno de los momentos, y aún así no sirve de mucho. Para mi gusto Viggo Mortensen está tremendo como Capitán Alatriste, y resulta lo mejor de la película... Es uno de los pocos personajes que se salvan, junto con Quevedo y el Conde Duque de Olivares. Lo demás poco tiene que ver con nada, Angélica de Alquézar nada tiene de diablo disfrazado de ángel, Íñigo adulto resulta demasiado prepotente (¿dónde queda esa relación tan especial con el Capitán?) y Malatesta está desprovisto de su misterio y de su tira y afloja particular con Alatriste.

*** A mi hermano le ha gustado (Pili Cantautora 03/09/2006 - 17:27)
Me he apresurado a contaros también su opinión, porque creo que es bastante interesante. Para mí ha resultado esperanzadora. Él fue a verla anoche con 2 amigos, ninguno de los tres había leído los libros y a todos les gustó. Me alegra saber que las sutilezas que sirven de enlace entre unas escenas y otras se captan con más facilidad de lo que yo creía, aún sin tener ningún conocimiento previo sobre las historias... Sí está de acuerdo en que hay momentos de aburrimiento y en lo inconexo que resulta la sucesión de fragmentos, pero globalmente le ha gustado. Lo mejor de todo es que se ha animado a leer los libros, habiéndole gustado la película no dudo de que realmente disfrutará con la lectura de las aventuras... (por cierto, se anuncia nuevo libro de la serie para diciembre)

Como bien ha comentado mi hermano, está claro que lo que uno no puede ir esperando es algo similar a Gladiator, o El Señor de los Anillos...

De momento, la semana que viene voy a ir a verla otra vez, con más tranquilidad... y cuando Godo vuelva, habrá que organizar la segunda convocatoria para el visionado ;)

*** Eso es devoción (el radioplanner 04/09/2006 - 10:37)
A pesar de que no te ha gustado... ¿piensas ir otras dos veces más?
Bueno, a mí me gustaría apuntarme a la segunda convocatoria aunque por los comentarios parece que la peli no es especialmente buena...

¡Saludillos y besillos!

*** Tengo que reconoce que fuí (Sofista 09/09/2006 - 17:41)
Tengo que reconoce que fuí a ver la pelí solo con tres de los libros leídos, pero no puedo estar de acuerdo casi en nada contigo PiliCantautora,... a mí me ha encantado la peli.
La fotografía me parece preciosa, la banda sonora bien elegida,... es verdad que los personajes podrían haber dado más de sí, pero entonces la pelí tendría que ser de más de dos horas y cuarto,... y con respecto a los trozos inconexos, es verdad, que podían haber hilado un poco más fino, pero esos vacios a mi me sirven para hacer la peli un poco más mía dibujando en ellos lo que yo creo que puede faltar.
A pesar de todo yo también voy a repetir peli por si se me ha pasado algo por alto, o por si el entusiasmo que me acompañaba me cegó en algo (adoro a Viggo y a Pérez-Reverte).

Otra cosa, si me dais a elegir una escena me quedo con la última... esos tercios de Flandes...

...somewhere over the rainbow...
