#+title: Lecturas de verano - Año 2006 (III)
#+date: <2006-10-01 21:08>
#+author: Godofredo Fdez.
#+description: El tercer libro que me he leído este verano es de la editorial Anagrama , su título es: " Seda ", y su autor: "Alessandro Baricco". 125 páginas divididas en 65 capítulos. Escritas de forma bellísima: ritmo calmado que rezuma a veces tensión, a veces intriga y casi siempre fantasía. Ritmo de fábula. Ritmo de los antiguos cuentos que se contaban. Es un cuento de amor. De ese que buscamos lejos para acabar descubriendo que lo teníamos más cerca de lo previsto. Aunque quizá esté traicionando al autor al decir esto ya que, en la contraportada del libro aparece un párrafo donde podemos leer: "Se podría decir que es una historia de amor. Pero si solamente fuera eso, no habría valido la pena contarla. En ella están entremezclados deseos, y dolores, que se sabe muy bien lo que son, pero que no tienen un nombre exacto que los designe. Y, en todo caso, ese nombre no es amor." .
#+filetags: Libros Pensamiento
#+options: _:nil
#+nid: 171

El tercer libro que me he leído este verano es de la editorial [[http://www.anagrama-ed.es/][Anagrama]], su título es: "[[http://www.anagrama-ed.es/autor/86][Seda]]", y su autor: "Alessandro Baricco".

125 páginas divididas en 65 capítulos. Escritas de forma bellísima: ritmo calmado que rezuma a veces tensión, a veces intriga y casi siempre fantasía. Ritmo de fábula. Ritmo de los antiguos cuentos que se contaban.

Es un cuento de amor. De ese que buscamos lejos para acabar descubriendo que lo teníamos más cerca de lo previsto. Aunque quizá esté traicionando al autor al decir esto ya que, en la contraportada del libro aparece un párrafo donde podemos leer: "Se podría decir que es una historia de amor. Pero si solamente fuera eso, no habría valido la pena contarla. En ella están entremezclados deseos, y dolores, que se sabe muy bien lo que son, pero que no tienen un nombre exacto que los designe. Y, en todo caso, ese nombre no es amor.".

¡Es increíble descubrir lo capacitados que estamos para confundir el sentimiento del amor con tantos otros! Claro que si no, no existiría el romanticismo, ni se hubieran derramado tantas letras en su nombre.

Mirad a vuestro alrededor...

...Y abrazadlo.\\


[[https://docs.google.com/forms/d/e/1FAIpQLSeGnXB3zyaNVYcb_2EoO8C5HRc6Emx-2rv2QS6OWNFz1yYSBQ/viewform?usp=pp_url&entry.55081144=Lecturas%20de%20verano%20-%20A%C3%B1o%202006%20%28III%29][Dejar comentario]].

