#+title: Eventos musicales de julio y agosto
#+date: <2006-07-27 20:55>
#+author: Sofista
#+description: Viendo que son muy variados los gustos musicales de los habitantes de este sitio os dejo información sobre varios conciertos que se van a celebrar este verano. Todos, y no es porque lo diga yo, muy interesantes... El viernes 28 de julio, el Espera's Folk Festival (con los Whiskey Rivers, grupo sevillano de folk irlandes)a las 23:00, en la plaza de la iglesia del pueblo de Espera (Cádiz) El sábado 29 de julio, a las 21:30, en La Tertulia (Granada), concierto de los cantautores Manuel Ruiz y Mariano Cuesta (más información en www.cantautoresdesevilla.com) Y en las Noches en los Jardines del Real Alcazar todo tipo de música en un marco de impresionante belleza, a partir de las 22:15 horas y por solo 3€:
#+filetags: Desde_ti
#+options: _:nil
#+nid: 155

Viendo que son muy variados los gustos musicales de los habitantes de este sitio os dejo información sobre varios conciertos que se van a celebrar este verano. Todos, y no es porque lo diga yo, muy interesantes...

El viernes 28 de julio, el Espera's Folk Festival (con los Whiskey Rivers, grupo sevillano de folk irlandes)a las 23:00, en la plaza de la iglesia del pueblo de Espera (Cádiz)

El sábado 29 de julio, a las 21:30, en La Tertulia (Granada), concierto de los cantautores Manuel Ruiz y Mariano Cuesta (más información en www.cantautoresdesevilla.com)

Y en las Noches en los Jardines del Real Alcazar todo tipo de música en un marco de impresionante belleza, a partir de las 22:15 horas y por solo 3€:
Os recomiendo: el 4 de agosto Khairkan (música de homenaje a Ibn Jaldun), el 11 y el 22 de agosto Dan Kaplan Trio (música inglesa del barroco para celebrar el 390 aniversario de Shakespeare), el 30 de julio y el 12 de agosto Sila Na Gig y Rei Cintolo (esto si os lo recomiendo fervientemente, si os gusta la música folk gallega e irlandesa, con Fran Verde como gaitero) y Hayet Ayad (música arabigo-andalusi para el homenaje a Ibn Jaldun).

Espero que esta información sea de vuestro interés y que podaís disfutar de alguno de estos conciertillos, especialmente pa los que tenemos que tirar el verano en Sevilla los conciertos en el Alcazar están muy "apañaos".

Un abrazo y que el calor del verano os sea leve. ;)


[[https://docs.google.com/forms/d/e/1FAIpQLSeGnXB3zyaNVYcb_2EoO8C5HRc6Emx-2rv2QS6OWNFz1yYSBQ/viewform?usp=pp_url&entry.55081144=Eventos%20musicales%20de%20julio%20y%20agosto][Dejar comentario]].

** Comentarios

*** El verano en Sevilla... (Godo 28/07/2006 - 20:32)
Hola Sofista.

Gracias por ser una más de nosotros, por compartir esta información...

Soy de los que "tienen que tirar el verano en Sevilla" y creo (si no surge nada extraño) que pasado mañana estaré (estaremos Esther y yo, al menos) en los Jardines del Real Alcázar escuchando a "Sila Na Gig"... a lo del 12 de agosto aún no puedo comprometerme.

No he ido nunca a este tipo de actos en el Alcázar, ¿es necesario sacar la entrada con antelación o es posible sacarla allí mismo, sobre la marcha? ¿Crees que será difícil conseguirlas?

Y por último, ¿tú irás? Si es así a ver si podemos conocernos y echar unas copillas después. Si te apetece, claro. Tú decides.

Aromas y música. Inigualable entorno.

Actualización: acabo de encontrar [[http://www.actidea.com/nochesalcazar_2006/index_1024.html][esta web]] con toda la información de esta temporada, horarios y venta de entradas incluidos. A ver si me da tiempo, mañana, de adquirir las entradas de pasado mañana :-?.

*** Las Noches del Alcázar (Pili Cantautora 30/07/2006 - 16:13)
También a mí este verano me picaba mucho el gusanillo de ir a uno de los concierto del Alcázar. Sólo he ido una vez, un amigo toca la Viola de Gamba y en una ocasión pudimos verle actuar allí, la experiencia fue inolvidable... El sitio es precioso, y la música te traslada a otros tiempos y lugares... Un placer.

Respecto a las pequeñas dudas, nosotros compramos las entradas justo antes del concierto y sin problemas de aforo. Además, viene muy bien llegar con tiempo para poder pasearse tranquilamente por los jardines e ir contagiándonos del ambiente...

A seguir disfrutando de la música :)

*** Las entradas... agotadas (Godo 30/07/2006 - 22:47)
Hola.

Siento comunicaros que, en contra de lo previsto (aunque para la chica de la taquilla fuera lo más normal del mundo tratándose de ese grupo - por lo visto tira mucho de la gente -), no pude conseguir las entradas ayer, sábado, para hoy, domingo 30 de julio.

Mañana se ponen a la venta las entradas para los conciertos de la semana que va desde el 7 hasta el 13 de agosto. Intentaré, pues, conseguir las del sábado 12 de agosto, día en el que vuelven a actuar "Síla Na Gig + Rei Cintolo".

¡OJO! Según las normas de la organización "se venderán un máximo de 4 entradas por persona y día". Tened cuidado con los compromisos :-).

Seguiremos informando.

P.D.: A Pili y José Ignacio: Me alegro mucho de que estéis de vuelta sanos y salvos. Seguro que os lo habéis pasado muy bien. Ya nos contaréis y nos "allanaréis el camino". A ver si os apuntáis a este concierto, si no puede ser... ya lo vamos viendo. Un abrazo.

*** Eventos musicales (Sofista 31/07/2006 - 12:59)
Holita a todos.
Me alegra saber que estais atentos a los movimientos musicales. No respondí al comentario de Godo, porque el viernes poco despues de dejar el mensaje en este foro cogi carretera a Granada para pasar el fin de semana y de paso ir al concierto de Manuel Ruiz y Mariano Cuesta, que son buenos amigos mios.
Quería ir al concierto del 12 de Sila na Gig, pero va a ser que tampoco voy porque me voy cuatro dias a Cuenca...

Esperando poder coincidir algún día por ahí... besos musicales para todos.

...somewhere over the rainbow...

*** Los calores del verano... (el radioplanner 02/08/2006 - 11:07)
...seguro que se llevan mejor con estos conciertillos (o conciertazos, tampoco quiero menospreciar a nadie). La verdad es que yo también estaba pensando en acercarme por alguno. Le echaré un vistazo a la programación a ver cuál me entra más por el ojo...

¡Nos vemos!

*** ¡Las conseguí! (Godo 02/08/2006 - 22:56)
El pasado lunes por la tarde conseguí las entradas para el concierto del sábado, día 12 de agosto.

Allí estaremos viendo a "Sila Na Gig y Rei Cintolo". Si alguien más va a disfrutar esa noche de la música y del entorno... a ver si conseguimos quedar y echar un "cacharrillo" (en mi pueblo cualquier combinado, en mi caso un johnniecola), si le apetece, claro está.

Aires del sur.
