#+title: Un ingeniero más y el 21 de Marzo
#+date: <2006-03-16 12:15>
#+author: Pili Cantautora
#+description: Holahola!! el tiempo pasa volando... y ya mismo estamos en primavera!! a parte de las florecillas, las macrobotellonas y las alergias, vuelve también nuestro querido y admirado webmaster al Perro Andaluz :P Si no hay ningún imprevisto, el próximo martes nos manifestaremos ante Antonio, que esperamos que no cause baja precisamente ese día, porque iremos lanzaos... :D por cierto, Antonio, sigues andando por aquí? Por otro lado, la primavera nos ha traido también una muy, muy, muy, muy buena noticia: ya tenemos un ingeniero más! sé que ya lo sabéis, pero quería dejar constancia oficial en este nuestro rinconcito... Si todo va según lo previsto, José Ignacio defenderá su PFC el próximo 31 de Marzo a las 17:00. Cuando se confirme el lugar os lo diremos, y después... que corran las Kaipiriñas!!! ;) que además a Esther le debemos ya una rondita...
#+filetags: Desde_ti
#+options: _:nil
#+nid: 111

Holahola!! el tiempo pasa volando... y ya mismo estamos en primavera!! a parte de las florecillas, las macrobotellonas y las alergias, vuelve también nuestro querido y admirado webmaster al Perro Andaluz :P Si no hay ningún imprevisto, el próximo martes nos manifestaremos ante Antonio, que esperamos que no cause baja precisamente ese día, porque iremos lanzaos... :D por cierto, Antonio, sigues andando por aquí?

Por otro lado, la primavera nos ha traido también una muy, muy, muy, muy buena noticia: ya tenemos un ingeniero más! sé que ya lo sabéis, pero quería dejar constancia oficial en este nuestro rinconcito... Si todo va según lo previsto, José Ignacio defenderá su PFC el próximo 31 de Marzo a las 17:00. Cuando se confirme el lugar os lo diremos, y después... que corran las Kaipiriñas!!! ;) que además a Esther le debemos ya una rondita...

Pues nada más chicos, que el martes nos vemos allí, y empezamos con las celebraciones! :D saluditos, Pili.


[[https://docs.google.com/forms/d/e/1FAIpQLSeGnXB3zyaNVYcb_2EoO8C5HRc6Emx-2rv2QS6OWNFz1yYSBQ/viewform?usp=pp_url&entry.55081144=Un%20ingeniero%20m%C3%A1s%20y%20el%2021%20de%20Marzo][Dejar comentario]].

** Comentarios

*** Mi más sincera enhorabuena (Anónimo 16/03/2006 - 21:38)
Quiero dar mi más sincera enhorabuena al nuevo Ingeniero de Telecomunicación. La batalla ha sido dura, pero ya ha terminado. Ahora a disfrutar de la calma.

Y a sonreir tras despertar de un sueño en el que aún sigues estudiando, o sintiendo el deber de estudiar, porque tienes los últimos exámenes la semana que viene. Sí, sí, no te extrañes... yo lo sigo sufriendo y ya son casi 10 años los que hace desde que hice el último. Bueno, no todos somos iguales, quizá a ti no te pase. No sé si es bueno o malo (como tantas otras cosas) pues, si bien durante el sueño lo pasas realmente mal, al despertar vuelves a valorar con emoción lo que tienes. Ya nos contaremos.

Como ha dicho Pili, si no pasa nada lo mojamos el martes 21.

Salud.

*** Hola!!  (Antonio Bernal 17/03/2006 - 12:45)
Hola!! :)

Sí, Pili, sigo por aquí jeje...entro con asiduidad por aquí, aunque no postee demasiado.

Bueno...antes de nada sumarme a la felicitación por el nuevo ingeniero...no lo conozco en persona pero es un gran mérito estar a las puertas de la meta de una ingeniería en Telecomunicaciones, y ya que yo estoy inmerso en la Ingeniería Informática, me puedo hacer idea del trabajo y esfuerzo que le ha supuesto todo este camino, así que no puedo más que darte le enhorabuena!!

Parece que al fin el próximo martes podremos vernos las caras jejeje...veamos que tal se da el concierto...este martes pasado tuvimos un par de elementos con elevado índice de alcohol el la sangre que generaron un numerito a ratos cómico, a ratos patético, pero bueno...podremos oficialmente, este martes, dar la bienvenida a la primavera entre letras y acordes.

En otro orden de cosas, hoy, viernes 17, es el día de San Patricio, patrón de Irlanda, y fiesta nacional del mismo país, así que, como mandan los cánones, estaremos tocando en el Pub Merchant's Malt House, en la C/Canalejas (a 50 m del Hotel Colón) a partir de las 20:30, como parte de la fiesta por el día de Irlanda que tendrán por allí...nada, sólo lo dejo caer por aquí, para que no se diga que este día todo son macrobotellones...y si alguno queréis pasar un rato, allí estaremos.

Un abrazo, nos vemos pronto.

Antonio

*** Muchas gracias a todos!!! (jibseijo 18/03/2006 - 15:44)
Bueno bueno, vaya sorpresita me he llevado cuando mi queridísima Pi me ha enseñado lo que se estaba escribiendo por aquí... La verdad es que ha sido muuuy grata, muchas gracias por las enhorabuenas. Incluso el magnífico Antonio Gaiteiro, es todo un honor recibir esa felicitación de tu parte. Mucho ánimo, que todo se acaba aunque haya momentos en los que parezca que no, sobre todo en carreras como las nuestras. :) He leído lo del S Patrick's Day un poco tarde, si no probablemente hubiera hecho algún plan para pasarme, seguro que os lo habéis pasado muy bien. Ya nos no contarás por aquí, ¿no? ;)

Godo, muchas gracias a ti también. Ya mismo puedo legalmente ser compañero tuyo, así que sigue en pie eso que que contéis conmigo... Además, ahora ya seríamos 3 los compis, que Miguel Ángel también está ahí ;) Hay que decirle que se una a la godobitácora sideral y se apunte a algún conciertillo. La vamos a liar ;)

El martes estaremos con Alfonso, la primavera y todo lo que conlleva. En el chuchillo nos manifestaremos, Antonio. Jeje...

Muchas gracias a todos los que sé que os habéis alegrado de mi alegría. Nos vemos mañana con el (genial) Joaqui!

Un abrazo,
José Ignacio.

--------------------------------------
Dime cuánto tiempo queda,
qué hago, aparte del vago,
finjo estar de acuerdo,
es un milagro que siga estando cuerdo

*** OLÉ Torero... digo Ingeniero (Miguel Angel 01/04/2006 - 15:58)
Sevilla, 5 de la tarde. No era la maestranza, sino la ESI. No había toros pero sí ratones -Yo te creo José Ignacio, si tú dices que era un ratón es que lo era, igual es que yo me esperaba a Mickey en 3D-. El tendido lleno a rebosar, vino hasta el apoderado desde Las Ventas.

Gran faena, empezó templando el capote, algún que otro sustillo sin importancia, no le hizo falta ni picador. Clavó los tiempos y luego entró a matar con la demo.

Al final se llevó las dos orejas y el rabo. Matrícula de Honor.

Enhorabuena ingeniero.

*** Tú sí que eres grande (jibseijo 02/04/2006 - 17:43)
Gracias Miguel Ángel. Es una alegría que te hayas manifestado por aquí, no me lo esperaba. Te quiero ver ya mismo viniéndote al Chucho Pulgoso, ¿eh?

Sí, fue difícil el comienzo porque la chicuelina no salió bien. Afortunadamente el toro (o ratón) fue dejándose torear, empezó demasiado bravo pero acabó noble. No sé por qué motivo me quedé un poco en blanco al principio, no encontraba palabras: como si mi vocabulario se hubiera reducido a 4 palabras. Y mientras estaba en el ruedo y notaba la gente en la grada (por cierto, lleno el graderío hasta la bandera, gran honor para mí), pensaba: "¿Cómo explico yo esto restringiendo todo mi diccionario a casa, ventana, lápiz y mesa?" Gracias a Dios luego me fueron viniendo más palabras a la cabeza y más o menos pude explicar algo...

Muchas gracias a todos por venir, me hizo mucha ilusión veros y sentir vuestro apoyo. Algún día ojalá pueda compartir cartel con Miguel Ángel "el Grande" y Godo, "el niño de Linux". No estaría nada mal ;)

-----------------------------
Dime cuánto tiempo queda,
qué hago, aparte del vago,
finjo estar de acuerdo,
es un milagro que siga estando cuerdo
