#+title: Webmaster, no te rajes
#+date: <2006-02-24 15:01>
#+author: Pili Cantautora
#+description: Holahola a todos!! el objetivo de este mensajito es presionar a nuestro webmaster de forma pública con motivo del concierto de Alfonso del Valle del martes 28... anda, GodEst, sed buenos y animaros a venir, no? yo me estoy concienciando, y trato de hacer lo propio con José Ignacio, para que no se nos raje en el útimo momento ;-) (más bien para que JiPi ¿? no nos rejemos) además, así echamos el ratito y nos contamos qué tal nos va, que estos días están siendo de locura... Puede que vengan María y Jose y todo ;-) sin olvidarnos de nuestro reencuentro con Antonio Bernal después de su incursión en La bitácora...
#+filetags: Desde_ti
#+options: _:nil
#+nid: 103

Holahola a todos!! el objetivo de este mensajito es presionar a nuestro webmaster de forma pública con motivo del concierto de Alfonso del Valle del martes 28... anda, GodEst, sed buenos y animaros a venir, no? yo me estoy concienciando, y trato de hacer lo propio con José Ignacio, para que no se nos raje en el útimo momento ;-) (más bien para que JiPi ¿? no nos rejemos) además, así echamos el ratito y nos contamos qué tal nos va, que estos días están siendo de locura... Puede que vengan María y Jose y todo ;-) sin olvidarnos de nuestro reencuentro con Antonio Bernal después de su incursión en La bitácora...

En fin chicos, que espero que os animéis a venir, que me haría mucha ilusión que nos juntáramos por allí y echáramos un buen ratito.

Saluditos,

Pili

PD: por cierto, que ahora que veo bien el asunto de este mensaje, me recuerda a cierto momento mariachi que vivimos en Madrid... "... Jalisco no te rajeeeeeees, me sale del aaaaaaaaaaaaaalma, cantar con fervooooooooooooor... " :P igual que las caritas, no tiene el drupal también simbolitos? como una nota musical, por ejemplo, en este caso me habría venido estupendo ;-)


[[https://docs.google.com/forms/d/e/1FAIpQLSeGnXB3zyaNVYcb_2EoO8C5HRc6Emx-2rv2QS6OWNFz1yYSBQ/viewform?usp=pp_url&entry.55081144=Webmaster%2C%20no%20te%20rajes][Dejar comentario]].

** Comentarios

*** Ayer en El Perro Andaluz (Pili Cantautora - 02/03/2006 - 18:49)
Holahola! al final he acabado contestándome yo a mí misma, qué triste... :P para los que tuvieran alguna duda, finalmente el webmaster se rajó... aunque no se pronunció públicamente, no pudo eludir mi pregunta el lunes. Dice que volverá en primavera, ¿será verdad? espero que sí... el martes 21 de Marzo, curiosamente, es martes ;)

Respecto a anoche, disfruté mucho, aunque hoy esté que me caigo por la oficina... Desde aquí una petición al infinito: Alfonso, por favor, empieza los conciertos a la hora plis!! se agradecería el haber dormido una horita más... María y Jose vivieron por primera vez experiencia en "el chucho pulgoso", y espero que se animen a compartir sus impresiones con nosotros por este rincón. Siento que Alfonso no tocara "Hola. Q tal?", para la próxima no se nos escapa, le haremos la petición antes del concierto para ir a lo seguro... Por cierto, que me encanta la canción "Juego" de Alfonso, y me quedé con las ganas de escuchar la nueva del Chiqui... y Javi Osorio no defraudó, a la altura de lo esperado ;)

Y paso al siguiente punto: nuestro reencuentro con Antonio. En fin, que nos perdone porque no hubo valor para manifestarnos... en realidad sí que lo hubo en algún momento, pero al final no llegamos a ningún acuerdo, y como no estaba nuestro webmaster... Me encantó la presentación de Alfonso, "soplagaitas y coco-guagua" ;) sonó estupendo, como siempre... Para la próxima nos animamos, con webmaster o sin él.

De momento me voy despidiendo ya... Lo hago, para variar, con una petición, esta vez dirigida a Jose: anda, veniros a ver a Manuel Cuesta el domingo, no? Piensa que el muchacho ahora viene muy poquito, que esta vez toca a una hora muy buena y podrás dormir todas tus horitas, que te invitamos a churros con chocolate... y sobre todo, que a María le hace mucha ilusión, que ya se sabe las canciones y todo! :)

Besos, Pili.

*** Hola a todos!la verdad es (jibseijo - 02/03/2006 - 18:58)
Hola a todos!

la verdad es que llevo muchos días (y semanas) pensando en escribir alguna cosilla, pero al final por una cosa o por otra ni siquiera he visitado la bitácora últimamente para leerla. Este mundo en el que vivimos apenas nos deja tiempo para nosotros mismo... En fin, como diría AQUEL, "vendrán tiempos mejores...".

Ayer el concierto estuvo genial, como siempre. Faltó la guinda de que te hubiéramos dicho quiénes somos, Antonio Gaiteriro. En realidad seguro que lo sabes, te teníamos al ladito. La próxima charlamos un rato, seguro. Íbamos a "manifestarnos", pero justo cuando iba a decirte que éramos los godobitácoros siderales llegaron Chiqui y compañía, y ya con tanta gente por ahí decidimos dejarlo. Si vas el domingo a ver al Cuesta, allí nos veremos. Por cierto, a ver si un día te marcas la de "María Soliña" o "Camiño de Santiago", que me encantaría oirlas.

Apoyo a Pi totalmente en su reivindicación sobre la hora: hay que explicarle a Alfonso que si el concierto se anuncia para las 21:30, sobre las 21:45 ya estamos todos, y si empezamos antes se agracede en el curro al días siguiente... Pero bueno, es una tradición eso de empezarlo como tres cuartos o una hora tarde ;)

Al webmaster, a ver si se apunta al del Cuesta del domingo. Es más, si se viene me comprometo a invitarlo a una barbacoa en mi azotea, un jonhycola (o caipirinha, a gusto del consumidor) y si se encarta hasta unos churritos antes del concierto. Si con esto ya no te vienes, no sé qué más ofrecerte (si conociera al pingu de linux lo invitaba también ese día, para presentaros). ¡Que te espero, Godo!

Un saludo para todos y a ver si le damos vidilla a esto!

---------------------------
Dime cuánto tiempo queda,
qué hago, aparte del vago,
finjo estar de acuerdo,
es un milagro que siga estando cuerdo

*** La lluvia y el viento nos llevan al Chucho (María 03/03/2006 - 09:21)
Hola a todos!!
Bueno, como ya han comentado los anfitriones el concierto fue genial (Jose volvió a dar palmas y todo!!!).

Apoyo que nos falto manifestarnos al Coco-Guagua, aunq creo q lo sabe....Nuestra identidad secreta casi al descubierto ¡ q momento!
A ver si el webmaster se anima el domingo y nos vemos en el Chucho, porque al final (gracias a la lluvia y el viento) estaremos allí, aunq no estoy muy segura si estaremos en buenas condiciones después del atracón de "falsa morcilla" y "patatas de perritos".

Besitos,
María
PD: Montellano nos espera en primavera!!!!!!!!\\

*** Si no pasa nada, allí estaremos (Godo 04/03/2006 - 10:55)
Tras algunos esfuerzos creo que seré capaz de dar la talla y no hacerle un feo a un johnnie... han sido muchas horas juntos ;-)

También tengo ganas de ver en directo a Manuel Cuesta, lo he escuchado en el "godoutor" y creo que sus canciones suelen llegarte sin mucho trabajo previo.

Además, hemos de cerrar ya el "detectivesco" capítulo con Antonio Bernal, si está por allí, claro.

Y para cerrar este comentario, creo que hay dos cosas que no tendrán remedio: la hora de comenzar los conciertos de Alfonso y lo apretado que nos viene el tiempo en la edad adulta. Esto último tampoco es tan malo, significa que tenemos muchas cosas que hacer, y que estamos viviendo la vida.

Un abrazo.

*** Tirón de orejas :P (Antonio Bernal 06/03/2006 - 13:18)
Hola, gente de la Bitácora.

Bueno, antes de nada, lo siento pero no me queda otra opción que daros un pequeño tirón de orejas por esa NO-presentación en el concierto del martes pasado...jejeje...bueno, se entiende que si vistéis mucha gente por allí y tal...pero vamos, que uno no muerde y de momento no tengo que andar quitándome a las hordas de fans de encima (por suerte), aunque sí es verdad que el martes pasado estuvimos en plan "tertulia" antes del concierto, allí con Chiqui, Javi Osorio y demás...pero bueno que no vuelva a repetirse!! jaja

Y que tal estuvo el concierto de Manuel Cuesta de ayer?? Yo al final no pude ir, estuve el fin de semana fuera, en Arcos de la frontera (mi pueblo natal), y bueno, aparte tuve visita de unos amigos de Valencia...nada, me fue imposible ir...otra vez será. Pero contad algo sobre el concierto :)

Bueno, sobre la hora de comienzo, le pegaré un toque de atención a Alfonso...el tema es que realmente el bar tiene programada y anunciada la actuación a las 22 h, y no a las 21:30...pero en su web sigue poniendo 21:30 creo...bueno ahora me fijo y ya se lo digo mañana...el tema es que la gente llega a las 22:15...aunque claro, eso es la pescadilla que se muerde la cola...la gente llega tarde porque Alfonso empieza tarde, y él dice que empieza tarde porque la gente llega tarde...en fin, cosas de cantautores, ejeje, yo ahí ni pincho ni corto pero algo le diré de vuestra parte :P

Saludos y besos, nos vemos pronto (espero)

Desde Coco-Guagua Land...

Antonio Bernal

*** Manuel Cuesta y el Flaherty's (Anónimo 09/03/2006 - 15:09)
Holahola a todos! cada vez se va alejando más el conciertito del domingo, estamos a jueves y parece que hace ya una eternidad que estábamos allí, tan a agustito, en el perro andaluz... Vaya semana más ho-rro-ro-sa! en flin...

Antonio, estuvimos muy atentos por si te veíamos el domingo por allí, pero nada... hubiera sido seguramente la mejor de las oportunidades para manifestarnos, había casi pleno de asistencia! ;) Godo nuestro Webmaster, Esther, María, Jose, José Ignacio y yo (ya nos irás poniendo las caritas ;))

Eso de que el concierto fuera a las 6 de la tarde fue una de las mejores cosas, el "chucho" estaba como diferente, la gente con sus cafelitos y sus juegos de mesa... estaba bastante lleno, pero al final tuvimos suerte y pillamos sofá en primera línea :D El concierto estuvo bien, siempre se agradece ver a Manuel después de tanto tiempo, pero hay que reconocer que no andaba muy centrado, se le olvidó la letra de varias de las canciones... me lo veo de aquí a poco como a nuestro Alfonso, con su atrilito y las chuletillas ;) fíjate como sería la cosa, que le pedimos Estatuas de Sal, y se hizo el sordo porque no se acordaba... en fin, las cosas del directo :P La intervención de Alfonso estuvo mu guay, cantó Entre Tartas de Café.

Yo supongo que el próximo conciertito será ya el siguiente martes que nos animemos a ir a ver a Alfonso, espero que pueda ser dentro de poco... Sí que me sonaba haberle escuchado decir lo de que el concierto empezaba tarde porque la gente llegaba tarde, pero es que se hace muy, muy duro el levantarse el día siguiente después del concierto...

Para los que no lo hayan visto, os animo a leer el mensajito que Antonio ha escrito en el foro de Alfonso sobre los ratitos con gaitas y flautas en el Flaherty's los jueves por la tarde (por cierto, qué hora más buena ;-)) Yo no descarto el acercarme alguna tarde al salir de la oficina, siempre me ha gustado mucho ese sitio...

De momento nada más, ¿alguien más se anima a contar algo más sobre el concierto del pasado domingo? ;) Besos y hasta pronto!

Pili

PD: ¿Sabéis que muy cerquita de nuestra oficina hay una calle que se llama Antonio Bernal? :)

PD2: María y yo ya tenemos un chucho pulgoso!!! jejeje...

*** Holahola (jibseijo 09/03/2006 - 16:13)
Muy buenas a todos!

¡Por fin alguien se animó (o tuvo tiempo) de escribir algo sobre el concierto del domingo! Estuvo muy bien, pero puesto a buscar pegas, creo que Manuel (el Cuesta, pa los amigos ;) ) debería preparárselo mejor. O por lo menos tener las letrilla por ahí escritas por si las moscas, no fueron ni dos ni tres las veces que se quedó en blanco... En flin, tampoco pasa nada. Eso sí, me quedé con las ganas de escuchar "Estatuas de Sal", que hace muucho que no la canta. Por lo demás, todo muy bien, como siempre.

Cambiando de tema (más bien de lugar), os quiero comentar algo que hemos despubierto Pi y yo hace poco: los conciertos que se retransmiten en directo en la página del Galileo (www.salagalileogalilei.com). Me ha encantado ver que se ve más o menos bien, y se oye mucho mejor. Se pueden ver los conciertos diarios en directo (sobre las 21:30), y lo mejor es que a los pocos días están disponibles los mismos conciertos archivados, y con las canciones puestas una por una... de lujo, echad un vistazo. El sábado pasado se pudo ver al Joaqui colaborando en la celebración del aniverario de 5 Tristes Tigres. Por ahí anda, os lo rcomiendo (ADSL required, of course).

Y otra cosilla es que me apetece bastante ir un jueves a lo del Flaherty's, tenemos que planear una excursión. Seguro que me encanta. Si alguien se va animando, que lo ponga por aquí.

Bueno, de momento eso es todo. Dentro de poco nos volveremos a reunir en torno a un puñado de buenas canciones, seguro.

Un abrazo para todos desde Godolandia, este fantasticular mundo virtual.

-------------------------------
Dime cuánto tiempo queda,
qué hago, aparte del vago,
finjo estar de acuerdo,
es un milagro que siga estando cuerdo

*** Poco más que decir (Godo 11/03/2006 - 22:42)
Bueno, del concierto creo que hay poco más que decir, de hecho creo que ya casi habéis dicho más que "El Cuesta" en sus recordados cachos de canción ;-) (es broma, eh, sólo por ahondar en la herida). Me gusta mucho la de "esta primavera" aunque "sea la mujer de otro".

En fin, que yo quería decir que me apunto a lo del Flaherty... que los jueves me viene muy bien, y que a esa hora aún me viene mejor.

¿Quién da más?

Ah, sólo faltan 10 días para que llegue la primavera. Hoy ya se nota su ruido en el patio de mi casa: huele distinto, croan las ranas, se escuchan grillos... el silencio de las noches de invierno ha dado paso a la algarabía de la vida... temprana Sevilla.

Salud, sólo faltan 10 días para asistir a otro "estimulante" concierto de Alfonso.
