#+title: Lecturas de verano - Año 2006 (II)
#+date: <2006-08-31 00:19>
#+author: Godofredo Fdez.
#+description: El segundo libro que me he leído este verano ha sido este: dos estrelles nel firmamentu infinitu (Rubén Sánchez Antuña) Otro pequeño libro, 166 páginas, no escrito con doble espacio entre renglones pero con fuente suficientemente grande. Publicado por vtp editorial . Como el lector habrá apreciado el libro está escrito en bable, o asturiano, no sé que es más correcto. Llegó a mis manos esta primavera, enviado por el propio autor. Fuimos compañeros de carrera. Y ahora somos amigos en la distancia. El tema : la novela se desarrolla en los tiempos actuales y los dos personajes centrales son: un Ingeniero de Telecomunicación en paro y un Cura. Ambos son amigos desde pequeños y tras un periodo de desconexión vuelven a coincidir para compartir momentos y problemas. Dado que uno de ellos es Ing. de telecomunicación, el autor lo utiliza para divulgar conceptos sobre las nuevas tecnologías, virtudes y fracasos. Como el otro es Cura, es utilizado para indagar en las sensaciones de frustración y replanteamiento de la vida interior o privada.
#+filetags: Libros Pensamiento
#+options: _:nil
#+nid: 163

El segundo libro que me he leído este verano ha sido este:

*dos estrelles nel firmamentu infinitu* (Rubén Sánchez Antuña)

Otro pequeño libro, 166 páginas, no escrito con doble espacio entre renglones pero con fuente suficientemente grande. Publicado por [[http://www.vtpeditorial.com][vtp editorial]].

Como el lector habrá apreciado el libro está escrito en bable, o asturiano, no sé que es más correcto. Llegó a mis manos esta primavera, enviado por el propio autor. Fuimos compañeros de carrera. Y ahora somos amigos en la distancia.

*El tema*: la novela se desarrolla en los tiempos actuales y los dos personajes centrales son: un Ingeniero de Telecomunicación en paro y un Cura. Ambos son amigos desde pequeños y tras un periodo de desconexión vuelven a coincidir para compartir momentos y problemas. Dado que uno de ellos es Ing. de telecomunicación, el autor lo utiliza para divulgar conceptos sobre las nuevas tecnologías, virtudes y fracasos. Como el otro es Cura, es utilizado para indagar en las sensaciones de frustración y replanteamiento de la vida interior o privada.

En un determinado momento, y empujado por circunstancias que no revelaré aquí, el cura penetra en el increíble mundo de la creación literaria, y acaba creando cuatro cuentos que comparte con su amigo: "Como dos gotas de Rocío", "uniBErSOS", "Silvida o El Silencio Viviente" y "Entonces (una historia de ti)".

Esos cuatro cuentos fueron escritos por mi hace años (cuando yo también penetré en el increíble mundo que resulta de enfrentarte a la página en blanco). De hecho por ahí andan, colgados en la web del proyecto que compartimos con otros varios autores. Alguna vez lo he insinuado ya aquí.

Los dos últimos son cuentos desgarradores (o al menos eso me parecían cuando los escribí y ahora que los he vuelto a leer después de mucho tiempo todavía me lo siguen pareciendo, aunque un poquito menos), los dos primeros, sin embargo, creo que cambiaban de tono y reflejaban más el sentimiento de "apostar para ganar"...

Sería pretencioso recomendaros la lectura. ;-)


[[https://docs.google.com/forms/d/e/1FAIpQLSeGnXB3zyaNVYcb_2EoO8C5HRc6Emx-2rv2QS6OWNFz1yYSBQ/viewform?usp=pp_url&entry.55081144=Lecturas%20de%20verano%20-%20A%C3%B1o%202006%20%28II%29][Dejar comentario]].

** Comentarios

*** Qué curiosidad... (el radioplanner 31/08/2006 - 20:02)
¿Cómo puedes decir que tienes colgados algunos cuentos por internet y no decirnos dónde? Es como encontrar una estrella en el cosmos y sin puntero láser... Anda, no seas malo y pásanos la dirección (Google no me ha ayudado mucho...).
Por cierto, ¿cómo han llegado tus cuentos a formar parte de la historia del cura y del teleco?

Saludetes (calurosos, muy calurosos)!

*** Queremos datos! (Pili Cantautora 03/09/2006 - 12:21)
Qué ganitas de que vuelvas y nos des las claves para poder encontrar tus cuentos! Me encantaría de verdad poder leerlos, y también la novela de tu amigo en la distancia, indagaré para hacerme con ella... Espero que os vaya todo de maravilla por Asturias, qué ganas de volver y rodearse de tanta paz y belleza...
