#+title: Joaquín Calderón y Carlos Chaouen
#+date: <2007-11-29 09:00>
#+author: Pili Cantautora
#+description: Sala Malandar. Calle Torneo, número 43. Sevilla. Venta de entradas sólo en taquilla. Precio: 10€. http://bay01.imagebay.com/_upload/img/26/CARTELCALDERONCHAOUEN1-1.jpg ------------------------------- Este concierto forma parte de una serie de actuaciones en las que Joaquín Calderón nos está trayendo a algún buen amigo para compartir canciones. Anteriormente vinieron Paco Cifuentes y Diego Cantero.
#+filetags: 
#+options: _:nil
#+nid: 266

Sala Malandar. Calle Torneo, número 43. Sevilla.
Venta de entradas sólo en taquilla. Precio: 10€.
http://bay01.imagebay.com/_upload/img/26/CARTELCALDERONCHAOUEN1-1.jpg
-------------------------------
Este concierto forma parte de una serie de actuaciones en las que Joaquín Calderón nos está trayendo a algún buen amigo para compartir canciones. Anteriormente vinieron Paco Cifuentes y Diego Cantero.
Godo: ¿te acuerdas del chico de la acera, el que chuta a puerta en tu portal, el del Parque Norte? Pues aquí le tendremos el día 18, al gran Carlos Chaouen, con nuestro gran Joaquín Calderón, ahí queda eso :)

PD: y más adelante vendrán también Javier Ruibal, y Zahara... seguiremos informando.


[[https://docs.google.com/forms/d/e/1FAIpQLSeGnXB3zyaNVYcb_2EoO8C5HRc6Emx-2rv2QS6OWNFz1yYSBQ/viewform?usp=pp_url&entry.55081144=Joaqu%C3%ADn%20Calder%C3%B3n%20y%20Carlos%20Chaouen][Dejar comentario]].

** Comentarios

*** Entradas (jaime 12/12/2007 - 10:17)
alquien sabe donde puedo comprar las entradas?? mi correo es sshadess182@hotmail.com

Gracias

*** Sólo en taquilla (Pili Cantautora 12/12/2007 - 16:34)
¡Hola Jaime! Las entradas sólo se podrán comprar en taquilla. Te copio el texto que ha escrito un amigo en el foro de la web de Chaouen:
"Las puertas de la Sala Malandar se abrirán a las 22.00h. En ese momento se empezarán a vender las entradas, sin reservas, y según el orden de llegada (el aforo es limitado y se espera mucha gente, aviso...) El precio será de 10 euros. Joaquín llevará camisetas y puede que Carlos lleve algún disco. Para ver el cartel del concierto entra en: http://bay01.imagebay.com/_upload/img/26/CARTELCALDERONCHAOUEN1-1.jpg saludos"

Espero que la información te sea de utilidad. Nos vemos por allí!

Saluditos :)

*** gracias (jaime 24/12/2007 - 12:01)
muchas gracias :D el concierto estuvo bastante bien aunque por lo de la hora y demas fue un pelin corto! muchas gracias por avisarme y siento responderte una semana despues!
