#+title: NADA PUEDE IR PEOR
#+date: <2007-05-23 10:48>
#+author: Calavera Bob
#+description: EL CAMARERO SORDO GESTICULA MIENTRAS BEBO, ES MEJOR CUANDO ME CUENTAN ALGO Y NO PUEDO ENTENDERLO... MIS CONSEJOS SON TAN MALOS QUE PODRÍAN HACERTE DAÑO, ASÍ QUE PAGARÉ ESTA COPA Y NO PODRÁS LEER MIS LABIOS. LA BAILARINA SACA UN CONEJO DE SU TANGA, DOS BILLETES DE CINCUENTA Y UNA BOLA DE PETANCA... ¿QUIÉN QUIERE MÁS?. AQUEL BORRACHO QUIERE MAŚ, Y ALGUIEN HA LLAMADO A LOS GORILAS DE SEGURIDAD. EN UN CALLEJÓN MÁS NEGRO QUE LOS DIENTES DE LA MADRE DEL GORILA QUE ME DIO LA ÚLTIMA OSTIA ANTES DE ECHARME, BAJO UNA LUNA INQUIETANTE UN VAGABUNDO QUIERE DARME
#+filetags: Desde_ti
#+options: _:nil
#+nid: 235

EL CAMARERO SORDO GESTICULA MIENTRAS BEBO,
ES MEJOR CUANDO ME CUENTAN ALGO Y NO PUEDO ENTENDERLO...
MIS CONSEJOS SON TAN MALOS QUE PODRÍAN HACERTE DAÑO,
ASÍ QUE PAGARÉ ESTA COPA Y NO PODRÁS LEER MIS LABIOS.

LA BAILARINA SACA UN CONEJO DE SU TANGA,
DOS BILLETES DE CINCUENTA Y UNA BOLA DE PETANCA...
¿QUIÉN QUIERE MÁS?. AQUEL BORRACHO QUIERE MAŚ,
Y ALGUIEN HA LLAMADO A LOS GORILAS DE SEGURIDAD.

EN UN CALLEJÓN MÁS NEGRO QUE LOS DIENTES DE LA MADRE
DEL GORILA QUE ME DIO LA ÚLTIMA OSTIA ANTES DE ECHARME,
BAJO UNA LUNA INQUIETANTE UN VAGABUNDO QUIERE DARME
UN TRAGO DE UN CARTÓN Y YO NO HE PODIDO NEGARME...

NO TENGO PROBLEMAS CON EL VINO Y LAS MUJERES
EXCEPTO CUANDO ME FALTA UNA COPA
Y ALGUIEN QUE ME ESPERE
EN EL ANDÉN DE LA ESTACIÓN,
SÉ QUE AHORA NADA PUEDE IR AÚN PEOR,
YA SÉ QUE NADA PUEDE IR PEOR.

SUJETANDO LAS PAREDES,
SOSPECHANDO DE LAS SOMBRAS,
TROPEZANDO EN LOS BORDILLOS,
INTERMITENCIA EN LAS FAROLAS.

EL CHASQUIDO DE LAS BOLAS DEL BILLAR DE OTRO GARITO,
EL ZUMBIDO DEL NEÓN ME LLAMA
Y NO ENCUENTRO EL CAMINO...

ASÍ QUE LA PARED SE ACABA
Y COMO QUIEN CAE A UN ABISMO
ME ENCONTRÉ AGARRÁNDOLE UNA TETA
A LA CAMARERA DEL GARITO,
Y DE LA OSTIA QUE ME DIO
ME VI DE NUEVO EN EL CALLEJÓN,
MALHERIDO Y CONSUMIDO,
ME LO TENGO MERECIDO...

NO TENGO PROBLEMAS CON EL VINO Y LAS MUJERES
EXCEPTO CUANDO ME FALTA UNA COPA
Y ALGUIEN QUE ME ESPERE
EN EL ANDÉN DE LA ESTACIÓN,
SÉ QUE AHORA NADA PUEDE IR AÚN PEOR,
YA SÉ QUE NADA PUEDE IR PEOR.

javi osorio
Córdoba 2007

(Aquí os dejo un regalito, es una canción nueva).


[[https://docs.google.com/forms/d/e/1FAIpQLSeGnXB3zyaNVYcb_2EoO8C5HRc6Emx-2rv2QS6OWNFz1yYSBQ/viewform?usp=pp_url&entry.55081144=NADA%20PUEDE%20IR%20PEOR][Dejar comentario]].

** Comentarios

*** I am formulating a study (Kari Markworth 01/04/2013 - 15:47)
I am formulating a study paper and gathering details of this area. Your post is among the more suitable I have read. Thank you for keeping this level of detail in to one specific space.\\
