#+title: ¡Música gratis, legal...
#+date: <2007-09-22 21:57>
#+author: Godofredo Fdez.
#+description: ...y en directo! Escribo este "post" para animar a la gente joven a que se aproxime a otras formas de música existentes, y tan distintas a las habitualmente difundidas en radios, televisión y demás antros que pugnan por la creación de una sociedad uniforme (el peligroso "hombre masa" orteguiano). ¡Ojo! que no critico la música actual sino la homogeneidad y la falta de anchuras.
#+filetags: Música
#+options: _:nil
#+nid: 249

...y en directo! Escribo este "post" para animar a la gente joven a que se aproxime a otras formas de música existentes, y tan distintas a las habitualmente difundidas en radios, televisión y demás antros que pugnan por la creación de una sociedad uniforme (el peligroso "hombre masa" orteguiano). ¡Ojo! que no critico la música actual sino la homogeneidad y la falta de anchuras. Uno, que desde pequeño ha participado en diferentes bandas de música, desde la de la Cruz Roja de mi pueblo, donde comencé a tocar el tambor atraído por los rítmicos "contracantos" de la caja, hasta la municipal, donde toqué la trompeta, instrumento en el que me asenté y del que me regalaron (siempre mis padres) un par de ejemplares (el de "trote" y el de "lujo"). Algunas colaboraciones/sustituciones hice con diferentes bandas de la provincia... En fin, que siempre que puedo acudo a los conciertos que ofrece la
"Banda Sinfónica Municipal de Sevilla", principalmente en el "Teatro Hogar Virgen de los Reyes". Ayer, a las 20'30 horas con británica puntualidad nos deleitaron con magnificas interpretaciones de:

#+BEGIN_QUOTE
  1ª Parte
  ===========

  - Doña Francisquita (Pasodoble) A. Vives
  - La Dolorosa (Selección) J. Serrano
  - Gran Jota de la Dolores T. Bretón

  2ª Parte
  ===========

  - Oregon (Fantasía) (*) J. de Haan
  - Los Ríos (Impresiones Rítmicas) (*) A. Malando-Arr. K. Vlak
  #+BEGIN_QUOTE
    1. Río Negro
    2. Orinoco
    3. Chubut
  #+END_QUOTE

  - The Fifties (Selección años 50) (*) Arr. P. Jennings (*) Primera vez por la Banda Sinfónica Municipal de Sevilla = Director: José Salazar Rodríguez
#+END_QUOTE

La primera parte, centrada en zarzuelas que ya conocía, me pareció sumamente entrañable -siempre me han transmitido mucho las zarzuelas-. La segunda, de la cual no conocía nada, me dejó impactado: las "impresiones rítmicas" hicieron honor a su descripción, resultando imposible mantener quietos los pies, creando una infinidad de climas "americanos" que te hacían sentir protagonista de la inmensa llanura. Creo que hubieran hecho las delicias de cualquier persona joven con ganas de descubrir nuevas percepciones, de verdad. Les doy desde aquí mi más sincera enhorabuena a los miembros de la Banda Sinfónica de Sevilla, a sus directores, a los organizadores, patrocinadores, etc. Y les animo a que sigan deleitándonos con el transcurrir interpretativo de tan variados caminos. Desde esta tribuna intentaré aportar mi pequeño grano de arena difundiendo, en nuestro calendario de eventos, todas aquellas actuaciones programadas. Sigan escuchándonos. P.D.: La [[http://www.rossevilla.com/index_f.html][Real Orquesta Sinfónica de Sevilla]], hermana mayor de nuestra protagonista, ofrece [[http://www.rossevilla.com/pages/menu01.html][16 conciertos en la temporada 2007-2008]], y está disponible un [[http://www.rossevilla.com/pages/ppabono.html][abono joven]] (30 Euros) para menores de 26 años.


[[https://docs.google.com/forms/d/e/1FAIpQLSeGnXB3zyaNVYcb_2EoO8C5HRc6Emx-2rv2QS6OWNFz1yYSBQ/viewform?usp=pp_url&entry.55081144=%C2%A1M%C3%BAsica%20gratis%2C%20legal...][Dejar comentario]].

