#+title: Jorge Gallego – Espacio y Tiempo
#+date: <2007-02-27 14:16>
#+author: Pili Cantautora
#+description: Hola holita a todos! He de reconocer que para mí es muy complicado hablar de la obra de Jorge. Básicamente no tengo ninguna idea sobre arte, así que esto se me queda muy, muy grande... Aún así, no quería dejar de recomendaros que visitéis su exposición de pintura “Espacio – Tiempo”. Tendremos esta pequeña muestra de sus obras en Sevilla hasta el 18 de Marzo, en la Casa de la Provincia, Plaza del Triunfo, de martes a domingo, de 10 a 14 y de 17 a 20 (lunes cerrado). Sólo os comentaré dos pequeños alicientes: - Podéis visitar su web: www.jorgegallego.es, visitándola podréis haceros una idea del gran artista que es Jorge (a pesa de contar tan sólo con 26 añitos, ahí queda eso :))
#+filetags: Desde_ti
#+options: _:nil
#+nid: 206

Hola holita a todos! He de reconocer que para mí es muy complicado hablar de la obra de Jorge. Básicamente no tengo ninguna idea sobre arte, así que esto se me queda muy, muy grande... Aún así, no quería dejar de recomendaros que visitéis su exposición de pintura “Espacio -- Tiempo”.

Tendremos esta pequeña muestra de sus obras en Sevilla hasta el 18 de Marzo, en la Casa de la Provincia, Plaza del Triunfo, de martes a domingo, de 10 a 14 y de 17 a 20 (lunes cerrado).

Sólo os comentaré dos pequeños alicientes:

- Podéis visitar su web: www.jorgegallego.es, visitándola podréis haceros una idea del gran artista que es Jorge (a pesa de contar tan sólo con 26 añitos, ahí queda eso :))

- Uno de sus cuadros ha sido adquirido por el museo Thyssen, ni más ni menos. Se llama Tic -- Tac, y forma parte de la exposición.

Ya me comentaréis que os parece. Para mí es una maravilla.\\


[[https://docs.google.com/forms/d/e/1FAIpQLSeGnXB3zyaNVYcb_2EoO8C5HRc6Emx-2rv2QS6OWNFz1yYSBQ/viewform?usp=pp_url&entry.55081144=Jorge%20Gallego%20%E2%80%93%20Espacio%20y%20Tiempo][Dejar comentario]].

