#+title: Nuestro Evento Mayor
#+date: <2007-07-27 14:59>
#+author: Pili Cantautora
#+description: En fin, parece increíble, pero ha llegado el momento de incluir aquí nuestro propio Evento Mayor... :) Me hacía mucha ilusión incluirlo en nuestro calendario,…
#+filetags: 
#+options: _:nil
#+nid: 246

En fin, parece increíble, pero ha llegado el momento de incluir aquí nuestro propio Evento Mayor... :) Me hacía mucha ilusión incluirlo en nuestro calendario, e ir siguiendo aquí nuestra particular cuenta atrás, ¿qué mejor lugar para llevar esta cuenta, que este rinconcito al que tanto cariño le tengo? A día de hoy quedan: 9 meses menos 1 día.


[[https://docs.google.com/forms/d/e/1FAIpQLSeGnXB3zyaNVYcb_2EoO8C5HRc6Emx-2rv2QS6OWNFz1yYSBQ/viewform?usp=pp_url&entry.55081144=Nuestro%20Evento%20Mayor][Dejar comentario]].

** Comentarios

*** ¡¡¡Lo mejor es que parece (Paquito 01/08/2007 - 09:45)
¡¡¡Lo mejor es que parece que el Evento Mayor va a durar 24 horas!!! ¡¡¡Como una boda gitana!!! ¡¡¡Yujuuuuuuuuu!!!

*** Durará más :) (Pili Cantautora 17/08/2007 - 12:56)
Llevas toda la razón Paquito!! Pero es que realmente creo que durará 24 horas, al menos para nosotros, y puede que incluso más ;)

*** La ilusión (Esther 16/11/2007 - 22:02)
Debe parecer mentira recordar el primer día os mirasteis a los ojos, siendo entonces los de unos extraños y que ahora sean casi como mirarse a los de uno mismo, ojos de confianza, de respeto, de apoyo y de construcción.
El evento mayor durará 24 horas, pero la ilusión... toda la vida.

PDTA. Paquito, no he tenido ocasión de decírtelo, pero espero que esta nueva etapa que habéis estrenado recientemente, sea el inicio del mejor proyecto de vuestra historia. Muchas felicidades!!

*** ¡¡¡Gracias muchas!!! Es (Paquito 27/11/2007 - 09:33)
¡¡¡Gracias muchas!!! Es otra ilusión distinta, mirarle desde el primer día a los ojos y ya ser uno parte del otro. A ver si conoces a Javi... ¡¡¡¡Es más guapo!!!!

*** ¡Es mu guapo! (Pili Cantautora 29/11/2007 - 09:02)
¡Confirmo que Javi es muy guapo! y verle acurrucaito con nuestro Paquito toda una experiencia ;) Tenemos que organizar otra quedada prontito...

Ojalá que sea así, que la ilusión nos dure toda la vida y vosotros sigáis a nuestro lado para compartirla... ¡¡muchos besitos!!
