#+title: JAVI OSORIO  "PRESENTACIÓN NUEVA MAQUETA Y MÁS..."
#+date: <2007-04-13 11:52>
#+author: Calavera Bob
#+description: WENAS FAMILIA!! ESPERO QUE OS ESTÉ SENTANDO BIEN LA PRIMAVERA...YO FLIPANDOLO CON NUESTRA TIERRA...ANDALUCÍA QUÉ GRANDE ERES!!. DESPUÉS DE HABER ESTADO VIVIENDO EN MÁLAGA Y EN CÓRDOBA UNA TEMPORADITA...ESTO ES LO QUE OS PUEDO OFRECER: - HOY, VIERNES 13 DE ABRIL A LAS 22:00 H. EN EL ROOM (c/ALFAROS), PRESENTACIÓN DE LA NUEVA MAQUETA EN DIRECTO "ROOM" GRABADA EL DÍA 8 DE MARZO DE 2007 EN EL ROOM (CÓRDOBA).INCLUYE 12 TEMAS, 10 DE ELLOS NUEVOS.GUITARRA Y VOZ. - EL 3 DE MAYO DE 2007, CONCIERTO TAMBIÉN EN EL ROOM, JUNTO A ANTONIO "EL BIÓNICO", CANTANTE Y COMPOSITOR DE "TODOS LOS SISTEMAS ACTIVADOS" (PODEIS VER SU MUSICA EN EL YOUTUBE PONIENDO "TODOS LOS SISTEMAS ACTIVADOS"),UNO DE LOS GRUPOS JUNTO A LOS ASLANDTICOS, SATÁN GONZÁLEZ Y KEJARTE, MÁS IMPORTANTES DEL PANORAMA UNDERGROUND ANDALUZ.SERÁ GUITARRA Y VOZ.
#+filetags: Desde_ti
#+options: _:nil
#+nid: 220

WENAS FAMILIA!!

ESPERO QUE OS ESTÉ SENTANDO BIEN LA PRIMAVERA...YO FLIPANDOLO CON NUESTRA TIERRA...ANDALUCÍA QUÉ GRANDE ERES!!.

DESPUÉS DE HABER ESTADO VIVIENDO EN MÁLAGA Y EN CÓRDOBA UNA TEMPORADITA...ESTO ES LO QUE OS PUEDO OFRECER:

- HOY, VIERNES 13 DE ABRIL A LAS 22:00 H. EN EL ROOM (c/ALFAROS), PRESENTACIÓN DE LA NUEVA MAQUETA EN DIRECTO "ROOM" GRABADA EL DÍA 8 DE MARZO DE 2007 EN EL ROOM (CÓRDOBA).INCLUYE 12 TEMAS, 10 DE ELLOS NUEVOS.GUITARRA Y VOZ.

- EL 3 DE MAYO DE 2007, CONCIERTO TAMBIÉN EN EL ROOM, JUNTO A ANTONIO "EL BIÓNICO", CANTANTE Y COMPOSITOR DE "TODOS LOS SISTEMAS ACTIVADOS" (PODEIS VER SU MUSICA EN EL YOUTUBE PONIENDO "TODOS LOS SISTEMAS ACTIVADOS"),UNO DE LOS GRUPOS JUNTO A LOS ASLANDTICOS, SATÁN GONZÁLEZ Y KEJARTE, MÁS IMPORTANTES DEL PANORAMA UNDERGROUND ANDALUZ.SERÁ GUITARRA Y VOZ.

- 25 DE MAYO DE 2007,PRESENTACIÓN DE LA NUEVA MAQUETA EN ALCALÁ DE GUADAIRA, EN EL BAR LA BIBLIOTECA. JAVI OSORIO Y LOS SANTOS PERVERSOS.

- 31 DE MAYO DE 2007, PRESENTACIÓN DE LA NUEVA MAQUETA EN SEVILLA, EN LA SALA MALANDAR, JUNTO AL GRUPO "SATÁN GONZÁLEZ" (GRUPO DE FUSIÓN, CORDOBÉS).

- NUEVA PÁGINA WEB A PARTIR DE ESTE DOMINGO 15 DE ABRIL. CON FORO Y MUCHAS NUEVAS FOTOS, MULTIMEDIAS,..ETC.

- NUEVOS VIDEOS EN EL YOUTUBE, CON EXCELENTE CALIDAD, GRABADOS DEL CONCIERTO DEL ROOM EN CÓRDOBA. (DENTRO DE MUY POCO).

ADEMÁS: CAMBIOS EN LA BANDA, OTRA BANDA NUEVA ADEMÁS DE JAVI OSORIO Y LOS SANTOS PERVERSOS (PIANO,CONTRABAJO,GUITARRA FLAMENCA,SAXO..).NUEVAS GRABACIONES PROXIMAMENTE, NUEVOS TEMAS...ETC.

MUCHAS GRACIAS FAMILIA POR ESTE HUECO QUE SIEMPRE ME DEJAIS,ESPERO QUE NOS VEAMOS PRONTO, ETERNAS GRACIAS.

PARA MÁS INFORMACIÓN WWW.JAVIOSORIO.NET


[[https://docs.google.com/forms/d/e/1FAIpQLSeGnXB3zyaNVYcb_2EoO8C5HRc6Emx-2rv2QS6OWNFz1yYSBQ/viewform?usp=pp_url&entry.55081144=JAVI%20OSORIO%20%20%22PRESENTACI%C3%93N%20NUEVA%20MAQUETA%20Y%20M%C3%81S...%22][Dejar comentario]].

** Comentarios

*** Gracias, Javi (Godo 15/04/2007 - 13:45)
De momento me apunto el 31 de mayo para intentar ir al concierto de la Sala Malandar. Quizá también estudie la posibilidad de ir el 25 a Alcalá...

Muchas gracias por mantenernos siempre informados. Es un placer seguir viéndote por aquí.

Y mucha suerte en tus nuevos proyectos: nueva formación, nueva web, nueva maqueta, etc.

Encantado de ver que sigues trabajando, y deseando de comprobar los nuevos éxitos que te traerá dicho esfuerzo.
