#+title: SE BUSCA SAXOFONISTA 
#+date: <2007-11-05 15:59>
#+author: Calavera Bob
#+description: WENAS A TODOS Y A TODAS, SE BUSCA SAXOFONISTA PARA JAVI OSORIO Y LOS SANTOS PERVERSOS. INTERESADOS LLAMEN AL: 687 22 82 89 LA WEB: www.javiosorio.net
#+filetags: Desde_ti
#+options: _:nil
#+nid: 258

WENAS A TODOS Y A TODAS,

SE BUSCA SAXOFONISTA PARA JAVI OSORIO Y LOS SANTOS PERVERSOS.

INTERESADOS LLAMEN AL: 687 22 82 89

LA WEB: www.javiosorio.net


[[https://docs.google.com/forms/d/e/1FAIpQLSeGnXB3zyaNVYcb_2EoO8C5HRc6Emx-2rv2QS6OWNFz1yYSBQ/viewform?usp=pp_url&entry.55081144=SE%20BUSCA%20SAXOFONISTA%20][Dejar comentario]].

** Comentarios

*** saxofonista (manuel marcos 17/01/2008 - 13:04)
soy un saxofonista cordobés y estoy interesado en tocar contigo, aquí te dejo mi numero de tlfno por si recalas y lees,toco el tenor el soprano el baritono y la flauta travesera. 622160157 un saludo

*** soy saxofonista (Osiris chamorro 11/02/2010 - 21:55)
Hola, si todabia buscas un saxo...Saludos
http://www.youtube.com/watch?v=gUagPRqthdI

http://www.youtube.com/watch?v=MOSYOLZ_WnY&feature=related

http://www.youtube.com/watch?v=LUShUdENFZ4

lo unico malo que vivo en Argentina...jeje pero puedo ir

*** saxofonista profesional (miguel 16/03/2010 - 23:33)
Hola, si todavia necesitas un saxofonista, mi nombre es miguel y soy saxofonista profesional y con mucha ezperiencia, puedes ver algo en youtube introduciendo "alarzaxo". tengo 30 años y vivo en alicante pero puedo desplazarme.Soy muy serio y profesional en mi trabajo. mi tlf es 638244360.
un saludo, gracias.
