#+title: ¿Asociación Internacional de los Trabajadores (AIT)? 
#+date: <2008-12-13 20:46>
#+author: Godofredo Fdez.
#+description: Recuerdo que de pequeño leí en uno de esos “libros de lectura” que solían acompañar al de “lengua” una fábula que relataba lo siguiente: en una cuadra vivían, entre otros, dos magníficos caballos. Uno de ellos era negro, de pelo corto y brillante, ojos profundos, delgada constitución y fuerte musculatura, cola y crines recortadas. El otro era blanco, de pelo largo y sedoso, ojos radiantes como el sol y fuerza inmensurable en cada uno de sus músculos. Por más que su dueño se esmeraba en cuidarlos a los dos por igual siempre estaban peleándose entre ellos.
#+filetags: ochentaveinte
#+options: _:nil
#+nid: 301

Recuerdo que de pequeño leí en uno de esos “libros de lectura” que solían acompañar al de “lengua” una fábula que relataba lo siguiente: en una cuadra vivían, entre otros, dos magníficos caballos. Uno de ellos era negro, de pelo corto y brillante, ojos profundos, delgada constitución y fuerte musculatura, cola y crines recortadas. El otro era blanco, de pelo largo y sedoso, ojos radiantes como el sol y fuerza inmensurable en cada uno de sus músculos. Por más que su dueño se esmeraba en cuidarlos a los dos por igual siempre estaban peleándose entre ellos. Uno sentía celos del otro en su único afán de ser el mejor caballo de la cuadra. Un largo trecho de su vida lo dedicaron a ese menester de intentar vencer al competidor para ser el primero. Esto fue así hasta que un día en el que se hallaban solos, inmersos en una de sus continuas batallas, observaron como un león aparecía por la puerta del establo. Verlo y detener su pelea fue una misma cosa. Comenzaron a temblar. Cada uno de ellos, sin atreverse a mirar al otro para que no descubriera el pavor que se había adueñado de su rostro, se preguntaba: ¿cómo va a morir el mejor caballo de la cuadra a uñas de un león? ¿estaré soñando? No, no estaban soñando, el león se aproximaba a ambos, los tenía arrinconados y sus rugidos casi servían como primeros zarpazos. Estuvieron a punto de morir por el orgullo, por mantenerse cada uno en su postura enfrentada, sin ni tan siquiera mirarse para establecer una estrategia común. Finalmente, cuando el león lanzó un doble zarpazo, la zarpa izquierda alcanzó ligeramente al caballo negro, lo suficiente para hacer brotar su sangre, la zarpa derecha al blanco, que también sangró. Ambos fueron conscientes de que o se unían contra ese enemigo común o no saldrían vivos de allí. Así, sin pensárselo dos veces, ambos arremetieron a coces contra el león, sin parar hasta que este sintió tal resquebrajamiento de los huesos de su cuerpo que decidió marcharse. Desde aquel día ambos caballos fueron los mejores amigos del lugar.

La moraleja estaba clara: un objetivo común de suma importancia ayuda a superar las miles de nimias guerras que nos separan.

Parece ser que esa moraleja la aprendieron rápido los chicos que iban para directivos de las grandes multinacionales, bancos, y demás manejadores del capital. Al unísono se dedicaron a la deslocalización (ese fenómeno que consiste en producir donde menos derechos sociales se les exige respetar y vender donde más nivel de renta hay disponible), a situar los capitales en aquellos paraísos fiscales donde más rentan (por acción: intereses elevados, o por omisión: evasión de impuestos)... el objetivo está claro: aumentar los beneficios, o lo que en mi tierra suelen llamar “llevárselo calentito”.

Sin embargo, aquellos que no fuimos tan listos (ya sabemos que en estos tiempos es más listo aquel que más dinero gana, incluso sin importar cómo) y que acabamos siendo mano de obra, proletariado, o clases medias espoliadas, olvidamos pronto la moraleja. No sabemos si nuestro objetivo es dejarnos la piel por la empresa que nos emplea para hacerle aumentar las ganancias, consiguiendo así asegurar nuestro sueldo y hacer frente a nuestras esclavizantes deudas, eso sí, hasta los 48 años en el que nos planten un ERE y nos larguen con una mano delante y otra detrás. No sabemos si nuestro objetivo es ser más nosotros mismos y menos los demás, creyéndonos que porque hoy le toca al otro jamás nos tocará a nosotros, o al menos, como no nos ha tocado a nosotros no chillemos y sigamos para adelante. Para nosotros parece ser que no existe ningún objetivo común: jamás he visto más pasividad y más renuncia a conquistas sociales que las que voy observando, con creces, cada año que cumplo.

Algunas concreciones de todo esto se pueden leer en los artículos de prensa que adjunto a este (al final): las 35 “mayores” empresas Españolas tuvieron beneficios en la época de vacas gordas (último ciclo económico expansivo que ha durado aproximadamente desde el 2003 hasta septiembre de 2007) que superaban a los del año anterior, es decir, que crecían, en torno al 30% (¿qué salario o conjunto de beneficios particulares: salario+seguro médico+vacaciones+etc., ha crecido de forma parecida o ni tan siquiera la quinta parte de esto? Además, en este año donde el ritmo de destrucción de empleo ha superado todas las previsiones (En noviembre el paro crece un 42,7% interanual: 900.000 parados más, hasta rozar los 3 millones), las empresas del IBEX 35 publicaron beneficios en el tercer trimestre que superaban los del año anterior en un 8,97% (¡OJO!, sí, esto significa que siguen aumentando los beneficios del año anterior, ni siquiera se resienten y ganan lo mismo, hecho que implicaría mantener la plantilla: mismos beneficios / misma capacidad de trabajo, y por tanto, tampoco están ganando menos: donde éticamente creo que no estaría justificado disminuir excesivamente la plantilla).

Pero claro, qué nos importa todo esto al grupo formado por el 80% de la población que no es tan lista como el 20% que se lo sigue llevando a manos llenas. Seguimos observando pasivamente la situación, sin exigir nada a nuestros representantes que continúan permitiendo/aprobando EREs y medidas de apoyo a los que más tienen: la banca siempre gana (frase que uno escuchaba en el Monopoly y no acababa de entender). Y extendiendo la jornada laboral hasta un máximo de 65 horas, eso sí, siempre que sea acordada de forma voluntaria entre el trabajador y el empresario. Voluntariedad que indudablemente ha plasmado ahí alguien que ha trabajado muchos años en la empresa privada. ¡Lo que hay que oír!

¿Cuánto más vamos a permanecer desunidos y pasivos? ¿Dónde están los sindicatos que enarbolaban la bandera de la solidaridad? ¿Dónde la internacionalización del movimiento obrero y la extensión de los derechos humanos? ¿Alguien se apunta? ¿La Izquierda? ¿Los progresistas?

P.D.: léase el título de este artículo como un guiño a este otro (http://es.wikipedia.org/wiki/Primera_Internacional) de la wikipedia, no por estar de acuerdo con todos los planteamientos que allí se hicieron sino por considerar necesaria la internacionalización de las conquistas sociales y los derechos humanos, para lo que es inevitable la unión entre las clases medias y trabajadoras.\\

** Archivos adjuntos
- [[https://godest.vivencias.net/static/files/El_Imparcial-65_horas.pdf][El\_Imparcial-65\_horas.pdf]]
- [[https://godest.vivencias.net/static/files/Las_empresas_del_8_97.pdf][Las\_empresas\_del\_8\_97.pdf]]
- [[https://godest.vivencias.net/static/files/Las_grandes_2007.pdf][Las\_grandes\_2007.pdf]]

[[https://docs.google.com/forms/d/e/1FAIpQLSeGnXB3zyaNVYcb_2EoO8C5HRc6Emx-2rv2QS6OWNFz1yYSBQ/viewform?usp=pp_url&entry.55081144=%C2%BFAsociaci%C3%B3n%20Internacional%20de%20los%20Trabajadores%20%28AIT%29%3F%20][Dejar comentario]].

