#+title: 40 de abril... o soñando de nuevo
#+date: <2008-09-12 00:15>
#+author: Godofredo Fdez.
#+description: Debió de ser un verano cualquiera del comienzo de la década de los noventa, pongamos que... verano del 91. Recuerdo que ese año, como tantos otros más, unos…
#+filetags: Música
#+options: _:nil
#+nid: 294

Debió de ser un verano cualquiera del comienzo de la década de los noventa, pongamos que... verano del 91. Recuerdo que ese año, como tantos otros más, unos cuantos componentes de la banda de música de mi pueblo formamos una "minibanda", y fuimos hasta Pontones, un par de aldeítas situadas en el corazón de la Sierra de Segura y pertenecientes al ayuntamiento de Santiago de la Espada. Lo recuerdo como uno de los mejores veranos de mi vida (quizá porque "...sólo recuero lo bueno. De lo malo, nada..."). Todavía la inocencia de la niñez no me había abandonado, y cada una de las vivencias se me iba guardando sin filtros, y con una intensidad similar a la que deja el hierro incandescente, en mi alma, en esa parte con capacidad de sentir y revivir.

Una de esas vivencias está formada por el "culto" rendido por casi todos los integrantes de la "minibanda" al entonces último disco de [[http://www.celtascortos.com/][Celtas Cortos]]: *Gente Impresentable*. Todos teníamos nuestra canción preferida, para algunos lo era "¿Qué voy a hacer yo?", para otros "Haz turismo", y para casi todos, "La senda del tiempo"... junto a más de una luna me ha acompañado. Eran tiempos de reivindicar: aún no había desaparecido el servicio militar obligatorio y todos debíamos "pasar por la piedra", la URSS se empezaba a descomponer y el "ideal comunista" no soportaba las embestidas del capitalismo que ahora nos invade...

...Y algún amor imposible rondaba nuestras calles.

En fin, los jóvenes seguíamos con nuestros sueños.

Aunque ya conocía el disco anterior: "Salida de Emergencia", con "Gente Impresentable" se afianzó una larga relación con uno de mis grupos "insignia". Después me acompañaron durante toda mi vida universitaria, haciéndome más llevadero el estar lejos de casa mientras revivían en mí las mismas sensaciones de siempre. Más de una noche aliñaron la intimidad de mi habitación (Pamplona/Sevilla) y animaron el jolgorio de algunos ¿discopubs?: Casino (Pamplona), Archivo (Sevilla)... y más de un salto, desfase y momento especial junto buenos amigos han amenizado.

Los vi en diversos conciertos en directo: Vilches, Santisteban del Puerto, Espárrago Rock (Jerez)... y el último, creo que el año pasado, en el auditorio de Dos Hermanas.

¡Os podéis imaginar como me siento saboreando este nuevo disco! Y empapándome de la energía positiva de este tema, "Retales de una vida", en el que atisbo la vuelta a sus sonidos más genuinos a pesar de que, creo, no están todos los que eran. Pero no nos pongamos ¿nostálgicos?

Sirva este "artículo" para darles las gracias por continuar... y para inaugurar un nuevo "look" de este rincón (¿no sé si lo habíais notado? ;-)).

Y tú, ¿me cuentas tu cuento?

Acechando un concierto próximo a Sevilla... ¡Nos vemos allí!\\


[[https://docs.google.com/forms/d/e/1FAIpQLSeGnXB3zyaNVYcb_2EoO8C5HRc6Emx-2rv2QS6OWNFz1yYSBQ/viewform?usp=pp_url&entry.55081144=40%20de%20abril...%20o%20so%C3%B1ando%20de%20nuevo][Dejar comentario]].

** Comentarios

*** Oye...
Que bueno es eso (Alba 03/10/2008 - 19:11)
Oye...
Que bueno es eso cuando recuerdas solo lo bueno, y de lo malo nada... jejejejeje
Aunque a veces los recuerdos caen como un jarro de agua fría en invierno.
Antes de nada quisiera dar un gran aplauso a esos amigos que siempre acompañan, ;)
Un saludo.!!

*** Los recuerdos... ¿nuestros cimientos? (Godo 14/10/2008 - 23:02)
Bueno, con lo que he tardado en contestar :-) seguro que te has dado cuenta que esa frase que te llamó la atención no es mía. Celtas Cortos siempre puso el dedo en la llaga: recuerda 20 de abril, En estos días inciertos, Tranquilo majete...

Los recuerdos, que a veces "caen como un jarro de agua fría en invierno" casi siempre son parte de la materia que compone nuestra forma de ser. Muchas veces no actuamos de otra manera, no nos dejamos caer, e incluso reímos a toro pasado por nuestros recuerdos. Un amigo escribió un día: "me cago en mi pasado"... mejor dicho, esa frase la pronunció un personaje al que dio vida este amigo mío. Aunque creo que todos atravesamos un periodo de nuestra vida, ese de rebeldía ante todo y sin ninguna causa, en el que nos asemejamos a este personaje (forma parte del ritual renegar del pasado e incluso echarle la culpa de todo al "sistema"), desde hace mucho tiempo me identifico justo con la actitud contraria: los recuerdos es algo que hay que digerir, aprender a convivir con ellos, y, aunque quede un poco "cursi", ver el lado positivo que nos construyó un poco más, haciéndonos lo que ahora somos. Quizá por esta forma de pensar acabé resaltando esa frase de la canción.

Un jarro de agua fría en invierno es mejor que no tener nada, sobre todo si te estás muriendo de sed.

Encantado de conocerte.
