#+title: Manifiesto por la lengua común
#+date: <2008-06-23 22:07>
#+author: Godofredo Fdez.
#+description: Una de las cosas que permite el disponer de la información en formato electrónico es su rapidez de consulta. Hoy me he hecho de la constitución española de…
#+filetags: Activismo Pensamiento
#+options: _:nil
#+nid: 286

Una de las cosas que permite el disponer de la información en formato electrónico es su rapidez de consulta. Hoy me he hecho de la [[http://narros.congreso.es/constitucion/index.htm][constitución española de 1978]] y he buscado la palabra *lengua* en su interior. A continuación presento los lugares donde esta aparece, así como el contenido de los mismos: *1.-* PREÁMBULO

#+BEGIN_QUOTE
  La Nación Española, deseando establecer la justicia, la libertad y la seguridad y promover el bien de cuantos la integran, en uso de su soberanía, proclama su voluntad de:
  ...
  Proteger a todos los españoles y pueblos de España en el ejercicio de los derechos humanos, sus culturas y tradiciones, *lenguas* e instituciones.
  ...
#+END_QUOTE

*2.-* TÍTULO PRELIMINAR.
Artículo 3:

#+BEGIN_QUOTE
  1. El castellano es la *lengua* española oficial del Estado. Todos los españoles tienen el deber de conocerla y el derecho a usarla.
  2. Las demás *lenguas* españolas serán también oficiales en las respectivas Comunidades Autónomas de acuerdo con sus Estatutos.
  3. La riqueza de las distintas modalidades lingüísticas de España es un patrimonio cultural que será objeto de especial respeto y protección.
#+END_QUOTE

*3.-* TÍTULO I. DE LOS DERECHOS Y DEBERES FUNDAMENTALES.
CAPÍTULO II. DERECHOS Y LIBERTADES.
SECCIÓN I. DE LOS DERECHOS FUNDAMENTALES Y DE LAS LIBERTADES PÚBLICAS.
Artículo 20.

#+BEGIN_QUOTE
  ...
  3. La Ley regulará la organización y el control parlamentario de los medios de comunicación social dependientes del Estado o de cualquier ente público y garantizará el acceso a dichos medios de los grupos sociales y políticos significativos, respetando el pluralismo de la sociedad y de las diversas *lenguas* de España.
  ...
#+END_QUOTE

*4.-* TÍTULO VIII. DE LA ORGANIZACIÓN TERRITORIAL DEL ESTADO.
CAPÍTULO III. DE LAS COMUNIDADES AUTONOMAS.
Artículo 148.

#+BEGIN_QUOTE
  ...
  17. El fomento de la cultura, de la investigación y, en su caso, de la enseñanza de la *lengua* de la Comunidad Autónoma.
  ...
#+END_QUOTE

*5.-* DISPOSICIÓN FINAL.

#+BEGIN_QUOTE
  Esta Constitución entrará en vigor el mismo día de la publicación de su texto oficial en el Boletín Oficial del Estado. Se publicará también en las demás *lenguas* de España.
#+END_QUOTE

Y de esto hemos llegado a esto otro:

El Mundo (http://www.elmundo.es) *18 intelectuales piden al Parlamento que garantice el derecho y el deber de conocer y hablar el español* PALOMA DIAZ SOTERO
23 de junio de 2008 *LA LENGUA COMUN.*
La ausencia de acción política en defensa del derecho a aprender y usar el castellano en las comunidades que han impuesto la inmersión lingüística en sus respectivas lenguas cooficiales ha llevado a 18 intelectuales a emprender, por su cuenta, una lucha por la igualdad de todos los ciudadanos y contra la discriminación de quienes quieren usar y aprender la lengua oficial del Estado y no pueden. Hoy, 30 años después de que la Constitución fijara una «protección especial» para el catalán, el gallego y el vasco, es el español -la única lengua que todos los ciudadanos tienen el deber de conocer- el que está en vías de extinción en Cataluña, Baleares, Galicia y el País Vasco. No en la calle, pero sí en las comunicaciones oficiales, la Administración Pública y los colegios. El *'Manifiesto por la lengua común'* lanzado hoy en busca de la adhesión de la ciudadanía reclama un verdadero bilingüismo en las autonomías con dos lenguas y observa que no son ellas quienes tienen derechos, sino las personas. Por ello, reclaman a los políticos una normativa legal que impida la imposición lingüística. *MADRID.*
El apartheid al que algunos gobiernos autonómicos están sometiendo al castellano, lengua oficial del Estado, ha llevado a un grupo de intelectuales españoles a impulsar un manifiesto que reclama a los políticos que garanticen el derecho y el deber de todos los ciudadanos a aprender el castellano y usarlo en sus comunicaciones privadas y públicas. Lo presentan hoy en el Ateneo de Madrid.
Los abajo firmantes son: Mario Vargas Llosa, José Antonio Marina, Aurelio Arteta, Félix de Azúa, Albert Boadella, Carlos Castilla del Pino, Luis Alberto de Cuenca, Arcadi Espada, Alberto González Troyano, Antonio Lastra, Carmen Iglesias, Francisco Sosa Wagner, Carlos Martínez Gorriarán, José Luis Pardo, Alvaro Pombo, Ramón Rodríguez, José Mª Ruiz Soroa y Fernando Savater.
El manifiesto parte, dicen, «de una inquietud estrictamente política» sobre el papel del castellano «como lengua principal de comunicación democrática en este país» y «los derechos educativos y cívicos de quienes la tienen como lengua materna o la eligen con todo derecho como vehículo preferente de expresión y comunicación».
«Son los ciudadanos quienes tienen derechos lingüísticos, no los territorios -afirma el texto-. Las lenguas no tienen el derecho de conseguir coactivamente hablantes ni a imponerse como prioritarias en educación». De esta manera interpretan lo que ocurre ya en Baleares y Cataluña y está en vías de asentarse en el País Vasco y Galicia. Sus gobiernos lo llaman «normalización lingüística» y ha pasado de significar que el uso de la lengua cooficial llegue a ser normal a implicar que lo normal sea que no se hable castellano. *Baleares.* La inmersión lingüística de las islas ha sido la más silenciosa, tal vez porque ningún partido nacionalista ha encabezado su Gobierno. No ha habido desafíos. El PP estuvo al frente de Baleares hasta las últimas elecciones autonómicas, que dieron como resultado un gobierno socialista apoyado por ERC y Unió Mallorquina. Y fue el PP el responsable de la ley aprobada en los 80 que priorizaba el uso del catalán por encima del castellano. La enseñanza es plenamente en catalán y la comunicación de la Administración con los ciudadanos también.
En las últimas semanas, la imposición ha llegado a cotas obsesivas. El Gobierno balear ha instado, no sólo al personal de la Administración, sino a sus ciudadanos, a que se dirijan a los inmigrantes y a los turistas en catalán en vez de en español.
A ello se suma la petición del Govern a la aerolínea Air Berlin -la principal en Baleares- para que emplee el catalán en vuelos y comunicaciones. El presidente de la compañía respondió que «hoy el castellano ya no es una lengua oficial» en las islas. *Cataluña.* Aunque la Generalitat la ocupa el PSE -junto a ERC e ICV-, la inmersión lingüística en la escuela a partir de los siete años llega heredada de los gobiernos de CiU. Sólo se imparte en castellano la asignatura de Lengua Española. Pero el Gobierno catalán no llega a cumplir con el mínimo de tres horas semanales de enseñanza en castellano en la Primaria, que un decreto del Ministerio de Educación fija para las comunidades con lenguas cooficiales.
ERC presionó al presidente, José Montilla, amenazando con irse del Govern, para impedir lo que creen una injerencia del Estado. Finalmente, Montilla se ha comprometido a blindar el modelo instaurado y que ese blindaje se materialice a través de la Ley de Educación catalana, que está en fase de redacción y que empezará a tramitarse en el Parlament tras el verano. Entretanto, Montilla da libertad a los centros.
Nada tiene que ver con la convicción de la ministra de Educación, Mercedes Cabrera, quien dijo que «Cataluña cumplirá lo que la LOE dice» y, «si no se cumple, el deber del Gobierno es exigir que se cumpla».
La Generalitat también ha lanzado una campaña para convencer a los inmigrantes de que hablar catalán es garantía de mejor vida y para instar a los autóctonos a que se dirijan a los extranjeros en la lengua cooficial con el noble fin de la «cohesión social». *País Vasco.* Han tenido que pasar décadas para que un porcentaje significativo de la población se anime a emplear el euskara o, al menos, lo entienda. Su modelo educativo garantiza, en teoría -por ley-, la libertad de elección al establecer tres modelos: A (en castellano, salvo la asignatura de euskara), B (mitad en castellano, mitad en euskara) y D (en euskara, salvo la asignatura de lengua castellana).
Ahora que se ha convertido en lengua cooficial de hecho en la comunicación institucional y que se ha asentado como vehicular a medias en la enseñanza -con presencia mayoritaria del modelo B en los colegios-, llegó el momento de tensar la cuerda. El lehendakari firmó en 2007 un decreto que contradice a su propia ley de enseñanza, según el cual, los alumnos deben alcanzar un nivel B-2 de euskara (el anterior al de los profesores de dicha lengua) al terminar la ESO. Para asegurar esas cotas de conocimiento, muchos colegios han desterrado el modelo A.
Pero el decreto ha resultado ser una mera transición hacia la inmersión lingüística total que prepara el Gobierno vasco con una ley educativa que quiere aprobar a lo largo del próximo curso político. EA, miembro del tripartito al frente de Educación, ha asegurado que en septiembre será «la última vez» que los niños de dos y tres años «podrán optar por un modelo lingüístico», aunque «nadie pretender erradicar» el castellano. El consejero, Tontxu Campos, ha asegurado que, si no logra el consenso con PSE y PP, es partidario de aprobar la reforma con el único apoyo de partidos nacionalistas. *Galicia.* El Gobierno de Fraga aprobó en 1983 la ley de «normalización lingüística» que obligaba a garantizar la igualdad de competencias en los dos idiomas oficiales al término de la ESO. Un decreto posterior, de 1995, fijaba el gallego como lengua vehicular de la enseñanza y «lengua oficial de la Administración educativa en Galicia». «La lengua -dice- constituye una de las bases esenciales de la identidad del pueblo y es el más fuerte vínculo de unión entre sus gentes».
Igual que en los colegios, la lengua de la Administración y de sus empleados debe ser el gallego, que es el idioma en el que se realizan las comunicaciones oficiales. Oficialmente, no hay bilingüismo. El gallego es la «lengua propia» de Galicia, dice su Estatuto.
Un último decreto de 2007, ya del Ejecutivo del socialista Emilio Pérez Touriño, establece unos mínimos competenciales de conocimiento del gallego, fija que la enseñanza en gallego sea de al menos el 50% e incluya a las materias troncales. También dicta que la lengua en la que debe hablar el personal de los colegios sea el gallego y ordena la creación de «equipos de normalización y dinamización lingüística».
La plataforma Galicia Bilingüe, atacada por pedir que no se elimine el castellano de la escuela y la Administración, denuncia que los nacionalistas, con la aquiescencia del PSOE, fomentan el axioma si no hablas gallego, estás contra Galicia. *COMO ADHERIRSE AL MANIFIESTO* 1. Enviando el cupón de adhesión por fax. La primera forma que tienen los lectores de EL MUNDO de adherirse al manifiesto es completando el cupón que se publica en esta misma página (a la izquierda) y enviarlo por fax a este periódico, acompañándolo de una fotocopia del DNI. El número de fax es el 91 297 47 98.
2. Enviando el cupón de adhesión por correo postal. También puede enviar el cupón que encontrará en esta misma página, acompañado de una fotocopia de su DNI, por correo postal, a la dirección de EL MUNDO: Avda. de San Luis, 25-27, 28033, Madrid indicando en el sobre: «Adhesión al Manifiesto por la Lengua Común»,
3. A través de 'elmundo.es'. Otra forma de adherirse al manifiesto es a través de la página web de este periódico, rellenando con sus datos (nombre, apellidos y DNI) el cupón que todos los lectores encontrarán en esta dirección de internet: http://elmundo.es/elmundo/2008/06/22/espana/1214165304.html#formulario

Desde esta débil tribuna en La Red, os animamos a todos los que estéis de acuerdo con lo expresado en el manifiesto (ver archivo adjunto al final de este artículo) que no permanezcáis impasibles, que os arméis de valor y emprendáis la lucha [[http://www.elmundo.es/elmundo/2008/06/22/espana/1214165304.html][adhiriéndoros al mismo]], así como en todos y por todos los medios que seáis capaces de influir, por ejemplo, cuando llegue la [[http://vivencias.net/ccount/click.php?id=7][hora de votar]]. La única forma de que te respeten es hacerte respetar. *Notas:* *28-08-2008*: Arturo Pérez-Reverte [[http://xlsemanal.finanzas.com/web/firma.php?id_edicion=3387&id_firma=6850][explica por qué se adhirió al manifiesto]], con cierto paralelismo de enfoque con lo escrito arriba, en su columna de opinión del "XLSemanal". *07-09-2008*: añado los artículos que Arturo Pérez-Reverte le dedicó al tema en el XLSemanal (fechas: 24 y 31 de agosto de 2008), así como uno más de Fernando Savater en El País (fecha: 5 de septiembre de 2008).

** Archivos adjuntos
- [[https://godest.vivencias.net/static/files/manifiesto-por-la-lengua-común.pdf][manifiesto-por-la-lengua-común.pdf]]
- [[https://godest.vivencias.net/static/files/080824-Perez-Reverte-Mi_propio_manifiesto_I.pdf][080824-Perez-Reverte-Mi\_propio\_manifiesto\_I.pdf]]
- [[https://godest.vivencias.net/static/files/080831-Perez-Reverte-Mi_propio_manifiesto_II.pdf][080831-Perez-Reverte-Mi\_propio\_manifiesto\_II.pdf]]
- [[https://godest.vivencias.net/static/files/080905-Savater-Balance.pdf][080905-Savater-Balance.pdf]]

[[https://docs.google.com/forms/d/e/1FAIpQLSeGnXB3zyaNVYcb_2EoO8C5HRc6Emx-2rv2QS6OWNFz1yYSBQ/viewform?usp=pp_url&entry.55081144=Manifiesto%20por%20la%20lengua%20com%C3%BAn][Dejar comentario]].

