#+title: 2008: 60 años de la Declaración Universal de los Derechos Humanos
#+date: <2008-06-21 19:23>
#+author: Godofredo Fdez.
#+description: Cuando este año alcancemos el 10 de diciembre estaremos de aniversario: la Declaración Universal de los Derechos Humanos cumplirá 60 años. Y aunque todos…
#+filetags: Activismo
#+options: _:nil
#+nid: 282

Cuando este año alcancemos el 10 de diciembre estaremos de aniversario: la [[http://www.un.org/es/documents/udhr/index.shtml][Declaración Universal de los Derechos Humanos]] cumplirá 60 años.

Y aunque todos pensemos que quedan muchas cosas por hacer, la verdad es que no podremos dejar de felicitarnos por la existencia de la misma, pues estableció unos principios básicos que a lo largo del tiempo se han ido desarrollando en tratados internacionales especializados que abordan cuestiones o grupos sociales específicos. Así, los derechos y libertades fundamentales se han ido aplicando a temas como: la discriminación racial, la tortura, las desapariciones forzadas, la discapacidad, y los derechos de las mujeres, la infancia, las personas migrantes, las minorías y los pueblos indígenas.

Desde que [[/node/192][leí este libro]]: "*La lucha por la dignidad*", soy consciente de la tremenda precariedad de las estructuras sociales en las que vivimos, así como del trabajo que ha costado levantarlas y sigue costando sostenerlas y mejorarlas. Cuando hoy escucho decir a mucha gente que "pasa de la política", siento parte de mi pasado reflejado en ellos, esos días donde la desconfianza y el desaliento era tal que la resignación se convertía en la única puerta hacia una calmada, creía, indiferencia. Hoy, por suerte, he recuperado las ganas de luchar por un ideal: construir un mundo más justo, más humano, más digno (Artículo 1: Todos los seres humanos nacen libres e iguales en dignidad y derechos y, dotados como están de razón y conciencia, deben comportarse fraternalmente los unos con los otros).

Entre otras acciones para pasar al [[/taxonomy/term/19][activismo]], tras leer [[http://www.es.amnesty.org/quienes-somos/nuestros-objetivos/][sus objetivos]] y comprobar, en la medida de lo posible, [[http://www.es.amnesty.org/quienes-somos/independencia/][su independencia]], decidí hacerme socio de [[http://www.es.amnesty.org/][Amnistía Internacional]].

Y comparto sus frutos.

Carta recibida con motivo de la declaración de la renta correspondiente al ejercicio de 2007.

Con un poco de tu dinero, millones de personas pueden ganar lo que jamás deberían haber perdido: su libertad, su integridad, su dignidad y en definitiva, los derechos que a todo ser humano corresponden por el hecho de serlo.
Sólo en 2007, con tu dinero y el trabajo de todas las personas que apoyáis a Amnistía Internacional, hemos podido mantener toda una estructura de activistas, voluntarios, abogados, investigadores, viajes, campañas de denuncia...

Esa estructura es costosa, pero gracias a que existe muchos de los que estaban ilegalmente recluidos en Guantánamo han regresado a sus hogares. También han sido liberados presos de conciencia como el monje tibetano Ngawang Phulchung, el activista tunecino Mohammed Abou o el disidente cubano Francisco Chaviano, que llevaba 13 años en prisión. Y todo con tu dinero.

Tu dinero, créetelo, ha contribuido a poner fin a la pena de muerte en Ruanda, ha cambiado la legislación china sobre la pena capital y ha evitado la ejecución de menores como el iraní Sina Paymard o el yemení Hafez Ibrahim. Con tu aportación has conseguido recordar al mundo la realidad de la población civil de Darfur, proteger a las mujeres nativas estadounidenses víctimas de malos tratos y a otros miles de personas cuyos Derechos Humanos estaban siendo violados.

Has conseguido todo eso con un poco de dinero. Así que imagina lo que podrías conseguir con un poco más. Podrías evitar muchas más ejecuciones, torturas, malos tratos, encarcelamientos ilegales, reclutamientos de menores... podrías hacer que el mundo se acercase un poco más al día en que los Derechos Humanos sean respetados por todos y en todas partes. Pero hasta que llegue ese día, cada euro es vital. Porque si incrementas tu cuota de socio aunque sea en 1 euro, tú no perderás nada y millones de personas pueden ganarlo todo.

Ahora, recibe lo que te corresponde: el agradecimiento de todas esas personas y el nuestro propio, así como el certificado para tu declaración de la renta, que servirá para que la Administración te devuelva parte de lo que has empleado en hacer lo que ella misma debería haber hecho.

Si quieres aportar tu granito de arena a esta ingente tarea...

...¡[[https://www.es.amnesty.org/ssl/socio/?origen=home][Únete a nosotros]]!\\

** Archivos adjuntos
- [[https://godest.vivencias.net/static/files/Decl_Universal_Derechos_Humanos.pdf][Decl\_Universal\_Derechos\_Humanos.pdf]]

[[https://docs.google.com/forms/d/e/1FAIpQLSeGnXB3zyaNVYcb_2EoO8C5HRc6Emx-2rv2QS6OWNFz1yYSBQ/viewform?usp=pp_url&entry.55081144=2008%3A%2060%20a%C3%B1os%20de%20la%20Declaraci%C3%B3n%20Universal%20de%20los%20Derechos%20Humanos][Dejar comentario]].

