#+title: Va a nacer un "nuevo" Sistema Operativo... de Google
#+date: <2009-07-09 23:09>
#+author: Godofredo Fdez.
#+description: Hoy me apetece jugar un poco con el futuro, como si de un adivino se tratara voy a pronosticar como imagino que será lo que Google nos ha comunicado en su blog…
#+filetags: GNU/Linux Seguridad Software
#+options: _:nil
#+nid: 329

Hoy me apetece jugar un poco con el futuro, como si de un adivino se tratara voy a pronosticar como imagino que será lo que Google [[http://googleblog.blogspot.com/2009/07/introducing-google-chrome-os.html][nos ha comunicado]] en su blog oficial: *Google Chrome OS*. Para ello voy a ir copiando cada uno de los párrafos de la noticia y, tras los mismos, voy a insertar mis comentarios.

#+begin_example

Introducing the Google Chrome OS
7/07/2009 09:37:00 PM
It's been an exciting nine months since we launched the Google Chrome browser. Already, over 30 million people use it regularly. We designed Google Chrome for people who live on the web — searching for information, checking email, catching up on the news, shopping or just staying in touch with friends. However, the operating systems that browsers run on were designed in an era where there was no web. So today, we're announcing a new project that's a natural extension of Google Chrome — the Google Chrome Operating System. It's our attempt to re-think what operating systems should be.

#+end_example

Creo que en este párrafo hay dos ideas clave: “people who live on the web” y “we're announcing a new project that's a natural extension of Google Chrome”. La ESTRATEGIA de Google es clara desde su nacimiento, de hecho hay pocas empresas con las ideas tan claras, el objetivo de vivir en Internet guía cada uno de sus pasos. Google sí se cree que la humanidad va a cambiar su casa por Internet. Es a esto a lo que está dedicando todos sus esfuerzos, cada uno de los pasos que da está claramente enfocado a conseguirlo. Y no desfallece por muy duro que le resulten algunas pendientes del camino. Podría utilizar muchos más adjetivos pero intentaré condensarlos todos en la palabra /alucinante/. Es alucinante la cantidad y calidad de las aplicaciones que Google tiene en red. Su punto de acceso: el navegador. Su táctica: apoyó a firefox (recuerdo un programa de “referencias en google adsense” que por cada descarga que se conseguía de dicho navegador te embolsaba ¿x? fracción de dólar) mientras no tuvo su propio navegador, y de ahí saltó a Google Chrome: ya tenía su primera herramienta de acceso a la "suite". ¿Era este paso necesario? Esto daría para otro debate. La segunda idea condiciona y presenta el resto de disertación. Continuemos pues.

#+begin_example

Google Chrome OS is an open source, lightweight operating system that will initially be targeted at netbooks. Later this year we will open-source its code, and netbooks running Google Chrome OS will be available for consumers in the second half of 2010. Because we're already talking to partners about the project, and we'll soon be working with the open source community, we wanted to share our vision now so everyone understands what we are trying to achieve.

#+end_example

En este párrafo sólo una idea que destacar: “Google Chrome OS is an open source”. El resto es desarrollo de la misma. ¿Qué pensará Microsoft de esto? La partida se pone interesante. Magnífico movimiento de Google que, por otra parte, se veía venir. No podía ser de otra forma: es la única que poco a poco ha venido arañando cuota de mercado a Microsoft, con permiso de Apple que, en mi opinión, se sigue dirigiendo a un segmento de mercado de alto poder adquisitivo (estrategia de desnatación). ¿Qué implicaciones tendrá esto en la comunidad open source? El más inmediato es el efecto que genera la competencia en todo mercado: reparto de cuota, y por tanto, reparto de esfuerzos. Esto, que a primera vista puede parecer negativo no tiene por qué serlo, véase como está funcionando Ubuntu con Debian, y el dinero que el propio Google está metiendo en algunos proyectos open source con sus [[http://code.google.com/soc/][Google summer of code]]. Hay miedo con la división que se puede producir en la comunidad de desarrolladores, supongo que habrá más miedo aún en aquellas empresas que habían apostado por un modelo de negocio basado en software libre como S.O. en sus clientes y como desarrollo/adaptación/servicios de aplicativos sobre éste. El proyecto de Google Chrome OS aún está muy inmaduro, su primer objetivo serán los netbooks, el siguiente los desktops de usuario y...

El modelo de negocio actual seguirá siendo válido durante varios años y, mientras tanto, habrá que estar atentos a como evoluciona “la vida en internet”. A mi lo único que me preocupa es la cuota de libertad y la información privada que esté en juego. ¡Ojo con el monstruo! Como se decía en mi pueblo: “o juego o no se juega”. ¡Cuidado con el “ojo que todo lo ve”!

#+begin_example

Speed, simplicity and security are the key aspects of Google Chrome OS. We're designing the OS to be fast and lightweight, to start up and get you onto the web in a few seconds. The user interface is minimal to stay out of your way, and most of the user experience takes place on the web. And as we did for the Google Chrome browser, we are going back to the basics and completely redesigning the underlying security architecture of the OS so that users don't have to deal with viruses, malware and security updates. It should just work.

#+end_example

Este párrafo no tiene desperdicio. TODO ES IMPORTANTE. Un S.O. que tarde poco en arrancar y que conforme termine ya nos habrá llevado a la web. Presiento que Google va a acelerar el camino que ha emprendido Linux en sus últimas versiones de kernel, va a detectar lo mínimo del hardware que le permita arrancar: disco duro, pantalla y teclado; el escritorio va a desaparecer como tal, no habrá papel tapiz sino un navegador con un cuadro de mandos, una futurista página web personalizable desde la que podremos saltar a cada una de las aplicaciones que deseemos usar: todo estará en La Red y a un sólo click: tu correo, las noticias, los documentos, etc. ¡Ojo, no confundir con un “active desktop” lleno de tonterías, páginas estáticas y enlaces que acaban abriendo un navegador como si de otra aplicación se tratara! Será conceptualmente más parecido a lo que ocurre en algunos móviles avanzados o PDAs, o como esos sistemas operativos en red a los que podemos acceder con nuestros navegadores actuales: [[http://www.eyeos.org/es/][Eye OS]], por ejemplo. Por cierto, esta gente (no sólo los de Eye OS sino todas las iniciativas que apostaron por esto) sí que debe de estar tiritando: ¡Que viene el lobo!

Que sea mínimo, el interfaz de usuario e incluso el sistema operativo, es obvio: no necesitamos nada en el disco duro excepto a él mismo pues, como venimos diciendo, “gran parte de la experiencia de usuario ocurrirá en la web”. Permitidme que vuelva a mostrar mi miedo: ¿quién tiene mis datos? ¿mi tesoro! ...mi tesoro!

Y ahora viene la definitivo: la seguridad. La seguridad del propio sistema, la que damos por hecho cuando compramos uno, la que en cualquier otro mercado haría desaparecer a una empresa: ¿alguien imagina un coche que un día arrancara y otro no porque tiene virus en el motor, es decir, algo que no le deja funcionar como debe?. Bueno, pues esto es común hoy en día en los ordenadores, sobre todo si esos ordenadores tienen Windows. Y no porque Microsoft sea el demonio, ni muy mala programando, ni sólo le importe vender y ganar mucho dinero, que quizá también, sino porque Windows es el sistema más rentable de atacar pues es usado por el 9X% de la población mundial. Sí señores, sí, en otros sistemas operativos también hay fallos de seguridad (otro debate que no quiero abrir). Y entonces llegó Google, dio un puñetazo en la mesa y dijo: se acabó, mi S.O. no se resentirá. En fin, bien es verdad que si, como dicen abajo, se basan en Linux como kernel, lo fortalecen de las varias formas que son posibles, se preocupan de mantener un buen sistema de permisos, privilegios, controles de acceso y actualizaciones, separan todas aquellas acciones de usuario de las propias de gestión y administración del sistema... y siguen investigando sin creerse que son invencibles, tienen mucho ganado. De partida: todos los virus que hoy existen para Windows serán simples rémoras de un pasado que existió. Y no esta mal nacer cepillándose al 9X% de las amenazas posibles, ¿verdad? Yo quiero uno así 8-) Es broma, mi [[http://www.debian.org][Debian GNU/Linux]] ya me tiene a salvo.

#+begin_example

Google Chrome OS will run on both x86 as well as ARM chips and we are working with multiple OEMs to bring a number of netbooks to market next year. The software architecture is simple — Google Chrome running within a new windowing system on top of a Linux kernel. For application developers, the web is the platform. All web-based applications will automatically work and new applications can be written using your favorite web technologies. And of course, these apps will run not only on Google Chrome OS, but on any standards-based browser on Windows, Mac and Linux thereby giving developers the largest user base of any platform.

#+end_example

Este párrafo es de refuerzo de los anteriores: mínimo sistema de ventanas, kernel Linux y aviso a navegantes, en este caso desarrolladores: “señores, programen para la web... ¡el sistema final no existe! Y programando para la web, obviamente, la interoperabilidad está asegurada. ¿Llegarán mis ojos a ver este nuevo cambio de ERA?

#+begin_example

Google Chrome OS is a new project, separate from Android. Android was designed from the beginning to work across a variety of devices from phones to set-top boxes to netbooks. Google Chrome OS is being created for people who spend most of their time on the web, and is being designed to power computers ranging from small netbooks to full-size desktop systems. While there are areas where Google Chrome OS and Android overlap, we believe choice will drive innovation for the benefit of everyone, including Google.

#+end_example

¿Cómo queda Android en todo esto? Bueno, yo creo que la idea de fondo es la misma y simplemente no desaparecerá porque nació para otras plataformas hardware, y ya se sabe: no es lo mismo un potito o una papilla para un bebe que un buen potaje con choricito picante para un adulto. Todo es comida, sí, pero démosle a cada cual lo que necesita. Así que, Android para los pequeños y Google Chrome OS para medianos y grandes. Y tampoco muy grandes, del mercado de los “servers” ni hablamos, ¿no? Claro, lógico, quién va a querer un servidor si todo su trabajo y sus datos van a estar en los servidores de otros, ¿uuummm? :-?

Y el péndulo volvió a su lugar: grandes servidores y terminales tontos que ya no son de fósforo verde y en modo texto sino magníficos navegadores webs llenos de ventanitas y gráficos... hacia ahí vamos, señores, es esa la tendencia. No tarden mucho en estudiarla e intentar subirse al carro: les inundarán con ROIs, reducción de costes operativos y mantenimiento, facilidad de administración, seguridad, redundancia, disponibilidad... ¡Tenemos de todo, señora! ¡Pasen y vean!

#+begin_example

We hear a lot from our users and their message is clear — computers need to get better. People want to get to their email instantly, without wasting time waiting for their computers to boot and browsers to start up. They want their computers to always run as fast as when they first bought them. They want their data to be accessible to them wherever they are and not have to worry about losing their computer or forgetting to back up files. Even more importantly, they don't want to spend hours configuring their computers to work with every new piece of hardware, or have to worry about constant software updates. And any time our users have a better computing experience, Google benefits as well by having happier users who are more likely to spend time on the Internet.

#+end_example

Este párrafo refuerza lo dicho en el anterior. Describe alguna que otra ventaja más, y nos dice de nuevo por qué Google hace todo esto: “ Google benefits as well by having happier users who are more likely to spend time on the Internet”. Sí, Google gana más dinero cuanto más tiempo pasamos en Internet. Ese es su modelo de negocio y a eso empujan. Se lo creen y apuestan. Fácil.

#+begin_example

We have a lot of work to do, and we're definitely going to need a lot of help from the open source community to accomplish this vision. We're excited for what's to come and we hope you are too. Stay tuned for more updates in the fall and have a great summer.

Update on 7/8/2009: We have posted an FAQ on the Google Chrome Blog.

Posted by Sundar Pichai, VP Product Management and Linus Upson, Engineering Director

#+end_example

¡Que os sea provechoso el trabajo que tenéis por delante! Tampoco mucho si es como yo lo veo, está casi todo hecho y sólo hay que pegarlo/afinarlo. ¿En qué estaría pensando yo para que no se me ocurriera a mi antes y pudiera habéroslo vendido? ;-)

Lo mejor de todo es que yo me lo creo. Esta gente trabaja muy bien. Será cuestión de tiempo pero lo conseguirán. Aquí queda esto, negro sobre blanco, con posibilidad de ser revisado dentro de unos años. Se abren las apuestas.

Seguiremos atentos a los movimientos que se producirán este otoño... y sí, intentaremos tener un “gran verano”... fresquito, de momento.

Y tú, ¿qué piensas de todo esto? Ansioso estoy por leer un comentario con tu punto de vista.

Salud y vida para verlo.\\


[[https://docs.google.com/forms/d/e/1FAIpQLSeGnXB3zyaNVYcb_2EoO8C5HRc6Emx-2rv2QS6OWNFz1yYSBQ/viewform?usp=pp_url&entry.55081144=Va%20a%20nacer%20un%20%22nuevo%22%20Sistema%20Operativo...%20de%20Google][Dejar comentario]].

