#+title: XXI Carrera Nocturna del Guadalquivir
#+date: <2009-07-30 20:38>
#+author: Godofredo Fdez.
#+description: Crónica : noche de viernes 25 de septiembre de 2009. Recojo a A. Sierra alrededor de las 20:45. Nos dirigimos hacia la Isla de La Cartuja y conseguimos aparcar cerca del edificio del CSIC. Aún faltan 30 minutos largos. Quedamos con J.A. Ternero y A. Estepa en la puerta de la Escuela de Ingenieros que lleva a los laboratorios. El pelotón de gente ya se extiende varios cientos de metros desde la línea de salida. A las 22:00 comienza la carrera. Hemos de ir andando un ratito: no hay espacio para correr. Los primeros kilómetros los hacemos en una media de 6 minutos 30 segundos.
#+filetags: Juegos/Deportes
#+options: _:nil
#+nid: 336

*Crónica*: noche de viernes 25 de septiembre de 2009. Recojo a A. Sierra alrededor de las 20:45. Nos dirigimos hacia la Isla de La Cartuja y conseguimos aparcar cerca del edificio del CSIC. Aún faltan 30 minutos largos. Quedamos con J.A. Ternero y A. Estepa en la puerta de la Escuela de Ingenieros que lleva a los laboratorios. El pelotón de gente ya se extiende varios cientos de metros desde la línea de salida. A las 22:00 comienza la carrera. Hemos de ir andando un ratito: no hay espacio para correr. Los primeros kilómetros los hacemos en una media de 6 minutos 30 segundos. Hace calor. No sé si es que no corre aire o es que no es capaz de pasar entre la marabunta. Llegamos al primer avituallamiento de agua, Paseo Colón frente a la Maestranza. A. Sierra se acerca a coger una botella, pisa otra que estaba en el suelo, entre miles (fallo de la organización y de civismo: una fila de contenedores a continuación de los avituallamientos, algo salteados, y extendidos tras los siguientes 250 m., que es lo que sueles tardar en darle dos o tres sorbos, aproximadamente, facilitaría el que los corredores se deshicieran de las botellas), y... ¿Dónde está A.? Seguimos los tres restantes juntos. Al llegar a Plaza de Cuba, para entrar a Pagés del Corro es tan grande la cantidad de corredores, y se forma tal embudo, que es imposible pasar corriendo. Varias decenas de metros andando. Hay mucha gente y esto implica cambio de ritmo constantes: ahora corro, ahora paro, ahora más lento porque arrollo al de delante, ahora aprieto para adelantar... Para colmo, un par de espabilados cruzan entre todos nosotros con sus respectivas bicicletas de Sevici. Una chavala cae cerca de mi tras tropezar con una de ellas. Parece que no se ha hecho nada. Me siento bien hasta el kilómetro 8,5 situado frente a Isla Mágica. Esa recta hasta las proximidades del estadio se me hace casi interminable: ahora siento un poco de flato, ya no soporto los cambios de ritmo, hace mucha calor, me molesta muchísimo una motito con una cámara que está grabando: ya pita para que me aparte, ya para y graba, ya la adelanto, ya pita para que me aparte. No puedo más. Estoy hecho polvo. J.A. Ternero decidió partir hace unos minutos a un ritmo más fuerte. A. Estepa me acompaña y me anima. Encontramos a A. Sierra casi en la cuestecita que lleva a la entrada del Estadio: se torció un tobillo al pisar la dichosa botella y ha llegado hasta allí en bici ¿! De nuevo somos tres. Trote cochinero por mi asfixia y por su tobillo. Pasamos bajo la puerta exterior del Estadio. Me siento hormiga bajo una galería de cemento: media vuelta bajo las gradas hasta salir a la pista. ¡Oh, luz! ¡Oh, aire! Ya estoy ahí, veo la meta, prácticamente una vueltecita y... mastico el momento, lo saboreo, lo trago despacito envuelto en la escasa saliva que soy capaz de segregar. ¡LO HE CONSEGUIDO! ¡HE ACABADO! Paro el cronómetro: 1 hora 11 minutos 7 segundos para los 10,5 Km. No nos dejan pararnos tras la línea de meta. Obvio. Sin embargo la organización ha montado los tornos de control de dorsales (supongo que para elaborar las listas de participantes que han acabado) bajo las galerías de cemento del Estadio. Mi cuerpo ha roto a sudar. Estoy empapado. Hace mucho calor aquí dentro, bajo el cemento, hay mucha gente hacinada ¡Otro fallo de la organización! Podían haber montado los tornos casi fuera, justo como estaban los de recogida de la bolsa de gratificación: pantalón, camiseta, refresco, etc., esto hubiera disminuido el sopor que sufrimos. Son críticas constructivas: es complicado organizar un evento con tanta gente. Y es de agradecer.

2º Tiempo: cervecitas de recuperación en los mostradores de CruzCampo. El Gatorade estaba literalmente arrasado, no bebí nada con la ilusión que me hacía: ¡Maravillosa publicidad, yo también quería sentirme deportista!

3er Tiempo: más cervecitas en la rotonda del Puente del Alamillo. Estas sí que me supieron a Gloria: gambitas, papas aliñás...

¿Para cuando la próxima?

Salud.\\

** Archivos adjuntos
- [[https://godest.vivencias.net/static/files/cuenta-atras-php_drupal.txt][cuenta-atras-php\_drupal.txt]]

[[https://docs.google.com/forms/d/e/1FAIpQLSeGnXB3zyaNVYcb_2EoO8C5HRc6Emx-2rv2QS6OWNFz1yYSBQ/viewform?usp=pp_url&entry.55081144=XXI%20Carrera%20Nocturna%20del%20Guadalquivir][Dejar comentario]].

** Comentarios

*** Allí nos vemos! (José Ignacio 13/08/2009 - 11:38)
Hola Godo!

Allí nos veremos. Yo voy un poco ajustado porque no entreno desde el 5 de Junio (Nocturna de Los Palacios) y con esta calor cada vez voy retrasando más el momento de volver a entrenar, pero espero correrla aunque sea a ritmo "trote cochinero".

http://cadap.wordpress.com

Un abrazo!

*** José Ignacio!!! (Godo 13/08/2009 - 23:47)
Me alegra de volver a leerte por aquí. Muchas gracias por tu comentario.

Siento decirte que por más que me esfuerce creo que estaré muy lejos de vuestro ritmo (según he leído en vuestra preparación/recorrido de la nocturna de Los Palacios): vosotros estáis ya por debajo de 6 min./km, y aquí el "trote cochinero" está más cerca de 7 min./km ... y sí, me está costando mucho entrenar con el "sopor" que está haciendo estos días, tanto es así que mañana voy a intentar levantarme temprano para ver si puedo entrenar con algo más de fresco antes de ir al curro. La parte buena es que ya consigo aguantar en torno a 7,5 Km. sin acabar destrozado (donde hay siempre queda :-D).

Tengo otro handicap añadido: he comenzado a correr hace 15 días, aproximadamente, después de años sin hacer nada, por lo que me está costando mucho coger ritmo. Además, por si fuera poco, antes de la carrera estaré de vacaciones, con lo que ello implica: viajecitos == cambios de lugar == diferentes rutinas == dificultad de mantener los entrenamientos... No sé, amigo, si llegaré a conseguirlo.

Pero vamos, mientras hay vida hay esperanza 8-)

P.D.geek: ya me contarás como sacaste el grafiquito distancia/pulsaciones ;-)

*** ¿Es posible correr así? (Godo 14/08/2009 - 08:58)
Jueves, 13 de agosto de 2009.

Sevilla, en torno a las 00:25 de la noche: 30'6ºC, 40% hr, 1009mb - según datos del sensor externo de la [[http://www.oregonscientific.es/shop/browse.asp?cid=35&scid=138][estación meteorológica]] que en su día me regaló Esther.

No fui capaz de salir... un entrenamiento menos :-(

*** La clave es entrenar (José Ignacio 14/08/2009 - 12:24)
Hola Godo!

La clave es entrenar, cuanto más entrenas, más corres, y se acaba convirtiendo en un vicio. Yo estaba igual que tú hace unos meses: tras años sin moverme absolutamente nada (ni un triste partidito de esos que la gente suele echar de vez en cuando), me puse a correr. El primer día, en 1 km, ya tuve que parar reventado porque estaba a casi 190 pulsaciones por minuto y se me salían las tripas por la boca.

Poco a poco se va progresando, y muy rápido. Fíjate en ti: en sólo 2 semanas ya aguantas 7,5km! Eso es espectacular, diría yo. Yo empecé a correr unos 3 meses antes de la carrera y al final mi marca fue de poco más de 5:30 el km, y eso no lo podía ni soñar unos días antes. Ahora estaré más cerca de 6, porque el parón lo voy a notar, pero desde el lunes vuelvo a entrenar. ¿A que te sientes como en éxtasis cuando terminas un entrenamiento duro? ¿Y en general, mucho más ágil y en forma? Es increíble. Y el subidón máximo llega en la carrera.

El gráfico (velocidad, ritmo, ppm, altura, tiempo, hora, recorrido en google maps, etc.) lo saco de aquí: https://buy.garmin.com/shop/shop.do?pID=349&ra=true

Un abrazo!

*** Planteándome la Nocturna... (Pili Cantautora 17/09/2009 - 13:18)
¡Hola Godito! ¿Cómo va ese entrenamiento? Yo he empezado a correr hace muy poquito, no hace todavía ni un mes, y lo que suelo correr son sólo 30 minutillos... pero mis compis de trabajo están animándote a que haga la Nocturna, y lo peor es que me estoy picando y todo ;-) Dependerá un poco de cómo vaya el entrenamiento mañana y el domingo. La verdad es que me haría mucha ilusión participar, pero no lo veo del todo claro...

Y tú, ¿cómo lo llevas?

¡Besos!\\

*** Sí, voy a intentarlo... (Godo 18/09/2009 - 10:56)
Hola Pili.

Pues sí, voy a intentar llegar a la meta. Por ahora no he corrido aún la distancia de 10Km. pero sí 7,5Km en torno a unos 45 minutos, y me he sentido bien, por lo que creo que podré llegar... ¡Ilusión no me falta!

Me he registrado a través del [[http://www.coitaoc.org/index.php?option=com_content&task=view&id=785&Itemid=115][COITAOC]] para "hacer colectivo".

Venga, anímate ;-)

*** Primera aproximación: conseguida (Godo 20/09/2009 - 22:17)
Si la herramienta de medición de distancias de [[http://maps.google.com/][Google maps]] no falla demasiado, y si mi cronómetro no me engaña, hoy he conseguido correr 10.500 metros en 67 minutos. Ese sigue siendo el objetivo: invertir 6 minutos en 1000 metros.

A ver si las fuerzas no me fallan este próximo viernes.

Salud.

*** Lo intentaré :-) (Pili Cantautora 21/09/2009 - 08:55)
¡Eso está estupendo Godo! No dudo que conseguirás tu objetivo. Yo lo tengo un poquitín más complicado... Mi objetivo se limita a ser capaz de terminar la carrera :-D Ayer batí mi record de distancia: 7,10km. Cuento con que alimentándome e hidratándome muy bien ese día, siendo la carrera de noche y eliminándose por tanto el sol y el calor, siendo los primeros km lentos porque seremos muchos..., pueda rascar y conseguir llegar al estadio corriendo, y no arrastrándome ;-)

Finalmente yo también me inscribí por el Colegio. El jueves por la tarde iré a recoger el dorsal, ¡qué nervios!

Besos!\\

*** Lo conseguí :-D (Pili Cantautora 19/10/2009 - 13:05)
Hola Godo! Al final conseguí terminarla. Tardé 1 hora 19 minutos, muy lentita yo, pero al menos llegué sana y salva :-)

Nunca había corrido tanta distancia, así que para mí fue un logro tremendo. Pensaba que la hora a la que era la carrera y la ausencia de sol me ayudarían a llevarlo mejor, pero el calor se me hizo insoportable. Los peores momentos los pasé por Triana, pero una vez que pasamos por el avituallamiento que había a la entrada de la Cartuja me sentí mucho mejor. ¡Y qué largo se hizo el último kilómetro y medio! Una vez que pasas por al lado del estadio te crees que ya has llegado, y de eso nada... Lo mejor fue la sensación de después, y el masajito nada más llegar :-D

De momento sigo sin abandonar el “running”, a ver si me dura. Ahora mismo mi propósito es mejorar la velocidad, ya te iré contando.

Un besote.\\
