#+title: PRIMER DISCO DE JAVI OSORIO Y LOS SANTOS PERVERSOS
#+date: <2009-01-25 16:08>
#+author: Calavera Bob
#+description: HOLA AMIGOS, HACE TIEMPO QUE NO ESCRIBÍA POR AQUÍ, PUES BUENO, APAREZCO PARA QUE SEPÁIS QUE NUESTRO PRIMER DISCO YA ESTÁ GRABADO Y APUNTO DE SER EDITADO PARA VENDERSE... PODÉIS ESCUCHAR PARTE DE ÉL EN: www.myspace.com/javiosorioylosantosperversos POR AHÍ AVISAREMOS COMO SE VENDERÁ, PORQUE HABRÁ VARIAS OPCIONES...YA SABÉIS...INTERNET, TIENDAS, BARES... Y SIEMPRE LO PODRÉIS ENCONTRAR EN LOS CONCIERTOS, QUE TAMBIÉN SE VAN PONIENDO EN EL MYSPACE, PORQUE LA PÁGINA WEB YA NO EXISTE, AUNQUE SÍ SU FORO.
#+filetags: Desde_ti
#+options: _:nil
#+nid: 303

HOLA AMIGOS, HACE TIEMPO QUE NO ESCRIBÍA POR AQUÍ, PUES BUENO, APAREZCO PARA QUE SEPÁIS QUE NUESTRO PRIMER DISCO YA ESTÁ GRABADO Y APUNTO DE SER EDITADO PARA VENDERSE...

PODÉIS ESCUCHAR PARTE DE ÉL EN:
www.myspace.com/javiosorioylosantosperversos

POR AHÍ AVISAREMOS COMO SE VENDERÁ, PORQUE HABRÁ VARIAS OPCIONES...YA SABÉIS...INTERNET, TIENDAS, BARES...
Y SIEMPRE LO PODRÉIS ENCONTRAR EN LOS CONCIERTOS, QUE TAMBIÉN SE VAN PONIENDO EN EL MYSPACE, PORQUE LA PÁGINA WEB YA NO EXISTE, AUNQUE SÍ SU FORO.

BUENO, ESPERO TENER NOTICIAS VUESTRAS PRONTO, UN SALUDO GRANDE DE UN AMIGO EN EL TIEMPO, CALAVERA.


[[https://docs.google.com/forms/d/e/1FAIpQLSeGnXB3zyaNVYcb_2EoO8C5HRc6Emx-2rv2QS6OWNFz1yYSBQ/viewform?usp=pp_url&entry.55081144=PRIMER%20DISCO%20DE%20JAVI%20OSORIO%20Y%20LOS%20SANTOS%20PERVERSOS][Dejar comentario]].

** Comentarios

*** HOLA A JAVI Y LOS SANTOS (MON 14/04/2009 - 04:32)
HOLA A JAVI Y LOS SANTOS PERVERSOS.
SIGO VUESTRAS ANDANZAS DESDE QUE OS VI HACE UNOS AÑOS EN LA CARBONERÍA, EN REALIDAD IBA TODOS LOS MIÉRCOLES QUE EL TRABAJO ME LO PERMITÍA. AHORA MO VIVO EN SEVILLA, PERO INTENTO ESTAR AL DÍA CON LAS CANCIONES QUE VAIS CREANDO.DONDE VIVO YA OS CONOCEN, PORQUE TENÍA UN BAR Y APARTE DE JANIS DE BOB, DE BILLIE, DE LA NIÑA DE LOS PEINES, ETC,TAMBIÉN SONÁBAIS VOSOTROS, Y EN FIN ES UN GUSTAZO ESCUCHAROS.ESPERO VEROS PRONTO POR AQUÍ CERCA.
GRACIAS POR ESTAR AHÍ.
