#+title: Backups online: cubriéndonos las espaldas
#+date: <2009-11-21 21:56>
#+author: Godofredo Fdez.
#+description: ¡Que levante la mano aquel que por algún motivo no ha perdido información valiosa almacenada en su ordenador! Uno, dos, tres… casi todo el mundo. Bien. Ahora, que levante la mano aquel que no ha echado de menos un documento que un día creó en el ordenador de casa y, tras algunos kilómetros recorridos para llegar al lugar de vacaciones, ups… ¡si tuviera aquí el documento con el análisis de las cuentas!
#+filetags: Seguridad Software
#+options: _:nil
#+nid: 342

¡Que levante la mano aquel que por algún motivo no ha perdido información valiosa almacenada en su ordenador! Uno, dos, tres... casi todo el mundo. Bien. Ahora, que levante la mano aquel que no ha echado de menos un documento que un día creó en el ordenador de casa y, tras algunos kilómetros recorridos para llegar al lugar de vacaciones, ups... ¡si tuviera aquí el documento con el análisis de las cuentas! Y es que, en esta sociedad donde el escritorio de madera se ha convertido en un PC y sus cajones en discos duros, cada día es más difícil sobrevivir sin echar de menos esos trabajos que vamos almacenando sin apenas darnos cuenta de que los tenemos hasta que no nos faltan. Recientemente he descubierto un servicio que nos ayuda a resolver ambas situaciones: [[https://mozy.com/?ref=PF8V8B][mozy]]. Pone a nuestra disposición un espacio gratuito de almacenamiento de 2GB en sus servidores a través de Internet. Para comenzar a utilizarlo basta con pulsar sobre el enlace anterior y, una vez cargada la página, hacer uso de la solución para “home users” que aparece en la parte superior derecha, seleccionando: “Sign up now”. Tras rellenar un par de formularios con nuestro correo electrónico (real porque nos envían un enlace), nuestra contraseña, y algunos datos estadísticos, recibiremos un mail para validar nuestro registro. Tras pulsarlo nos dejarán descargar una pequeña utilidad que se instalará en nuestro PC, integrándose en el menú derecho del “explorador de windows” y creando una unidad virtual (al estilo de un CD o nuevo disco duro). Durante el proceso de instalación nos guiará un asistente que seleccionará algunas carpetas por defecto de nuestro PC para comenzar con los backups: los favoritos del explorer y del firefox, “mis documentos”, “mi música”... en fin, podemos deseleccionarlas si no queremos que sean esas. Más adelante podremos elegir las que de verdad nos interesen. Me ha gustado:

#+BEGIN_QUOTE
  - La integración con el explorador de Windows facilita mucho seleccionar qué archivos o carpetas incluir en las copias de seguridad. Basta hacer click con el botón derecho sobre ellos y seleccionar la opción correspondiente. *No es necesario meter todas esas carpetas en "la unidad virtual correspondiente a nuestro espacio en los servidores remotos" sino que las carpetas siguen estando en su sitio, con nuestra organización actual, simplemente serán monitorizadas por la aplicación, y los archivos serán respaldados cuando así se programe (ver opciones)*.
  - La recuperación de ficheros a partir de la unidad virtual que nos crea es muy intuitiva y rápida. También se puede hacer accediendo a nuestra cuenta desde cualquier lugar con un navegador web.
  - Según nos cuentan (esto no lo he probado haciendo un verdadero análisis del software) los datos suben a los servidores cifrados con una contraseña de 448 bits (algoritmo blowfish) o 256 bits (algoritmo AES). Yo he elegido el segundo, creo que es lo suficientemente fuerte y rápido como solución de compromiso.
  - *¡OJO!* porque los datos están cifrados y para eso nos solicitan una "clave de cifrado", si la perdemos jamás podremos volver a recuperarlos. Nos advierten de que ellos tampoco pueden ayudarnos en este caso.
#+END_QUOTE

*Aspecto negativo a tener en cuenta, no tanto del programa en sí sino del uso que hagamos de él*: cada cual es dueño de su información hasta que decide “contarla”. Os exhorto a que consideréis que datos son lo suficientemente importantes pero no llegan a ser críticos (contraseñas bancarias, impresiones de recibos de cuentas, etc.) para que, si hay un fallo de seguridad, no os “desvalijen”. Sólo después de hacer esta reflexión, siendo conscientes de los riesgos que se corren en todos los servicios de almacenamiento web (correo web al estilo Hotmail, gmail, etc.) y remotos (como este que nos ocupa), y asumiendo dicho riesgo, la utilización de [[https://mozy.com/?ref=PF8V8B][mozy]] nos ayudará a preservar y utilizar nuestra información allí donde estemos. Que os sea propicio.\\


[[https://docs.google.com/forms/d/e/1FAIpQLSeGnXB3zyaNVYcb_2EoO8C5HRc6Emx-2rv2QS6OWNFz1yYSBQ/viewform?usp=pp_url&entry.55081144=Backups%20online%3A%20cubri%C3%A9ndonos%20las%20espaldas][Dejar comentario]].

