#+title: Identidad en Internet (I)
#+date: <2010-08-27 13:54>
#+author: Godofredo Fdez.
#+description: A continuación os dejo el artículo número 8 que, continuando mi línea de colaboración, he publicado en el blog del Colegio Oficial de Ingenieros de…
#+filetags: COITAOC LinkedIn Seguridad
#+options: _:nil
#+nid: 361

A continuación os dejo el artículo número *8* que, continuando mi línea de colaboración, he publicado en el [[http://blog.coitaoc.org/][blog del Colegio Oficial de Ingenieros de Telecomunicación de Andalucía Occidental y Ceuta]]. Divulgad que algo queda ;-)

Un par de [[http://www.internetlibros.com/650391/Nuevos-casos-de-Lupi%C3%B3n.html][lecturas]] de este verano me han sugerido escribir aquí sobre la identidad en la Red (algunos dirán en la nube), los peligros que la acechan y las posibles formas de protegerla.

Cuando nos adentramos en el concepto identidad vemos la gran problemática que ha originado desde la antigüedad griega, pasando por la época moderna, hasta nuestros días. Y los que seguirá ocasionando en un futuro. En este artículo simplificaremos para poder delimitar el problema y abordar, si cabe, la solución que nos interesa.

Identidad es uno de esos conceptos que se define “hacia fuera” y “hacia dentro”. El primer caso, “hacia fuera”, es el que nos interesa a nosotros y es el que el DRAE recoge en sus acepciones: “2. Conjunto de rasgos propios de un individuo o de una colectividad que los caracterizan frente a los demás. 3. Conciencia que una persona tiene de ser ella misma y distinta a las demás”. Como podemos observar en todas estas acepciones “los demás”, los otros, son necesarios para observar diferencias a través de las interrelaciones establecidas. El segundo caso, “hacia dentro”, es el que le preocupa a los filósofos y responde a las preguntas: ¿quiénes somos? o ¿cómo y cuándo dejamos de ser lo que somos? (resulta curiosa la lectura de la “[[http://es.wikipedia.org/wiki/Paradoja_de_Teseo][Paradoja de Teseo”]]).

Algunos rasgos que construyen nuestra identidad son: nuestro físico, nuestros recuerdos, nuestros sentimientos, nuestras inquietudes, el sentido del humor, etc. Hasta esta época el conjunto de estos elementos estaba tan ligado a nuestro espacio y a nuestro tiempo que era tan fácil de controlar que pasaba desapercibido. Pero, ¿qué está ocurriendo en la Red masivamente y en la “tecnosociedad” en general? La tecnología posibilita la construcción, la copia, la destrucción, la “perennidad” (en un futuro quizá la “inmortalidad”, como sugieren los cuentos referenciados al comienzo del artículo) de identidades, y así, la pérdida de control sobre las mismas con los problemas que esto causa.

Avancemos pues desde lo más simple hasta lo más complejo para ver qué está ocurriendo en Internet.

En un principio, cuando escasamente interactuábamos en la Red, lo único que nos identificaba en ella era nuestro nombre (login) y nuestra contraseña (password). Parece que ha pasado mucho tiempo pero hace tan sólo 10 años, aproximadamente, la web era estática, la información fluía desde el emisor hasta el receptor, y casi todos éramos destinatarios de la misma con escasas posibilidades de verter comentarios, indicar si “me gusta / no me gusta”, compartirla con nuestros amigos; había pocas “cookies” que se interesaran por nuestros sitios frecuentados y el correo no vivía perennemente en el servidor sino que se descargaba habitualmente (algunos hemos convivido con pop1/pop2 y convivimos con pop3) a nuestra máquina. Aquí el principal riesgo era el robo de nuestras credenciales, login y password, cosa no muy difícil pues viajaban sin cifrar y bastaba una simple captura de tráfico para obtenerlas. Un ataque a la privacidad en toda regla, pero limitado: sólo se obtendría el correo no descargado aún. La mejor defensa entonces: cambiar la clave frecuentemente, obligando a que la captura de ayer no fuera útil para hoy, y minimizar el número de sondeos de correo nuevo contra el servidor. Nadie lo hacía: todos aprendimos a convivir con el riesgo. Lo interiorizamos, supongo. Actualmente, cuando el acceso a estos servicios se debería plantear de forma cifrada, hay que incidir en la fortaleza de la contraseña (la típica mezcla de mayúsculas, minúsculas, números y signos), pues el ataque por fuerza bruta (prueba y error de sucesivas contraseñas hasta encontrar la válida) cobra mayor peso.

Posteriormente la Red evolucionó, la web pasó a llamarse “web 2.0”; el correo, “correo web”; los foros y chats se convirtieron en espléndidas “redes sociales” y la mensajería instantánea añadió tráfico multimedia: intercambio de fotos, voz y video en tiempo real.

Y a todos se nos olvidó ese viejo consejo que nos daban nuestras madres: “niño, no hables con extraños, ni te acerques cuando te ofrezcan caramelos”.

Continuará.


[[https://docs.google.com/forms/d/e/1FAIpQLSeGnXB3zyaNVYcb_2EoO8C5HRc6Emx-2rv2QS6OWNFz1yYSBQ/viewform?usp=pp_url&entry.55081144=Identidad%20en%20Internet%20%28I%29][Dejar comentario]].

** Comentarios

*** ¿Para cuando la segunda (elradioplanner 11/09/2010 - 17:39)
¿Para cuando la segunda parte?

*** Está al caer. (Godo 12/09/2010 - 22:16)
Este mes de septiembre, si las circunstancias no lo impiden.

*** Como has empezado con el (Ricardo (como verás pongo mi nombre) 16/09/2010 - 13:53)
Como has empezado con el tema de la identidad, tema que me interesa muchísimo, te dejo una frase que me impactó:

Si yo soy yo porque tu eres tu, y tu eres tu porque yo soy yo, entonces ni yo soy yo, ni tu eres tu.

*** Identidad (Otra vez Ricardo 18/09/2010 - 11:37)
“Si yo soy yo porque tu eres tu, y tu eres tu porque yo soy yo, entonces ni tu eres tu, ni yo soy yo”. Esta frase cuadra muy bien con la de todos conocido "si yo soy tu y tu eres yo ¿quien es mas tonto de los dos?".jejejejej
La frase (que no quien la dijo), está muy bien porque en lo profundo no sabemos quienes somos, somos en la medida que nos comparamos con el otro, pero esto pierde el poco sentido que pudiera tener, cuando los demás hacen lo mismo con nosotros.

Ese sentido ilusorio del ser es lo que Albert Einstein, con su percepción profunda no solamente de la realidad del espacio y el tiempo sino de la naturaleza humana, denominó "ilusión óptica de la conciencia". Esa ilusión del ser se convierte entonces en
la base de todas las demás interpretaciones o, mejor aún, nociones erradas de la realidad, de todos los procesos de pensamiento, las interacciones y las relaciones. La realidad se convierte en un reflejo de la ilusión original.
Pues bien, esa identidad a la que llamamos YO con la cual nos relacionamos normalmente es lo que también podríamos llamar ego.

Una relación genuina es aquella en la cual no domina el ego con su búsqueda del yo y su creación de imágenes. En una relación genuina hay una corriente de atención sincera y alerta hacia la otra persona, en la cual no hay sensación alguna de deseo. Esta atención alerta es la Presencia. Es el requisito para toda relación auténtica. Pero ¿nos relacionamos así normalmente?, ¿estamos viendo de verdad a la otra persona o son las imágenes las que se relacionan?.

Una de las estructuras mentales básicas a través de la cual entra en existencia el ego es la identificación. El vocablo "identificación" viene del latín "ídem" que significa "igual" y "facere" que significa "hacer". Así, cuando nos identificamos con algo, lo "hacemos igual". ¿Igual a qué? Igual al yo. Dotamos a ese algo de un sentido de ser, de tal manera que se convierte en parte de nuestra "identidad". En uno de los niveles más básicos de identificación están las cosas: el juguete se convierte después en el automóvil, la casa, la ropa, etcétera. Tratamos de hallarnos en las cosas pero nunca lo logramos del todo y terminamos perdiéndonos en ellas. Ese es el destino del ego.

Partiendo de esto, partiendo de esta falsa percepción de lo que somos que habitualmente todos tenemos, ¿Qué es lo que puede salir perjudicado en una supuesta invasión de lo que llamamos intimidad?. Tanto en la vida “real” como en que podemos llamar virtual, que por cierto, puede llegar a ser como un sueño dentro de otro sueño. ¿Qué es lo que tememos?. ¿Qué hay en el fondo del miedo al ridículo?.
Entiendo que la seguridad, la privacidad en Internet, es o debiera ser, la misma que en la vida real. Creo que hay un miedo exagerado cuando se habla de Internet, cuando los riesgos son idénticos que en de la vida real.
En la vida real también puedo coger una foto tuya en situación, digamos, comprometida y pegarla en los alrededores de tu casa. Quizás en Internet sea mas fácil, pero en la vida real es mas efectivo, porque al hacerlo así, seguro que la van a ver personas cercanas de tu entorno. Pero en ninguna de las dos, mi verdadero ser se va a ver comprometido. Es mi imagen, mi ego, el que sale dañado.

Resumiendo, estoy diciendo dos cosas, por un lado el riesgo me perece idéntico en Internet que en la vida real y por otro lo que tratamos de proteger tanto en un plano como en el otro, es nuestro ego, nuestra imagen, no lo que verdaderamente somos.\\
