#+title: Upgrade a Drupal 6
#+date: <2010-10-02 21:40>
#+author: Godofredo Fdez.
#+description: El idioma inglés dispone de dos palabras distintas para hablar de actualizaciones: update y upgrade . Se utiliza update para hablar de los frecuentes parches…
#+filetags: Bitácoras LinkedIn
#+options: _:nil
#+nid: 368

El idioma inglés dispone de dos palabras distintas para hablar de actualizaciones: update y upgrade. Se utiliza update para hablar de los frecuentes parches que corrigen diversos problemas dentro de la rama actual del código. Por ejemplo: pasar de la versión de Drupal 5.22 a la 5.23; aunque corregimos problemas seguimos manteniéndonos en la versión 5 del código y, por tanto, seguimos teniendo disponibles las mismas funcionalidades. Se utiliza upgrade para referirnos a una subida de versión y, así, de funcionalidades asociadas. Por ejemplo: pasar de la versión 5.23 a la 6.19. Esto ha sido lo que he hecho. Ten claro estos matices para tu vida de comprador y/o mantenedor de software, he asistido a varios malentendidos que han costado más de una desagradable discusión: una cosa es que Microsoft te mantenga tu windows parcheado, otra que te regale la nueva versión del sistema operativo :-P.

Despido así a la anterior rama 5.xx que tantos años me ha acompañado subiéndome al carro de la rama 6.xx, y lo hago casi dos años y medio después de que la versión [[http://drupal.org/drupal-6.0][6.0]] fuera estrenada. He dejado que los más intrépidos se enfrenten a los tempranos bugs que suelen acompañar a todo lanzamiento. Es una buena política que descubrimos y compartimos diversos compañeros de trabajo desde hace años, en todos los contextos: desarrollo web, software de comunicaciones, sistemas operativos, etc.

Y es una mala política de seguridad hablar aquí de la versión de software que "soporta" el sitio web: se da una pista a los que me quieran atacar... en fin, confío no estar en el punto de mira de nadie con malas intenciones y, sobre todo, en la seguridad de Drupal.

Aprovechando la subida de versión he lavado la cara del tema gráfico y estreno uno nuevo basado en [[http://drupal.org/project/zen][Zen]], una magnífica "escritura" del "motor gráfico" de Drupal, que clarifica mucho tanto los "layout" como las "hojas de estilo". He creado un subtema que hereda y refina el que usaba en la versión anterior. ¿Os gusta? Espero que sí. También he reescrito/readaptado casi todas las secciones del menú principal, situado arriba, al comienzo de la página. Especialmente nuevas son: contactar y presentación.

Puedes consultar las mejoras que incorpora la versión 6 de Drupal [[http://drupal.org/drupal-6.0][aquí]]. Yo intentaré aprovechar: la pontencia de jQuery, la flexibilidad de CCK, la espectacularidad de presentación de contenido con Views...

...ya lo irás descubriendo en futuros artículos.

Si detectas algo que no funciona como debiera, por favor, [[/contact][házmelo saber]].

Muchas gracias.


[[https://docs.google.com/forms/d/e/1FAIpQLSeGnXB3zyaNVYcb_2EoO8C5HRc6Emx-2rv2QS6OWNFz1yYSBQ/viewform?usp=pp_url&entry.55081144=Upgrade%20a%20Drupal%206][Dejar comentario]].

