#+title: Los Hijos
#+date: <2010-11-17 07:35>
#+author: Godofredo Fdez.
#+description: Quiero dedicar este poema, leído y sentido del libro que me acompaña estos días, a mis padres, porque estoy seguro que ellos han sentido la belleza que derrama, con su extrema sencillez, mientras nos criaban, y nos dejaban marchar, a mi hermana y a mí. Los hijos Por favor, no hagan ruido en la tranquilidad de este poema escrito con la mano del que cierra la puerta al apagar la luz. Mis tres hijos acaban de dormirse. Necesito el silencio para pensar en ellos. Colores indelebles en un lápiz de trazado infantil, vuelven a dibujar
#+filetags: Libros
#+options: _:nil
#+nid: 377

Quiero dedicar este poema, leído y sentido del libro que me acompaña estos días, a mis padres, porque estoy seguro que ellos han sentido la belleza que derrama, con su extrema sencillez, mientras nos criaban, y nos dejaban marchar, a mi hermana y a mí.

*Los hijos*
Por favor, no hagan ruido
en la tranquilidad de este poema
escrito con la mano
del que cierra la puerta al apagar la luz.
Mis tres hijos acaban de dormirse.
Necesito el silencio para pensar en ellos.

Colores indelebles en un lápiz
de trazado infantil,
vuelven a dibujar
-pero esta vez en serio-
un árbol, una casa, la memoria
de una luz encendida
con sabor a diciembre,
los cristales del miedo
y la ilusión del porvenir
bajo el sol de los días laborables.

Un hijo es el segundo país donde nacemos.
Con su falta de edad nos hace cumplir años
y nos devuelve
al mundo del reloj,
a las llamadas telefónicas
que son una raíz
en la orilla del tiempo.
Un hijo nos enseña a preguntar
con voz de agua
la verdad decisiva de la tierra.
Ser como juncos, y en amor flexibles,
no asegura respuestas
ni confirma el reposo.

Elisa, Irene, Mauro,
cada cual con su puerto y con su lluvia,
luces cambiantes en el mismo río.
Nadie comente, por favor,
que acabo de escribirles un poema.
Los hijos crecen con espinas.
Nunca sé imaginar
lo que pueden decir de lo que digo,
lo que pueden pensar de lo que pienso,
lo que pueden hacer con lo que hago.

Del libro "Vista Cansada" de Luis García Montero. Colección Palabra de Honor. Visor Poesía. 2ª Edición, marzo de 2008.


[[https://docs.google.com/forms/d/e/1FAIpQLSeGnXB3zyaNVYcb_2EoO8C5HRc6Emx-2rv2QS6OWNFz1yYSBQ/viewform?usp=pp_url&entry.55081144=Los%20Hijos][Dejar comentario]].

