#+title: El principal mal de aquí y ahora
#+date: <2010-10-12 21:35>
#+author: Godofredo Fdez.
#+description: Aprovechando el tiempo libre de estos días he hecho algo que venía deseando: he vuelto a ver "La lista de Schindler", y he visto por primera vez "Persépolis".…
#+filetags: ochentaveinte Pensamiento
#+options: _:nil
#+nid: 371

Aprovechando el tiempo libre de estos días he hecho algo que venía deseando: he vuelto a ver "La lista de Schindler", y he visto por primera vez "Persépolis". Os recomiendo ambas películas, pertenecen a ese tipo de cine que te ayuda a algo más que a pasar un rato: te hace pensar.

Y quizá por eso, por lo que ocurrió el día 29 de septiembre (convocatoria de huelga general) y porque hace tiempo que lo vengo "cociendo", me he decidido a dejar aquí una frase: *el principal mal de aquí y ahora es que no se valora lo que se tiene*. Se puede decir de otras muchas formas: no defendemos lo conquistado por otras generaciones, nos cargamos las instituciones como si fueran papeleras, y las papeleras como si no fueran de nadie. No respetamos el conocimiento que atesoran las personas mayores, ni a las propias personas. Y nos sentimos poseedores de toda la verdad, siendo lo único que cuenta el yo, lo que nos afecta y cómo yo quiero que me afecte. Todos los demás están ahí para servirnos. A ellos no les afecta nada, ni siquiera nuestras acciones. Lo peor es que esto no lo piensan sólo personas individuales esporádicas, pertenecientes a distintas clases sociales, con estudios y sin ellos, con mayor sensibilidad artística y sin ella... lo piensan y actúan así hasta las instituciones. ¡Alucinante pero cierto!

En próximos artículos iré haciendo hincapié en este mensaje, demostrándolo con ejemplos del día a día. Hoy sólo lo enfatizaré haciendo unas cuantas preguntas: ¿quién y cómo se conquistaron los derechos sociales de los que disponemos nosotros? ¿Qué llevó a países “normalizados” socialmente a ser regímenes absolutistas donde se violaban todos los derechos, donde la vida de una persona no valía nada? ¿Qué extraña confluencia de causas provoca que la humanidad deambule en precario por la selva más salvaje?

Esta es una de las pocas cosas que tengo claras en esta vida: no se valora lo que se tiene y se deja perder por acciones que lo dilapidan y omisiones que las consienten.

¿Utopías?


[[https://docs.google.com/forms/d/e/1FAIpQLSeGnXB3zyaNVYcb_2EoO8C5HRc6Emx-2rv2QS6OWNFz1yYSBQ/viewform?usp=pp_url&entry.55081144=El%20principal%20mal%20de%20aqu%C3%AD%20y%20ahora][Dejar comentario]].

