#+title: Botnets y medios de comunicación
#+date: <2010-04-04 20:44>
#+author: Godofredo Fdez.
#+description: A continuación os dejo el artículo número 5 que, continuando mi línea de colaboración, he publicado en el blog del Colegio Oficial de Ingenieros de…
#+filetags: COITAOC LinkedIn Seguridad
#+options: _:nil
#+nid: 351

A continuación os dejo el artículo número 5 que, continuando mi línea de colaboración, he publicado en el [[http://blog.coitaoc.org/][blog del Colegio Oficial de Ingenieros de Telecomunicación de Andalucía Occidental y Ceuta]]. Divulgad que algo queda ;-).

Este mes de marzo ha saltado la noticia de la desactivación de la “Red Mariposa” que, desde España, controlaba millones de ordenadores esparcidos por todo el mundo. Aquí podéis leerla en tres medios distintos: [[http://www.elmundo.es/elmundo/2010/03/09/navegante/1268151520.html][1]], [[http://www.google.com/hostednews/epa/article/ALeqM5iRnXGn7g8LfAV_sXa5EAGmH6SUAQ][2]] y [[http://elpais.com/articulo/20100302elpeputec_8/Tes][3]]. Y como casi siempre, después de leer esto queda una sensación que podríamos describir como: “mucho ruido y pocas nueces”, que equivale a: “mucha alarma y poca formación”. Pues, ¿en qué consisten este tipo de redes conocidas como botnets? ¿Por qué se expanden? ¿Cómo operan? Y lo que es más importante, ¿cómo podemos intentar no caer en sus pegajosos hilos-trampa?
“Bot” es una abreviación de “robot”. En este contexto un bot es un tipo de programa que, con malos fines, es instalado en un ordenador de forma “silenciosa”, pasando desapercibido a su propietario, siendo controlado en remoto por su dueño, conocido como “Bot Master”. Este tipo de programas suelen tener la capacidad de tomar el control completo del ordenador donde se instalan y de su funcionamiento en Internet, pero, al contrario de otro tipo de “malware”, su principal característica es no levantar sospechas. Pretenden así extenderse en el tiempo, despertando sólo cuando se le ordena, logrando formar verdaderos ejércitos denominados “Botnets”, redes de robots, uniéndose a gran cantidad de semejantes. Ejércitos dispuestos a lanzarse sobre el objetivo dictado por su “Bot Master” con tan sólo recibir la orden apropiada.

¿Qué buscan los “Bot Master” con estas “botnets”? La respuesta es cada vez más fácil: rentabilidad. Los “Bot Master” alquilan este tipo de redes a todo aquel que quiere hacer uso del gran potencial distribuido que brindan: spammers, scammers, phishers, grupos terroristas, etc. Presumen de su robustez y efectividad: ataques lanzados desde todas estas máquinas colonizadas consiguen ser más difícil de evitar que un ataque lanzado desde la propia máquina del “Bot Master”.

Sus principales vías de propagación son las habituales: correos electrónicos y redes de mensajería instantánea (ofreciendo increíbles videos o programas antivirus gratuitos que no hacen más que esconder bajo el plugin que falta para ver el video, en el primer caso, o bajo el falso antivirus, en el segundo, el verdadero software robot), páginas web especialmente diseñadas para ejecutar el código de instalación de dicho software en nuestra máquina con tan sólo ser visitadas con un navegador vulnerable y sin nosotros ser conscientes, redes peer-to-peer que ofrecen gratuidad con peligro, distribución de software por medio de redes sociales tras la “ingeniería social” correspondiente, etc.

¿Cómo funcionan? Una vez instalado el software en nuestro ordenador abrirá una conexión con algún servicio ofrecido desde Internet público: suscripción a grupos de noticias o a canales de chat (IRC), abriendo conexiones a redes peer-to-peer, etc., o privado: simplemente conectándose al servicio especialmente diseñado y alojado en su “propio servidor”. A través de esta conexión inicial el bot es capaz de recibir órdenes, actualizarse, e incluso desinstalar otros bots alojados en nuestra máquina o convivir con ellos.

Todos nos deberíamos hacer estas preguntas: ¿formo parte de una botnet? ¿Qué puedo hacer para evitarlo? Los consejos son los ya conocidos y poco practicados: no trabajar habitualmente en nuestro sistema operativo con una cuenta de administrador, interesarnos por la seguridad de nuestra máquina y [[http://www.hispasec.com/rss/unaaldia.xml][permanecer informados]] sobre la evolución de las amenazas, mantener actualizado nuestro antivirus, instalar un buen cortafuegos que inspeccione y filtre todas las conexiones salientes que se produzcan sin nuestro consentimiento (evitando que el bot “llame a casa” para ponerse en contacto con su dueño), dejar el ordenador encendido sin ningún programa que haga uso de Internet y observar la actividad de nuestra conexión (hay [[http://www.softonic.com/windows/medidores-de-trafico-opinion][programas]] que ayudan a monitorizar la actividad de red), junto con lo anterior, acudir a la línea de comandos y al viejo amigo “netstat” ;-) si observamos actividad sospechosa. Además, podemos complementar todo esto con herramientas gratuitas de “escaneo desde la nube” como [[http://www.pandasecurity.com/activescan/index/][esta]], esta [[http://free.antivirus.com/rubotted/][otra]], y muchas más.

Salud, y evitad caer en las teledirigidas telarañas.


[[https://docs.google.com/forms/d/e/1FAIpQLSeGnXB3zyaNVYcb_2EoO8C5HRc6Emx-2rv2QS6OWNFz1yYSBQ/viewform?usp=pp_url&entry.55081144=Botnets%20y%20medios%20de%20comunicaci%C3%B3n][Dejar comentario]].

