#+title: Avast antivirus en GNU/Linux
#+date: <2010-12-05 20:19>
#+author: Godofredo Fdez.
#+description: Desde hace tiempo todo lo que descargo de Internet lo hago en una máquina GNU/Linux. La resistencia de este sistema operativo, hoy por hoy, frente a virus es mucho mayor que la de un windows. Así, descargar en un GNU/Linux e intentar chequear lo descargado sobre este sistema, antes de sacarlo a una "caja windows", es bastante saludable.
#+filetags: GNU/Linux LinkedIn Seguridad Software
#+options: _:nil
#+nid: 389

Desde hace tiempo todo lo que descargo de Internet lo hago en una máquina GNU/Linux. La resistencia de este sistema operativo, hoy por hoy, frente a virus es mucho mayor que la de un windows. Así, descargar en un GNU/Linux e intentar chequear lo descargado sobre este sistema, antes de sacarlo a una "caja windows", es bastante saludable.

Basta una [[http://www.google.es/search?q=free+antivirus+for+linux&ie=utf-8&oe=utf-8&aq=t&rls=org.mozilla:es-ES:official&client=firefox-a][búsqueda en google]] para encontrar varios antivirus gratuitos para GNU/Linux. Yo me he inclinado por [[http://www.avast.com/linux-home-edition#tab1][Avast]], pues su uso es bastante simple y no carga ningún demonio en la máquina, por lo que no hace que esta vaya más lenta. Esto nos obliga a hacer "escaneos" bajo demanda pues no hay módulo residente. Es justo lo que necesitaba...

Y lo simple si funciona, dos veces bueno. }:)

Descargar versión desde aquí:

#+begin_example

[19:26:47(godo@surco)~/temp]> wget http://files.avast.com/files/linux/avast4workstation_1.3.0-2_i386.deb
--2010-12-05 19:46:52--  http://files.avast.com/files/linux/avast4workstation_1.3.0-2_i386.deb
Resolviendo files.avast.com... 67.228.147.162, 74.55.40.226, 74.55.48.42, ...
Connecting to files.avast.com|67.228.147.162|:80... conectado.
Petición HTTP enviada, esperando respuesta... 302 Found
Localización: http://download834.avast.com/files/linux/avast4workstation_1.3.0-2_i386.deb [siguiendo]
--2010-12-05 19:46:52--  http://download834.avast.com/files/linux/avast4workstation_1.3.0-2_i386.deb
Resolviendo download834.avast.com... 174.120.185.10
Connecting to download834.avast.com|174.120.185.10|:80... conectado.
Petición HTTP enviada, esperando respuesta... 200 OK
Longitud: 29093380 (28M) [text/plain]
Saving to: `avast4workstation_1.3.0-2_i386.deb'

100%[===============================================================================================================================>] 29.093.380   543K/s   in 51s

2010-12-05 19:47:44 (553 KB/s) - `avast4workstation_1.3.0-2_i386.deb' saved [29093380/29093380]

[19:27:44(godo@surco)~/temp]>

#+end_example

Actuando como "root", instalar así:

#+begin_example

[19:34:11(root@surco)~]> dpkg -i avast4workstation_1.3.0-2_i386.deb

#+end_example

Al finalizar la instalación os pedirá que vayáis a una URL de avast y os registréis, gratuitamente, para obtener una licencia, la cual tenéis que teclear.

Comandos disponibles:

#+begin_example

[19:39:35(root@surco)/home/godo/temp]> avast
avast         avastgui      avast-update

#+end_example

Scripts útiles para ser ejecutados al inicio:
Actualización:

#+begin_example

[19:42:50(godo@surco)~/bin]> more avast-get-update
#!/bin/bash

# Hacemos ping a una dirección IP pública
# security.debian.org
/bin/ping -c 5 -W 1 212.211.132.32

# Informamos y ejecutamos "apt-get update"
echo "Actualizando las firmas de virus... " > /tmp/avast-update
/bin/date >> /tmp/avast-update
/usr/bin/avast-update && /usr/bin/avast -V >> /tmp/avast-update
echo "Fin de la actualizacion" >> /tmp/avast-update
/bin/date >> /tmp/avast-update

#
# FIN del script.
#
[19:42:55(godo@surco)~/bin]>

#+end_example

Escaneo de un directorio:

#+begin_example

[19:42:48(godo@surco)~/bin]> more avast-scan
#!/bin/bash

# Esperamos 5 minutos -> 5 * 60 = 300
ping -c 300 127.0.0.1

# Escaneamos el directorio de descargas
echo "Escaneando directorio de descargas " > /tmp/avast-scan.txt
/bin/date >> /tmp/avast-scan.txt
/usr/bin/avast -a -r /tmp/avast-scan.txt /mnt/vm/aa-almacen/*
echo "Enviando mail..."
/usr/bin/mail -s "Escaneo antivirus del directorio de descargas" g...@gmail.com m...@gmail.com  < /tmp/avast-scan
.txt
echo "Mail enviado."

#
# FIN del script.
#

#+end_example

Y eso es todo. A disfrutar de un mundo un poco más ¿seguro? ;-)


[[https://docs.google.com/forms/d/e/1FAIpQLSeGnXB3zyaNVYcb_2EoO8C5HRc6Emx-2rv2QS6OWNFz1yYSBQ/viewform?usp=pp_url&entry.55081144=Avast%20antivirus%20en%20GNU%2FLinux][Dejar comentario]].

** Comentarios

*** can not initialize avast! engine (Godo 16/01/2011 - 14:04)
Tras la última actualización avast lanza este mensaje al intentar ejecutarlo:

#+BEGIN_EXAMPLE
  avast: can not initialize avast! engine: Argumento inválido
#+END_EXAMPLE

La solución para la sesión actual es hacer esto como root:

#+BEGIN_EXAMPLE
  sysctl -w kernel.shmmax=128000000
#+END_EXAMPLE

Y la definitiva es agregar esta línea al fichero /etc/sysctl.conf

#+BEGIN_EXAMPLE
  kernel.shmmax=128000000
#+END_EXAMPLE

*** Gracias por tu post me fue de (DanySam 27/09/2011 - 03:19)
Gracias por tu post me fue de mucha ayuda
