#+title: andLinux (II)
#+date: <2011-04-01 22:23>
#+author: Godofredo Fdez.
#+description: INSTALACIÓN Recomiendo elegir la compartición de ficheros entre Windows y andLinux mediante Cofs... es simple y funciona. Basta con seleccionar la carpeta que quieres compartir de windows para que aparezca enlazada en la carpeta windows que se crea por defecto en tu cuenta de usuario "andLinux". CONFIGURACIÓN godo@andLinux:~$ sudo su [sudo] password for godo: [root@andLinux default]# locale-gen es_ES.UTF-8 Generating locales... es_ES.UTF-8... up-to-date Generation complete. [root@andLinux default]# pwd /etc/default
#+filetags: GNU/Linux Software
#+options: _:nil
#+nid: 383

*INSTALACIÓN*

Recomiendo elegir la compartición de ficheros entre Windows y andLinux
mediante Cofs... es simple y funciona. Basta con seleccionar la carpeta que
quieres compartir de windows para que aparezca enlazada en la carpeta
windows que se crea por defecto en tu cuenta de usuario "andLinux".

*CONFIGURACIÓN*

#+begin_example

godo@andLinux:~$ sudo su
[sudo] password for godo: 

[root@andLinux default]# locale-gen es_ES.UTF-8
Generating locales...
  es_ES.UTF-8... up-to-date
Generation complete.

[root@andLinux default]# pwd
/etc/default

[root@andLinux default]# more locale
#  File generated by update-locale
LANG=es_ES.UTF-8
LANGUAGE=es_ES.UTF-8
LC_CTYPE="es_ES.UTF-8"
LC_NUMERIC="es_ES.UTF-8"
LC_TIME="es_ES.UTF-8"
LC_COLLATE="es_ES.UTF-8"
LC_MONETARY="es_ES.UTF-8"
LC_MESSAGES="es_ES.UTF-8"
LC_PAPER="es_ES.UTF-8"
LC_NAME="es_ES.UTF-8"
LC_ADDRESS="es_ES.UTF-8"
LC_TELEPHONE="es_ES.UTF-8"
LC_MEASUREMENT="es_ES.UTF-8"
LC_IDENTIFICATION="es_ES.UTF-8"

[root@andLinux etc]# tzselect 
Please identify a location so that time zone rules can be set correctly.
Please select a continent or ocean.
...
...
You can make this change permanent for yourself by appending the line
	TZ='Europe/Madrid'; export TZ
to the file '.profile' in your home directory; then log out and log in again.

Here is that TZ value again, this time on standard output so that you
can use the /usr/bin/tzselect command in shell scripts:
Europe/Madrid
[root@andLinux etc]# 
exit
godo@andLinux:~$ vi .profile 
godo@andLinux:~$ more .profile
# ~/.profile: executed by the command interpreter for login shells.
# This file is not read by bash(1), if ~/.bash_profile or ~/.bash_login
# exists.
# see /usr/share/doc/bash/examples/startup-files for examples.
# the files are located in the bash-doc package.

# the default umask is set in /etc/profile; for setting the umask
# for ssh logins, install and configure the libpam-umask package.
#umask 022

# if running bash
if [ -n "$BASH_VERSION" ]; then
    # include .bashrc if it exists
    if [ -f "$HOME/.bashrc" ]; then
        . "$HOME/.bashrc"
    fi
fi

# set PATH so it includes user's private bin if it exists
if [ -d "$HOME/bin" ] ; then
    PATH="$HOME/bin:$PATH"
fi

# Agregamos la zona de tiempo
TZ='Europe/Madrid'; export TZ

#+end_example

¡¡OJO!! tzselect sólo selecciona la "zona de tiempo" para la visualización de éste pero no para la hora local de la máquina. Me he dado cuenta de esto intentando ejecutar un cron y viendo que no funcionaba. Para ajustar la hora local de la máquina a la "zona horaria" correcta hay que hacer esto:

#+begin_example

[14:33:16(root@andLinux)/etc]> tz
tzconfig  tzselect
[14:33:16(root@andLinux)/etc]> tzconfig
WARNING: the tzconfig command is deprecated, please use:
 dpkg-reconfigure tzdata
[14:33:21(root@andLinux)/etc]> dpkg-reconfigure tzdata

Current default timezone: 'Europe/Madrid'
Local time is now:      jue may  5 14:33:52 CEST 2011.
Universal Time is now:  Thu May  5 12:33:52 UTC 2011.

[14:33:53(root@andLinux)/etc]>

#+end_example

ARRANCAMOS EL SISTEMA DE NUEVO...

#+begin_example

godo@andLinux:~$ sudo shutdown -r now

#+end_example

Podemos ver que acaba de arrancar haciendo doble click sobre el icono del escritorio "andLinux console" y viendo si aparece ya el prompt "andLinux login: ".

*INSTALANDO MÁS APLICACIONES*

Para instalar kmymoney (gestor de finanzas personales), emacs y algunas cosillas más:

#+begin_example

[root@andLinux godo]# sudo su
[sudo] password for godo: 

[root@andLinux godo]# apt-get update
[root@andLinux godo]# apt-get install kmymoney2 kde-i18n-es emacs22 rsync
[root@andLinux godo]# apt-get clean

#+end_example

ACCEDIENDO AL SISTEMA DE FICHEROS DE NUESTRA MÁQUINA WINDOWS

Podemos ver a continuación como hemos compartido una unidad (en mi caso la correspondiente a la letra D:\ del windows) con andLinux. A continuación muestro el fichero: "C:\Program Files\andLinux\settings.txt". Nos fijamos en la última línea. He utilizado la compartición propia de coLinux (cofs) en lugar de la que aconseja la instalación, pues el "samba" me daba problemas de acceso.

#+begin_example

mem=512
root=/dev/cobd0
kernel=vmlinux
cobd0=Drives\base.vdi
cobd1=Drives\swap.vdi
cofs31=.
eth0=slirp
eth1=tuntap,"TAP-Colinux",00:11:22:33:44:55
cofs0=D:\

#+end_example

Una vez que accedemos a nuestro terminal de andLinux veremos lo siguiente:

#+begin_example

godo@andLinux:~$ pwd
/home/godo
godo@andLinux:~$ ls -l
total 0
lrwxrwxrwx 1 root root 9 2010-11-21 12:39 windows -> /mnt/win/
godo@andLinux:~$

#+end_example

Tenemos accesible todos los contenidos de la unidad d:\ de windows a través de un enlace simbólico, llamado windows, situado en nuestro home de andLinux.

Por comodidad, he creado más enlaces simbólicos a los directorios que más utilizo en ambos mundos (windows y linux) y que residen en la partición accesible a través de la letra de unidad d:\ de windows.

Lo hago, para cada uno de ellos, así:

#+begin_example

godo@andLinux:~$ ln -s windows/home/godo/universidad/ universidad

#+end_example

Y este es el resultado:

#+begin_example

godo@andLinux:~$ ls -l
total 0
lrwxrwxrwx 1 godo godo 28 2010-11-21 14:02 articulos -> windows/home/godo/articulos/
lrwxrwxrwx 1 godo godo 22 2010-11-21 14:01 bin -> windows/home/godo/bin/
lrwxrwxrwx 1 godo godo 25 2010-11-21 14:02 sincro -> windows/home/godo/sincro/
lrwxrwxrwx 1 godo godo 30 2010-11-21 14:02 universidad -> windows/home/godo/universidad/
lrwxrwxrwx 1 root root  9 2010-11-21 12:39 windows -> /mnt/win/

#+end_example

¡¡ TODO PERFECTO !!


[[https://docs.google.com/forms/d/e/1FAIpQLSeGnXB3zyaNVYcb_2EoO8C5HRc6Emx-2rv2QS6OWNFz1yYSBQ/viewform?usp=pp_url&entry.55081144=andLinux%20%28II%29][Dejar comentario]].

** Comentarios

*** Tomo nota (jfc 02/04/2011 - 21:26)
Me apunto lo de añadir enlaces simbólicos, no sabía cómo hacerlo (uno que aún es joven en esto de unix).

Voy a probar a instalar Simple Scan con AndLinux. Tengo un escáner antiguo para el que no existen drivers en W7, intentaré hacerlo funcionar con Simple Scan, que es la herramienta que utilizo en linux. No se si lo reconocerá automáticamente... Cuando arranque W7 en el otro ordenador comento la historia.

Aunque se que no es el tema del artículo: estoy probando kmymoney, me parece bastante útil y pienso empezar a usarlo. :cool:

Un saludo.

*** Bueno... he probado con Xsane (jfc 03/04/2011 - 00:33)
Bueno... he probado con Xsane ya que Simple Scan no viene en los repositorios y este también lo uso a menudo.

No reconoce el escáner. Por otra parte, pensándolo bien, creo que es obvio. Al fin y al cabo el SO es windows, y los dispositivos los controla él. No se si de alguna forma andLinux podrá "tomar el control" de los perifericos USB.
Por ejempo VirtualBox te permite tomar el control de un dispositivo USB en una máquina virtual independientemente de si los drivers del periférico están en el SO anfitrión. Aunque esto no sea lo mismo, quizás exista la forma de que el núcleo coLinux gestione estos puertos.

Hoy me doy por vencido, tengo cosas que estudiar y sueño por recuperar, pero volveré.

*** Es lo bueno y lo malo (Godo 03/04/2011 - 10:18)
El espacio de drivers del sistema operativo lo sigue gestionando Windows. Esto suele ser una ventaja: la mayoría de dispositivos da menos problemas al ser reconocidos y gestionados por Windows que por GNU/Linux, pues hay más apoyo en drivers de los fabricantes.

Sin embargo, tú necesitas justo lo contrario. No se nada sobre si es posible o no. Lo más que te puedo decir es que has detectado la situación y que el camino que propones recorrer es el adecuado: "/No se si de alguna forma andLinux podrá "tomar el control" de los periféricos USB/". Es cierto que las soluciones clásicas de virtualización (VMware y VirtualBox) sí que lo hacen: yo gestiono mi scanner desde una máquina virtual con "VMware Player" y un WinXP, pues tampoco me lo reconoce Win7.

Ya me cuentas si lo consigues.

Muchas gracias por los comentarios y... ¡Ánimo!
