#+title: Lecturas de verano 2011: El bolígrafo de gel verde
#+date: <2011-08-28 13:16>
#+description: 
#+filetags: Libros Refinar

Mi música para este libro es "Don't live me now" de la extraordinaria banda "Supertramp", porque me desgarra tanto la fuerza de los instrumentos y el grito llorado de Roger Hodgson como lo ha hecho el libro.

#+BEGIN_HTML
<div style="position: relative; padding-bottom: 56.25%; height: 0; overflow: hidden;">
  <iframe style="position: absolute; top: 0; left: 0; width: 100%; height: 100%;" src="https://www.youtube.com/watch?v=9o4AQZ0M-vU" frameborder="0" allowfullscreen></iframe>
</div>
#+END_HTML

El libro, del que ya hablamos [[https://godest.vivencias.net/2011-05-17-el-boligrafo-de-gel-verde.html][aquí]], comienza así:

#+begin_quote
Una vida -cualquiera- se resume en una serie de acontecimientos especiales, de puntos y aparte. Puntos que, por más tiempo que transcurra, permanecen intactos en la memoria, remanentes hasta el mismo día en que nos alcanza la muerte.

...

No suelen ser hechos trascendentes, sino simples momentos tan insignificantes para cualquier otra persona como especiales para uno mismo: el primer "te quiero", la muerte de un familiar o la muerte de un ser querido, la frontera que traza el primer "usted", el temblor de piernas incontrolable tras un accidente, las noches pasadas en un hospital prometiendo cosas a un dios que después olvidas, el primer beso en los labios o el primer beso en la boca -nunca es lo mismo-, la peor discusión con tu mejor amigo, ver tempranear el sol, la cicatriz más grande del cuerpo, el brotar de una vida, las noches en casa de los abuelos, descubrir que una pesadilla ha sido una pesadilla o la primera vez que comprendes que siempre que alguien quiere comprar hay alguien que, al final, vende.
#+end_quote

Al terminar de leer ese párrafo fue la primera vez que cerré el libro y me quedé un rato pensando. La vida, ¿qué es la vida? Simplemente eso.

El libro está escrito en forma de diario y, por tanto, de forma autobiográfica: a cada fecha concreta, a cada hora de dicha fecha, le sigue un relato en primera persona del protagonista: un informático que trabaja en el departamento de desarrollo software de una empresa. Un informático que va sufriendo día tras día el ritmo infernal al que nos somete la actual sociedad de consumo.

#+begin_quote
Hace años que tuvimos que contratar a alguien que hiciera lo que nosotros no podíamos. Nos ha faltado siempre tiempo. Nos ha faltado tiempo porque hemos tenido que trabajar demasiado. Hemos tenido que trabajar tanto porque, hoy en día, para todo se necesita dinero. Dinero para mantener a un niño al que apenas veíamos; dinero para contratar a una persona que nos limpiara la casa en la que apenas estábamos; dinero para vivir una vida que no hemos disfrutado. Todo tan circular, todo tan ridículo.
#+end_quote

Un informático que, como si de una aguja más de un virtual reloj terrestre, cada día traza puntual (incluso en los retrasos, en las prisas posteriores, en los nervios, en los golpes al claxon...) todo su recorrido, de forma exacta, confundiendo lo importante con lo irrelevante, como hacemos todos más veces de las que debemos.

Un informático que se adentra en el mundo del dolor más sublime: aquel que jamás puede ser desprendido, aquel que es fruto de una pérdida irrecuperable, aquel que te deja todo un mundo plagado de emociones que mientras estaban no llegabas a apreciar con todo su sabor, con todo su significado, que incluso despreciabas por la rutina que acaba envolviéndolo todo:

#+begin_quote
Jamás podré expresar el dolor que llegué a sentir bajo aquella manta. Jamás podrá nadie comprender la dureza de la realidad en estado puro. Débil, abatido, derribado, dejé, sin oponer resistencia, que la tristeza comenzase a enraizarse en mi cuerpo. Unas raíces que, en su crecer, rozaron las partes más sensibles del recuerdo: la lucha por las sábanas en plena madrugada; las tres cucharadas de azúcar en el café; el primer beso del día bajo la puerta, antes de separarnos; el segundo al regresar a casa, de noche; el tercero, el que nos dábamos por rutina antes de cerrar los ojos; el yogur con trozos de chocolate; el disimular de unas lágrimas que le asomaban apenas aparecía una escena romántica en cualquier película; el correr por las mañanas para, de un salto, subirse en nuestra cama; su sonrisa incondicional al verme llegar por la noche; la lucha diaria para que se acabase de tragar la comida; sus primeras palabras; sus pequeños ojos mientras dormía, mientras dormían ambos...
#+end_quote

Una lectura demoledora para un mes de vacaciones. Una lectura que más de una vez me ha hecho sentir tres puñales clavados en mi pecho. Una lectura que, ¡ojalá!, haya reafirmado en mí todo aquello que de verdad importa.

Y, para aquellos que os sintáis atraídos y queráis leer el libro, no leáis el siguiente recuadro azul pues creo que en él está la clave de todo, no la trama ni el argumento del libro, sino el quid último de todas nuestras vidas de ciudad de siglo XXI de productividad entredicha de carreras de infartos y continua competición por todo:

#+begin_quote
Hay una palabra capaz de resumir todo un cambio de vida: tiempo. Tiempo para conocer nuevos lugares; tiempo para disfrutar por las mañanas de unas caricias, por las noches de unos roces más profundos. Tiempo para hablar de problemas y soluciones, para besar en cualquier parte del otro cuerpo, para aprender cosas que enseñar a los demás, para saber que los niños siempre desean jugar con sus padres, para leer y disfrutar haciéndolo, para perderlo porque se tiene, para disfrutar de la soledad, para estar en compañía...

*Cuando las cosas no van como esperamos, nos empecinamos en cambiar de personajes, cuando lo único que hay que hacer es cambiar de historia*.
#+end_quote

Salud para intentar seguir viviendo.

Datos: /"El bolígrafo de gel verde" de Eloy Moreno. Espasa Narrativa. 1ª Edición: enero de 2011. 6ª Edición: febrero de 2011/.

[[https://docs.google.com/forms/d/e/1FAIpQLSeGnXB3zyaNVYcb_2EoO8C5HRc6Emx-2rv2QS6OWNFz1yYSBQ/viewform?usp=pp_url&entry.55081144=Lecturas_de_verano_2011-El_boligrafo_de_gel_verde][Dejar comentario]].

** Comentarios
*** elradioplanner (no verificado Lun, 29/08/2011 - 00:02)
¿Pero te ha gustado o no? A mi no sé... tras las primeras páginas me esperaba más, la verdad. Por un lado, los libros (o pelis) que transmiten su mensaje de una forma tan directa y explícita siempre me dejan un poco frío, como que te lo ponen en bandeja y de alguna forma pierden valor (intelectual) para mí. Quiero decir, que para contar tu idea de la vida de forma literal, haz un ensayo pero no una novela.
Por otro lado, el estilo del libro también me acabó cansando un poco, siempre adelantando las consecuencias de los acontecimientos. Ese recurso puede estar bien una vez o dos, pero no con la asiduidad con la que lo utiliza el autor. No quiero destripar el final, pero también me pareció un poco hiperbólico (por el lado de la acción, no por el de los pensamientos o sentimientos del protagonista).

En fin, la temática no puede ser más actual y cotidiana, una especie de naúsea existencialista que en mayor o menor medida todos sentimos, y el libro es entretenido, con algunos pasajes memorables y otros agobiantes, pero para mí le falta... ¿sutileza?

*** Godofredo Fdez. (Jue, 22/09/2011 - 21:23)
A nadie le gusta sufrir, ¿o sí?
Estuve pensando cómo transmitir la respuesta a tu pregunta. Es complicado responder con este tipo de historia entre manos. He sufrido mucho. Eso no me gusta (disto mucho del masoquismo) aunque sepa que exista el dolor y, en ocasiones, resulte inevitable. Creo que el libro puede ayudarnos a despertar lo cotidiano y, aunque creamos que no, este tipo de cosas nos van calando y nos ayudan, confío, a ser mejores con nosotros mismos y con los demás. Por eso, sí que le doy su valor. Entiendo que es difícil de recomendar un libro así... es como desearle a tus amigos que sufran pero por otro lado que ¿aprendan/valoren?.

Respecto al estilo creo que en parte comparto tus comentarios y en parte no. La novela se ha caracterizado por ser un género donde ha cabido todo: desde la realista del siglo XIX a la "mágica" de Isabel Allende... por tanto una novela con estilo autobiográfico, de diario íntimo, no tiene por qué no tener cabida. Si fuese más sutil creo que sería otra novela. Sí que puedo estar de acuerdo con tu opinión respecto a los continuos "ejercicios de anticipación", de hecho, muchos de ellos para mí han sido innecesarios porque mi propia mente ya los imaginaba... creo que ahí sí que hay que darle más libertad al lector y "abusar" menos de ellos.

El final me gustó... seguir hablando de él lo destriparía, pero tú, que me conoces, sabes a lo que me refiero.

Muchas gracias por compartir tu comentario y tu ¡RT! }:)

*** Godesa (no verificado Lun, 29/08/2011 - 02:05)
Un post con una enorme carga emocional, no se si paralela al libro o amplificada por tu propio esqueleto interno y una banda sonora desesperada elejida para clavarse más aún.

*** Godofredo Fdez. (Lun, 29/08/2011 - 14:22)
Sobre la carga emocional, qué puedo decirte, de las dos cosas seguro que hay.

De la banda sonora no la elegí yo, fue ella a mí, fue ella la que eligió al libro ;-) Pero sí, ese tema es impresionante, desde el arranque hasta la finalización. Es de los que se escuchan muchas veces y en cada una de ellas podrías destacar un detalle: el piano, un golpe de batería, el saxo, la voz...

Gracias por tus líneas...
