#+title: Parecidos
#+date: <2011-03-17 07:27>
#+author: Godofredo Fdez.
#+description: Del paso del tiempo, de las batallas vividas, de los recuerdos, de lo perdido... arañazos en el alma. Parecidos Pura vida los ojos, y la piel una templada…
#+filetags: Libros
#+options: _:nil
#+nid: 381

Del paso del tiempo, de las batallas vividas, de los recuerdos, de lo perdido... arañazos en el alma.

*Parecidos*
Pura vida los ojos, y la piel
una templada sucesión del tiempo.
Se parecen los árboles al bosque
como tu cuerpo se parece a ti.

La mañana se ha ido entre las hojas.
Están hechas de luz
verde, rojiza, fatigada en oro,
según las estaciones y las horas del día.
Su color es un modo de lealtad,
la forma de vivir entre los suyos.

Reconozco mis años en tu cara,
el poder de mirarme
con una historia dentro de tus ojos,
la experiencia del mundo
que conservan los gestos,
mientras los años borran
las fechas en los árboles.

El destino nos busca con recuerdos
que a veces huyen de su rostro
como si fuese un nido sin canciones.
Más que la edad,
hay caras que reflejan
todo lo que perdieron.
Confunden la sequía y el otoño
en una helada de renuncias.

Pero tu cuerpo se parece a ti,
a la mujer que tiene
una ciudad, un mundo, un sol de guante negro,
una ambición en armas,
una historia vivida
con sus cuentas pendientes,
un atado de sobres
y un amor
que no se cansa de mirarla.

Del libro "Vista Cansada" de Luis García Montero. Colección Palabra de Honor. Visor Poesía. 2ª Edición, marzo de 2008.


[[https://docs.google.com/forms/d/e/1FAIpQLSeGnXB3zyaNVYcb_2EoO8C5HRc6Emx-2rv2QS6OWNFz1yYSBQ/viewform?usp=pp_url&entry.55081144=Parecidos][Dejar comentario]].

