#+title: La crisis en España
#+date: <2011-06-18 21:29>
#+author: Godofredo Fdez.
#+description: Una buena explicación en tan solo 6 minutos y 45 segundos.
#+filetags: Pensamiento
#+options: _:nil
#+nid: 415

Una buena explicación en tan solo 6 minutos y 45 segundos.

Extraña casualidad porque yo siempre lo he explicado de forma parecida. Estoy de acuerdo, claro. ¿Y tú?

Y se abren muchas otras preguntas: ¿somos conscientes del problema? ¿es la mejor solución competir a "lo chino" (tirando de la esclavitud de los trabajadores) o a "lo alemán" (creando valor y exportándolo)? Supongo que todos nos decantamos por lo segundo pero, ¿tenemos mimbres para conseguirlo? ¿podemos de verdad competir en conocimiento con la preparación obtenida en nuestro sistema educativo? ¿qué ejemplos tenemos? ¿cuánto contribuyen al PIB? ¿Se está dedicando el esfuerzo necesario desde la administración hacia la creación de empresas que aporten valor? ¿tenemos una administración sobre dimensionada que consume gran parte de lo que recauda? ¿cómo se reparte el dinero de los impuestos - la tarta-? ¿Habrá mejores formas de hacerlo? ¿Qué pasaría si la administración redujera el gasto e inversión en si misma y destinara mayores cantidades, aumentara el esfuerzo, a incentivar la competitividad de empresas verdaderamente solventes en el terreno técnico, en la investigación, en la innovación? Si de cada 20 [[http://es.wikipedia.org/wiki/Compa%C3%B1%C3%ADa_startup][startups]] triunfa 1, ¿cuánto tendríamos que empujar en España en ese sentido para crear una empresa que acabara empleándonos? ¿Hay mimbres para conseguirlo? Si el sistema educativo no nos los ofrece, ¿cuánto tiempo vamos a tardar en invertir la tendencia?...

Interesante debate del que no veréis a hablar a muchos especialistas en televisión... pan y circo vende más y da menos problemas.

Suerte.


[[https://docs.google.com/forms/d/e/1FAIpQLSeGnXB3zyaNVYcb_2EoO8C5HRc6Emx-2rv2QS6OWNFz1yYSBQ/viewform?usp=pp_url&entry.55081144=La%20crisis%20en%20Espa%C3%B1a][Dejar comentario]].

** Comentarios

*** Muy "divertido" el vídeo, (Elradioplanner 18/07/2011 - 09:03)
Muy "divertido" el vídeo, pero sigo pensando que es tendencioso: ¿toda la culpa es de Aznar? ¿acaso Zapatero ha hecho una buena gestión de la crisis? ¿el pobrecito no ha tenido culpa de ná?

*** A mi modesto entender (Godo 18/07/2011 - 09:52)
Como tú apuntas, Zapatero es corresponsable al haber querido seguir jugando a la "champion league" (¿recuerdas?) creyendo que todo iba a seguir así. Luego, dicen (porque yo no lo veo) quiso reaccionar pero no ha sabido dar respuesta a muchas, por no decir todas, de las preguntas que señalaba en el texto que agregué tras el vídeo.

Los poderosos han de serlo por demostrar la capacidad de afrontar este tipo de situaciones, por tanto, como decía Anguita, por acción u omisión, culpa sí que tiene.

Un placer leerte por aquí.
