#+title: Sobre redes sociales, Google+ y falsas sensaciones de seguridad
#+date: <2011-08-13 13:57>
#+author: Godofredo Fdez.
#+description: Cada día son más frecuentes los indicios que en todos los ámbitos (personal/profesional, de compras/de viajes, etc.) vamos recogiendo sobre el uso y la…
#+filetags: COITAOC LinkedIn Pensamiento Seguridad
#+options: _:nil
#+nid: 426

Cada día son más frecuentes los indicios que en todos los ámbitos (personal/profesional, de compras/de viajes, etc.) vamos recogiendo sobre el uso y la importancia que el concepto de "red" va tomando en la actualidad. Parece que todo el mundo ha descubierto a la vez que el mantener el contacto con las personas que te interesan es beneficioso. A mi me gusta digerir y explicar el concepto de red en el sentido mas amplio de su palabra: no estamos hablando de redes de ordenadores (LAN, WAN, Wireless, etc.), ni de redes sociales por Internet (Facebook sigue siendo, por ahora, su máximo exponente)... quizá lo que más se le parece a la idea que quiero transmitir sea simple y llanamente una red de contactos, en su versión más genérica, que se soporta en diferentes "tecnologías" (desde simples llamadas de vez en cuando, cañas de cerveza dialogadas, hasta las diferentes implementaciones que se han ido creando en Internet) y que acaba especializándose, o fragmentándose en diferentes subconjuntos, según los intereses compartidos entre cada uno. Y así surge una red de amigos, una red de profesionales, una red de amigos que juegan al fútbol los jueves, una red de cervecitas los viernes después de trabajar... o una red de frikis del Linux ;-).

Una vez entendida y formada la red, el estudio de este tipo de "asociaciones" entre personas está vertiendo mucha literatura y es un campo de investigación multidisciplinar en la actualidad: identificación de roles (líderes -con mayor influencia sobre los demás- y seguidores), estudio del crecimiento y decrecimiento, cómo se organizan, cómo se interrelacionan (tanto internamente -los individuos que las componen- como externamente -entre ellas-), qué hace que un determinado mensaje cale y se propague con más o menos virulencia, etc.

Tanto es así que algunas compañías están destinando cada vez mayor presupuesto, y por tanto mayor esfuerzo, en utilizarlas como vehículos de selección de personal, lanzamiento de productos, reputación de imagen corporativa... o simplemente como un canal de "ida y vuelta" que les permite pulsar a sus clientes y recuperar su opinión, con la potencia que esto tiene para realizar, por ejemplo, estudios de mercado en sus diferentes formas o soporte a incidencias. Si me animo, escribiré un artículo sobre cada uno de estos usos.

Aunque este concepto de "interrelación" ha existido en diferentes formas durante toda la vida de la humanidad, parece que ha sido ayer mismo, con el lanzamiento sobre Internet: Facebook, Tuenti, Twitter, etc., cuando ha surgido. Estas diferentes implementaciones permitían, en mayor o menor grado, crear tu grupo de contactos online y compartir con ellos pensamientos/opiniones, fotos, localización, etc. Creo que la principal ventaja apreciada ha sido su potencia para mantener un nivel de interrelación muy rico, en vivo y en directo. *Y estoy seguro que su mayor desventaja ha sido su escaso control sobre lo compartido y la privacidad, por ende, del que lo compartía o formaba parte de él*(una foto indiscreta, por reflejar un ejemplo simple).

En este contexto nace Google+ (28 de junio de 2011). La enésima apuesta de Google por participar en este "juego". Esta vez parece que le va a ir mejor que las anteriores. *A mi juicio la idea que la sustenta, los círculos, es tan potente como falsa*. Me explico: la filosofía con la que han ido naciendo las implementaciones anteriores era que hacía falta una relación de amistad, aceptada recíprocamente por dos individuos, para formar parte cada uno de ellos de la red del otro. Tras este paso inicial, todo lo compartido en tu red era visible por todos tus amigos, incluso por los amigos de tus amigos. Esto dio lugar a problemas de privacidad -sensación de pérdida de control sobre lo que se publicaba-. Luego se han ido refinando las posibilidades hasta permitir fijar permisos sobre lo que se comparte: accesible a todo el mundo, compartir sólo con alguien determinado, y todas las posibilidades intermedias. Pero la usabilidad de esto, al no haber nacido con la concepción inicial de las plataformas, ha sido difícil de entender por muchos usuarios. Google+ nace incorporando esto en su ADN, como podéis ver en el vídeo que dejo abajo (que no es mío, su autor aparece justo al principio).

Y si tras ver el vídeo pensáis que todos los problemas de privacidad han sido resueltos, *¡os equivocáis!*

Os aconsejo que penséis en los círculos como una herramienta que te da parte de control sobre con quién compartes y hasta dónde compartes (esto no se ve en el vídeo pero Google+ permite fijar la prohibición de que alguien con quien tú compartes, a su vez, también comparta lo que recibe de ti). Perfecto, ¿verdad?

Pues no, *¡SIEMPRE ES POSIBLE HACER UNA CAPTURA DE PANTALLA!*

Es verdad que si compartís una foto de vuestro bebe con vuestro círculo "familiar", presuponiendo que en él estén las personas bien seleccionadas, es difícil (que no imposible -fallos de seguridad siempre puede haber-) pensar que dicha foto va a acabar en manos de un pedófilo (por ser brusco e impactar)... pero, ¿qué pasa si esa misma foto la compartís con un círculo de "amigos" y alguien no lo es tanto, o deja de serlo, o le "hackean" su pc, su cuenta...

*La idea de los círculos me parece genial pero hay que tratarla con mucho cuidado y responsabilidad*.

Mi consejo: pensad que todo lo que compartís por Internet corre el riesgo de acabar siendo público antes o después, contad hasta diez y actuad con el mayor cuidado posible.

Tras la técnica siempre hay un ser humano. Google+ aporta lo mejor de la técnica hasta el momento. Las intenciones, buenas o malas, sólo son controlables por el ser humano que está detrás.

Y tras esto, ¿nos circulamos? }:-)


[[https://docs.google.com/forms/d/e/1FAIpQLSeGnXB3zyaNVYcb_2EoO8C5HRc6Emx-2rv2QS6OWNFz1yYSBQ/viewform?usp=pp_url&entry.55081144=Sobre%20redes%20sociales%2C%20Google%2B%20y%20falsas%20sensaciones%20de%20seguridad][Dejar comentario]].

