#+title: El bolígrafo de gel verde
#+date: <2011-05-17 23:53>
#+author: Godofredo Fdez.
#+description: Hoy, mi querido compañero SanNico, me ha regalado un buen momento. Ha compartido conmigo uno de los personajes del libro que se está leyendo. El libro es el…
#+filetags: Libros
#+options: _:nil
#+nid: 410

Hoy, mi querido compañero SanNico, me ha regalado un buen momento. Ha compartido conmigo uno de los personajes del libro que se está leyendo. El libro es el que figura en el título de este artículo. Su autor: Eloy Moreno.

En la página 101 del libro aparece el siguiente párrafo:

No le llamamos Godo porque tenga unos kilos de más o una 'r' de menos, no, eso es una pequeña broma suya. La razón es que Godofredo es un nombre muy 'fredo', como dice él con su permanente sentido del humor. Godo es capaz de jugar con las palabras como quien juega con los dedos. Tiene una de las mentes más creativas que he conocido, es una persona en el lugar equivocado. Godo podría ser escritor, escultor, cantante, en fin... artista de cualquier tipo, pero ha estado desaprovechando su vida entre líneas y líneas de código.

¿Habrá estado Eloy (a quien no conozco de nada, creo) observándome por una mirilla? ¿Estará el personaje basado en un "caso real"? ¿Seré yo?
No, hay cualidades que no tengo, por desgracia. Y aunque refleja algunas cosas que me suelo preguntar de vez en cuando, creo que la respuesta no es exactamente la misma. }:)

Un libro más a la cola de lectura.

Datos: "El bolígrafo de gel verde" de Eloy Moreno. Espasa Narrativa. 1ª Edición: enero de 2011. 6ª Edición: febrero de 2011.

Actualizado: posteriormente a escribir este post, leí el libro. Puedes encontrar una entrada más extensa en este mismo blog, [[http://godest.vivencias.net/content/lecturas-de-verano-2011-el-bol%C3%ADgrafo-de-gel-verde][aquí]].\\


[[https://docs.google.com/forms/d/e/1FAIpQLSeGnXB3zyaNVYcb_2EoO8C5HRc6Emx-2rv2QS6OWNFz1yYSBQ/viewform?usp=pp_url&entry.55081144=El%20bol%C3%ADgrafo%20de%20gel%20verde][Dejar comentario]].

** Comentarios

*** Coincidencias (jfc 26/05/2011 - 09:30)
Jejeje... Me parece muy muy curioso...quizás el autor te conozca aunque tu a èl no. Quizás un antiguo alumno, o algun compañero...

*** Que bueno... Esta mañana (Anonymous 27/05/2011 - 20:30)
Que bueno... Esta mañana estaba pensando precisamente en este libro. Ahora fijo que me lo pongo también en mi "cola de lecturas", sabiendo que aparece tu alter ego.
