#+title: Vista cansada
#+date: <2011-05-17 08:27>
#+author: Godofredo Fdez.
#+description: Hace ya tiempo que padezco este tipo de vista. Y hoy no soy tan viejo aún. O quizá sí. Vista cansada La vida no es un sueño. He comprobado el mar con sus…
#+filetags: Libros
#+options: _:nil
#+nid: 382

Hace ya tiempo que padezco este tipo de vista.

Y hoy no soy tan viejo aún. O quizá sí.

*Vista cansada*
La vida no es un sueño.

He comprobado el mar con sus cadáveres,
la existencia del sol, la piel, los fríos,
las luces con sus horas,
las puertas que los años se dejan mal cerradas.
Olvidos y recuerdos tienen los mismos ojos.

Las palabras, como un atardecer
que se confunde con la noche,
son arena que cae delante del vacío.
Nunca discute el tiempo
la consigna de musgo que recibe.
Pero pierde las llaves de sus puertas.
Ahora aprendo a vivir con la vista cansada.

Cansado estoy de verte
mundo extraño,
prestigio del dolor,
exactitud de la mentira,
corona turbia
de los estercoleros habitados.
Cansado estoy de ver las muertes humilladas
en las habitaciones del silencio.

Me duelen
los finales injustos,
que cierran nuestros ojos
porque somos cadáveres vivientes.

He comprobado el mar. La vida no es un sueño.

¡Qué lepra de banderas!
¡Qué decencia de números podridos!
¡Qué paisaje de escombros!

Pierde el tiempo sus llaves,
y yo busco mis gafas,
para seguir aquí,
en las ventanas y las mesas,
con los años abiertos
al pie de la ciudad.

Allí se reconocen,
al sur, al otro lado de esa nube,
de la torre, a la izquierda, justo allí,
las ramas de la vida, la memoria,
los pinares pacíficos,
el abrazo que pide una verdad,
el viento que levanta una alegría,
las ruinas hermosas,
la habitación serena en donde se recuerda,
con la luz apagada,
la historia libre de la dignidad.

No hablo de ilusiones,
sino de dignidad, y de mis gafas,
cristales trabajados que me ayudan
a comprobar el precio de las cosas,
a buscar los teléfonos que quiero,
a recorrer los libros,
a mirar el reloj y los periódicos.

A estar aquí,
en una compartida soledad,
para ver lo que pasa
con nosotros.

Del libro "Vista Cansada" de Luis García Montero. Colección Palabra de Honor. Visor Poesía. 2ª Edición, marzo de 2008.


[[https://docs.google.com/forms/d/e/1FAIpQLSeGnXB3zyaNVYcb_2EoO8C5HRc6Emx-2rv2QS6OWNFz1yYSBQ/viewform?usp=pp_url&entry.55081144=Vista%20cansada][Dejar comentario]].

** Comentarios

*** Al menos seguimos viendo y (Dientitos o paquetito inquieto 17/05/2011 - 19:24)
Al menos seguimos viendo y viéndonos, que ya es mucho.
Muchas felicidades, pequeño
