#+title: andLinux (III)
#+date: <2012-05-11 07:22>
#+author: Godofredo Fdez.
#+description: Continuamos con nuestras entregas sobre andLinux. Hoy vamos a ver como se actualiza y optimiza nuestro sistema instalado. ACTUALIZACIÓN Como en cualquier sistema GNU/Linux basado en Debian, con la herramienta apt procedemos así: [root@andLinux godo]# apt-get update [root@andLinux godo]# apt-get upgrade El sistema se actualiza sin ningún problema.
#+filetags: GNU/Linux Software
#+options: _:nil
#+nid: 401

Continuamos con nuestras entregas sobre andLinux. Hoy vamos a ver como se actualiza y optimiza nuestro sistema instalado.

*ACTUALIZACIÓN*

Como en cualquier sistema GNU/Linux basado en Debian, con la herramienta /apt/ procedemos así:

#+begin_example

[root@andLinux godo]# apt-get update
[root@andLinux godo]# apt-get upgrade

#+end_example

El sistema se actualiza sin ningún problema.

No obstante, aún quedan paquetes /retenidos/. Son aquellos que necesitan de otros para actualizarse. Debian en este sentido es muy conservador: siempre que es necesario instalar software nuevo el sistema opta por dejarle decidir al usuario. Otros te inundan el disco duro de software y cuando te das cuenta no tienes espacio.

Veamos los paquetes retenidos:

#+begin_example

[root@andLinux godo]# apt-get upgrade
Leyendo lista de paquetes... Hecho
Creando árbol de dependencias
Leyendo la información de estado... Hecho
Los siguientes paquetes se han retenido:
  bind9-host firefox firefox-3.0 firefox-3.0-branding libbind9-40 libdns45 libisc45 libisccc40 libisccfg40 liblwres40
0 actualizados, 0 se instalarán, 0 para eliminar y 10 no actualizados.

#+end_example

Instalamos los dos paquetes que son programas finales, las librerías necesarias se actualizarán solas:

#+begin_example

[root@andLinux godo]# apt-get install bind9-host firefox

#+end_example

Tras la instalación podemos comprobar que nuestra distribución está actualizada al completo:

#+begin_example

[root@andLinux godo]# apt-get upgrade
Leyendo lista de paquetes... Hecho
Creando árbol de dependencias
Leyendo la información de estado... Hecho
0 actualizados, 0 se instalarán, 0 para eliminar y 0 no actualizados.
[root@andLinux godo]#

#+end_example

*ELIMINAMOS LO SOBRANTE*

Comprobamos si ha quedado alguna librería suelta que se pueda borrar. Para eso instalamos la utilidad /deborphan/:

#+begin_example

[root@andLinux godo]# apt-get install deborphan
Leyendo lista de paquetes... Hecho
Creando árbol de dependencias
Leyendo la información de estado... Hecho
Se instalaron de forma automática los siguientes paquetes y ya no son necesarios.
  xulrunner-1.9 firefox-3.0-branding
Utilice «apt-get autoremove» para eliminarlos.
Se instalarán los siguientes paquetes NUEVOS:
  deborphan
0 actualizados, 1 se instalarán, 0 para eliminar y 0 no actualizados.
Se necesita descargar 0B/81,9kB de archivos.
Se utilizarán 483kB de espacio de disco adicional después de esta operación.
Seleccionando el paquete deborphan previamente no seleccionado.
(Leyendo la base de datos ...
120392 ficheros y directorios instalados actualmente.)
Desempaquetando deborphan (de .../deborphan_1.7.27_i386.deb) ...
Procesando disparadores para man-db ...
Configurando deborphan (1.7.27) ...

[root@andLinux godo]#

#+end_example

Antes de seguir nos fijamos en que la herramienta /apt/ ya nos propone que eliminemos paquetes sobrantes:

#+begin_example

[root@andLinux godo]# apt-get autoremove

#+end_example

Ahora vamos a ver que nos dice /deborphan/ respecto a librerías huérfanas, que son aquellas que antes eran necesarias para alguna aplicación pero que ahora ya no lo son:

#+begin_example

[root@andLinux godo]# deborphan     
libdb1-compat                                  
libxml1
libperl5.10
libident
libssl0.9.7
libungif4g
cupsys-common
libgdbmg1
fileutils
shellutils
libnss3-0d
slang1a-utf8
libkcddb4
libdb4.4++
libbluetooth2
libltdl3
libopensync0
textutils
libsnmp10
libmyspell3c2
libdb4.2
libdb4.3
libdb4.4
libdb4.5
libiw29
libmaildir4
libcurl3
libgadu3
libtunepimp5
gdk-imlib1
libexiv2-4
libgpmg1
libstrigiqtdbusclient0
libdns45
libhunspell-1.1-0
libmikmod2
libdb3
librasqal0
sysvutils
libsasl7
libcupsys2
libpcap0
libxklavier11
libmeanwhile1
libdevmapper1.01
libgnutls12
libgnutls13
libgnutls11
liblaunchpad-integration0
[root@andLinux godo]#

#+end_example

Podemos eliminar todas esas librerías sin ningún problema:

#+begin_example

[root@andLinux godo]# dpkg --purge libdb1-compat libxml1 libperl5.10 libident libssl0.9.7 libungif4g cupsys-common libgdbmg1 fileutils shellutils libnss3-0d slang1a-utf8 libkcddb4 libdb4.4++ libbluetooth2 libltdl3 libopensync0 textutils libsnmp10 libmyspell3c2 libdb4.2 libdb4.3 libdb4.4 libdb4.5 libiw29 libmaildir4 libcurl3 libgadu3 libtunepimp5 gdk-imlib1 libexiv2-4 libgpmg1 libstrigiqtdbusclient0 libdns45 libhunspell-1.1-0 libmikmod2 libdb3 librasqal0 sysvutils libsasl7 libcupsys2 libpcap0 libxklavier11 libmeanwhile1 libdevmapper1.01 libgnutls12 libgnutls13 libgnutls11 liblaunchpad-integration0                                                                                                                     
(Leyendo la base de datos ... 

#+end_example

Repetimos el paso varias veces pues hay librerías que son dependencias de otras, y van quedando al descubierto conforme eliminamos éstas últimas. Descubrimos:

#+begin_example

[root@andLinux godo]# deborphan
libtasn1-2
liblzo2-2
libsnmp-base
liblzo1
libofa0
libopencdk8
libmusicbrainz4c2a
libopencdk10
[root@andLinux godo]#

#+end_example

Y purgamos:

#+begin_example

[root@andLinux godo]# dpkg --purge libtasn1-2 liblzo2-2 libsnmp-base liblzo1 libofa0 libopencdk8 libmusicbrainz4c2a libopencdk10
(Leyendo la base de datos ...
119648 ficheros y directorios instalados actualmente.)
Desinstalando libtasn1-2 ...

#+end_example

Hasta que llegamos a tener la distribución totalmente limpia de paquetes innecesarios:

#+begin_example

[root@andLinux godo]# deborphan
[root@andLinux godo]#

#+end_example

Continuará.


[[https://docs.google.com/forms/d/e/1FAIpQLSeGnXB3zyaNVYcb_2EoO8C5HRc6Emx-2rv2QS6OWNFz1yYSBQ/viewform?usp=pp_url&entry.55081144=andLinux%20%28III%29][Dejar comentario]].

