#+title: La Gestión de la Seguridad... y el Miedo
#+date: <2012-06-14 22:01>
#+author: Godofredo Fdez.
#+description: Os dejo a continuación el artículo con el que comencé mi colaboración con el blog AunCLICdelasTIC . El miedo es una de las cinco emociones básicas.…
#+filetags: LinkedIn Seguridad
#+options: _:nil
#+nid: 475

Os dejo a continuación el artículo con el que comencé mi colaboración con el blog [[http://www.aunclicdelastic.com/][AunCLICdelasTIC]].

El miedo es una de las cinco emociones básicas. Etimológicamente el término emoción significa “lo que nos hace movernos”. El miedo es procesado por una de las estructuras más antiguas del cerebro, la amígdala, que prepara al organismo de forma rápida e inconsciente para responder de la forma más eficaz posible. Así, el miedo es una adaptación evolutiva: los humanos que reaccionaron rápido a un peligro lograron sobrevivir y al reproducirse fueron contribuyendo a su propia selección natural. Por eso, la palanca del miedo es la más accionada para buscar una reacción, desde el control de un niño pequeño hasta la dominación de todo un pueblo.
No es de extrañar que *el miedo sea uno de los argumentos más frecuentemente utilizados para “motivar” la gestión de la seguridad en una organización*. Prácticamente todas las presentaciones realizadas por cualquiera de los actores del “sector” a alguno de sus clientes dedican un gran porcentaje en su inicio a mostrar las miríadas de males que acechan ahí fuera.

*Otro argumento utilizado es el cumplimiento normativo*. En España casi todas las organizaciones se ven empujadas a cumplir con la “Ley Orgánica de Protección de Datos (LOPD)” y, dependiendo del sector, con algunas más particulares, por ejemplo: los organismos públicos con el “Esquema Nacional de Seguridad”. El razonamiento positivo de este bloque debería ser el de contribuir a la difusión y aumento del uso de sistemas de información por parte del ciudadano, ganándose su confianza al saber que sus datos y los sistemas que los tratan están especialmente bien gestionados/protegidos. Sin embargo, según aprecio en mi día a día, nuestra cultura suele interpretar el ordenamiento jurídico en negativo: actuamos de acuerdo a la ley porque si no nos sancionan. Y si esto es así, el miedo vuelve a ser el principal agente motivador.

*El tercer argumento*, con el que siempre me he sentido más identificado, *apuesta por alinear la seguridad con los objetivos de la organización*. A la respuesta de: ¿para qué gestionamos la seguridad?, este argumento responde: para incrementar los ingresos, disminuir los gastos o aumentar nuestro prestigio.

Los dos primeros argumentos nos llevan a movimientos tácticos: decidimos con qué recursos, técnicos o humanos, nos defendemos de “los malos” y cumplimos con el ordenamiento normativo. *El tercer argumento nos conduce a un planteamiento estratégico*: ya hemos respondido al “para qué”, pero aún nos quedaría responder al: qué, cómo, a quién y por qué. Hallar estas respuestas depende de cada organización y es lo más difícil.

*El miedo, cuando sobrepasa ciertos umbrales, pone a la víctima bajo el “efecto túnel”*: si la emoción es demasiado intensa, la visión periférica se reduce y, junto con la atención, se concentra en el arma que esgrime el atacante. La víctima podrá describirla con precisión pero no registrará detalles importantes para la identificación del agresor: su ropa, su voz, sus rasgos, etc. La víctima se pierde todo lo que ocurre a su alrededor, incluyendo lo que hay detrás del atacante. Esta es una de las principales causas de disparos accidentales entre agentes de la policía.

Deberíamos evitar este “efecto túnel” que nos lleva a concentrarnos en un determinado aspecto de la seguridad para dedicar mayor tiempo a pensar cómo plantearla estratégicamente, contribuyendo a alcanzar los objetivos globales del “negocio”. Una vez que la organización es consciente del enfoque global y estratégico de la seguridad, debería plantearse una serie de *medidas tecnológicas, organizativas y formativas para ir disminuyendo el riesgo* que asume.

*En los siguientes post nos centraremos en aspectos más tecnológicos de la seguridad*. Analizaremos casos de uso, productos y servicios concretos. Detallaremos las “buenas prácticas” que están siendo emprendidas en los diferentes sectores, e intentaremos compartir con todos vosotros aquellas tendencias dignas de ser tenidas en cuenta para la evolución de la seguridad en nuestra organización.


[[https://docs.google.com/forms/d/e/1FAIpQLSeGnXB3zyaNVYcb_2EoO8C5HRc6Emx-2rv2QS6OWNFz1yYSBQ/viewform?usp=pp_url&entry.55081144=La%20Gesti%C3%B3n%20de%20la%20Seguridad...%20y%20el%20Miedo][Dejar comentario]].

** Comentarios

*** Es inútil decir que no (Anonymous 22/06/2012 - 14:59)
Es inútil decir que no deberíamos querer la seguridad. Hemos de descubrir que no existe la seguridad, que buscarla es doloroso y que cuando imaginamos haberla encontrado, no nos gusta. Lo principal es comprender que no hay ninguna seguridad.
Para comprender la seguridad no hay que enfrentarse a ella, sino incorporarla a uno mismo.

Una mente íntergra y sincera no actua de acuerdo con las reglas, sino con las circusntancias del momento, y el "bien" que desea a los demás no es seguridad, sino libertad
