#+title: Sobre la FELICIDAD
#+date: <2012-05-24 07:27>
#+author: Godofredo Fdez.
#+description: Robo aquí una pregunta y su correspondiente respuesta de la sección "Punset Responde" incluida en la revista " Redes Para La Ciencia " número 26. Por tanto, de lo que sigue nada es mío, excepto la enfatización intencionada de las negritas y el subrayado ;-). Pregunta: Si no soy feliz, ¿vivo en un estado de infelicidad, o hay un punto intermedio? (Santiago Solares) Respuesta:
#+filetags: Pensamiento
#+options: _:nil
#+nid: 473

Robo aquí una pregunta y su correspondiente respuesta de la sección "Punset Responde" incluida en la revista "[[http://www.eduardpunset.es/revista-redes][Redes Para La Ciencia]]" número 26. Por tanto, de lo que sigue nada es mío, excepto la enfatización intencionada de las negritas y el subrayado ;-).

Pregunta:

Si no soy feliz, ¿vivo en un estado de infelicidad, o hay un punto intermedio? (Santiago Solares)

Respuesta:

Hay un punto intermedio, naturalmente. La inmensa mayoría del tiempo estamos en ese punto en que no somos del todo felices o infelices. Es la forma natural de estar, lo más común y normal. Y está bien que sea así. Yo siempre digo que *la felicididad está en la antesala de la felicidad*. Lo que nos hace más felices no es llegar a nuestra meta sino estar a punto de lograrla. Si lo piensas, verás que es lógico que sea así. Si siempre nos sintiéramos satisfechos, contentos y plenos, no nos moveríamos, no haríamos nada, y eso nos impediría seguir avanzando, pensar cosas nuevas, luchar por nuevos objetivos, evolucionar. Y, en el caso contrario, pasa lo mismo. Si siempre nos sintiéramos infelices, agobiados, tristes y desesperados, no tendríamos la energía necesaria, la motivación, para luchar por aquello que necesitamos para sobrevivir.

*El equilibrio es lo que resulta más óptimo para nuestra especie*. Una cosa es el miedo que paraliza y otra la ansiedad necesaria para acometer nuevas tareas. Dicho esto, debo añadir que debemos intentar ser lo más felices posible, porque el bienestar genera salud. Sentirnos tranquilos y satisfechos induce a la secreción de hormonas que nos ayudan a mantener nuestro cuerpo y mente en forma. *Lo que no debemos hacer nunca es acomodarnos, rendirnos, dejar de tener ilusiones por las que luchar*.\\


[[https://docs.google.com/forms/d/e/1FAIpQLSeGnXB3zyaNVYcb_2EoO8C5HRc6Emx-2rv2QS6OWNFz1yYSBQ/viewform?usp=pp_url&entry.55081144=Sobre%20la%20FELICIDAD][Dejar comentario]].

** Comentarios

*** Hay una confusión en la (Juan Fernando 31/10/2012 - 18:57)
Hay una confusión en la respuesta entre la felicidad y el bienestar, además de una identificación sin justificar entre lo bueno para la especie y lo bueno para el individuo.
