#+title: Continuos cuadros de dignidad
#+date: <2013-01-13 21:22>
#+author: Godofredo Fdez.
#+description: La dignidad es uno de esos conceptos que todos empleamos pero que pocos, estimo, sabríamos definir con claridad. Yo llevo años intentándolo y aún hoy creo que…
#+filetags: Libros Pensamiento
#+options: _:nil
#+nid: 500

La dignidad es uno de esos conceptos que todos empleamos pero que pocos, estimo, sabríamos definir con claridad. Yo llevo años intentándolo y aún hoy creo que no ando muy suelto haciéndolo. La idea que tengo de ella la obtuve al leer este libro: [[/content/la-lucha-por-la-dignidad][La lucha por la dignidad]] (José Antonio Marina y María de la Válgoma. Edición 2005). Es uno de esos conceptos en continua construcción, como la libertad, una tierra conquistada palmo a palmo por el hombre con miles de esfuerzos y sacrificios. La dignidad es aquello que nos hace ser nosotros mismos, que nos permite desarrollarnos de forma auténtica, elegida. La capacidad de poder ser lo que queremos ser. Y que se autolimita al tener en cuenta la dignidad del otro. En el libro lo dicen de muchas maneras, pero quizá estas frases puedan servir de extracto: “/La Humanidad, por distintos y convergentes caminos, ha descubierto que el modo más seguro y eficaz de conseguir la felicidad y la justicia es afirmando el valor intrínseco de cada ser humano”...”En los últimos siglos, este valor ha sido designado con el término dignidad, que en la actualidad figura en muchas Constituciones políticas/”.

Ayer, en nuestra sesión nocturna “SábadoCine”, vi una de las mejores películas que probablemente veré en mi vida: [[http://www.filmaffinity.com/es/film733438.html][Los miserables]] (Bille August, 1998). Basada en el libro de Víctor Hugo del mismo título que, habiendo pasado varias veces por mis manos, lamento mucho, ahora, no haber leído. Y creo que no lo leí porque el propio título me hacía creer que iba a ser fuente de dolor inmenso... equivocado estaba y encolado queda.

La película me atrapó en los primeros compases: un par de planos captando la fuerza de sendos cruces de miradas fueron suficientes para hacer clic en mí y dejarme conectado a la historia del protagonista hasta el final. La sucesión de situaciones resueltas acudiendo siempre a lo más difícil pero más humano es tan ancha como enriquecedora. Destaco la inicial del obispo frente al preso, por ser la que me atrapó; y la intermedia, el alegato de defensa que el protagonista realiza en el juicio donde se pretendía acusar a un inocente, porque ahí, en esa trampa que le tejieron unos poderosos miserables quedaron al descubierto las miserias de los más débiles, porque ahí, en esos momentos donde la vida nos pone contra la espada y la pared, el protagonista, firmemente convencido de la verdad de su postura ante la vida, insiste en ella aún sabiendo que sólo le quedará perder.

Por otro lado, la película muestra, en continuo contrapunto, la grandeza y la miseria del ser humano. De todos: los grandes tienen momentos miserables y los miserables tienen momentos que los engrandecen. Quizá nuestro transcurrir por este mundo consista en creer que es posible luchar para subir la media, asumiendo que la perfección no existe. Es el único camino para morirte tranquilo, con la mirada limpia y con el alma llena. Aún a costa de vivir solo. Todos los demás senderos, aunque te ofrezcan vivir lleno de opulencia, social y material, a costa de todo y de todos, te conducen al vacío más extremo. A morir solo. Y a vivir como un muerto.

Ya para finalizar, la película resuelve bien, no una sino varias veces, hasta este párrafo extraído del libro mencionado al principio:

“/Resulta incomprensible que ante tanta maldad, ante tanto comportamiento indigno e indignante, afirmemos que todos los seres humanos están dotados de dignidad, es decir, de un valor intrínseco, independiente de sus actos, de su barbarie, de ese inicuo refinamiento de la crueldad. Resulta incomprensible que no sigamos enarbolando el equilibrado principio del talión, culminación de la justicia conmutativa, que tengamos consideración con quien no la tuvo previamente, que nos empeñemos en librar de la pena capital a quien ha violado y matado a una niña, o en rehabilitar a quien sin razón y sin excusa nos ha destrozado la vida. ¿De dónde hemos sacado una idea tan extraña? ¿Por qué la aceptamos hasta el punto de que está recogida en muchas Constituciones modernas? ¿No va contra el sentido común, contra los sentimientos comunes, contra la sana indignación ante el salvajismo, contra el equilibrio de la justicia?/

/Es contradictorio afirmar la dignidad de los indignos. ¿Por qué lo hacemos?.../”


[[https://docs.google.com/forms/d/e/1FAIpQLSeGnXB3zyaNVYcb_2EoO8C5HRc6Emx-2rv2QS6OWNFz1yYSBQ/viewform?usp=pp_url&entry.55081144=Continuos%20cuadros%20de%20dignidad][Dejar comentario]].

** Comentarios

*** Dignidad (Juan Fernando 16/01/2013 - 10:15)
"La dignidad es aquello que nos hace ser nosotros mismos, que nos permite desarrollarnos de forma auténtica, elegida. La capacidad de poder ser lo que queremos ser. Y que se autolimita al tener en cuenta la dignidad del otro." En esas palabras creo que hay una confusión entre "libertad" y "dignidad". Yo diría que esas palabras hablan de la libertad. Aunque basada en la libertad, la dignidad consistiría en el VALOR de la persona por el hecho de serlo. Yo enfocaría el asunto así: una cosa podemos usarla solamente, de modo que si no me sirve puedo tirarla, mientras que con una persona, además de usarla (uso a un camarero, a un taxista), la trato como algo que no es sólo un medio, de modo que si me falla no ha lugar a matarlo. Esa característica de ser algo valioso en sí mismo, de que carecen los objetos, es la dignidad. Por eso no creo que se autolimite al tener en cuenta la dignidad del otro, porque se trata de algo que se halla en todo hombre por serlo. En ese sentido, está ligado a los Derechos Humanos. Acabo de leer en un artículo de Elorza sobre la cuestión catalana que hay un editorial colectivo de 2009 titulado "La dignitat de Catalunya". Eso me choca mucho, hablar de dignidad de una organización histórica.
El asunto es muy complejo, porque fundamentar la dignidad, decir por qué todo hombre tiene un valor intrínseco por el hecho de serlo, por qué no puede ser solamente un medio (como lo sería un esclavo), supone internarse por el ámbito de la metafísica, lo que prueba lo unidas que están las partes de la filosofía, en este caso la ética, la política y una teoría sobre la realidad y sobre el hombre.\\

*** Dignidad y libertad (Godofredo Fdez. 16/01/2013 - 22:37)
Gracias, Juanfer, por el oportuno comentario (porque aún me encuentro en un tempo cercano al que me marcó la película y por venir de ti que tan bien conoces el tema) y por la exactitud expresada en el mismo (se nota que cuando uno se esfuerza en no sólo entender sino además explicar una materia ha de desarrollar formas sencillas de transmitirla).

Llevas razón al remarcar mi confusión entre los conceptos dignidad y libertad. Ahora entiendo mejor la diferencia señalada por ti. Cuando escribí el artículo era consciente de que ese párrafo no acababa de funcionar. Había algo en mí disconforme pero a su vez convencido de la "sensación" que quería transmitir. A ver si la explico ahora mejor: un hombre tiene la "libertad" de reconocer la "dignidad" (el VALOR de la persona por el hecho de serlo) a los demás o no. Por ejemplo, en el pasaje del juicio mencionado todo el mundo, desde los poderosos hasta los miserables, estaba utilizando a un inocente como un medio para conseguir su objetivo. Este hacer le reconoce poca dignidad al inocente (se usa como medio para conseguir un fin: rebajar la condena, y puede acabar liquidándolo: piensa en la posible condena a muerte o a muchos años de prisión), pero, al hacerlo, ¿no estás corrompiendo tu propia dignidad? ¿erosionamos nuestra dignidad cuando libremente elegimos actuar negándosela a los demás y la elevamos cuando la reconocemos en los otros? Dicho de otro modo: si negamos la dignidad a un hombre, ¿nos la estamos negando a nosotros mismos en tanto en cuanto somos hombres? ¿estamos concediendo que otros nos la nieguen y acaben concediéndonos el mismo VALOR que nosotros concedemos? Y llegado hasta aquí, ¿no hay cierta relación entre nuestra dignidad y la de los demás (se autogeneran o limitan)?

Yo veo la libertad y la dignidad como dos caras de la misma moneda. La libertad implica acción, posibilidad... y la dignidad estado. Y ambas se influyen: si quieres mantenerte digno no puedes actuar de cualquier forma, y dependiendo de como actúes conservas mayor o menor grado de "dignidad".

Pero soy consciente también de que visto así esto abre una puerta muy peligrosa: ¿podrías perder tu dignidad, VALOR de la persona por el hecho de serlo, a consecuencia de tus actos? ¿podrías dejar de ser una persona si no te comportas como una persona? ¿y cómo han de comportarse las personas para ser personas? Y si alguien cree que pierdes el valor, ¿podría acabar contigo? Y si esto lo piensa un estado, ¿se implanta la pena de muerte?

...ya me callo ;-)\\

*** Dignidad (Juan Fernando 17/01/2013 - 10:36)
Lo que más me agrada es que yo detecté que tú sabías que ese párrafo no acababa de funcionar. Quiero decir: me agrada por lo que supone de cercanía entre nosotros.
Me parece fina esa distinción entre libertad referida a la acción o a la posibilidad y la dignidad como estado. Creo que la discrepancia en nuestras interpretaciones de la dignidad estriba en que para ti ésta tiene grados y para mí no. Cualquier hombre, haya hecho lo que haya hecho, tiene dignidad POR EL HECHO DE SER HOMBRE. En cuanto a la libertad, podemos hablar de grados de libertad en el sentido de que una persona con más opciones para elegir es más libre, pero, desde otro punto de vista, definiendo sin más la libertad como capacidad de elegir, tenemos que ya es libre el que sólo tiene para elegir entre A o B, tan libre (es decir, con esa capacidad de elección) como el que puede elegir entre todas las letras del abecedario.
Ahora debería hablar de la fundamentación de la dignidad, de por qué somos dignos y de por qué es digno quien atenta contra la dignidad de los demás. Pero eso queda para otro momento.
Lo que sí te agradezco es tu comentario sobre Los miserables. Yo he visto en el cine estas vacaciones la película del musical, que está bien para quien guste de esas canciones. En cuanto a la novela, me consta que a Vargas Llosa le encanta, y yo también la tengo a la cola para leerla, porque no hace mucho leí Nuestra Señora de París, la historia del jorobado de Notre-Dame, y me sorprendió gratamente por cuanto se aleja de la historia tal y como la cultura popular nos la ha transmitido.
En fin, yo también me callo ya.

*** Luchando contra el spam (Godo 22/03/2016 - 23:30)
Amigo Juanfer, habrás recibido varios mails cuyo contenido era, básicamente, una gran cantidad de enlaces. Esos envíos los recibes porque "programas/robots (funcionan con un fin e ininterrumpidamente)" visitan este sitio web, en concreto parece que se han fijado justo en esta entrada, y cada cierto tiempo publican un comentario con dicho contenido. Su misión es plagar la red de enlaces a esos sitios webs que "promocionan", intentando dos cosas: que la gente pique, entrando en ellos cuando visita las páginas que han "infectado"; y crear enlaces de vuelta, que apuntan a dichos destinos, con el objetivo de "ser más citados" y conseguir más reputación en Internet.

Aunque tengo un par de técnicas habilitadas en la infraestructura software que sostiene este sitio web, GodEst, parece que las están sobrepasando con facilidad. Así que acabo de incluir una tercera defensa que tiene en cuenta el comportamiento de envío de un comentario cuando este está siendo realizado por un humano...

...a ver si no dificulta los envíos verdaderos y sí los de tipo "spam", que es el objetivo.

Esto es aprendizaje continuo: "los malos" aprenden a esquivar las defensas y "los buenos" intentamos aprender un poco más protegiéndonos. Y así, ahora mueven ellos ahora nosotros, poco a poco. Al más puro estilo ajedrecístico.

Mis disculpas y mis gracias.

Salud, compañero.
