#+title: Estirar - Correr - Estirar
#+date: <2013-08-22 22:39>
#+author: Godofredo Fdez.
#+description: Hace unos cinco años que comencé a correr. Recuerdo que fue después de un verano. Y una camiseta que aún conservo lleva inscrito el año 2009, cuando corrí la…
#+filetags: Juegos/Deportes
#+options: _:nil
#+nid: 510

Hace unos cinco años que comencé a correr. Recuerdo que fue después de un verano. Y una camiseta que aún conservo lleva inscrito el año 2009, cuando corrí la nocturna de Sevilla. Si bien no he sido muy regular en el ejercicio hasta mayo de 2012, cuando comencé a correr de forma más o menos continua (3 ó 4 veces por semana), ahora creo que ya no puedo parar :-).

Desde mediados de mayo de este año, y con mayor intensidad a finales de junio, he venido sintiendo un dolor, molesto pero no inhabilitante, en la parte exterior del muslo derecho. Como si fuera un roce eterno que va desde la mitad del fémur hasta el glúteo, irradiándome más ligeramente hacia la parte externa de la rodilla y de forma prácticamente imperceptible hasta el tobillo.

Entonces pensé que se debía a que había forzado demasiado y dejé de correr todo el mes de julio a ver si se me aliviaba, pero prácticamente no noté mejoría. Cuando me incorporé al trabajo después de las vacaciones hablé con varios compañeros deportistas y me recomendaron que fuera a un fisioterapeuta. El dolor era tan molesto que incluso barajamos la idea de que quizá fuera mejor ir a un traumatólogo para ver si tenía “algún vicio oculto”: problemas de pisada, etc.

Pero yo sospechaba que no estaba estirando bien... el conocimiento del propio cuerpo es uno de los placeres a los que te lleva el hacer deporte. Había hecho muchas y variadas actividades físicas en mi juventud y nunca había tenido problemas.

Hice una búsqueda en Youtube de vídeos de estiramiento que tuvieran que ver con “correr” y encontré este que inserto a continuación, donde el autor describe exactamente mi dolor entre los 3:45 y los 5:15 minutos.

Descubrí dos cosas:
* Mi piramidal me estaba irradiando un pequeño dolor hacia abajo (falsa ciática). Comprobé que lo tenía muy sobrecargado porque al hacer el ejercicio la sensación de estiramiento en dicha zona fue muy fuerte los primeros días y ha ido bajando conforme lo he ido repitiendo.
* Mi fascia-lata estaba también tocada. Lo mismo que antes, cuando comencé a hacer el ejercicio propuesto sentí un estiramiento muy fuerte en la zona mencionada, que ha ido bajando poco a poco en las repeticiones que he ido haciendo en días sucesivos.

La mejoría ha sido “casi” total. Tanto es así que sigo haciendo ejercicio. Eso sí: estirando - corriendo - estirando. Estoy memorizando tanto la gama de estiramientos de antes de la carrera como los de después, e intento hacerlos de la forma más correcta posible cada vez que salgo.

Aquí os dejo también el vídeo que detalla los que hay que realizar al final:

Muchas gracias a “enformasinlesiones” por subir estos vídeos. Por experiencia puedo decir que son muy buenos. Hay un antes y un después de conocerlos.

Y Ahora... ¡a por la media maratón de Los Palacios!

P.D.: parece que a Elena (http://saludalacarta.net/2013/05/04/mi-fascia-lata-y-yo/) le ocurría igual que a mí. Interesante la figura con ejercicios concretos.
P.D.: más estiramientos para después de correr: http://www.foroatletismo.com/estiramientos/los-7-estiramientos-imprescindibles-despues-de-correr/
P.D.: más estiramientos en general: http://www.runners.es/entrenamiento/estiramientos/articulo/mejores-estiramientos-para-correr


[[https://docs.google.com/forms/d/e/1FAIpQLSeGnXB3zyaNVYcb_2EoO8C5HRc6Emx-2rv2QS6OWNFz1yYSBQ/viewform?usp=pp_url&entry.55081144=Estirar%20-%20Correr%20-%20Estirar][Dejar comentario]].

