#+title: Descomposición de un fichero .c en varios ficheros
#+date: <2013-01-10 21:59>
#+author: Godofredo Fdez.
#+description: En la última clase de teoría que ayer impartí de la asignatura " Fundamentos de Programación I " correspondiente al Grado en Ingeniería de las Tecnologías de…
#+filetags: Programación
#+options: _:nil
#+nid: 499

En la última clase de teoría que ayer impartí de la asignatura "*Fundamentos de Programación I*" correspondiente al Grado en Ingeniería de las Tecnologías de Telecomunicación, mostré como descomponer en varios ficheros un código fuente en C, evitando los típicos errores de "doble inclusión" que se producen si no se hace uso de las directivas oportunas del preprocesador.

Los errores que pretendemos solucionar son estos (o similares):

$ gcc -W -Wall -o descompuesto-mal principal.c rellena.c imprime.c
In file included from principal.c:4:
imprime.h:15: error: redefinición de `struct articulo'
imprime.h:18: error: redefinición de la definición de tipo 'ARTICULO'
rellena.h:18: error: la declaración previa de 'ARTICULO' estaba aquí
imprime.h:20: error: redefinición de la definición de tipo 'TABLA'
rellena.h:20: error: la declaración previa de 'TABLA' estaba aquí

Tras descomprimir el fichero adjunto a este post, encontrarás tres directorios:

- codigo-completo: contiene todo el código en un único fichero.
- descomposicion-bien: contiene el código anterior ya descompuesto en tres ficheros .c y dos ficheros .h. Como su nombre indica, esta descomposición es correcta y se hace uso de las directivas del preprocesador que evitan la doble inclusión de los typedef.
- descomposicion-mal: es igual que el anterior pero en este caso se ha comentado la línea que hay en los .h que evita la doble inclusión.

Puedes comparar el código descompuesto con el código completo y observar cómo se ha llevado a cabo el proceso.

Obviamente, también puedes detectar el error de "redefinición" que muestran los mensajes del compilador y cómo se soluciona.

Si tienes alguna duda o comentario házmelos llegar por aquí.

Espero que te resulte útil.

** Archivos adjuntos
- [[https://godest.vivencias.net/static/files/descomposicion-en-varios-ficheros.7z][descomposicion-en-varios-ficheros.7z]]

[[https://docs.google.com/forms/d/e/1FAIpQLSeGnXB3zyaNVYcb_2EoO8C5HRc6Emx-2rv2QS6OWNFz1yYSBQ/viewform?usp=pp_url&entry.55081144=Descomposici%C3%B3n%20de%20un%20fichero%20.c%20en%20varios%20ficheros][Dejar comentario]].

