#+title: ¿Por qué corro?
#+date: <2013-10-20 22:00>
#+author: Godofredo Fdez.
#+description: Hace algunos días, durante un desayuno, me sobrecogieron algunas afirmaciones que vertieron mis contertulios sobre la cantidad de personas que nos rodean que,…
#+filetags: Juegos/Deportes Pensamiento
#+options: _:nil
#+nid: 516

Hace algunos días, durante un desayuno, me sobrecogieron algunas afirmaciones que vertieron mis contertulios sobre la cantidad de personas que nos rodean que, por una cosa o por otra, están pasando un mal momento. La frase fue, más o menos así: “Godo, te sorprenderías si supieras la cantidad de gente que te rodea que está yendo a un psicoterapeuta...”. Creo que vivimos tiempos difíciles, concretamente ahora que hay escasez de dinero o de trabajo o de comprensión o...

La verdad es que cuando uno relativiza esta época frente a otras que les tocaron vivir a nuestros padres, abuelos y a nuestros antepasados en general, no encuentra grandes motivos de por qué ahora parecemos estar más infelices, más insatisfechos y con más cuadros de estrés, ansiedad y demás cosas parecidas.

He pensado mucho sobre ese tema y he conversado largo y tendido con amigos que se interesan por las cosas. Mi opinión se fundamenta en la idea de que *vivimos muy deprisa*. Creo que es la única diferencia frente a otras vidas que he tenido la suerte de conocer: me crie en un pueblo junto a personas mayores y tuve la posibilidad de observar de cerca sus hábitos.

Ese vivir deprisa se concreta en querer abarcar muchas más cosas de las que podemos, ya sea por imposición (en el trabajo con el ritmo que nos marcan) o por deseo desenfrenado: queremos leer mil cosas, hacer otra tantas, visitar muchas más ciudades pero a la vez estar con los amigos, aprender a tocar la guitarra pero también hacer deporte, responder emails, socializar y compartir contenido por las redes, educar a nuestros hijos, llevarlos a mil y una actividad... y eso nos hace volar superficialmente de una cosa a otra, sin entrar de lleno en su esencia y, así, creyéndonos que estamos disfrutando de todo, de mucho, cuando en realidad, pienso yo, disfrutamos muy poco. Superficialidad versus profundidad.

Y para vivir profundamente necesitamos conocernos.

Hablar de las diferentes formas que nuestros contemporáneos utilizan para encontrarse a sí mismos daría para otro artículo, así que voy a hablar de las tres que yo he encontrado después de ir explorando muchas de ellas a lo largo de mi vida:

1.- Leer y pensar con sentido crítico sobre lo leído. Intento siempre buscar el fundamento de las opiniones, ponerme en el lugar del que las dice o del que narra los hechos ya me parezcan buenos o malos a priori. Sí, todos prejuzgamos, lo importante es no quedarse ahí sino intentar avanzar, dar una oportunidad a esa otra idea que no es la tuya, preguntarte por qué la rechazas...

2.- Hablar y compartir momentos con esas personas, pocas, que de verdad te quieren. Porque básicamente han llegado a tal conocimiento de ti que algunas veces son capaces de radiografiarte el alma y encontrar en ella cosas que ni tú mismo habías imaginado.

3.- Plantearme metas a corto, medio y largo plazo y luchar empecinadamente para conseguirlas. *Sólo así uno conoce sus verdaderos límites*. A esto me está ayudando mucho correr. Lo que consigo corriendo refuerza la confianza en mí mismo e irradia esa sensación al resto de objetivos. Además de este beneficio "psicológico" asociado a la *fortaleza mental* (el mejor ejemplo de este concepto es Rafa Nadal), correr también conlleva todos los demás beneficios de hacer deporte: mejora de la salud, sobre todo la del corazón -dicen-, equilibrio de peso, menos tensiones, mejores sueños... 

(A este artículo le sigue este otro: "[[http://godest.vivencias.net/content/el-desaf%C3%ADo-de-los-100-estadios][El desafío de los 100 estadios]]").

19-12-2013--P.D.: adjunto un archivo que contiene una noticia que me hizo llegar Esther donde relatan los efectos positivos que tiene el deporte para la salud. Más motivación.

** Archivos adjuntos
- [[https://godest.vivencias.net/static/files/mejor_vayase_a_sudar_al_parque.pdf][mejor\_vayase\_a\_sudar\_al\_parque.pdf]]

[[https://docs.google.com/forms/d/e/1FAIpQLSeGnXB3zyaNVYcb_2EoO8C5HRc6Emx-2rv2QS6OWNFz1yYSBQ/viewform?usp=pp_url&entry.55081144=%C2%BFPor%20qu%C3%A9%20corro%3F][Dejar comentario]].

