#+title: Lista de deseos
#+date: <2015-10-27 23:12>
#+author: Godofredo Fdez.
#+description: Pongo a continuación una pequeña lista de deseos que, como todo buen deseo que se precie, pretendo conseguir :-) El orden no indica preferencia, más bien…
#+filetags: Juegos/Deportes Libros Música Software
#+options: _:nil
#+nid: 542

Pongo a continuación una pequeña lista de deseos que, como todo buen deseo que se precie, pretendo conseguir :-)

El orden no indica preferencia, más bien antigüedad en la lista (el último es el más antiguo, voy agregando al principio).

- Cartera: en concreto [[http://bellroy.com/wallets/coin-fold-wallet?color=tamarillo][esta]].

- Libro: +¡DESPERTAD AL DIPLODOCUS!: UNA CONSPIRACION EDUCATIVA PARA TRANSFORMAR LA ESCUELA Y TODO LO DEMAS (En papel). JOSE ANTONIO MARINA , ARIEL, 2015. ISBN: 9788434422773+. Conseguido el 15 de enero de 2016 . ¡Muchas gracias, Kader!

- Libro: EL INVERSOR INTELIGENTE (En papel). BENJAMIN GRAHAM DEUSTO S.A. EDICIONES, 2007. ISBN: 9788423425174.

- Libro: LA EDUCACION DEL TALENTO (En papel). JOSE ANTONIO MARINA, ARIEL, 2010. ISBN: 9788434469334.

- Libro: AUDAZ, PRODUCTIVO Y FELIZ: UNA GUIA PARA CONSEGUIR OBJETIVOS INCREIBLES Y DOMINAR TU VIDA PERSONAL Y PROFESIONAL (En papel). ROBIN SHARMA, CONECTA, 2015. ISBN: 9788416029563.

- Libro: DOS AÑOS, OCHO MESES Y VEINTIOCHO NOCHES (En papel). SALMAN RUSHDIE, SEIX BARRAL, 2015. ISBN: 9788432225215

¡Gracias!


[[https://docs.google.com/forms/d/e/1FAIpQLSeGnXB3zyaNVYcb_2EoO8C5HRc6Emx-2rv2QS6OWNFz1yYSBQ/viewform?usp=pp_url&entry.55081144=Lista%20de%20deseos][Dejar comentario]].

