#+title: Seguridad TIC - Modelo de Negocio
#+date: <2015-06-08 16:58>
#+author: Godofredo Fdez.
#+description: Imparto esta ponencia en una jornada de seguridad organizada en la Escuela Superior de Ingenieros de la Universidad de Sevilla. Para más información ver el…
#+filetags: Seguridad Seguridad_de_la_información
#+options: _:nil
#+nid: 531

Imparto esta ponencia en una jornada de seguridad organizada en la Escuela Superior de Ingenieros de la Universidad de Sevilla. Para más información ver el archivo adjunto al final de este post.

Está estructurada así: comenzaremos viendo el panorama actual y cómo la seguridad influye en el negocio. Luego nos centraremos en el concepto "cadena de valor" y analizaremos los modelos de negocio que emergen al aplicar este concepto al de seguridad. Continuaremos presentando las tendencias que "suenan" en el presente y "prometen" desarrollo futuro. Finalmente, expondremos qué conocimientos y habilidades/cualidades se consideran necesarias y son valoradas en los perfiles buscados en las ofertas de trabajo, dando algunos consejos para afrontar el proceso de selección.

Y a ti, ¿qué pregunta/preocupación no querrías que se quedara sin responder en la [[https://twitter.com/search?q=%23SecESI9j&src=typd&vertical=default&f=tweets][#SecESI9j]]?

Gracias.

P.D.: os dejo [[https://www.mediasplash.co/los-4-tipos-de-canvas-business-vs-lean-vs-social-vs-ongs/?utm_content=buffer269a6&utm_medium=social&utm_source=facebook.com&utm_campaign=buffer%3Cbr%3E%0A][aquí]] el enlace al blog de donde obtuve el "canvas" del "modelo de negocio de un emprendedor" (Lean Model Canvas).

P.D.: [[http://www.slideshare.net/JulianJGonzalez/metasploit-class-shellshock-attack][Aquí]] podéis encontrar la ponencia que realizó [[https://twitter.com/rhodius][Julián González]] sobre "Metasploit Class: Shellshock Attack".

P.D.: Y [[http://www.slideshare.net/zekivazquez/hacking-hardening-drupal][aquí]] podéis encontrar la ponencia que realizó [[https://twitter.com/RabbitLair][Zeki Vázquez]] sobre "Drupal Hacking & Hardening".

P.D.: en el adjunto que sigue está la agenda de la jornada.

** Archivos adjuntos
- [[https://godest.vivencias.net/static/files/seguridad-9j.pdf][seguridad-9j.pdf]]

[[https://docs.google.com/forms/d/e/1FAIpQLSeGnXB3zyaNVYcb_2EoO8C5HRc6Emx-2rv2QS6OWNFz1yYSBQ/viewform?usp=pp_url&entry.55081144=Seguridad%20TIC%20-%20Modelo%20de%20Negocio][Dejar comentario]].

