#+title: pdftk y pdfnup, las navajas suizas para trabajar con PDFs
#+date: <2019-10-24 15:43>
#+author: Godofredo Fdez.
#+description: Hace tiempo que descubrí pdftk como herramienta en línea de comandos para trabajar con documentos pdf. Básicamente la he venido utilizando para extraer partes…
#+filetags: Software
#+options: _:nil
#+nid: 573

Hace tiempo que descubrí [[https://www.pdflabs.com/tools/pdftk-the-pdf-toolkit/][pdftk]] como herramienta en línea de comandos para trabajar con documentos pdf. Básicamente la he venido utilizando para extraer partes concretas de dichos documentos (algunas páginas seleccionadas ya sean consecutivas o salteadas), y para fusionar dos documentos (por ejemplo, una oferta y un anexo que te llegan o "fabricas" por separado pero luego quieres distribuir juntos, como un único documento).

Lo que más me gusta es que, como he dicho, es una herramienta que puede utilizarse en línea de comandos, y esto, aunque el común de los mortales no está muy preparado para entenderlo, suele ser una fuente de potencia inimaginable a la hora de hacer tareas de preprocesamiento como las que he descrito en el párrafo anterior, y, por tanto, obtenemos un gran ahorro de tiempo.

Yo llegué a esta herramienta desde mi [[https://www.debian.org/][Debian]] (pues venía en su sistema de paquetes), pero luego busqué una versión para Windows y la encontré. Además, es gratuita. Podéis descargarla directamente de la página de los autores, aunque yo por mi comodidad, sólo por la mía ;-), he subido un .zip de los dos ficheros que son necesarios a este mismo post (lo tenéis al final). Basta con descargarlo, descomprimirlo en la carpeta donde queráis trabajar, es decir, donde tengáis también los documentos objeto del trabajo, y utilizarlo (modo usuario básico). Si sois usuarios avanzados, lo mejor es meter ambos ficheros en una carpeta que esté en el PATH de vuestra máquina.

La potencia de esta herramienta permite cosas como:
a) Extraer las páginas impares de un documento pdf, resultando un documento nuevo:

#+begin_example

$ pdftk Finanzas.pdf cat 1-endodd output newFinanzas.pdf

#+end_example

b) Lo mismo, pero con las páginas pares:

#+begin_example

$ pdftk Finanzas.pdf cat 1-endeven output newFinanzas.pdf

#+end_example

c) Reconstruir el documento original a partir de dos documentos separados en pares e impares:

#+begin_example

$ pdftk A=doc1.pdf B=doc2.pdf shuffle A B output complete.pdf

#+end_example

e) Fusionar dos documentos, como decía al principio, uno detrás de otro:

#+begin_example

$ pdftk oferta.pdf anexo.pdf cat output oferta-anexo.pdf

#+end_example

Además, viene con una ayuda muy completa a la que se accede con:

#+begin_example

$ pdftk --help

#+end_example

Recientemente [[https://unix.stackexchange.com/questions/254308/printing-two-pages-per-sheet-from-the-command-line][he descubierto]] otra utilidad que permite muy fácilmente pasar un documento original a otro que tenga dos páginas del original, o más, en una sola hoja. Algo muy útil para imprimir "borradores" o versiones no definitivas. Esta herramienta también la he conseguido [[https://takitamblog.tk/free-pdfnup-for-windows-compiled-to-exe-python-script-gpl-3/][compilada para Windows]] y, tras revisar "su malware" con [[https://www.virustotal.com/gui/home/upload][Virustotal]], la he utilizado satisfactoriamente. También te dejo un .zip al final de este artículo.

#+begin_example

$ pdfnup --help

#+end_example

Pues nada más, espero que te ayude.\\

** Archivos adjuntos
- [[https://godest.vivencias.net/static/files/pdftk-para-windows.zip][pdftk-para-windows.zip]]
- [[https://godest.vivencias.net/static/files/pdfnup(py2exe).zip][pdfnup(py2exe).zip]]

[[https://docs.google.com/forms/d/e/1FAIpQLSeGnXB3zyaNVYcb_2EoO8C5HRc6Emx-2rv2QS6OWNFz1yYSBQ/viewform?usp=pp_url&entry.55081144=pdftk%20y%20pdfnup%2C%20las%20navajas%20suizas%20para%20trabajar%20con%20PDFs][Dejar comentario]].

